### ISSUE TITLE
GeoIP when using azure gateway doesn't work

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#10111]
## Is your feature request related to a problem?

Azure gateway forwards ipv4 ips in form of `ip:port` which our mmdb server cannot handle. 

Source: https://docs.microsoft.com/en-us/azure/application-gateway/how-application-gateway-works#modifications-to-the-request
Spec: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For

## Describe the solution you'd like

Strip the port during capture.

## Describe alternatives you've considered

support the port being present in the geoip works

## Additional context

Zendesk ticket: https://posthoghelp.zendesk.com/agent/tickets/48

**Comment by jwisener** [comment]
I believe, I was the one that originally reported this issue. I was able to create a rewrite rule for our azure gateway (serving as the reverse proxy) and modify the X-Forwarded-For header: see this article below, the variable I used (instead of their example) was **{var_client_ip}**

https://docs.microsoft.com/en-us/azure/application-gateway/rewrite-http-headers-url#common-scenarios-for-header-rewrite
