### ISSUE TITLE
Enable a project wide save of custom columns in live events list

### ISSUE THREAD

**Issue by anna-rusk** [PostHog/posthog#10138]
## Is your feature request related to a problem?

Our team has some custom properties that we are sending to PostHog that help distinguish our events. The default columns are not quite enough for us. Additionally, we are not using the URL/Screen column so it just is an empty space for us.

## Describe the solution you'd like

We would like to be able to select and save our "custom columns" and have them save project wide for all project users.

## Describe alternatives you've considered

Bookmarking a page where those custom columns are already set.

**Comment by tatey** [comment]
Hey,

I've been emailing @marcushyett-ph about customising columns and he encouraged me to leave my feedback here. I'm new to PostHog and my expectation was customising columns would be persisted project wide which is why I reached out.

Here's why: I've started a project to send data to PostHog and have been setting up the schema. It's the schema that's dictating which columns are useful, and which ones aren't. My co-workers would have an easier time getting used to the project if the columns had useful columns to begin with. 

Just my one vote.

**Comment by clarkus** [comment]
Thanks for filing this issue. It overlaps a good bit with https://github.com/PostHog/posthog/issues/10143 where we're already discussing some improvements. I'm going to close this one so we can consolidate feedback on a single issue. Thanks again for filing the feature request!
