### ISSUE TITLE
Design Feedback: Funnel creation

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/posthog#10144]
I've been away for four days due to national holidays. It turns out this is exactly long enough for me to forget how to do basically anything, including making funnels. 

As a result, I had a moment of confusion which prompted this feedback. 

When you create a funnel, this is what you see:

<img width="1501" alt="Screenshot 2022-06-06 at 13 46 05" src="https://user-images.githubusercontent.com/84011561/172164248-ca282666-3c14-462a-a0b0-b0aace640ac1.png">

Personally, my eye is drawn straight to the centre of the page where it tells me to add another step. It's big. It's got those icons. It's in the middle. However:

1. I haven't added _one_ step yet to my knowledge, so adding _another_ step sounds strange. 
2. A first step has already been added (Pageview) which may not be where I want my funnel to start. 
3. Steps aren't usually added by clicking in this central graph view area. 

It was step 3. that caused me to have a post-holiday brainfreeze because, after clicking `+ Add funnel step` I saw this. 

<img width="922" alt="Screenshot 2022-06-06 at 13 56 48" src="https://user-images.githubusercontent.com/84011561/172164968-d2ba7312-9c45-4ab8-9949-b477ed800624.png">

And then spent a good 10 seconds looking for another `+ Add funnel step` button in the centre of the screen. It's not there. You have to use the query builder on the right. 

However this was what highlighted the issues of step 1. and 2. above. Because by following the process above I've now got a funnel which is tracking two generic pageview events. That's not what I want, so I have to change each step of the funnel to track the right event -- which means reloading the entire funnel twice. Once for Funnel Step 1 (and while it's loading, I can't edit the funnel), and once for Funnel Step 2.

This issue repeats if I add subsequent steps, as each is created as a generic Pageview event (which causes the funnel to reload) and then has to be changed to the correct event (which causes the funnel to reload). 

If I want to track a basic four step funnel, I need to reload the entire funnel _seven times_:

- Once when I add my first event (which is actually Step 2)
- Once when I change Step 1 to track the right event
- Once when I change Step 2 to track the right event
- Once when I add Step 3
- Once when I change Step 3 to track the right event
- Once when I add Step 4
- Once when I change Step 4 to track the right event

Crucially, that's without adjusting the date range. If I do that first the insights can take longer to complete, making funnel creation quite arduous. 

## Possible solution

I'm sure the design team will have better ideas, but focusing users on the query builder and getting them to begin by setting the correct event for Step 1 may make sense. 

Tagging @clarkus and @lottiecoxon from a UI design POV.

**Comment by clarkus** [comment]
Thanks for filing this, @joethreepwood. I think there are multiple issues to tackle here. 

The core issue for the query builder is that when adding subsequent steps / graph series, unless you want to use pageview as your event value, it requires another click to trigger the workflow for selecting the event you want. 

Tactically that translates to `click to add step`, `click the event field` again to trigger the taxonomic filter for finding the event you want, `find the thing`, click to `select the thing`. Ideally, when adding a subsequent step, we'd trigger that taxonomic filter automatically. So tactically it'd look something like `click to add step`, `find the thing`, `select the thing`. We shouldn't make a user click the field again to change the value - we can prompt for that immediately. 

The other issue is our ongoing exploration of [insight editor panels](https://github.com/PostHog/posthog/issues/8929). In the current implementation, we show the insight results before the query builder. This hierarchy isn't working for everyone and it's come up in slack at least two times now ([one](https://posthog.slack.com/archives/C011L071P8U/p1653298412107269), [two](https://posthog.slack.com/archives/C025W6MN8SG/p1653593671834859)). As you called out, because the empty state prompt to add another step is shown before the action in the query builder, users look back to that original add step prompt when wanting to add a step 3, 4, etc. Hierarchically, the query builder should come before the results, especially if the results aren't available until the query builder is complete enough to render a result. This change in hierarchy would make it easier to get back to the proper position for adding subsequent steps. 

I've [posted](https://posthog.slack.com/archives/C0368RPHLQH/p1654545637596839) in our internal slack to discuss ending the editor panels exploration until we have some better layouts. I have some other ideas in progress that could improve this, but they need more time and engagement before we can put effort into building them.
