### ISSUE TITLE
First-Class React Support

### ISSUE THREAD

**Issue by curtvict** [PostHog/posthog#10153]
## Is your feature request related to a problem?

Not a problem, per se, but I was curious if first-class React support was something that's been kicked around as a feature. I see there is [a discussion](https://github.com/PostHog/posthog/pull/3761) around the use of data attributes to track specific UI components within the Admin. I've seen a few consumptive solutions hook into React `displayName` properties to automatically surface data in their admins ([LogRocket comes to mind](https://docs.logrocket.com/docs/react-plugin)).

## Describe the solution you'd like

A way to surface React component data in the admin without needing to enforce the hook in the DOM itself.

## Describe alternatives you've considered

Just adding the data attributes :)

**Comment by mariusandra** [comment]
Hey! Unfortunately we can automatically track with React components. We need to employ some tricks.

The LogRocket package you linked to achieves its magic by using a `babel` plugin that rewrites your code to include the component's name inside the `React.createElement`, very similar to another plugin I once wrote to [add paths to kea](https://www.npmjs.com/package/babel-plugin-kea).

[Heap does something similar](https://heap.io/blog/how-we-leveraged-asts-and-babel-to-capture-everything-on-react-native-apps) for React Native. 

We could build a similar babel plugin (and might have to for Expo autocapture), but in many setups, babel is no longer in use because it's slow compared to new alternative. For example in PostHog, we swapped babel + webpack for `esbuild` and got a ~20x build time improvement. We're not going back, even if our build pipeline is a bit less flexible.

**Comment by curtvict** [comment]
That makes sense. Right now we're married to create-react-app for ease of upgradability, so we're currently at their mercy.
