### ISSUE TITLE
Demo Environvment: Onboarding

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/posthog#10193]
## Is your feature request related to a problem?

We're about to launch an awesome new demo environment, thanks to @Twixes. That will enable people to get in, and have a play with PostHog without having to deploy and do all the usual onboarding. 

We're also considering potentially putting the demo environment as [a front-and-center CTA option on the website](https://github.com/PostHog/posthog.com/issues/3533). 

However, the demo environment has no tutorial or onboarding process built into it which will help users understand how to use PostHog. This is a problem for three reasons.

1. **The demo env may reach a very different audience to normal users.** Most PostHog users are technical and are both familiar with our docs (they often need them to deploy) and used to using developer docs in general. Those who aren't typically don't succeed in deploying because of the complexity, so they never reach the product. Removing this barrier means less technical users who are not familiar with docs will be able to get into the product, without the technical knowledge and docs familiarity to rely on. 

2. **Users will have a poor experience**. Users who jump into the demo environment may not know how to achieve the things they want to without help, especially as they are unfamiliar with the data we provide. If they're not able to test what they want to test, they may churn and generate negative word of mouth. At best, they will create more work for support heros (especially a problem if these are less technical users). 

3. **Users who have a good experience, have no progression path.** Let's assume a user has a great experience within the demo env. We currently have no method for drawing a conclusion to their demo experience and upselling them to an appropriate path. 

## Describe the solution you'd like

I think we need some sort of onboarding or tutorial process in the demo environment, one which we could potentially mirror within the final product. 

Open to what features need to be included in the tutorial and what the overall scope should be, but I'd argue that the tutorial should as a minimum cover:

1. How to make a funnel with the demo data. (We know this is a common starting point).
2. How to save that funnel to a dashboard. (We know this is a common early need).
3. How to share that funnel with others you invite. (We know this is both a common need and also an indicator of success).
4. A closing message which directs users to an upsell path (To convert users and bring a close to the demo onboarding).

Very open to other ideas.

## Describe alternatives you've considered

None. I'm a fool like that. 

## Additional context

Tagging both @clarkus and @kappa90 to kick off this discussion.

**Comment by joethreepwood** [comment]
@simfish85 and @camerondeleone may have feedback too!

**Comment by clarkus** [comment]
@kappa90 and I were talking about secondary onboarding paths today during a 1:1. I think some kind of walkthrough or guided tour could help here. We have a functional and usable demo, we just need some prominent pointers to show users where to get started on each page. 

While making the recent updates to data management and live events, we talked about an idea for pointing users to the switch for making live events realtime. This actionable tooltip is almost like a toast message you can point at an area of the page that can act as a proxy interface for doing the thing it describes. In this example, a user could click on the tooltip and it would toggle on the live events switch. This is probably a poor example because it lacks affordance for that action, but you get the idea. Check it out in [figma](https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf/PostHog-App?node-id=11313%3A49525) and let me know if you have feedback. Also worth noting this kind of functionality would make a killer app (in-product messaging and onboarding based on the DOM you already instrumented / autocaptured). 

![Live events with guided tooltip](https://user-images.githubusercontent.com/254612/173159444-65579bfa-f603-4100-87b9-5ed613d7fdfc.png)

**Comment by clarkus** [comment]
@liyiy thought of you while reading this issue. It's somewhat of a secondary onboarding workflow. This might be a good way to also prompt users to answer questions about themselves, their company, or their needs. Check it out 👀

**Comment by neilkakkar** [comment]
This is a great issue! I think we deferred it to Onboarding 2+, but I've been pushing for a video game like tutorial when you first start. Videogames are great at introducing new mechanics incrementally, building on top of what you already know, finding interesting things, etc. etc.

We already have the first part sorted, since the demo data now has 'hidden scenarios': real life data where you can find 'Firefox' being broken for some reason, and other scenarios.

Would be nice for the tutorial to go through figuring out all these challenges. Starting with something like you say: 'here's how to create a funnel'. And then, 'now you have a funnel, but what if you wanted to see browsers? - use the breakdown'. And then, the significance highlight would show how 'firefox' conversion is say, 5%, while everything else is > 70%. 

Now check out recordings to find what was wrong. Here's how to seamlessly find recordings.

And then, oh, you want to try fixing the issue with firefox? Why don't you run an experiment, and so on.

**Comment by kappa90** [comment]
I have started taking some notes about this, will share a RFC soon.

**Comment by joethreepwood** [comment]
Did [a bit of a dive into the demo request data](https://posthog.slack.com/archives/C01FHN8DNN6/p1655303012309379) today, which may be relevant. 

Short version: The slight majority of demo requesters have a technical background and most are either in Engineer (34.1%) or Product (34.1% also) roles. This probably means we should cater any onboarding content to these audiences most.
