### ISSUE TITLE
Better activation of users (in-app)

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#1031]
It's obvious that we lose a lot of people who sign up to the product, but we're not sure where.

A basic funnel I'd love to see is:

- Sign-ups
- Send a single event (/integrate snippet)
- Does "something of note": create funnel/create action/add dashboard item

To get the second step, we'd need to report whether that user has sent any events. I propose we add a daily job that checks for the existence  of an event for each team on an instance, and then adds that as a property for each user. I'd also be worth adding some more stats, such as
- number of dashboards
- number of dashboard items
- number of actions
- number of funnels
- number of cohort
- ?

We should be getting data from app immediately, and from other instances later.

(P.S. thinking about this, it feels like we should really have the concept of groups that we can add properties to, rather than adding all of these properties to individual users. We have been asked about this before and I think it makes sense)

Feel free to edit ticket rather than comment

**Comment by EDsCODE** [comment]
Initial findings using raw methods to query

**Total Teams Analyzed**: 384

**How many people manage to send events through?** 

- 155 teams have sent some events, 19 of them have less than 10 events logged

**How many dashboard items are created?**

- 	42 teams created more than 3 dashboard items (3 is default)
- 	21 teams created more than 1 dashboard (1 is default)

**How many actions are created?**

- 	278 teams created atleast 1 action
- 	61 teams created atleast 2 actions
- 	43 teams created atleast 3 actions

**How many funnels are created?**

- 	49 teams created atleast 1 funnel
- 	12 teams created atleast 2 funnels

**How many cohorts are created?**

- 	24 teams created atleast 1 cohort
- 	10 teams created atleast 2 cohorts

**Comment by timgl** [comment]
I find it very hard to believe that no-one dropped out between signing up and sending events but that is encouraging.

The next question is, what is the a-ha moment in our app? Which of these things (creating a funnel, creating an action, visiting /events page etc) causes a user to come back repeatedly?

**Comment by EDsCODE** [comment]
Going to check more thoroughly what’s happening because many could be demo events too I think

**Comment by EDsCODE** [comment]
Was looking at query results incompletely, the results I was getting were exclusively of teams that had sent events which is 155 of the 384. Updated above

**Comment by EDsCODE** [comment]
**Goal:** Increase user **activation**. Right now roughly 40% (155/384) of created teams send a single event. The decision to sign up and use the deployed app without sending an event is most likely due to 1) running into a bug or 2) interest in seeing more of the product beyond what's describe on the home page 3) don't know/don't feel compelled to go through the process of integrating the snippet. There's more analysis to be done regarding what keeps users coming back, but the first chokepoint to solve is why people sign up and don't do anything.

**Possible methods:**

**Solving user curiosity for more information on product:**
1. More content and demonstrations on the home page. Users should be able to watch videos and see more graphics/animations of what the product looks like and what you can do with it. 

2. Having a live demo/sample that users can access directly from the homepage (posthog.com). Users would be able to interact with a demo deployment and be guided through actions, creating trends, viewing dashboards, paths, etc. This solution should eventually be extended to include a mock website such as our Hogflix site with a fully functional toolbar to analyze/interact with elements on page.

3. Have the live demo #2 but within the app which is currently accessible though not heavily showcased. 

**Making sure users send events**

1. To solve Like sentry, upon signing up, compel users to go through a sign up wizard that's highly interactive and waits for users to integrate the snippet. Sentry polls a users's deployment/account until the snippet/package is connected before allowing users to pass through to their account.

**Comment by EDsCODE** [comment]
I'm don't have many ideas for making sure users send events but I'm on board with @fuziontech suggestion with having the onboarding wizard. This will still allow us to capture user email/information because they're creating an account. It will also force users to actually integrate posthog rather than show up to a blank dashboard and churn before seeing anything. If they churn within the wizard then we have a different problem.

The experience leading up to sign up should be very informative RE: solving curiosity of user using one of the methods above or some other targeted solution.

**Comment by timgl** [comment]
I think this makes sense in general. Lottie is [redesigning the home page](https://github.com/PostHog/posthog.com/issues/129) so would be worth focussing on giving more information.

In terms of stuff to do right away, worth changing the current app /signup page so it doesn't distract users, and find ways of increasing that conversion rate. Then moving on to the install/setup wizard.

Does that make sense?

**Comment by EDsCODE** [comment]
Do you mean it's confusing that /signup has both options hosted/self-hosted rather than just one or the other?

**Comment by timgl** [comment]
Yep, especially as you've just clicked 'Try hosted' on our website. The conversion rate has actually been going up [(it's about 24% at the moment)](https://app.posthog.com/funnel/210) but could probably be improved with a little bit of work

**Comment by EDsCODE** [comment]
Yeah good call. Also, just added some funnels showing people going from the homepage through try hosted to signing up and the [self hosted button is barely used](https://app.posthog.com/dashboard/267) so it's just a distraction

**Comment by EDsCODE** [comment]
mark June 24 as reference for growth experiment when comparing before and after data

**Comment by EDsCODE** [comment]
To track usefulness:

#916 Create Actions/Trends/Funnels Tutorial Widget
#1051 Snippet Tutorial Wizard
Posthog.com [CTA update](https://github.com/PostHog/posthog.com/pull/144)
