### ISSUE TITLE
It is hard to debug self-hosted instances

### ISSUE THREAD

**Issue by neilkakkar** [PostHog/posthog#10325]
## Bug description

Not sure if this repo is the right one for this, please move if so.

When something errors out in PostHog Cloud, it's easy to debug what went wrong because we have a Sentry integration.

On local dev, we can run in DEBUG mode which throws all errors.

However, there's no easy way to get this information in a self hosted installation. I can ask for the logs, but all errors are swallowed by drf-exceptions-hog and all we see is 'Internal Server Error'.

Asking people to run in DEBUG mode is annoying and can expose their secrets. Asking them to setup a sentry org, and put in the right env vars is a hassle too: it means lot of work on their side to figure out what random thing broke.

A solution might be a simple env var which also logs all errors, rather than just sending them to Sentry, right here: https://github.com/PostHog/posthog/blob/master/posthog/exceptions.py#L41

Putting up the issue if Team Platform has better ideas in mind!

## Additional context

https://posthogusers.slack.com/archives/C01GLBKHKQT/p1655205879762289

**Comment by macobo** [comment]
Note that [drf-exceptions-hog](https://github.com/PostHog/drf-exceptions-hog) is a package we own and can easily make edits for - perhaps we want to invest into improving this? I think team east or west might have best context for this to be honest - what form of stack traces would be useful for you?

Also note I have a hate-hate relationship with drf-exceptions-hog and API testing since it swallows 500 errors in tests, meaning you don't get a stack trace or a error while writing code. I often disable it locally due to that reason.

**Comment by neilkakkar** [comment]
I think Team West would be very happy to take this on, if platform has no concerns here. Adding an ENV_VAR is pretty straightforward, and I could just use some help from platform testing this for self-hosted versions.

+1 to exceptions-hog being very annoying for local dev as well - I turn it off too. I think we can solve this for our use case by updating the exception_handler, or the exceptions-hog package.

**Comment by neilkakkar** [comment]
(cc: @EDsCODE )

**Comment by mariusandra** [comment]
Why is it a separate package? :)

**Comment by Twixes** [comment]
It was made by Paolo, I suppose it's because it can be nicely packaged away as a Django `EXCEPTION_HANDLER` setting. Also, it's a bit of a contribution to the open-source world, there are some external users and contributors.
