### ISSUE TITLE
Popups no longer increase the screen-height if they can

### ISSUE THREAD

**Issue by benjackwhite** [PostHog/posthog#10338]
## Bug description

[This PR](https://github.com/PostHog/posthog/pull/10278) introduced an issue for non-modal views where the Popup no longer expands the window content

<img width="935" alt="Screenshot 2022-06-17 at 11 49 38" src="https://user-images.githubusercontent.com/2536520/174274298-d2dc1d0c-838e-464a-85dc-25751f9968c5.png">

## How to reproduce

1. Go to an Insight with EditorPanels on
2. Click the "add breakdown"
3. See the Popup doesn't expand fully

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

## Additional context

We have an [open WIP](https://github.com/PostHog/posthog/pull/10295) to move to FloatingUI which _may_ solve this. In the meantime we could add a property for this so that it is only set on views that need it

**Comment by clarkus** [comment]
I am not sure this change is an improvement. What's the core problem we're trying to solve? I get that there are constraints with sizing popovers and other popover-like components, but if we're cropping those components arbitrarily based on the viewport, they're going to be really cumbersome to use. I'd rather the user be made to scroll and see the full component size or that we place the component in such a way that we can show it fully while still being in context of the corresponding element that triggered it. 

**That taxonomic filter looks like it'll be very cumbersome to use to me. Here's what I'm seeing that causes me to question this solution:**
- Double scrollbars on the taxonomic filter. Depending on your cursor position, you might wind up scrolling a container you didn't intend to scroll. 
- In this approach, the taxonomic filter has the container height changed to fit within the viewport. This makes it so you can only really see the categories and search bar but very little of the list of results you need to click to select something. 
- What happens when you're really close to the bottom viewport edge and click this? Will you get a 20px tall taxonomic filter? What's the min-height there to ensure that the component is usable across scenarios? Does this also happen with the horizontal viewport edges?

**Questions I have that might inform an alternate solution:**
- Why wouldn't we let the user scroll the viewport to see the remaining 160px of the taxonomic filter? It's much easier to scroll the viewport, and it's a really natural and low friction user action. In this screenshot, I can see that the document has more content below the viewport edge... I'd have to scroll to see that anyway so why not allow that same interaction for this filter popover?
- Can we place the popover relative to the viewport in sensible ways? Why not flow the popover up instead of down when it collides with the viewport edge? Likewise if it's conflicting with the right edge, why not flow left?
- This gets somewhat into components that are more responsive to viewport constraints. If I think about this experience on a mobile device where the viewport is much more of a fixed size, how would this work? Could we place it such that it's still fully visible and usable without having to crop it to fit? 
- When the document edge and viewport edge are the same (you're at the bottom of the page and can't scroll futher) and you trigger a popover, what would happen? The linked PR says we can't increase the document height based on the popover size. Could we change flow instead to flow up instead of down? 
- Why not set a min-height on popover menus so that they show a reasonable amount of items but still don't push the limits with the viewport edges?

**Comment by benjackwhite** [comment]
I think this is a misunderstanding. The change before was to deal with popovers in a modal (for weird technical reasons scrolling isn't possible with the library we use so as a quick fix we made sure the select box never exceeded the window which worked well for that use case). 

This change essentially reverts that as a default and **only** applies it in the one tricky use case we have right now. 

@mariusandra is working hard on implementing the latest version which should solve (we hope) all of these edge cases.

**Comment by clarkus** [comment]
Got it. It wasn't very clear based on the description if this was an intended change or not. Just want to make sure that the popover overlays are flowing and placing in reasonable ways.

**Comment by mariusandra** [comment]
Here's the followup that hopefully fixes most things: https://github.com/PostHog/posthog/pull/10295
