### ISSUE TITLE
Remove `onAction` from apps

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#10404]
## Is your feature request related to a problem?

We added `onAction` as a potential plugin function, but it isn't being used at least on cloud. I think the documentation around it is also non-existing.

However it adds a lot of load to plugin-server as we need to:
1. Be consistently reloading _all_ actions - see https://metabase.posthog.net/question/344-most-time-consuming-postgres-queries
2. If a single action-related plugin is installed on a large team, _every_ action on _every_ event will be checked, slowing down the plugin server.

## Describe the solution you'd like

It's not being used on cloud. I think this is safe to kill as a result. Only reload actions related to webhooks.

## Describe alternatives you've considered

- Explicitly tag certain actions to be visible for plugin-server and only fetch/check these actions.
- Put this behind a environment variable as a beta feature.

## Additional context

cc @yakkomajuri as the original author of the feature
cc @marcushyett-ph for product context

**Comment by yakkomajuri** [comment]
Yeah as you note we still need actions for webhooks, so `onAction` might be blocking us from optimizing, but it didn't change the action reload logic already in place.

Nevertheless, I've become trigger happy with removing features, so happy to do so here. Me and Marius built this over a pairing session because Sam at the time had built a plugin that supposedly _required_ this, so not having it was blocking the Growth team. 

Either way, happy to nuke

**Comment by macobo** [comment]
> didn't change the action reload logic already in place.

I think there's a way to change logic to only reload actions which have webhooks/slack/etc attached which should still reduce load. I haven't verified this though.

**Comment by yakkomajuri** [comment]
Yeah I believe there might be a way indeed, just meant that when the feature was added the logic remained untouched
