### ISSUE TITLE
Adding actions causes Postgres out of memory with partitions

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#1059]
**Describe the bug**

Report from OpenRent that adding a simple $autocapture action causes Postgres to run out of memory. I think this has something to do with the fact that they've got things partitioned.

**To Reproduce**
1. TBD
2. 
3. 

**Expected behavior**

It should work.

**Screenshots**

**Hosted or self hosted?:**
- self-hosted

**Additional context**

**Comment by macobo** [comment]
@timgl Will I be looking into this tomorrow? Do we have a repro case? :)

**Comment by timgl** [comment]
The issue from what I've seen and been able to reproduce is:
- An instance that is [partitioned](https://posthog.com/docs/deployment/scaling-posthog)
- Has high-ish volume, somewhere around 3 RPS
- Has an action defined. This seems to happen with both pageview actions and $autocapture ("frontend element") ones, but I can consistently reproduce with a single autocapture event, even if that event doesn't match anything.
The errors that appear all indicate out of memory on the postgres database:
![image](https://user-images.githubusercontent.com/1727427/85517932-09ddaf80-b600-11ea-8be4-14c9942709ea.png)
Removing the one action solves these errors
- We do [some caching](https://github.com/PostHog/posthog/blob/master/posthog/models/event.py#L294) of the generation of the queries, so the issue here is the actual query that function generates causes the database to run out of memory quickly.

I think the solution is finding a way of making that query more optimized.

**Comment by macobo** [comment]
Thanks for the overview @timgl. I dug into this briefly as well:

So the issue seems to come from **data ingestion** running into errors on a high level.

On a high level, what happens during ingestion seems to be the following:
1. API receives a request, it gets queued in celery for the worker node to pick up (posthog/api/event.py)
2. Worker node processes event data, creates/updates appropriate users and events (posthog/tasks/process_event.py)
3. `Event.create` gets called, which first creates the event itself (posthog/models/event.py EventManager.create)
4. After saving, it finds actions associated with these events. (posthog/models/event.py Event#events)
5. From this it calculates relations to be added, adds them to the database (posthog/models/event.py EventManager.create)
6. Also notifies slack if there's a webhook

I think there's two ways to approach this:

### Specific problem: `Event.create` OOM

From above, we think the OOM error is caused by step 4, which is storing stuff in memory as well as querying the database. Note that `TEAM_ACTION_QUERY_CACHE` for example is never cleared, which might end up taking up a significant chunk of memory.

### High-level problem: does this flow scale?

There's two potential bottlenecks during ingestion:

1. API throughput
2. The database

Step 4 is fundamentally gonna require looking through the database in some fashion, in ways that get slower as users get more data. I think 2 is gonna become an issue much faster than 1 due to this.

Given that steps 4-6 (gonna call them post-processing henceforth) require tying up a lot of db resources, I'd argue it's worth doing them asynchronously from the rest of the ingestion. That would open us up to some further optimizations like:

1. Dedicated workers which can calculate event -> action relations more efficiently (by using e.g. in-memory caching). By using in-memory caching, this could ease the load on the db as well.
1a. Dedicated workers which are partitioned by e.g. team for hosted solution or by id range otherwise.
2. Scaling ingestion and "post-postprocessing" separately.
3. Post-processing in batches

The downside here is that the solution is more complex (scalability inevitably is) and that not all ingested data is always ready to query.

### My thoughts

I think it's briefly worth taking a look at the specific problem (e.g. via heapdumps, etc), I think most of the benefit will come from tackling the high-level problem here.

### Questions:

1) Is Celery set up to retry tasks when they fail or would they currently go to the dustbin?
2) Since action.events relation many-to-many is hard to scale, what are the arguments for it to be made "virtual"? I.e. instead of figuring it out at write-time, figure it out when querying. Not familiar enough with the schema yet to answer this.

**Comment by timgl** [comment]
Re the 'specific problem': the memory issue isn't on the worker side but definitely on the database side, as the errors are Postgres errors. So it's the query that we generate that's causing the issue.

Those queries are already called in the workers and they happen constantly, so I don't think handling them separately is going to work. Instead I'd be good to understand (using explain etc) _why_ these queries are using so much mem, because each query only calls a single event.

To answer your specific questions
1. I think we don't have any retrying implemented, could be worth looking at but would only make this specific problem worse
2. Querying at run time is what we had originally and become really slow, which is why we moved to m2m. It'd be awesome to find a way to do this quickly during run time but not sure that's realistic?

**Comment by macobo** [comment]
> Re the 'specific problem': the memory issue isn't on the worker side but definitely on the database side, as the errors are Postgres errors. So it's the query that we generate that's causing the issue.

Thanks for the additional context. :+1: 

> Those queries are already called in the workers and they happen constantly, 

I realize that and what I described above tried to take that into consideration.

So my goal with the "high level problem" was to bring out that there's a fundamental scalability issue trying to do ingestion not at 3 RPS but at 300 or 3000 RPS.

The latter is very well possible - but I posit the "post-processing" steps here would become the bottleneck due to how the underlying dbs work.

Given that this issue is at least tangentially related to this issue I thought it best to bring it up as well and to propose a solution.

In this case I think a solution to the high-level problem could help with the specific issue - being able to cache in memory, doing less expensive queries. That said, I think _both_ sides of this issue are worth taking a look at.

**Comment by macobo** [comment]
Discussed this with Tim. As said before - we'll tackle the "specific problem" for now. Happy I have some thoughts regarding scaling written down though :) Only later realized that this might not apply as badly as I thought since not every unique event type creates an action :sweat_smile:

**Comment by macobo** [comment]
@timgl How is OpenRent hosting posthog? Do we know what sort of memory/cpu limits their setup has, are worker/api/postgres co-hosted, how many actions they have?

**Comment by macobo** [comment]
I managed to create a repro case.

The issue is not directly related with partitioning itself, but is a function of autocapture + no of actions defined on autocapture + amount of data. Partitioning can however make the issue worse: queries may hit more partitions than needed.

## How to reproduce the issue

1. Get a dump of prod data on ph team (tim can help here)
2. Open shell via `python manage.py shell_plus --print-sql` (depends on PR https://github.com/PostHog/posthog/pull/1090). You might need to also set SHELL_PLUS_PRINT_SQL_TRUNCATE if you want to see full queries (https://django-extensions.readthedocs.io/en/latest/shell_plus.html?highlight=print-sql#sql-queries)
3. Run the following command(s):

```python
from posthog.tasks.process_event import process_event; import datetime

process_event(**{'distinct_id': '2020-06-22::0', 'ip': '127.0.0.1', 'site_url': 'http://0.0.0.0:8000', 'data': {'timestamp': '2020-06-24T14:07:36.150Z', 'event': '$autocapture', 'properties': {'$lib': 'posthog-node', '$lib_version': '1.0.3', 'some_prop': 'foobar', 'idx': 55}, 'type': 'capture', 'library': 'posthog-node', 'library_version': '1.0.3', 'distinct_id': '2020-06-22::0'}, 'team_id': 1, 'now': datetime.datetime(2020, 6, 24, 14, 7, 36), 'sent_at': None})
```

You should see in the console sql queries the process event does, with one of the queries taking ~40 seconds. Dump of the SQL it generated for me: https://gist.github.com/macobo/036d44d9143acd15937d87d7d6dcd7ab

Note that this query has 334 FROM clauses in various subselects.

## Background, what's causing the issue

So the query originates from the following lines in models/event.py: https://github.com/PostHog/posthog/blob/f6df41a/posthog/models/event.py#L348-L355

So lines 332 to 342 are trying to load all actions user has defined with the same name as the sent event ($autocapture in our case). 

Next steps on line 348-355 are trying to create a column for every one of these actions has a yes/no response if this action truly matches the event or not. This is done via a subquery generated by `query_db_by_action` function.

This logic breaks down when:
1. There are a lot of actions which match the sent event
2. There is a considerable amount of data already in the db
3. Query generated does not work as intended

All 3 are the case here:
1. $autocapture has a lot of actions defined - by nature. 
    - Postgres in turn needs to do a lot of work running a bunch of subqueries and then joining the results of which back together. I'd say this is a relatively tricky task for pg.
2. prod database has considerable size, though not massive by any means currently.
3. $autocapture queries can get tricky 
    - see e.g. https://github.com/PostHog/posthog/issues/1089 for an example where the generated subquery is much more complicated than expected. 
    - See also the generated explain in gist above - some of these subqueries are far from simple. See e.g. https://gist.github.com/macobo/036d44d9143acd15937d87d7d6dcd7ab#file-explain-sql-L424-L641 which is one of "Deploy to X" actions which gets turned into quite a complicated subquery, most of it to do with css selector matching.

#### Q: What about caching, does it help here?

There's a caching layer implemented in posthog/models/event.py, but this caching does not affect this problem - it only deals with query building, not executing it. 

## Where to from here?

This seems like a NotTrivialProblem™ - a side-effect of the current schema choices.

Some thoughts/ideas/suggestions:

1. Pulling out separate workers for action <-> event matching still seems like a great idea for the reasons outlined above. Instead of doing the matching in complicated SQL queries which both the ORM and postgres struggle with, this would mean we can do the matching in memory and load actions from the db lazily - easing the load considerably.
2. Loading actions into memory within the current pipeline should work well and also lend itself well to memoization/caching.
3. Optimizing CSS selector matching will help both here and elsewhere. The current solution tricky currently both in terms of SQL it generates and performance. Few ideas: it might be possible to extract a PL/pgSQL function for doing this matching or turn the css selector into a regex.
4. Reconsider actions completely. Currently they are used for both "annotating" common filters, making some queries more efficient (thanks to the 1:n relationship with events) and slack webhooks. Perhaps instead of trying to solve all 3 issues at once, instead make actions focus on the filtering part and use other tricks (indexing/queues/workers) for the latter two.
