### ISSUE TITLE
Back end events are confusing to users who didn't implement them

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/posthog#106]
**Is your feature request related to a problem? Please describe.**
* PostHog receives back end events AND Front end ones.
* Front end ones are easy for non technical users to understand. You can see them.
* Back end events currently appear like this:

![Screenshot 2020-02-16 at 12 32 39](https://user-images.githubusercontent.com/47497682/74612264-90b1d700-50b8-11ea-9095-7c3fd25f66e7.png)
* As someone who didn't implement that event, I don't have any context on where it came from. 'User signed up' could mean many things (sidenote: object - verb is best practice for labelling events),

**Describe the solution you'd like**
* Add a property to the event automatically based on the API. For example, adding a property automatically that says "event_source: python API" or similar?
* Encourage the back end API to capture the Event title AND a description property, so that I can have a bit more context as to what the event is.
* In the Actions table at /actions, add a column to make it very clear if an Action is back or front end by tagging it as 'PostHog Toolbar' | "Python API" | whatever, for each event type within the Action. That'd mean as a marketer I'd know where the ACtions actually come from.
* In the Events table at /events, add the same column - the tag for where the event came from
* In the 'Edit action' page, a back end event will say 'Match event' as the event type. The event name should be listed in the dropdown, but ideally it'd also have the tag right after it ie Python API, so I'd know what it actually is, in this section:
![Screenshot 2020-02-16 at 12 36 20](https://user-images.githubusercontent.com/47497682/74612312-22214900-50b9-11ea-9345-c50db79cb3a4.png)

**Describe alternatives you've considered**
* Asking an engineer on our team. That's annoying for them.

**Additional context**

**Comment by timgl** [comment]
@jamesefhawkins I have ticked off following

- [x] Add a property to the event automatically based on the API. For example, adding a property automatically that says "event_source: python API" or similar?

- [x] In the Actions table at /actions, add a column to make it very clear if an Action is back or front end by tagging it as 'PostHog Toolbar' | "Python API" | whatever, for each event type within the Action. That'd mean as a marketer I'd know where the ACtions actually come from.
- [x] In the Events table at /events, add the same column - the tag for where the event came from


I'm not sure what you mean by
- [ ] Encourage the back end API to capture the Event title AND a description property, so that I can have a bit more context as to what the event is.

Do you mean every time you add an event in the backend using `posthog.capture('user signed up')` you'd add something like `, description="This happens when a user signs up"` or something?


- [ ] In the 'Edit action' page, a back end event will say 'Match event' as the event type. The event name should be listed in the dropdown, but ideally it'd also have the tag right after it ie Python API, so I'd know what it actually is, in this section:

This one is harder to do as the same event can come from multiple places (frontend/backend). Maybe we could show like (70% python, 30% JS) but it's a lot of faff and not sure it adds too much value (esp given what's already been done)?

**Comment by jamesefhawkins** [comment]
Thanks for this Tim - it's already nicer. 

To answer your qs:

> Do you mean every time you add an event in the backend using posthog.capture('user signed up') you'd add something like , description="This happens when a user signs up" or something?

Yes.

> In the 'Edit action' page, a back end event will say 'Match event' as the event type. The event name should be listed in the dropdown, but ideally it'd also have the tag right after it ie Python API, so I'd know what it actually is, in this section:

Let's drop that for now if it's hard. You're at 90% of the value already.

**Comment by timgl** [comment]
Done
