### ISSUE TITLE
Bad update link

### ISSUE THREAD

**Issue by CrBast** [PostHog/posthog#1061]
**Link to posthog update docs is broken (from update news page)**

![image](https://user-images.githubusercontent.com/31575093/85201792-69874280-b302-11ea-9c50-cf35a4bce9c0.png)

Link url : https://docs.posthog.com/#/upgrading-posthog => https://posthog.com/

**To Reproduce**
1. Click on "New version available" button
2. Click on "Click here for instructions on how to update PostHog"

**Expected behavior**
Opening the documentation with the right url (https://posthog.com/docs/deployment/upgrading-posthog)

**Hosted or self hosted?:**
- self-hosted (only tested on self-hosted)
- 1.8.0

**Comment by timgl** [comment]
Done!

**Comment by crbast** [comment]
Hi 👋, the link doesn't work anymore 

**To Reproduce**
1. Click on "New version available" button
2. Click on "Click here for instructions on how to update PostHog"

**Expected behavior**
Opening the documentation with the right url (https://posthog.com/docs/deployment)

**Hosted or self hosted?:**
- self-hosted (only tested on self-hosted)
- 1.8.0
