### ISSUE TITLE
Apps take ~20 minutes to shut down

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#10765]
## Bug description

After disabling an app it still takes ~20 minutes to shut down (on cloud)

## How to reproduce

1. Enable a plugin
2. Disable it

Hubspot plugin disabled at 13:05, continued working until 13:22
<img width="1283" alt="image" src="https://user-images.githubusercontent.com/1727427/178733702-02fa80d8-857b-4db7-b28c-b99d7c77249b.png">
<img width="1193" alt="image" src="https://user-images.githubusercontent.com/1727427/178733726-b0cb57ba-ae33-4406-ad91-2ed90619a92a.png">

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

## Additional context

Yakko suggested it might be waiting until the next deploy
https://posthog.slack.com/archives/C0374DA782U/p1657714680319529

**Comment by yakkomajuri** [comment]
As one would expect, this is also affecting config updates etc which makes things very hard to debug.

A few random ideas I'll just drop in here:

- Provide some feedback to the user about what "app version" is running, either by printing the config, or displaying some version number that can be cross-referenced in the logs. Note that this sounds like duct-tape over the problem but it actually isn't - even if we fix the issue here there will always be a delay between when you click a button and when the app updates, and that distinction is probably useful
- A hunch here is that we might want to look into the pubsub system - the less likely thing is that it has an issue, the more likely thing is that we're triggering the update/disable when some but not all plugin servers are ready, and thus they get lost
