### ISSUE TITLE
FF UI: Have an 'Enabled' toggle at the bottom

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/posthog#10986]
## Is your feature request related to a problem?

Say you want to create a new flag. You got to the Feature Flag section, you fill out all the info. It's a long page. Eventually you get to the bottom and you press Save. 

<img width="712" alt="Screenshot 2022-07-26 at 17 02 51" src="https://user-images.githubusercontent.com/84011561/181054702-e24b11ee-644b-45bf-b941-613151a35efe.png">

But, do you want that flag enabled, or not? That's a natural last decision to make. But that toggle? It's at the top of the page, so you have to scroll back to the top. 

<img width="711" alt="Screenshot 2022-07-26 at 17 03 45" src="https://user-images.githubusercontent.com/84011561/181054867-28d1fa8c-13ec-48ce-834e-f96212e5336d.png">

Feels like the last thing you want to do shouldn't be the first thing on the page. 

## Describe the solution you'd like

Mirror the enabled toggle to the bottom of the page, so that users don't accidentally save a flag in the enabled position when they want it off. 

## Describe alternatives you've considered

We could move it to the bottom, but what if you're checking out an existing flag? Then you don't want to scroll down. Seems best to have it in both places. 

## Additional context

@clarkus

**Comment by clarkus** [comment]
There is an upcoming effort for updating feature flags documented at https://github.com/PostHog/product-internal/pull/324. The changes here could be considered as part of the scope for that work. That said, I don't think we should have multiple controls for toggling the flag on or off. Instead of placing the switch in the header and the footer, why not just have a reasonable default (off) and put in the main form area for the flag? That would make it straightforward to configure the flag and leave it off until the user is read to enable / launch it. This also aligns with how experiments work. 

We need to add distinct edit and read views for flags to ensure permissions and ownership are enforced. If the core problem is making it easy to enable / disable flags, I could see us doing that view specialized workflows for users with appropriate access to the flag. As an example, you configure a flag and save it as disabled. When ready to launch, we could have a user edit to enable / launch the flag, or we could have a menu item for the flag that makes enabling / disabling immediately available form the list view for users with sufficient rights to change the flag.

**Comment by joethreepwood** [comment]
There you go again, Chris. Proposing perfectly reasonable and well-thought-out responses to my incredibly minor issues. 😂
