### ISSUE TITLE
Simplify getting started with local development

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#1099]
**Is your feature request related to a problem? Please describe.**

Currently getting started with local development can be tricky due to setting up various tools.

**Describe the solution you'd like**

Current approach is outlined in https://posthog.com/docs/developing-locally.

It should only take a few commands to start developing and development scripts should work on all setups. For this reason, standardization is needed.

Thoughts on how to make this happen:

1. Suggesting to use `docker-compose -f docker-compose.dev.yml up db redis` over installing postgres + redis via brew/apt. This gets rid of some steps in local setup.
2. Using dotenv to manage all local environment variables, providing a baseline .env file (which assumes a docker-based setup) inside the repo. Current solution causes a ton of incompatibilities with some of the `bin/` scripts, I've needed to monkey-patch all the test-running scripts at least once. 
3. Switching database port in dev.yml from 5439 to 5432, but making it configurable via environment variable. This should satisfy both having a easy first-time-setup but also give flexibility to users like @fuziontech who might have multiple postgres instances running locally.
4. Suggesting to use [pyenv](https://github.com/pyenv/pyenv) or similar, providing instructions for turn-key solutions. Virtualenv is fine but requires quite a lot of setup every time project is opened.
5. Worker docker image sometimes leaves `celerybeat.pid` laying around and refusing to start while it exists. This can create some confusion both when looking at the UI or when doing development.

Some other suggestions not directly related to first setup:
1. Set up, suggest using better development consoles, write instructions on how to get code autoreloading to work there. This will help people experiment with the ruby code faster. Open PR: https://github.com/PostHog/posthog/pull/1090
2. Split code up more - it's currently hard to figure out where to put code and tests _because_ there's a lot of large files.

**Describe alternatives you've considered**

Docker-compose based development, but this gets messy fast when needing to run migrations, update dependencies or anything else.

**Additional context**

Love the work that has been put into this already - kea, black, etc are all awesome tools.

***Thank*** you for your feature request - we love each and every one!

**Comment by macobo** [comment]
Note: I might be interested in solving these issues if cycles free up. It should be relatively straight-forward but a bit worried about breaking deploys with the dotenv setup.

**Comment by fuziontech** [comment]
Hey! Personally I am a huge fan of what is suggested on the top of the [dev doc](https://posthog.com/docs/developing-locally)

```bash
docker-compose -f docker-compose.dev.yml up
```

I don't think it's too much of a hassle to run
```bash
docker-compose -f docker-compose.dev.yml run web python manage.py makemigrations
docker-compose -f docker-compose.dev.yml run web python manage.py migrate
```

I am super fond of docker-compose driven development since it ensures consistency overall and think the trade-offs are generally worth the simplified management of dev environments. I personally use mac, windows, and ubuntu to dev and I love docker-compose for making development so easy.

The worst case generally is an updated dependency where you have to `build` the entire stack over again, but that is a small price to pay.

My personal belief and what I've seen work elsewhere is to basically focus on the generic docker-compose setup since that will get people setup the fastest and then allow people to use whatever they want if they want to go 'power user' since most people have their own setups that they are comfortable with. As an anecdote I'm a huge user of virtualenv burrito when I want to setup an environment locally out of a docker container.

Final though:
I do think it makes sense in this context to recommend people to use docker to bring up postgres and redis locally so I am totally down for changing up the ports on the setup to be 5432:5432, but definitely keep in mind a lot of people already have pg and redis already setup. This is especially true on their personal laptops if they are doing open source for fun. So it's a balance between keeping things simple and having the fewest potential hiccups like a conflicting port, and providing 'power users' the flexibility of pulling things out of the composition selectively. Suggesting to start those up with docker makes the instructions cross platform too which is better than just having brew instructions.

I do think there is room to improve here, especially around getting building the frontend more consistently. I have to run `yarn build` pretty frequently to have the css display correctly.

**Comment by macobo** [comment]
Good thoughts @fuziontech! Would be awesome to hear other contributors weigh in as well. :)

> My personal belief and what I've seen work elsewhere is to basically focus on the generic docker-compose setup since that will get people setup the fastest and then allow people to use whatever they want if they want to go 'power user' since most people have their own setups that they are comfortable with.

Agreed re getting started with docker-compose when initially testing things out - it's a great way to start quick and small and avoid dependency hell.

I usually end up switching to local setup quite quickly due to issues you mention here: rebuilding containers when dependencies change usually ends up wasting 5-15 minutes. I have also run into a lot of similar issues with webpack-dev-server inside docker-compose and restarting it can be a pain.

One thing I consider a pain is that currently being a power user means also patching bin/ files to get tests running. This in turn makes the tooling harder to iterate upon and improve for all.

> So it's a balance between keeping things simple and having the fewest potential hiccups like a conflicting port,

This is where I think dotenv can really help with a lot though since you can make docker-compose ports depend on environment variables.

**Comment by fuziontech** [comment]
Agreed overall. For the dotenv config are you referring to something like this? https://github.com/fuziontech/graph2/blob/master/local.yml#L18

```yml
services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: graphy2_local_django
    container_name: django
    depends_on:
      - postgres
    volumes:
      - .:/app
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start
```
Where you specify `env_file` params to docker-compose? This would definitely clean up our docker-compose config files, but I don't think it would help with programatically setting the host port for the container. You might be talking about something totally different though :p

**Comment by mariusandra** [comment]
I'll add 0.02 EUR here - for me developing locally with docker is not a viable solution. The reason is that I heavily rely upon the python debugger inside PyCharm to get anything done. This won't work in docker... or at least not without serious setup.

**Comment by fuziontech** [comment]
good point, that's usually when I break it out with what Karl was saying `docker-compose -f docker-compose.dev.yml up db redis` and sometimes `worker` if I need to and then boot up the debugger in pycharm.

**Comment by adrienbrault** [comment]
I can recommend the approach taken by https://github.com/home-assistant/core with "Visual Studio Code + devcontainer": https://developers.home-assistant.io/docs/development_environment/#developing-with-visual-studio-code--devcontainer .

It was really simple and quick to get a local environment running, with the debugger working.

**Comment by Twixes** [comment]
This is now done – https://posthog.com/docs/contribute/developing-locally
