### ISSUE TITLE
Toolbar Bug

### ISSUE THREAD

**Issue by lottiecoxon** [PostHog/posthog#1100]
Hi guys, I was using the toolbar this morning to see how it looked visually, and I think I found a bug. When you click on the hedgehog after using the other features within the toolbar, it zooms out and becomes very strange on my screen- was unsure if this was supposed to happen. I can still click on certain buttons but it wouldn't let me zoom back in to the normal screen and the blank white sections couldn't be moved- I will attach an image to show what I am on about
![Screenshot 2020-06-26 at 10 41 50](https://user-images.githubusercontent.com/65415371/85844110-1d248280-b79a-11ea-8586-b82a684cb28c.png)

**Comment by mariusandra** [comment]
Hey! Thanks for reporting! Some or most of this problem should have been fixed yesterday... but the fix is not yet live. Unfortunately [something broke](https://github.com/PostHog/posthog/pull/1009#issuecomment-650148484) and I can't deploy the latest version. I'll post an update once it's working :)

**Comment by mariusandra** [comment]
Hi @lottiecoxon , a new bunch of fixes for the toolbar went up a few hours ago. Could you check and report if you're still seeing that weirdness?

**Comment by lottiecoxon** [comment]
@mariusandra Just checked and all good! It looks great - I love what you've done with the fire icon !

**Comment by mariusandra** [comment]
Wonderful! Closing this issue then! 🔥
