### ISSUE TITLE
Sessions are very slow/don't load on app

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#1107]
**Describe the bug**

Sessions don't finish loading on app

**To Reproduce**
1. Go to app
2. Go to sessions

**Expected behavior**

Should work. The strange thing is that this happens even for smaller clients (where you'd think the indexing of team_id would make sure this works properly).

**Comment by EDsCODE** [comment]
I think ideally for this data especially, there should be no need for recalculating at all. Once the sessions have been found and stored in a db they should just be permanently stored as is. Right now, every time the endpoint is hit, the events table has to be queried, grouped, and transformed into sessions but history of sessions don't change. I had originally tried to use materialized views but even this type of caching is unnecessary as materialized views will need to be refreshed and the refresh will update the entire history of sessions again. A possible solution would be some sort of incremental table that periodically gets updated with new event data

**Comment by mariusandra** [comment]
I've been absent from the work on sessions... and haven't followed the previous discussions, so I apologise if this has been discussed. But indeed why not implement this incremental table?

More specifically, could this work:

- Every time a `$pageview` / `$autocapture` / whatever event is captured, we add a `session_id` to the event. This `session_id` is taken by running `select session_id from events where distinct_id = $1 and created_at > 1.hour.ago` (and from probably also a redis cache that's in front of the query).
- If nothing is returned, generate a new string/ID. 
- To avoid race conditions making duplicate sessions, the session ID could be "semi-random". For example: `session_id = md5(distinct_id + date_in_utc + hour_in_utc)`. This way all 30 events coming in at the same moment would still be hooked to the same session.
- Create a "sessions" table, where we store that ID and various other metadata that will be updated and kept up to date (first_event_time, last_event_time, etc)... This table would be updated async from the event capture itself I'd guess.

**Comment by mariusandra** [comment]
I've been debugging this a bit... and there's something strange happening. Perhaps someone with mode Django experience can pinpoint the issue quickly.

The slowness doesn't come from the sessions query. On my local db with 1M rows it takes ~11sec. Not great and could definitely be improved, but that should be fine.

However the page still doesn't load... and that's because [this line](https://github.com/posthog/posthog/blob/da5a48c33d059be9d5c0cb4259524560454e2df8/posthog/api/event.py#L302):

![image](https://user-images.githubusercontent.com/53387/87050827-13ba0200-c1ff-11ea-8501-d9ddb21e12cf.png)

... triggers this query that pulls in ALL the events since the dawn of time:

![image](https://user-images.githubusercontent.com/53387/87050621-cb024900-c1fe-11ea-85fc-db86e779a01d.png)

... and takes forever. 

I don't know *why* this happens. AFAIK a queryset should be "lazy" and only evaluate itself in the end. Yet here just adding a filter to it causes it to fetch a million events.

**Comment by EDsCODE** [comment]
#1221 potential fix

**Comment by EDsCODE** [comment]
fixed this specific issue. sessions could still be faster
