### ISSUE TITLE
Regression: Sidebar new Insight icon no longer has hover

### ISSUE THREAD

**Issue by benjackwhite** [PostHog/posthog#11108]
## Bug description

Sidebar new Insight icon used to have a hover state even when selected but now it doesn't.

**Comment by Twixes** [comment]
This is what hover looked like before:
<img width="238" alt="before" src="https://user-images.githubusercontent.com/4550621/182585531-d4a065b2-9e01-46d6-b1ac-bad9b177d797.png">

And here's now:
<img width="241" alt="after" src="https://user-images.githubusercontent.com/4550621/182585533-1fdc2e98-5074-4366-9635-903dd53e9b2c.png">

The regression comes from the new color palette's hover and active colors being fully opaque instead of translucent.

**Comment by clarkus** [comment]
I updated the documentation in [figma](https://www.figma.com/file/Y9G24U4r04nEjIDGIEGuKI/PostHog-Design-System-One?node-id=3249%3A1311) for this scenario. I think it's the only case where this applies right now. 

<img width="1256" alt="Screen Shot 2022-08-03 at 1 20 04 PM" src="https://user-images.githubusercontent.com/254612/182702927-c343d72f-e259-462f-8a63-a529acd94435.png">
