### ISSUE TITLE
Toolbar action counts seem incorrect

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/posthog#1127]
**Describe the bug**
Using the new toolbar on the homepage shows a count of 36:

![Screenshot 2020-06-30 at 14 44 17](https://user-images.githubusercontent.com/47497682/86133503-47e74180-bae0-11ea-86e4-39e98564c815.png)

However, I can only see these two numbers on the page:

![Screenshot 2020-06-30 at 14 44 13](https://user-images.githubusercontent.com/47497682/86133613-7107d200-bae0-11ea-954f-c804c31d4385.png)

(I presume this is because there are actions that aren't tied to an element that use this URL? In which case, perhaps these need displaying somehow OR the number should have them removed?)

Else, could it be because there were actions made on this page for elements that are no-longer there? In which case we need to work out how to treat those.

**To Reproduce**
1. go to posthog.com as a posthog team member logged into app.posthog.com
2. use the toolbar - see the counts

**Expected behavior**
I'd expect to see the actions count add up to the count of the elements on the page

**Comment by mariusandra** [comment]
Hi! This is indeed misleading. The reason is that the "actions list" that opens when you click the number shows all actions that are enabled on the Current URL, sorted alphabetically. "Enabled on the current url" means that either the url is empty or matches the current page. 

![image](https://user-images.githubusercontent.com/53387/86136145-fe045880-baeb-11ea-8477-31f246e5d6a0.png)

However, indeed: if the element that the action targets is no longer present, we can't really show it. One idea is to split the "actions (36)" list into "visible actions (9)" (expanded by default) and "other actions (27)" (collapsed by default).

For the "get started for free" button - there's a bunch of actions defined on this element. The number is just for the first one in the list (alphabetically). I would like to show "has many actions" somehow. The best idea I had so far was to just write `4+` instead of `4`.

**Comment by paolodamico** [comment]
Adding to this, I found another case were numbers change weirdly depending on the querystring. Maybe it's filtering depending on the QS? See below,

![base](https://user-images.githubusercontent.com/5864173/92240981-180f3e00-ee83-11ea-9134-b83afa68c400.png)
![qs1](https://user-images.githubusercontent.com/5864173/92240984-1a719800-ee83-11ea-93ee-bd5b7b2b4579.png)
![qs2](https://user-images.githubusercontent.com/5864173/92240988-1ba2c500-ee83-11ea-8431-95192d4003f4.png)

**Comment by Twixes** [comment]
Yeah, query strings are funny business, because a difference in the query string can mean both just a cosmetic change and a different page altogether. I do think however that in most cases the toolbar could disregard the query string. _Usually_ it's a different variant of the same page, so that should make sense.

**Comment by mariusandra** [comment]
I think this can be tackled together with https://github.com/PostHog/posthog/issues/4364 . I'm imagining you'll be able to specify what part of the URL will be searched for, including if the query string should match or not.
