### ISSUE TITLE
Support for feature flags in all client libraries

### ISSUE THREAD

**Issue by sjmadsen** [PostHog/posthog#1138]
**Is your feature request related to a problem? Please describe.**
The recent introduction of feature flags in 1.10 is not exposed to all client libraries. I'm using the iOS client myself, but I'll guess that users of other libraries would also like to check feature flags in their apps.

**Describe the solution you'd like**
Expose the value of feature flags for a user in all client libraries

**Describe alternatives you've considered**
I could reverse engineer how the JS library does it and make the necessary API calls myself, but this feels like something that should be exposed in the official libraries.

**Comment by timgl** [comment]
This'll be a non-zero amount of effort for each library. If you're reading this ticket and want this for your library, leave a comment. That way we'll know what to prioritise :)

**Comment by timgl** [comment]
My general spec:
- if `load_feature_flags()` is called, load all feature flags into memory and start a poller to update
- If a feature flag is `simple` (ie they only have a percentage distribution) we can do the checking of them offline
- If it's not (it uses person properties/cohorts) call out to server with the distinct_id to get the correct decision
- In either case, send a `$feature_flag_called` event with metadata (distinct_id, feature flag, time, library etc)

For now, we should recommend people use a personal api token as their api_key for backend servers. Feature flags aren't a massively popular feature yet and we can change that when this becomes an issue

**Comment by yakkomajuri** [comment]
I think this is the correct approach. 

And yeah the point about global API keys we discussed might become valuable later, but it's not unreasonable to expect (for now) that if a user leaves an organization they would notice the team that their API key was the one there. 

In general, I think it makes sense to slowly move away from team tokens to personal API keys (or a global equivalent) on the integrations since the personal key should now be able to do everything the token does and more.

**Comment by timgl** [comment]
I think the global write-only team token still makes sense for the frontend, but agree with the rest.

**Comment by yakkomajuri** [comment]
Oh right yeah I should have made that clear. I mean the frontend **has** to use the global token because the key is publicly available in that case, I meant the other integrations.

**Comment by fuziontech** [comment]
Seems reasonable. Can we change polling to a caching strategy? I that way we can have some feature flags that are cached and others that are not. At first we would only support cached flags, but eventually it might make sense to have a param for feature flags that is the TTL and evaluate that in the lib whether or not you can make a decision with the information that is cached in the lib or do we need to reach out to the posthog backend to get fresh rules.

You can kind of think of this as the same strategy as DNS with the TTL for an entity. Over time some entities will be sensitive to delay. At a previous company we had a feature flag go out that broke the client experience and there was nothing that could be done until the cache was busted (in this case it would be until the next poll). Would be nice to leave the door open to optimizations like that in the future.

**Comment by timgl** [comment]
LaunchDarkly has 30 second polling by the default which should be good enough for all use cases I think? The thing I never really get about TTL is you only think about setting a short one when you want it to be changed right now ha!

Edit: I guess you're aiming at "what happens if we have 1000s of feature flags" is that right? Still it seems like LaunchDarkly does this and they must have a decent amount of feature flags for some clients

**Comment by paolodamico** [comment]
> LaunchDarkly has 30 second polling by the default which should be good enough for all use cases I think? The thing I never really get about TTL is you only think about setting a short one when you want it to be changed right now ha!

In general I agree with a short TTL, especially if we're pushing the case (as in the new landing website) of using feature flags to roll-out new "experimental" features that might break something (you would likely want to roll back pretty quickly).

**Comment by timgl** [comment]
Just had a look at the way launch darkly does it, default they poll every 30 seconds for serverside libraries and every 5 minutes for client side libraries (like iOS). I'm still a little confused about the added benefits of a TTL on top of this?

**Comment by marcusgadbem** [comment]
> If you're reading this ticket and want this for your library, leave a comment.

It would be quite nice to have it on react-native sdk. 🙂

**Comment by Twixes** [comment]
Thanks for the issue! We've been working on spreading feature flags – now available in libraries for:
- JS (browsers)
- JS (Node)
- Python
- PHP
- Ruby
- Go

We will continue to add more in the future. For iOS specifically, status of this can be tracked in issue PostHog/posthog-ios#17.
I'll close this due to above progress + it being easier to track in issues per library.
