### ISSUE TITLE
Z-Index in donut charts wrong

### ISSUE THREAD

**Issue by corbt** [PostHog/posthog#1140]
**Describe the bug**

Tooltip with details about a specific segment of a donut chart shows up below the total user count in the center.

**To Reproduce**
1. Create a donut chart
2. Mouse over one of the segments

**Expected behavior**

The tooltip should appear above the user count.

**Screenshots**

<img width="316" alt="Screen Shot 2020-07-02 at 11 21 24 AM" src="https://user-images.githubusercontent.com/176426/86396255-70914780-bc56-11ea-92c6-c34a0a8a7178.png">

**Hosted or self hosted?:**
-self-hosted, 1.10

**Comment by mariusandra** [comment]
Hey! This is indeed an annoying quirk :). 
The problem is that the pie together with its floating label are rendered as a `canvas`, while the number on top is just a `div`. With the current implementation it's not possible to put the label above the number.

Since this is just a simple donut, it might make sense to replace the complicated vanilla JS code that we're calling with some simple React components that dynamically render a SVG.

Here are some examples of existing React SVG pies, though we should probably fork and extend them for our usecase:

- https://cedricdelpoux.github.io/react-svg-piechart/
- https://toomuchdesign.github.io/react-minimal-pie-chart/index.html?path=/story/pie-chart--full-option
- https://codepen.io/sujayraaj/pen/yPVGRx
- https://codepen.io/CrocoDillon/pen/dJMYKd

**Comment by corbt** [comment]
As a workaround/short-term fix, making the number on top smaller so it obscures less of the middle area would make this problem marginally less annoying.

Tangentially, would also be useful if the top 10 categories or so showed up as a legend to the side of the pie chart so I didn't have to mouse over it to remind myself which category corresponds to which slice.

**Comment by yakkomajuri** [comment]
Regarding the idea by @corbt of having a quick temporary fix, there's also two other options in my view:
1. Take the number out from the middle and add it at the bottom with a "Total" label (e.g. "Total: 16462")
2. Make the number disappear on hover

**Comment by Kacppian** [comment]
I'd like to pick this up. I would personally prefer point 1, it's cleaner IMO

**Comment by timgl** [comment]
@Kacppian Awesome! Let me know if you need any help getting started :)

**Comment by mariusandra** [comment]
Hey! Thanks for the work @Kacppian ! 

However I'm going to have to reopen this issue :). I had a look and the pie charts look really great now at a certain size:

![image](https://user-images.githubusercontent.com/53387/87140576-09047900-c2a2-11ea-92af-27f328700bb9.png)

... but when the dashboard item is differently sized, the text shows up in funny ways:

* Not visible
![image](https://user-images.githubusercontent.com/53387/87140414-c17ded00-c2a1-11ea-8402-2dff60de5cfd.png)

* Not properly centered (text-align) ... the location at the bottom is fine I think
![image](https://user-images.githubusercontent.com/53387/87140439-cb9feb80-c2a1-11ea-9fab-ef89abf1408c.png)

* Too much whitespace... and the text should probably be bigger
![image](https://user-images.githubusercontent.com/53387/87140463-d65a8080-c2a1-11ea-9a05-b4e59f20419d.png)

* Also, I can't select the text. This wasn't possible with the previous version either, so it's not a "new bug"... but at least it's written down now :)
![2020-07-10 11 41 44](https://user-images.githubusercontent.com/53387/87142161-70232d00-c2a4-11ea-84d5-47d92d3acacf.gif)

@Kacppian I really appreciate the work you put in the PR. Feel free to pick this up again if you wish. Otherwise, the issue will remain open.

**Comment by timgl** [comment]
@mariusandra Do you want to revert that PR? Or leave for now

**Comment by Kacppian** [comment]
I'll pick it up again. Really sorry for the inconvenience :(

**Comment by timgl** [comment]
No worries at all! I should have QA'd better :)

**Comment by EDsCODE** [comment]
#1211 finishes this i believe
