### ISSUE TITLE
Pageview urls / wildcards on user paths styling broken

### ISSUE THREAD

**Issue by camerondeleone** [PostHog/posthog#11489]
## Bug description
This has been broken for a long time. Probably need to expand the container to view the entire url. It would also probably be prudent to use the path name property here by default and then let people use url if desired / show them path cleaning options then? 

<img width="517" alt="image" src="https://user-images.githubusercontent.com/56287180/186543926-9438bede-5525-45b5-a00c-b39829942fa6.png">

## How to reproduce

1. 
2.
3.

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: please provide

**Comment by seunexplicit** [comment]
Hi @camerondeleone, can you please provide steps to reproduce this issue

**Comment by clarkus** [comment]
> This has been broken for a long time. Probably need to expand the container to view the entire url. It would also probably be prudent to use the path name property here by default and then let people use url if desired / show them path cleaning options then?

This tricky - URLs by their nature can be really long and complex. I think the best solution would be some smart truncation where we clip the redundant, non-identifying parameters and instead focus on the parameters that make the URL easily distinguished. I don't think we can show the full URL in every case because of space constraints and the nature of the taxonomic filter.
