### ISSUE TITLE
Having to save title changes as well as insight changes can be confusing

### ISSUE THREAD

**Issue by andrewm4894** [PostHog/posthog#11551]
## Bug description

https://posthogusers.slack.com/archives/CTLTM70RM/p1661521059037479

i often add a title in here, forget to press save on the title, then save the insight itself. And then end up with strange names. I'd expect that when i type into the title box, clicking anywhere else on the screen is same as clicking save.
having to save the title name and then save the insight sometimes is strange.

![image](https://user-images.githubusercontent.com/2178292/187444068-828f5a56-1d42-47f2-b34e-c1a13dcafb91.png)

## How to reproduce

1.
2.
3.

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: please provide

**Comment by clarkus** [comment]
Reopening due to the feedback in our internal [slack thread](https://posthog.slack.com/archives/C0368RPHLQH/p1662460197312949).

**Comment by clarkus** [comment]
I've spent a bit of time on this, and I've come to a different solution. I think we should restore the old pattern, but change the workflow. Here's what I propose for a workflow:

- User clicks the edit action
- The corresponding value (name or description) changes to use an inline-editable style, the field is focused and the contents are selected so that a user may start typing immediately to change the value.
- If the user clicks cancel, the changes are discarded and the input reverts to its read only style with the previous value
- If the user clicks save or (and here's the critical change) blurs the inline-editable field, we submit the change with the new value and the insight is updated.
- On save, display a toast notification that confirms the status of the action and provides a quick means of undoing the change
- Worth noting that this workflow also applies to dashboards, so we should try to be consistent with changes there. Currently dashboards are using the previous workflow while insights are using the persistent inline-editable style. 

This change will bias the workflow towards saving the new value. It could lead to more erroneous renames occurring but given the feedback it feels like a change worth trying. 

The alternative is to double down on the read and edit views. This would mean limiting rename actions to the insight edit view only. The name and description fields would use our standard label & input form patterns with the same validation rules that we apply to other parameters. The benefit here is that we bypass the inline-editable pattern and present all editable parameters consistently. It would also make rename actions restricted to just those users who have permission to edit the insight. This permission enforcement is true today, but it requires we handle renames on the read only view of the insight. 

If we have to chose a starting place, I'd advocate for the modified inline-editing workflow I described above. Thoughts?

**Comment by pauldambra** [comment]
Yep, I'll squeeze this in today. That was the first version of the fix iirc :)

**Comment by pauldambra** [comment]
This is resolved on insight and dashboard pages now by #11774 

We use this pattern on the calculated event page. But there's no view mode. Visiting a calculated event goes straight to an edit page and the editable fields there are controlled by the form. Is it better to use simple inputs in that page @clarkus ??

## a calculated event

![2022-09-15 08 37 59](https://user-images.githubusercontent.com/984817/190344356-78d04af4-ef28-474c-87b5-d305db2f2acf.gif)

## new onBlur interaction elsewhere

![2022-09-15 08 39 10](https://user-images.githubusercontent.com/984817/190344733-8a17ef47-dca7-464c-8304-ee1c70e6c1c3.gif)

**Comment by pauldambra** [comment]
I'm going to close this since (I think) we've resolved the direct issue.
