### ISSUE TITLE
Releasing rolling averages

### ISSUE THREAD

**Issue by EDsCODE** [PostHog/posthog#11716]
## Is your feature request related to a problem?

*Please describe.*
Currently, we have conflicting implementations of rolling averages. One option exists in the entity aggregation "weekly active" or "monthly active". The second option exists behind a feature flag as "smoothing". The second option was intended to replace the first option however, it leaves out functionality that the first option enables.

## Describe the solution you'd like

Steps in addressing this feature:

1. Decide where the filter should live

It seems that the filter should not be a chart option because you may want to compare a specific rolling average trend line to another type of aggregation. Therefore, the smoothing filter should exist alongside event aggregation.

<img width="756" alt="Screen Shot 2022-09-07 at 2 15 00 PM" src="https://user-images.githubusercontent.com/13127476/188949774-0661fb5c-7b14-49e3-9a80-2c2965ecb437.png">

2. Deprecation plan

Weekly active/monthly active event aggregation + smoothing filter options should be mapped to a separate per entity filter. 

3. Support breakdowns and compare

The current rolling averages support breakdown handling so this functionality should not be lost in the transition

## Describe alternatives you've considered
- just releasing as is. We will either lose functionality or have overlapping functionality that has different levels support

**Comment by amacneil** [comment]
Is it possible to get "smoothing" enabled on our account? I am looking to calculate rolling average 7 day and 28 day DAUs.

**Comment by Twixes** [comment]
Rolled out to Foxglove @amacneil :) Do note that it's still a beta feature though.

**Comment by amacneil** [comment]
Thank you! Dumb question though - where do I find this smoothing feature? Can't see it anywhere on the new insight page.

**Comment by Twixes** [comment]
Ah, apologies, I accidentally set the rollout condition incorrectly so it didn't take effect. _Now_ you should be able to see it above the graph. @amacneil

**Comment by amacneil** [comment]
Awesome, this is perfect! It even has both 7 day and 28 day 😄

**Comment by amacneil** [comment]
Still loving this feature. It would be even better if it were available on a per-series basis (then you would be able to deprecate/remove the existing WAU/MAU feature).

**Comment by amacneil** [comment]
Apparently I am the only person in the world using this feature, but I want to remind the good folks at PostHog that I love it and use it every day. I hope it reaches GA someday.

In the meantime I want to report two bugs:

1. If I set the `grouped by` to `day` with a `7-day` smoothing, then switch to `month` without first removing the smoothing, I get a smoothed month view, despite the smoothing option now being removed. The workaround is that I must remember to remove the smoothing before switching to `month`. This is pretty bad as it leads to incorrect data being displayed.
   <img width="283" alt="image" src="https://github.com/PostHog/posthog/assets/637671/1945d3bb-b1e8-4f15-b091-4bc75b2b42bc">
   <img width="292" alt="image" src="https://github.com/PostHog/posthog/assets/637671/f346134a-03f1-4170-985e-86372b30a2ea">

2. Smoothing only acts on data visible in my chart, when it should start calculating prior to the visible time range. For example, if I view `last 30 days` with `7 day` smoothing, then the first 7 out of 30 days are incorrect because they only represent a 1 through 7 day rolling average respectively (e.g. day 3 only represents a 3 day average). The correct thing to do would be for PostHog to fetch data starting _7 days prior to my visible time range_, calculate the rolling average, then discard the first 7 datapoints so that the first day on my chart represents a true 7 day rolling average (looking back 7 days prior to the start of my chart).
   <img width="740" alt="image" src="https://github.com/PostHog/posthog/assets/637671/080ba95e-61b1-45ed-9049-f29e3614fa7a">

**Comment by Twixes** [comment]
Rolling averages have been _rolled_ out for some time!

**Comment by amacneil** [comment]
Bug #1 above appears to be fixed but bug #2 is still an issue.
