### ISSUE TITLE
CMD+Click in sidebar

### ISSUE THREAD

**Issue by mariusandra** [PostHog/posthog#1187]
**Describe the bug**
I often CMD+click links to open them in a new tab. This doesn't work with the links in the sidebar.

**Comment by jamesefhawkins** [comment]
I often use right click -> open in new tab for the same reason, if trivial to bolt onto this. I felt myself wanting to do this when I used the sidebar to work out which pages of the homepage to prioritize re-designing with Lottie, because I wanted to look at "which ones are popular" and then to look at them as I went to then answer "and does this page need redesigning".
