### ISSUE TITLE
Unable to update user emails

### ISSUE THREAD

**Issue by huckleberryCalfinn** [PostHog/posthog#11996]
## Bug description

The goal is to update the email of various users within our organization's account. Regardless of the permission level of the user attempting to make a change to their own or any other user's email, no one in our organization seems to be able to update any email.

## How to reproduce
Note: this behavior occurs for all users attempting following steps, regardless of permission level (Organization Owner, Admin, member).

1. Go to Current Organization Settings via dropdown in upper-right-hand corner from home screen
2. Try to update user email by clicking on "..." icon next to any user in list. 
3. Observe message "Cannot update own user" or "you do not have permission to update user"

## Environment

- [ x] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: please provide

## Additional context

Thank you very much, PostHog rocks!

**Comment by liyiy** [comment]
Hey there! We don't actually have an option to change your email, if you want to change emails currently I would recommend just creating another account. Member permissions is working as expected because only admins and owners can change the status of members, and you can only change the status of members who are lower than you in level
