### ISSUE TITLE
Navigate from an event in the events table to a recording

### ISSUE THREAD

**Issue by pauldambra** [PostHog/posthog#12073]
## Is your feature request related to a problem?

I was creating a new action. When saved it uses the `EventsTable` component to show me matching events.

I wasn't completely sure I'd configured the action correctly. And wanted to quickly check

![Screenshot 2022-10-03 at 15 01 38](https://user-images.githubusercontent.com/984817/193597351-2c19da23-58fd-4694-8413-dfc2a4284494.png)

## Describe the solution you'd like

To be able to start a session recording over the events table for a row in the event table. Starting at the timestamp of the event.

## Describe alternatives you've considered

To see a screenshot of the recording in context in the expanded row (but I know that's way harder)

**Comment by benjackwhite** [comment]
@alexkim205 this feels like an easy win as an extension, same as we do for persons modal - include recordings in the query (we only need to do a simple join to see if we have A SR event with the same `$sessionId` and then filter for that event.

Timestamps might not come so easily but that's fine, we can always add that later

**Comment by alexkim205** [comment]
~Yeah definitely an easy win! I wonder if we can get away with not doing the join, since we don't distinguish between SR events and events when querying the list of events in the session recording. If an event has a window_id + session_id pair, can't we say for certain that a session recording exists for this event?~

~Unless we put TTLs on the session_recording_events table that isn't respected in the events table which in that case makes sense!~

Played around in metabase and saw that all SR events are events but not the other way around. Ignore the above!

**Comment by pauldambra** [comment]
done and dusted 💖
