### ISSUE TITLE
Sprint 1.41.0 2/2 - Oct 17 to Oct 28

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#12201]
# Global Sprint Planning

## 3 things that might take us down

1.
2.
3.

## Retro: Status of Outcomes from Previous Sprint

1. Curation: 🎨 Make it easy to quickly create an AARRR-inspired dashboard. @pauldambra > We did research, probably not very valuable. We'll do more customer interviews.
2. Exploration: 🧭 Build v0.1 of the "data explorer" / "universal search". @mariusandra > Fail, tunnel vision trying to wrap up. Carry over to next sprint.
3. 🇪🇺 cloud needs productionalization + billing @ellie  > in cloud and has billing!
4. Digitalocean single click + hobby deploy - make sure that works - testing if neccessary @fuziontech > it works, CI e2e tests are in review so should be wrapped up.
5. MVP for app metrics (how many events delivered, error rates) @macobo > so-so, main blocker is frontend experience but have a solution to this. Will get customers using this next week.
6. Ensure robustness of async handlers (jobs and scheduled tasks) @hazzadous (pair: @yakkomajuri) > rolling out to test teams for half of jobs. The rest of async handlers will roll out next week
7. Enabling Session Recording billing via BillingService @benjackwhite > Not on track b/c illness, EU cloud got in the way, but very close. End of the week we'll have this connected to dev.
8. Event filtering in Session Recordings & fuzzy filtering of events (MVP) @alexkim205 > This is done!
9. Revisit metahog (direct sql access) and set up for MVP deployment on self-hosted @EDsCODE > in progress, should be done for end of the week.
10. Cleanup and growth tasks for experiments @liyiy > on track to be completed. Switched OKRs so not implementing some of the additional growth tasks.

## Retro: What can we do better next sprint?

1. EU cloud, we didn't have a clear owner. Lots of confusion between teams.
2.
3.
4.
5.

## Support hero this sprint

Week 1: Tiina
Week 2: Marius

## Plan: Proposed Goals for Next Sprint 

Each goal should have a single owner. Owner can only be an engineer.

1. "I don't need PostHog to build all the features, I just need it to work" (citation needed) @Twixes
why? User interviews highlighted above quote, so we're fixing it
2. Exploration: 🧭 Build v0.2 of the "data explorer" / "universal search". @mariusandra
why? Hard to explore between related data.
3. Billing - Paying customer on the new BillingService @benjackwhite 
why? Billing is still our top prio
4. Event Summaries - Migrating our underlying CH table to surface key stats more easily @alexkim205 
why? Unblocker for higher performance and follow up features around querying and listing
5. 🚢 upgrade to Kubernetes v1.23 @danielxnj
why? We don't want to be behind, our current version will come out of long term support
6. 🚨 sort incident handling (setup pagerduty to work similarly to incident.io with /incident, retro process, etc) @ellie
why? we want to handle incidents better
7. Upgrade ClickHouse to >=v22.3.13 as our version has a memory leak causing issues @ellie
why? memory leak almost took us down
8. Offsite the first week. Make hackathon stuff live second week Thinking of targeting "developer integrated featureset for feature flags". Code linking/error logging/CI @EDsCODE 
why? do some _innovation_
11. Insert service for CH @fuziontech 
why? So we can use clickhouse cloud for direct sql access
12. Removing any dependencies on Postgres availability from the pipeline @hazzadous
Why: So our pipeline can be reliable even when external services are down
13. App metrics v1 @macobo
Why: This is a requirement for CDPs and will give us and users more confidence in the pipeline
14. CDP design/architecture document @lharries
Why: so we can have a sense of what to build for our CDP and how to build it

# Team sprint planning

For your team sprint planning copy this template into a comment below for each team.

```
Team ___

## Retro

<!-- Talk about what went well, what didn't go well and any actions to improve next time -->

- 

## Hang over items from previous sprint

<!-- For each item, decide to re-prioritise (and add below) or deprioritise -->

- Item 1. prioritised/deprioritise

## Planning

<!-- Each item should have a single owner. Owner can only be an engineer. -->

### High priority

-

### Bugs

-

### Low priority / side quests

-

```

**Comment by mariusandra** [comment]
Team Product Analytics

## Retro

- Marius: apps took all the attention, went too tunnel vision and ignored bugs
- Paul: text dashboards took longer, but a few quality of life dashboard bugs squashed along the way
- Michael: nailed actually working on product analytics
- Annika: great analysis

## Hang over items from previous sprint

- Curation: 🎨 Make it easy to quickly create an AARRR-inspired dashboard. @pauldambra
  - [Data now shows it's not going to be useful](https://github.com/PostHog/posthog/issues/12195).
  - Text cards on dashboards solve some of the curation help.
  - More research needed if there's anything we do.
- Exploration: 🧭 Build v0.1 of the "data explorer" / "universal search". @mariusandra
  - V0.0.1 built

## Planning

Paul off most of the sprint

### High priority

- "I don't need PostHog to build all the features, I just need it to work" (citation needed) @Twixes 
- Exploration: 🧭 Build v0.2 of the "data explorer" / "universal search". @mariusandra

### Bugs

- TBD

### Low priority / side quests

Media cards on dashboards
 - why? builds on text card work

**Comment by benjackwhite** [comment]
# Team Record-revenue-ings 💸

## Retro



- @kappa90 basically doing billing 😅 
  - Pairing is successful and having multiple people on a big topic makes a lot of sense
  - Should keep this up for items from the megaissue
  - Growth sprint planning and efforts are a little unclear atm. Assuming just to be included in SR work for now.
- @annikaschmid
  - Successfully used SR to actually learn things 🥳 
  - Clear goals meant that things were pretty straightforward
- @benjackwhite 
  - Billing is dragging along due to learning by doing **but** it's great to be pairing on this with Em
  - Jumping into actual SR feature improvements felt super good even though not the goal
  - I feel little bit distant from Alex partly because of being sick and partly because we are just out of sync
  - Next sprint want to invest more pairing time and also general time with Alex!
- @alexkim205
  - Worked on linking product analytics product to session recordings
  - Should continue working on interlinking as well as responding to incoming feedback
  - Also felt a little out of sync from team due to offsite and OOO schedules. This sprint should have more face-to-face time!

## Hang over items from previous sprint



- Item 1. **Billing!** - I think should continue to be our high prio for next sprint
  - Get it on dev by end of week

## Planning



### High priority
1. **Billing** - Paying customer on the new BillingService
 - why? Billing is still our top prio
2. **Event Summaries** - Migrating our underlying CH table to surface key stats more easily
 - why? Unblocker for higher performance and follow up features around querying and listing
 
### Bugs
-

### Low priority / side quests
- Add simplified link to the given SessionRecording

**Comment by ellie** [comment]
# 🚀 Team Infrastructure 🚀 

## Retro

- @danielxnj: The onboarding process was very clear and well-organized, and everything was ready for me for my first day. I even got to see our infrastructure during my first hour at work.
- @ellie: EU launch went well! Infra has held up 🙌 Definitely need to handle communication better next time though (eg marketing not being sure on launch timings)
- @guidoiaquinti: _enjoying a bank holiday today_




## Hang over items from previous sprint
N/A

## Planning
@danielxnj has joined us! woo!

- 🚢  upgrade to Kubernetes v1.23 @danielxnj 
- 🚨  sort incident handling (setup pagerduty to work similarly to incident.io with `/incident`, retro process, etc) @ellie
-  Upgrade ClickHouse to >=v22.3.13 as our version has a memory leak causing issues @ellie
- Plan and explore "Migrate postgres out of heroku" goal @ellie 
- Plan and explore "Regular synthetic load testing on production" goal @guidoiaquinti 
- Plan and explore "Progress made on SOC2" goal @danielxnj

Also a note we've now got [our board](https://github.com/orgs/PostHog/projects/27/views/1) sorted out!

**Comment by EDsCODE** [comment]
Team Experiments

## Retro
- https://github.com/PostHog/posthog/issues/10426 is done
- metahog revamp should be done by friday
- https://github.com/PostHog/posthog/pull/11935 done
## Hang over items from previous sprint
- NA

## Planning
- Offsite the first week. Thinking of targeting "developer integrated featureset for feature flags"
     - code linking
     - error logging
     - CI
- Second week can be used to polish and deploy what was done at the offsite

**Comment by yakkomajuri** [comment]
# Team Pipeline

## Planning

- Removing any dependencies on Postgres availability from the pipeline @hazzadous 
    - Why: So our pipeline can be reliable even when external services are down
- App metrics v1 @macobo 
    - Why: This is a requirement for CDPs and will give us and users more confidence in the pipeline
- CDP design/architecture document @lharries 
    - Why: so we can have a sense of what to build for our CDP and how to build it

**Comment by benjackwhite** [comment]
(For next sprint)

# Team Session IPA

## Retro
- @kappa90 morning cuddles with Ben are ❤️ - we should carry on with this more especially for close work
- @benjackwhite more cuddles with Alex wanted 
  - Billing stuff is an iceberg, started to feel like we made the wrong call
  - Strong validation chat with Simon put me back on track of this was the right call
- @alexkim205 Not super involved with billing but good keeping in sync via Ben through the sprint
  - Little siloed working on completely different things to the other guys
  - Working on one goal together with someone please (cuddles)
- @annikaschmid 
  - Not loads of progress due to other commitments
  - Super valuable and relevant user interviews reinforcing our decisions so far (+1 from Ben)

- [ ] @benjackwhite and @alexkim205 should work closely on something next sprint

## Hang over items from previous sprint
- [ ] Releasing billing to new customers (maybe done before end of sprint)
- [ ] Supporting and monitoring the new billing
- [ ] Event summary migration stuff

## Planning

### High priority
- Saving groups of recordings for easy future finding / playback
  - Saving filter configurations for future usage
  - Saving specific recordings to a list
- Supporting Billing rollout 

### Bugs
- Fix URL linking to a recording from PersonsModal

### Low priority / side quests
- Flamegraphs via Events summary

**Comment by mariusandra** [comment]
## Last sprint

### Team Retro

- We're in the "getting the crew together" stage of this team. 
- One person out for almost 2 weeks when there are 3 of us is felt... especially when one of the other two is support hero. How did we not see this coming?

- Paul - bugs and leftovers for 2 days out of 10
- Marius - 1 week support, other week tables and support
- Annika - great offsite
- Michael - implemented cool new features

### Goal retro

1. "I don't need PostHog to build all the features, I just need it to work" (citation needed) @Twixes
  - why? User interviews highlighted above quote, so we're fixing it
  - Status: Michael fixed what didn't exist or didn't work for him:
    - new math selector
    - min/max/avg count by user
    - in progress: adding avg/min/max count by group and property selector

2.  Exploration: 🧭 Build v0.2 of the "data explorer" / "universal search". @mariusandra
  - why? Hard to explore between related data.
  - Status:
    - Solid progress on tables, didn't get to exploring actual data. See this sprint.

## Next sprint

OKR: Nail Data Exploration. 
why? Hard to explore between related data.

- Michael "doing a refactor of the SQL queries"
- Marius "getting the tables just right everywhere"
