### ISSUE TITLE
RFC: we should stop using snapshots of database queries in backend tests

### ISSUE THREAD

**Issue by zackelan** [PostHog/posthog#12306]
background reading: [Change-Detector Tests Considered Harmful](https://testing.googleblog.com/2015/01/testing-on-toilet-change-detector-tests.html)

as of 2022-10-17 we have:

- 2,609 Python tests in the backend (`pytest --collect-only | head`). 

- 3,059 individual queries saved as snapshots (`find . -name '*.ambr' -exec grep -c '# name' {} \; | awk '{s+=$1} END {print s}'`)

- ~60,000 lines of SQL in those saved queries (`find . -name '*.ambr' -exec wc -l {} \; | awk '{s+=$1} END {print s}'`)

in theory, comparing database snapshots in a test can catch performance regressions, where a code change inadvertently causes different SQL to be generated, and that SQL is less performant in some way, such as by no longer making use of an index.

in practice:

- when you run tests using the `./bin/tests` script, it appends `--snapshot-update` for you. this means that differences in the snapshots will not cause test failures, and the snapshots will simply be overwritten.

- when we run tests through GitHub CI, we also use `--snapshot-update`, which means that those test runs will never fail due to a snapshot difference. 

this use of snapshotted database queries makes tests slower and more complicated, and does not deliver any meaningful value.

**Comment by macobo** [comment]
The motivation for saving the SQL isn't directly related to catching performance regressions: It's to make reviews better. 

Our backend for querying is quite flexible, so small code changes in e.g. how filters work have a large (and sometimes unforeseen) impact on the resulting queries. This flexibility is inevitable since we need to support a very wide and deep product in terms of querying. By saving snapshots, we _know_ what the resulting SQL looks like, making it possible to review with confidence.

> when we run tests through GitHub CI, we also use --snapshot-update, which means that those test runs will never fail due to a snapshot difference.

This is intentional - in theory CI should also automatically push snapshot changes as a new commit. @timgl added this feature a way back. 

However I've seen signs that this has been breaking down recently as unrelated PRs have been carrying snapshot changes. Time to review and fix this as needed?

> this use of snapshotted database queries makes tests slower and more complicated

Can you elaborate on this a bit? Given we automatically update snapshots, I don't see the complexity and writing files should be reasonably fast compared to everything else we do in tests.

**Comment by pauldambra** [comment]
https://github.com/PostHog/posthog/pull/12325

Interesting example here where there are no changes to any queries. The bot has committed updating a snapshot with a comment added to the SQL, and then added a commit with the comment removed

**Comment by pauldambra** [comment]
As a minimum we should take the context from Karl and add it to the `@snapshot_queries` decorator so the future traveller can find it...
