### ISSUE TITLE
Sprint 1.42.0 1/2 - 31st Oct - 11th Nov

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#12446]
# Global Sprint Planning

## 3 things that might take us down

1. OpenSSL, wait and see, doing inventory in the mean time
2. Graphile worker issues, working on that

## Retro: Status of Outcomes from Previous Sprint

1. "I don't need PostHog to build all the features, I just need it to work" (citation needed) @Twixes > Fixed some significant insight bugs in the last 2 weeks. No carry over.
2. Exploration: 🧭 Build v0.2 of the "data explorer" / "universal search". @mariusandra  > No explicit progress. Slowly moving, we've had support hero and time off etc. Carrying over.
3. Billing - Paying customer on the new BillingService @benjackwhite > Got bogged down. We fixed instance status report. We could probably release on Friday.
4. Event Summaries - Migrating our underlying CH table to surface key stats more easily @alexkim205 > Karl got ill. We got most of this done but waiting to merge.
5. 🚢 upgrade to Kubernetes v1.23 @danielxnj > Done!
6. 🚨 sort incident handling (setup pagerduty to work similarly to incident.io with /incident, retro process, etc) @ellie > Pagerduty didn't quite work. We're going to use incident.io.
7. Upgrade ClickHouse to >=v22.3.13 as our version has a memory leak causing issues @ellie > Done! Haven't done US yet as there are long running migrations.
8. Offsite the first week. Make hackathon stuff live second week. Thinking of targeting "developer integrated featureset for feature flags". Code linking/error logging/CI @EDsCODE > Beta rollout of auto rollback will be live. Recordings on feature flags is live internally.
11. Insert service for CH @fuziontech > Carried over, but a lot of progress. Found a great library. We've got an inserter that'll insert into clickhouse cloud.
12. Removing any dependencies on Postgres availability from the pipeline @hazzadous > Good progress, but need to roll over a few tasks. Found a few new failure modes.
13. App metrics v1 @macobo > Shipped, live!
14. CDP design/architecture document @lharries > This is out, feel free to comment.

## Retro: What can we do better next sprint?

1. Github bot that adds everyone's availability into the issue
2. 
3.
4.
5.

## Support hero this sprint

Week 1: James G
Week 2: Harry

## Plan: Proposed Goals for Next Sprint 

Each goal should have a single owner. Owner can only be an engineer.

1.Saving groups of recordings for easy future finding / playback @alexkim205 
why? Biggest thing requested by user feedback.
2. Supporting Billing rollout @benjackwhite
why? No money from new billing makes Ben's future at PostHog uncertain...
3. Expose more data in the persons modal (ie how many times the event was triggered) + sql refactor @Twixes 
why? Feedback from users, and will enable better querying in the future
4. Finish data exploration view and put live, also migrate existing insight views. @mariusandra 
why? To make it easier to explore data
5. Robust app failure handling @tiina303
Why: So that customers can have confidence on their apps and actually rely on them
6. Removing any dependencies on Postgres availability from the pipeline @yakkomajuri 
Why: So our pipeline can be reliable even when external services are down
7. OpenSSL security fix (whole team effort) @guidoiaquinti
why? Security patch coming out next week, could be like heartbleed.
8. Explore AWS cost reduction @ellie
why? Make sure we're only spending money we need to spend
9. SOC2, 4-5 issues that we want to fix this sprint @danielxnj
why? Get soc2 compliant
10. Permissioning @liyiy
why? Often requested during interviews
11. UI updates to make 100% rollouts prominent + showing user blast radius @neilkakkar
why? Often requested during interviews
12. Configure notifs on flag changes that people want to follow + alert when flag should be cleaned up @EDsCODE
why? Make sure people know when their flags are changed
13. Get clickhouse cloud ingestion working @fuziontech 
why? to enable directsql access.
14. Add sessions recordings to onboarding flow @kappa90 
why? Session recordings are super useful, make sure people enable it

# Team sprint planning

For your team sprint planning copy this template into a comment below for each team.

```
Team ___

## Retro

<!-- Talk about what went well, what didn't go well and any actions to improve next time -->

- 

## Hang over items from previous sprint

<!-- For each item, decide to re-prioritise (and add below) or deprioritise -->

- Item 1. prioritised/deprioritise

## Planning

<!-- Each item should have a single owner. Owner can only be an engineer. -->

### High priority

-

### Bugs

-

### Low priority / side quests

-

```

**Comment by benjackwhite** [comment]
# Team Session IPA

## Retro
- @kappa90 morning cuddles with Ben are ❤️ - we should carry on with this more especially for close work
- @benjackwhite more cuddles with Alex wanted 
  - Billing stuff is an iceberg, started to feel like we made the wrong call
  - Strong validation chat with Simon put me back on track of this was the right call
- @alexkim205 Not super involved with billing but good keeping in sync via Ben through the sprint
  - Little siloed working on completely different things to the other guys
  - Working on one goal together with someone please (cuddles)
- @annikaschmid 
  - Not loads of progress due to other commitments
  - Super valuable and relevant user interviews reinforcing our decisions so far (+1 from Ben)

- [ ] @benjackwhite and @alexkim205 should work closely on something next sprint

## Hang over items from previous sprint
- [ ] Releasing billing to new customers (maybe done before end of sprint)
- [ ] Supporting and monitoring the new billing
- [ ] Event summary migration stuff

## Planning

### High priority
- Saving groups of recordings for easy future finding / playback @alexkim205 
  - Saving filter configurations for future usage
  - Saving specific recordings to a list
- Supporting Billing rollout @benjackwhite 
 - why? No money from new billing makes Ben's future at PostHog uncertain...

### Bugs
- Fix URL linking to a recording from PersonsModal

### Low priority / side quests
- Flamegraphs via Events summary

**Comment by mariusandra** [comment]
For next sprint, team Product Analytics

## Last sprint

### Team Retro

- We're in the "getting the crew together" stage of this team. 
- One person out for almost 2 weeks when there are 3 of us is felt... especially when one of the other two is support hero. How did we not see this coming?


- Paul - bugs and leftovers for 3 days out of 10
- Marius - 1 week support, other week tables and support
- Annika - great offsite
- Michael - implemented cool new features

### Goal retro

1. "I don't need PostHog to build all the features, I just need it to work" (citation needed) @Twixes
  - why? User interviews highlighted above quote, so we're fixing it
  - Status: Michael fixed what didn't exist or didn't work for him:
    - new math selector
    - min/max/avg count by user
    - in progress: adding avg/min/max count by group and property selector

2.  Exploration: 🧭 Build v0.2 of the "data explorer" / "universal search". @mariusandra
  - why? Hard to explore between related data.
  - Status:
    - Solid progress on tables, didn't get to exploring actual data. See this sprint.

## Next sprint

@mariusandra is release hero and off on 3 days first week (public holidays)

Goal: Make progress towards the OKR "Nail Data Exploration":
- Michael "doing a refactor of the SQL queries"
- Marius "getting huge tables just right"

**Comment by yakkomajuri** [comment]
# Team Pipeline

## Constraints

- Karl will be offboarding and not actively involved in the goals
- Harry will be support hero the second week
- At best, we're 2.5 engineers 

## Goals

Robust app failure handling @tiina303 
Why: So that customers can have confidence on their apps and actually rely on them

Short term external service unavailability doesn’t cause plugin disabling @yakkomajuri 
Why: So our pipeline can be reliable even when external services are down

**Comment by ellie** [comment]
Team Infrastructure

## Retro

@ellie: Bunch of unplanned fixes, some good progress on OKRs and memory leak fixed

@danielxnj: Onboarding is going well; I got to meet several teammates, getting a better understanding of our infra and how our team works. Happy to make my first PRs. I still need to familiarize myself with our setup and support production issues.

@guidoiaquinti: happy to see the team is growing and that the infrastructure as code work is showing its value day after day! (read as SOC2 changes, PostHog Cloud EU, etc..)

## Hang over items from previous sprint
- Clickhouse upgrade in the chart @ellie 

## Planning
- OpenSSL security fix (whole team effort) @guidoiaquinti 
- Explore AWS cost reduction @ellie
- Support billing deployment @ellie
- SOC2 work @danielxnj

**Comment by EDsCODE** [comment]
## Team Experiments

**Retro:**

Goal: Make hackathon stuff live second week 
- Autorollback based on insight or sentry metrics beta rollout
- Recordings on feature flags beta 

Planning:

[RFC: Solve for intended actions on feature flags](https://github.com/PostHog/product-internal/pull/365)
- Permissioning @liyiy 
- UI updates to make 100% rollouts prominent @neilkakkar 
     - Showing user blast radius 
     - suggestion: Have cohort creation within feature flags
- Integrate alerting and notification system @EDsCODE 
     - Configure notifs on flag changes that people want to follow
     - Alert when a flag should be cleaned up
