### ISSUE TITLE
Consolidate all 'charts' into one view

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#1250]
### Is your feature request related to a problem? Please describe

At the moment, we have a lot of analytics capabilities but they're spread out in a lot of different places:
- Trends (which also does sessions and stickiness)
- Funnels
- Paths
- Retention

Right now, if I'm filtering something on /trends and I want to see how the retention is, I would have to re-create all those filters in retention

### Describe the solution you'd like

I want all of the analytics to happen in a single screen, which should make it easy to switch between screens.

The screen should be divided into 5 sections:

1. A switcher between the different chart types
1. ActionFilters, eg the ability to add any action/event. For trends those will be shown in the chart, for funnels it'll be the steps. For sessions, you won't be able to change this
1. Filtering and breakdown. 
1. Chart-specific options. For example for trends, you should be able to switch between things like volume, frequency etc. For funnels, it could be the time in which a user needs to complete the steps
1. The chart itself. This section should have chart options, like linear/stacked etc for trends and period.

While we're doing this, it'd be great to save each iteration with a uuid for easy sharing and saving to dashboards etc.

### Describe alternatives you've considered

Keep as is currently

### Additional context

This is basically how Amplitude is structured and I really like it, but obviously there is stuff we can improve! Thoughts @EDsCODE @jamesefhawkins ?

**Comment by EDsCODE** [comment]
I think this is a great idea. All of the pages you listed have very similar interfaces so I would agree taht they should be combined into a a more comprehensive page. This will declutter the sidebar and allow for different features to be added too

Pending more feedback: I can do a quick mockup of the interface

**Comment by EDsCODE** [comment]
I realized something that could make this refactor rather simple.

The major visualizations that should be condensed are (as listed above):
trends, trend-sessions, funnels, paths, retention. 

We can provide the necessary options for each of these "insights" as @Twixes neatly calls it, using a format similar to the one we already have for the trends page. For example (numbers refer below), 
- (1) and/or the title can be a switcher that determines which type of insight the user is trying to create. 
- (2) would be any time related filtering such as those options shown below (interval if applicable, date range, compare if applicable, etc.) 
- (3) would encapsulate the chart specific filtering. Some insights will have less options than others but since every insight allows users to atleast filter properties, there will always be some option present in that box.  

The visualizations would be displayed where the graph is as pictured below. The only insight that has a slightly different standard for display are funnels because of the list of people that appear beneath the funnel however, this can be easily fixed by either making the people appear onclick as we've done with many other areas of the app, still display below anyway, or make it a separate insight visualization mode. Other than funnels, the other visualizations should easy fit in the space. 

I'd suggest performing a refactor of this sort with the current ant design style to streamline the process. When that's complete and the _format_ feels right, then we can undergo a UI facelift to match it with the rest of the brand.

<img width="1365" alt="Screen Shot 2020-07-21 at 3 48 06 PM" src="https://user-images.githubusercontent.com/13127476/88099895-d132e680-cb69-11ea-857b-0b7dcbd16ade.png">

**Comment by timgl** [comment]
@EDsCODE I think this makes a ton of sense 👍
