### ISSUE TITLE
Role based permissioning

### ISSUE THREAD

**Issue by liyiy** [PostHog/posthog#12515]
## Is your feature request related to a problem?

Users would like a way to restrict or limit full edit access for certain features to custom "groupings" of team members (ex: engineers, product, marketing, on-call, etc.). For more context, check out the RFC [here](https://github.com/PostHog/product-internal/pull/365#discussion_r1006397710). 

Currently our PostHog system has "permissions" around organization member levels, project access, and dashboard collaboration but we don't have a re-useable pattern on how we do this and would like a solution that also solves the role type problem

## Describe the solution you'd like

A way for users to manage role based access to features based on team member groupings. 

An example of this flow would be:
- by default everyone has full edit access to feature flags
- admins+ want to set up roles that will only allow team members with the "product" role to be able to edit feature flags. But they also want team member Z to have access to feature flag 2 specifically

1. Admin goes into settings and sets default access to "view only" for everyone
2. They create a new "product" custom role
3. They apply this to team members A, B, and C. 
3. They set this role to "edit all flags"
4. If team member A is a part of the `product` and `engineering` team role, when they create a new feature flag, team members that are part of `product` or `engineering` will have edit access 

This would look like:

The role
```
class UserRole:
    id: product_role_id
    name: product
```
A member that is part of a role
```
class UserRoleMembership:
    user_id: eric_uuid
    user_role_id: product_role_id
```
Feature flag that is connected to the role
```
class FeatureFlagRolePrivilege:
    feature_flag_id: 1
    user_role_id: product_role_id
```
Feature flag that is connected to an individual user
```
class FeatureFlagUserPrivilege:
   feature_flag_id: 1
   user_id: team_member_Z_id
```
We can apply this to feature flags as a working example for now but this pattern should be re-useable to other features of our app too, like experiments or cohorts. For something like dashboards where permissioning is more collaborative, you can also allow for individual user access to certain dashboards along with team role groupings. Eventually 

## Describe alternatives you've considered

Out of scope for this initial implementation is 
- policy access, ex: super granular permissioning like "can turn on but can't turn off feature flag", "can edit only descriptions of a feature flag". 
- tagging resources and connecting it to the custom role (so tagging multiple feature flags and then assigning that tag to a custom role)

## Additional context
Good to haves:
 - Same group can have different permissions across environments. For example:
  -Engineering: can edit staging feature flags, view only production feature flags
  -Infrastructure: can edit staging feature flags, can edit production feature flags

**Comment by EDsCODE** [comment]
Questions from standup:

Should these roles be defined at the organization level or project setting? Organization level

**Comment by liyiy** [comment]
@Twixes

**Comment by neilkakkar** [comment]
Let's say admin sets the default for the entire org to 'view only' flags.

Let's say Neil and Eric belong to the role 'product', and we want to be able to edit each others flags, but not Li and Luke's flags, who belong to the role 'engineering'.

I create a flag called 'neil-test'. By default, it _seems_ like this is still 'view only' for everyone. Do I need to add the 'product' role to this flag to get what I want? (What I want is for Eric and me to be able to edit it, and not Li-Luke).

This feels wrong compared to what users wanted. See:

> It would be good to be able to create permission groups and provide the ability to add users to certain groups so we don't have to deal with the overhead of constantly managing permissions per feature flag

and

> we have a lot of flags at any given time and I’d like our on call engineers to be able to update [all of] them, but have our CS / support team be able to view them

---

Spending some time thinking about this, I _think_ the issue is coming from trying to combine flag specific user permissions, with global role based permissions.

I propose splitting these two up into their separate models. As such, instead of linking a role to a specific flag, we should design it such that it's linked to all flags, and whatever permission is granted to the role applies to all flags automatically.

So: If the product role can 'edit own flags only', then whenever Eric or I create a new flag, we can only edit our own flags.

If the 'engineer on call' role can 'edit all flags', then whenever random-person-A creates a new flag, the engineers belonging to 'engineer on call' role can edit their flag as well, say for example, if things go wrong, without explicit approval from random-person-A.

---

Then, we can have user level permissions *per flag* (if we really want them - idk if it makes sense to have them right now) - on top of these, with higher precedence than the global roles, so even if this user belonged to a 'view only' global role, they could edit this flag. 

---

Does this make sense?

**Comment by neilkakkar** [comment]
Aside: a reason against the implicit membership is that it's not extensible. If we want to introduce different kinds of permissions, like, say, 'no view mode', or 'view atmost 2 times', we'll have to start from scratch, since we can't just check whether the user is a row in `FeatureFlagUserPrivilege` or `FeatureFlagRolePrivilege`.

Thus, maybe we should include this in the model, as a field determining 'what kind of permission this is' ?

**Comment by liyiy** [comment]
> I create a flag called 'neil-test'. By default, it seems like this is still 'view only' for everyone. Do I need to add the 'product' role to this flag to get what I want? (What I want is for Eric and me to be able to edit it, and not Li-Luke).

By default Neil and Eric would be able to edit each other's flags but not Luke or Li if you set "product" roles to "can edit role's flags" under a general settings page, not per feature flag !

> So: If the product role can 'edit own flags only', then whenever Eric or I create a new flag, we can only edit our own flags.
> If the 'engineer on call' role can 'edit all flags', then whenever random-person-A creates a new flag, the engineers belonging to 'engineer on call' role can edit their flag as well, say for example, if things go wrong, without explicit approval from random-person-A.

This is the intention :D 

> As such, instead of linking a role to a specific flag, we should design it such that it's linked to all flags,

Do you mean like a role defined and then a foreign key array of feature flags it has access to within the model? That makes sense to me

> If we want to introduce different kinds of permissions, like, say, 'no view mode', or 'view atmost 2 times', we'll have to start from scratch,
> Thus, maybe we should include this in the model, as a field determining 'what kind of permission this is' ?

What do you mean by we'd have to start from scratch? Can't we just add this to the model later as a new field? Can you elaborate more on what this model looks like to you?

**Comment by EDsCODE** [comment]
> If the 'engineer on call' role can 'edit all flags', then whenever random-person-A creates a new flag, the engineers belonging to 'engineer on call' role can edit their flag as well, say for example, if things go wrong, without explicit approval from random-person-A.

This is the intended outcome with the original post. 

> Do you mean like a role defined and then a foreign key array of feature flags it has access to within the model? That makes sense to me

@liyiy If i'm understanding correctly, he's referring to `FeatureFlagRolePrivilege` -> `RolePrivilege ` and just having this privilege specify a model not an instance of the model. So there would be no feature_flag_id it would just be model: "feature_flag"

> > If we want to introduce different kinds of permissions, like, say, 'no view mode', or 'view atmost 2 times', we'll have to start from scratch,
> > Thus, maybe we should include this in the model, as a field determining 'what kind of permission this is' ?
> > 
> 
> What do you mean by we'd have to start from scratch? Can't we just add this to the model later as a new field? Can you elaborate more on what this model looks like to you?

+1 here, seems like you can just add precise permissions on `UserRole` if you need specificity down the line on what each role can do?


I think the main cause of confusion here is 

> They set this role to "edit all flags" 

I was thinking view access is always the default so we don't even need to manage permissioning level per role. The user workflow is: admin creates roles and tags each org member with this role. If this role is associated with a flag, then that role can edit the flag. The associations will be populated by default on creation based on the roles that a specific user is a part of. In effect, this would be like google doc collaborators but with groups that are default added so you don't need to repeat a list of users every time a flag is created. I'm not married to this idea but maybe we can use this as a foil to understand each viewpoint

<img width="702" alt="Screen Shot 2022-11-01 at 9 50 16 AM" src="https://user-images.githubusercontent.com/13127476/199249167-c9741d88-580f-4a39-8c12-4f0c32227706.png">
<img width="792" alt="Screen Shot 2022-11-01 at 9 51 36 AM" src="https://user-images.githubusercontent.com/13127476/199249388-1ed448b5-f964-4eac-95e1-9f348af6129f.png">

**Comment by neilkakkar** [comment]
Thanks for clearing that up! This is close enough to the model change I was suggesting that it's fine too. There's some interesting trade-offs between the two 🤔 . I think I prefer yours more now.

> seems like you can just add precise permissions on UserRole if you need specificity down the line on what each role can do?

I don't think it's that simple. 

1. It does mean changing everything that was reading from the model to decide permissions, which is what I meant (since it will be breaking behaviour, and not just as simple as adding a field). Not too big a deal though.
2. What feels problematic to me though is that we'll have to make the implicit connections explicit when this migration does occur. For example, for a flag that earlier used to be 'view only' / whatever the default was, would have no `UserRole` linked to it, and when we introduce the new field, we'll need to add _something_ to represent the default for all existing flags.


I'm not too sure yet either how the default permission is inferred  🤔 .

With that said, it _seems_ like you both do have a good idea of how this should work, just not fully written down here, which is mostly okay - happy to move on this if you're confident everything is thought out!

**Comment by Twixes** [comment]
I like the idea outlined here, this system sounds like a good fit! It should be intuitive to extend to other features.
From a code perspective, perhaps `FeatureFlagRolePrivilege` could be unified with `FeatureFlagUserPrivilege` as `FeatureFlagPrivilege` by using a constraint where _either_ `user_id` or `role_id` must be set, but those are implementation details.

**Comment by liyiy** [comment]
Roles:

- Admins+ can create, update, delete roles. Everyone can view.
- Roles have default feature flag access levels. If you belong to a certain role your role privileges will override your organization privileges.
- ex: organization default = view only but you belong to a role with full edit access. Then you have access to all feature flags (permitting)
- The reverse is true too: If you have organization full edit access and you belong to a role that has only view access to flags, then you will only have view access to all flags (restrictive)

Role memberships:

- Admins+ can create/delete role memberships. Everyone can view.
- Role memberships determine which user belongs to which role

Feature flag role access:

- This is for the access level where by default you belong to an organizational or role that has “default view unless belonging to a role connected to a feature flag”
- Ex: You have 10 flags and only flags 1, 2, and 3 should be edited by the product role. The product role has a feature flags access level of “default view allow edit based on role”. You then connect feature flags 1, 2, and 3 to the product role.
- You can permit a role edit access to a flag if you have either organization edit status or role full edit status or you are the creator of the flag

**Comment by annikaschmid** [comment]
Thoughts on the current functionality / UX:

## Background

**Scenarios we want to support:**

Scenario 1: “Everyone can edit feature flags.”

Scenario 2: “I only want engineers to be able to edit feature flags.”

Scenario 3: “I want teams to be able to edit their flags, not others.”

## Implementation

**Cadence of permissions:**

1. Project default permissions
2. Role default permissions
3. Feature flag permissions

**Scenarios:**

Project | Role default | Feature flag | Can edit flag?
-- | -- | -- | --
Edit | n/a | n/a | YES
View | Edit | n/a | YES
View | View | Role added as ‘Edit’ | YES
View | View | n/a | NO
View | n/a | n/a | NO

Note: I removed the “View & Assigned Edit” role from this model. I think it is redundant, with the feature-flag permissions overwriting the role permissions.

**UI changes to make permissions clearer:**

**On the feature flag detail page: [Figma](https://www.figma.com/file/UBPG5Wjpe0EbfABdlCavt1/Feature-Flag-Permissions-Mocks?node-id=1%3A798&t=ILQdW10qh46BxkR1-1)**

- The project level permissions and all roles who can edit a flag should be shown in the same table, so that a user doesn’t have to look at multiple tables to get a full picture of who can edit a flag.
- Always show the “Permissions” on the feature flag detail page, below “Release conditions”, instead of in a popup
- If all users or a role is set to ‘Edit’ on the project level, it can’t be changed on the feature flag

**On the project settings page: [Figma](https://www.figma.com/file/UBPG5Wjpe0EbfABdlCavt1/Feature-Flag-Permissions-Mocks?node-id=1%3A67&t=ILQdW10qh46BxkR1-1)**

- The project level permissions and all roles who can edit a flag should be shown in the same table, so that a user doesn’t have to look at multiple tables to get a full picture of who can edit a flag
- When creating a role: Show an example next to the role name, so that it’s clear it should describe the team (Engineering) not the functionality (Edit)

**How the scenarios can be implemented with this proposal:**

Scenario 1: “Everyone can edit feature flags.” -> Set project permissions to "Edit"

Scenario 2: “I only want engineers to be able to edit feature flags.” -> Set project permissions to "View", create a role, add all engineers, set role permissions to "Edit"

Scenario 3: “I want teams to be able to edit their flags, not others.” -> Set project permissions to "View", create role, add all people from the team to the role, set role permissions to "View", add role to relevant feature flags as "Edit"

Out of scope with this proposal:
- Overwrite "Edit" with "View": I don't think we need this functionality yet, which is why the UX currently doesn't account for this. 
- Permissions for who can create a feature flag: With permissions on multiple levels, it's hard to decide when to show the "New feature flag" button ("anyone who has edit access to any feature flag"??). I don't mind showing it to everyone for now, but it creates an edge case where you don't have edit permissions on feature flags, you create one and then you can't delete it anymore.
