### ISSUE TITLE
Feature request: Dashboard templates for product managers, marketers

### ISSUE THREAD

**Issue by joethreepwood** [PostHog/posthog#12732]
## Is your feature request related to a problem?

Following on as an action from [this industry report which pointed out a lack of templates in PostHog](https://github.com/PostHog/meta/issues/67) (especially for non-technical users) I'd like to propose two new templates. 

These templates are intended to help non-engineer users get more value from the product more quickly. One, for Product Managers, surfaces some information for starting user research. The other, for marketers, surfaces information about paid advertising performance. 

## Describe the solution you'd like

Rather than describe the templates - and after failing to build them myself as product PRs from @pauldambra's [example](https://github.com/PostHog/posthog/pull/12343) -  I decided to build the templates as dashboards. 

https://app.posthog.com/dashboard/54995 - Paid marketing analytics
https://app.posthog.com/dashboard/54985 - User research

I'd like if these were then turned into templates users could select. 

## Describe alternatives you've considered

None. Templates are just a slam-dunk idea.

**Comment by pauldambra** [comment]
I'll take a look at building these...

**Comment by andyvan-ph** [comment]
These look great:

- I don't think this insight works because of how long UTM paths can be: https://app.posthog.com/insights/MD0OZ7xX
- I'd probably call the advertising one "Performance Marketing"

**Comment by lharries** [comment]
@pauldambra as discussed I've done a dive into what we have so far, let me know any questions you have

**Related issues:**

https://github.com/PostHog/posthog/issues/12732

https://github.com/PostHog/posthog/issues/8300

https://github.com/PostHog/posthog/issues/12195

**High-level why people want templates?**
- Improve activation
    - give them a useful dashboard and set of insights to start with
    - share best practices
    - showcase the powerful tools we have e.g. tables and session recordings on dashboards when they come out
- Help with PostHog’s marketing and tutorials - allowing users to quickly replicate what they see in a tutorial
- Reducing manual setup required for things they frequently create e.g. evaluating the success of a feature
    - When building a new feature you might have a common dashboard that you use each time to evaluate success ([https://github.com/PostHog/product-internal/pull/426](https://github.com/PostHog/product-internal/pull/426))
      - Annika's opinion on the features concept is that what would be most useful is better dashboard templates

**From user interviews:**

- When the starting template is broken or wrong users think PostHog is broken
    - e.g. DAU being the wrong number caused loss of trust in 2 users from product analytics (used session recordings instead)
    - ⇒ Important to make sure the dashboards aren’t broken
- Less technical users primarily using the default template - not creating their own insights

**What we already have:**

- Can load a dashboard from the global repo
    - Need to install the template manually first

**Thoughts on what we currently have**

- I’m not convinced by the “Install” flow currently - I don’t think most people are going to discover it and instead will just think they have 1 template only. Instead it’d be better to just list the templates available for them
- I think what we currently have will be most useful for helping with onboarding and we should create all these dashboards by default
- Where I think further power for dashboards will be unlocked is:
    1. “variables” in dashboards
    2. ability to share dashboards within teams
    3. enabling installing from a link that our marketing teams can share in tutorials

**Next steps:**

- Detailed review of the templates we have in the global repo. @lharries and maybe input from Andy as he’s the expert at them
- The current templates we have in the repo look generally useful - we should install them by default for all new users to help with onboarding
    - The only people using the templates so far are those who are onboarding and exploring posthog, and this could help them:
        - [https://app.posthog.com/recordings/playlists/eAEQNbQF](https://app.posthog.com/recordings/playlists/eAEQNbQF)
        - [https://app.posthog.com/recordings/185bf6d49fc13bd-04eb8da829c862-17525635-384000-185bf6d49fd11c0](https://app.posthog.com/recordings/185bf6d49fc13bd-04eb8da829c862-17525635-384000-185bf6d49fd11c0)
        - [https://app.posthog.com/recordings/185b35e616a2af6-00dd016f9ae1668-3c626b4b-113a00-185b35e616b35b5](https://app.posthog.com/recordings/185b35e616a2af6-00dd016f9ae1668-3c626b4b-113a00-185b35e616b35b5)
- Make it so that all the global templates can be used without “installing”
- Then release what we currently have?

**Version 2:**

1. “variables” in dashboards. Then create a “feature” dashboard
    - This would unlock more custom templates e.g. for evaluating the success of a feature
    - For each template they’d need to be able to add the names and potentially the description
    - Ideally can create a dashboard where you haven’t yet used the event - this would allow you to create a dashboard for a new feature
2. ability to create their own templates and share it with their team

I'm happy to go into more input on version 2 including helping with mockups if useful

**Success criteria for version 2:**

Metrics:

- How many people create dashboards from the templates
- Are the dashboards made from templates reviewed regularly
- Number of templates made

Questions:
- Why are we using github as a backend rather than a database?

**Comment by pauldambra** [comment]
>  Instead it’d be better to just list the templates available for them

Do we have a templates tab at all on the dashboards page in this version?

It is way simpler (I think) always to offer the latest version of any template.

**Comment by pauldambra** [comment]
> Why are we using github as a backend rather than a database?

We started in the DB but moved to GitHub to mimic plugins and let external folk contribute more easily

**Comment by pauldambra** [comment]
I don't think we currently track if a dashboard was created from a template _when viewed_

otherwise https://app.posthog.com/dashboard/61137

**Comment by lharries** [comment]
I think the templates tab will become useful for managing templates (particularly team templates, personal templates) editing them etc. In terms of getting what you currently have shipped I'm not sure it adds much however

**Comment by lharries** [comment]
> We started in the DB but moved to GitHub to mimic plugins and let external folk contribute more easily

I suspect most of the way templates will be used is to share within teams, and from PostHog to individuals. Other advantage of it being in the database is you could edit the dashboard and then save it there. To me it seems we'd move very quickly to using our DB

**Comment by lharries** [comment]
For having external folks contribute, I'd expect we'd do something similar to figma templates in future - with the ability to make and share across the community. Better to have a web UI view rather than a github json

**Comment by pauldambra** [comment]
current flow is

1. build dashboard and see you like it
2. export it
3. this downloads a JSON representation 
4. add that as a file to the templates repository
5. update the template listing file in the repository to point to the head version of the file (or newly add it to the listing file)
6. visit PostHog
7. click install
8. click create new dashboard
9. choose the template

I kept the json separate from the listing file because it would quickly be an unmanageable mess of thousands and thousands of lines of text

I can remove the install/update flow and just auto add them, that removes one step from the flow

The decisions in here were

* all templates are global
* the templates are stored externally to PostHog so that anyone with GitHub access can contribute without understanding our code
* that also means we don't need to build any UI to manage them
* (implicitly) all templates use autocaptured events

------

That doesn't match 

* managing templates (particularly team templates, personal templates)
* editing them etc
* I suspect most of the way templates will be used is to share within teams, and from PostHog to individuals.
* Other advantage of it being in the database is you could edit the dashboard and then save it there

---

The GitHub flow also doesn't help someone who doesn't do Git...

**Comment by pauldambra** [comment]
@mariusandra you were pushing away from storing in the DB

To avoid splitting conversations do you care strongly if we wander back towards it?

**Comment by pauldambra** [comment]
made this https://github.com/PostHog/posthog/pull/14082 and then realised you still need to visit the tab to load the repository so it's more confusing 🤦

**Comment by joethreepwood** [comment]
There are really only two issues I have with the current flow. 

## I don't want to have to install each template 
The flow as I see it is that, if I want to create a new dashboard I'm being asked to first consider if there's a template for it (no idea). So, I go to the `/templates` tab, read through them and click install on each one, _then_ go into the normal dashboard creation flow. 

That's a lot of extra steps and mental load. What I'd end up doing, without doubt, is just installing ALL the templates as soon as I found them and never visiting the `/templates` section again. Which makes me think we don't need it and should just install all templates by default.

## I don't know what's in each template 
The best way, I think, to surface templates to users is at the point they are creating dashboards. That way, they don't need to go to a separate place. The templates are just right there. 

<img width="501" alt="Screenshot 2023-02-03 at 16 53 45" src="https://user-images.githubusercontent.com/84011561/216661131-e44ad078-97c6-42a4-ac0c-4fe4c322c30c.png">

Unfortunately our current solution to this (above) doesn't give me enough information about what's in each template to make a decision. I don't know what may be in user research, for example - curated playlists of power users? Demographic info? 

Ideally, I think we'd want some way to offer more info about each template (or to let users preview them?) at this point. 

---
The core question, however, is 'Is this better than what we have?' - and I think, yes, it is. Having somewhere that we can surface more templates to users at all is a step forward; I can just seem these issues as room for further iteration.

**Comment by pauldambra** [comment]
I wasn't sure what the best way to explain this thought is 🤔 

An external repo gives us an approval flow without building a UI

|                                     | DB Only | external repo |
|-------------------------------------|---------|---------------|
| posthog staff sharing to individual | safe    | safe          |
| posthog staff sharing to any team       | safe    | safe          |
| posthog staff sharing to any org        | safe    | safe          |
| posthog staff sharing globally      | safe    | safe          |
| non posthog sharing to individual   | safe    | safe          |
| non posthog sharing to own team     | safe    | safe          |
| non posthog sharing to own org      | ❌       | safe          |
| non posthog sharing to a different team     | ❌     | safe          |
| non posthog sharing to a different org      | ❌       | safe          |
| non posthog sharing to globally     | ❌       | safe          |

(non of which says that we should build/allow all of those options, but I think those are all of the logical options)

I _think_ the shortest route now is to make the templates global by default. At the moment they're team-specific.

That would mean a staff user could visit the templates tab and install templates once for all orgs/teams on an instance. Which for now lets us release them on Cloud. And then we can figure out what the next step / end goal is

**Comment by pauldambra** [comment]
Added https://github.com/PostHog/posthog/pull/14091 as the smallest step to make templates global

**Comment by josh-1851** [comment]
Yes, internal team templates would be ideal

**Comment by andreemic** [comment]
We create a dashboard for each A/B Test and it would save us a lot of time, if we could create our own templates for them!
