### ISSUE TITLE
Sprint 1.43.0 1/2 - Nov 28 - Dec 9

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#12886]
# Global Sprint Planning

## 3 things that might take us down

1. Hot partitions for distinct ids. Look at limiting this partition @fuziontech 
2.

## Retro: Status of Outcomes from Previous Sprint

1. Refactor onboarding with other options than just ingestion @kappa90 > Almost on track. Little bit of spillover.
1. Sentry is clean and errors are actionable and monitored actively @tiina303 > reprioritised: it's a good onboarding task, persons on events was higher priority.
1. It is easy for anyone to understand the current status of the pipeline with respect to the target metrics (and easy for us to spot and debug issues) @yakkomajuri > Done.
1. "Static" Playlists - Youtube style, adding individual recordings to a list @benjackwhite > Done!
1. Youtube style link to specific point in the recording @benjackwhite > Done!
1. Data Exploration continued - events list breakdowns. @mariusandra > We have an events list but no breakdown yet.
1. Make insights query performance measurable @macobo > Done! Already taken some actions off of this
1. Test feature flag permissioning beta with users & grab feedback @liyiy > Internal testing we should get done, beta will roll over. Thanksgiving.
1. : UI updates to make 100% rollouts prominent + detailed view of users who are hitting flags @neilkakkar > Should be done by the end of the week.
1. Improve our metrics + alerting, specifically around Kafka and Clickhouse, based on action items from incidents @guidoiaquinti > Has been improved a bunch, way more metrics. Alerting will roll over.
1. Sort out access to current monitoring systems, as right now we have several all over the place @ellie > re-prioritized to do metabase.
1. More SOC2 work: @danielxnj > Finished mintors and controls, and reviewed policies.
1. Get new postgres instance replicating @ellie > Didn't get this done, but spent some time configuring this

## Retro: What can we do better next sprint?

1. 
2.
3.
4.
5.

## Support hero this sprint

Week 1: Alex
Week 2: Ben

## Plan: Proposed Goals for Next Sprint 

Each goal should have a single owner. Owner can only be an engineer.

1. migrate billing v1 users to v2 (important) @kappa90 
why? So we have a single billing system
1. continue working on onboarding improvements (design, better tracking, add more ingestion options) @raquelmsmith
why? Improving conversion/activation rates
1. Recording (Comments) / Notes @benjackwhite
Why? - Users have asked for ways to persist context in recordings that would help with a specific problem/bug/idea.
1. "Static" Playlist items long term storage @alexkim205
Why? - Recordings added to static playlists are expected to hang around forever, as opposed to other recordings that have a default TTL
1. Data exploration: First steps live + drill down views (@mariusandra  and @thmsobrmlr )
why? users find it hard to explore data
1. Data integrity: persons on events + user experience component (@macobo & @Twixes )
why? Data integrity is # 1 priority
1. Performance: hit fewer queries from the dashboard, caching, query cancellation @pauldambra 
why? p95 of large customer performance is 18 seconds
1. Analyze and root cause issue impacting potentially 3% of events with events having the incorrect person attributed to the event. Confirm that scope and reach of this issue and find root cause. @fuziontech 
why? Data integrity is # 1 priority
1. Permissions beta testing & UI Polishing @liyiy 
why? We do not want to leave permissions half done and get feedback from suers
1. [Cohort immediate usability bugs](https://github.com/PostHog/product-internal/issues/386) fixing
Why? Leads to a very frustrating experience when basic things like uploading a list of emails doesn't work
1. We have improved monitoring this sprint, but are yet to improve our alerting @guidoiaquinti
why? help us catch incidents before they affect customers
1. Productionize internal metabase + shift to Tailscale internally @ellie
why: we need a metabase for both US and EU, this is mostly now done but will need to get the team setup with Tailscale. The UX for that is much nicer than for openvpn + we can use it for all internal services

# Team sprint planning

For your team sprint planning copy this template into a comment below for each team.

```
Team ___

## Retro

<!-- Talk about what went well, what didn't go well and any actions to improve next time -->

- 

## Hang over items from previous sprint

<!-- For each item, decide to re-prioritise (and add below) or deprioritise -->

- Item 1. prioritised/deprioritise

## Planning

<!-- Each item should have a single owner. Owner can only be an engineer. -->

### High priority

-

### Bugs

-

### Low priority / side quests

-

```

**Comment by kappa90** [comment]
Team Growth

## Retro
- @kappa90 off for half of the sprint due to unexpected wedding
- @raquelmsmith will be off two days for thanksgiving
- @raquelmsmith worked on onboarding demo project and improved signup flow
- @kappa90 worked on new secondary onboarding & customer.io integration

## Hang over items from previous sprint
- demo environment (will be released early next week) @raquelmsmith 
- customer.io new email flows (will be released by Friday) @kappa90 
- secondary onboarding (will be released early next week) @kappa90 

## Planning
- finalize onboarding v2 and launch new experiment @raquelmsmith 
- continue working on onboarding improvements (design, better tracking, add more ingestion options) @raquelmsmith 
- deprioritize self-hosted options (discourage hobby deployments and put kubernetes on forced enterprise plan) @kappa90 
- add posthog docs in-product @kappa90 

### High priority
- migrate billing v1 users to v2 (important)

### Bugs
- after migrating billing v1 to v2, check performance (many outstanding bugs due to users still on v1)

**Comment by alexkim205** [comment]
# Team PostHog TV

## Retro



- Speed > quality meant that we shipped static playlists with bugs, should have hidden behind feature flag

## Hang over items from previous sprint

None

## Planning

### High priority

- Recording (Comments) / Notes @benjackwhite
Why? - Users have asked for ways to persist context in recordings that would help with a specific problem/bug/idea.

- "Static" Playlist items long term storage @alexkim205 
Why? - Recordings added to static playlists are expected to hang around forever, as opposed to other recordings that have a default TTL

### Bugs
- 

### Low priority / side quests
- Continuing UX improvements

**Comment by mariusandra** [comment]
## Team Product Analytics

1. Data exploration: First steps live + drill down views (Marius and Thomas)
   - Replace the live events table with the data exploration view.
   - Replace the persons table with the data exploration view.
   - Next steps after: aggregations on event table views + pivot tables.
   - _Why? Users can't explore data, these are the next steps on the OKR goal._

2. Data integrity (Karl & Michael)
   - Diagnose root cause and (stretch) implement longer term fix for persons on events
   - Investigate UI errors around persons on events. Broader analysis on reliability and data integrity and shipping fixes
   - _Why? Users can't trust data._

3. Performance (Paul)
"to reduce the number of dashboard queries without reducing the number of dashboards analysed"
* dashboards caching https://github.com/orgs/PostHog/projects/71/views/1
* celery utilisation
     * i.e. does celery sit idle for 75 seconds and then hammer ClickHouse for 15 seconds
* query cancellation for dashboards

-------

**Edited December 7th**

Retro (will need to paste to next issue):

- Data exploration: First steps live + drill down views (@mariusandra and @thmsobrmlr )
why? users find it hard to explore data
--> **first steps live, drilldowns in progress**

- Data integrity: persons on events + user experience component (@macobo & @Twixes )
why? Data integrity is # 1 priority
--> pitched in with #team-pipeline at the start, they have it covered now. UX is in works by michael.

- Performance: hit fewer queries from the dashboard, caching, query cancellation @pauldambra
why? p95 of large customer performance is 18 seconds
--> Reduced load from dashboards significantly, property filters are faster, caching improvements will go live soon, query cancellation also nearing completion. On the way also fixing a bunch of bugs with dashboards. :)

----
@pauldambra in Lisbon with Ben at week 1

Possible rollover:
- Pivot tables

Sprint goals
- Data exploration: insights in the new system @thmsobrmlr & @mariusandra (tables cont, insights help)
- Yeet antd from all insight related code @Twixes 
- Web Performance - @pauldambra 
- Performance: @macobo create new tooling for benchmarking and exposing pain, validate moonshot alternative schema (posthog with no sharding). https://posthog.slack.com/archives/C0368RPHLQH/p1670363579097329 for more context

**Comment by fuziontech** [comment]
# Team Pipeline

## Planning

### High priority

- Analyze and root cause issue impacting potentially 10% of events with events having the incorrect person attributed to the event. Confirm that scope and reach of this issue and find root cause.

### Bugs

- Just the above

### Low priority / side quests

- Person on event is top priority

**Comment by neilkakkar** [comment]
Team Experimentation
---

Hang over items from previous sprint
---
Rollout UX to everyone. Needs some beta testing first for perf reasons.
Permissions beta testing

Planning
---

1. Permissions beta testing & UI Polishing
2. [Cohort immediate usability bugs](https://github.com/PostHog/product-internal/issues/386) fixing
Why? Leads to a very frustrating experience when basic things like uploading a list of emails doesn't work

**Comment by ellie** [comment]
# 🚀 Team Infrastructure 🚀 

## Retro

@danielxnj: We discovered more things to be done for SOC2 after digging into the policies, most of them were related to Backups and Security and we managed most of them, but that caused a delay in the Disaster recovery test.
@guidoiaquinti: Good to have Ellie and Harry in Barcelona! Overall: too many interruptions as usual, we are always spread too thin (incidents, ClickHouse EU materialized view issue, customer support, DNS & pgbouncer max conn issue, etc...)
@ellie: Nice to see people in Barcelona! Lots and lots of interruptions, the interruption stack got quite deep this sprint. I've had a few ideas on how to resolve this. Will discuss with the team + implement soon.

## Planning

- We have improved monitoring this sprint, but are yet to improve our alerting @guidoiaquinti 
   why? help us catch incidents before they affect customers

- SOC 2 items remaining: @danielxnj 
   a) Finalize Github backups
   b) DR tests
   c) SOC2 security headers
   d) Risk assessment for Tech and Info Sec questionaries.

- Productionize internal metabase + shift to Tailscale internally @ellie 
   why: we need a metabase for both US and EU, this is mostly now done but will need to get the team setup with Tailscale. The UX for that is much nicer than for openvpn + we can use it for all internal services
- Reduce distractions for the team @ellie 
- Get postgres replicating! Hangover from the previous sprint @ellie
