### ISSUE TITLE
Pages having web controls loading Infragistics DataGrid is not getting recorded

### ISSUE THREAD

**Issue by samratdeb** [PostHog/posthog#12896]
## Bug description

We have an internal web app using web controls and within those controls, we have used Infragistics grids to show data but the recording is done without the grid. The space for the grid is empty/blank space on the screen.

The data is being shown on the browser, but it is weird enough that the recording is missing those parts of the page.

*If this affects the front end, screenshots would be of great help.*  

This is a screenshot from the recording:

![image](https://user-images.githubusercontent.com/9079938/203130225-1f9681f2-0da6-4294-a6ce-0d218bd60b47.png)

This is how it looks on the browser.

![image](https://user-images.githubusercontent.com/9079938/203129566-b083ee97-14dd-4f59-8a1d-798c9bb4c2f9.png)

## How to reproduce

It is an Intranet app, so it cannot be reproduced outside of the office network.

## Environment

- PostHog Cloud

**Comment by benjackwhite** [comment]
Could it be that this part of the page is an iframe? Currently iframes aren't supported due to browser restrictions.

Alternatively it could be that some of the resources needed for playback aren't accessible by PostHog (like some CSS files). You can check the developer console when playing back the recording and look for issues like ".css file was not able to be loaded" - often due to CORS issues. If you can add your PostHog domain as an whitelisted caller then it should work again.

**Comment by pauldambra** [comment]
closing as stale
