### ISSUE TITLE
Shard event data by person_id

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#12909]
## In what situation are you experiencing subpar performance?

Funnel (and other person-analytics) queries frequently need to stream a lot of data to coordinator queries. Read more in the ClickHouse manual: https://posthog.com/handbook/engineering/clickhouse/replication

## Proposed solution

Reshard data by `person_id` and leverage query settings to make queries faster.

Might be wise to combine with https://github.com/PostHog/posthog/issues/12908

**Comment by Twixes** [comment]
100% agree (assuming we're past the point of no return with persons-on-events).

Extra thing to note: `person_id` is a `UUID`, and in ClickHouse that type can't be put in the primary key, because the underlying data is a string. (This is the case for us, because the sampling key must be in the primary key AND it must be an unsigned int.) :/ That means we'll have to transform it. I'd suggest parsing it as an integer, because UUIDTs we use are roughly time-sortable (though there's no direct `toInt()` for UUIDs in ClickHouse, which is a bit annoying). Alternatively we could hash it, but then we lose time-sortability.

The tedious thing about primary keys is that if a key component is some form of `hashOrParse(column)` (e.g. due to `column` being a string), ClickHouse will NOT use that key component in queries with `column = 'foo'` (same for `=!`, `IN` etc.) It will only use the key to that extent when the condition is explicitly formulated as `hashOrParse(column) = hashOrParse('foo')`. We don't do this anywhere, so our present `cityHash64(distinct_id)` primary key is completely unused. I tested this on CH 22.3 and 22.8 – no difference. We could probably improve this in ClickHouse and provide ourselves some automatic performance gain, but the biggest problem is we'd only get the improvement months later when upgrading to the next LTS version (+ none of us have contributed to ClickHouse, but the skill is probably there).
