### ISSUE TITLE
Regressions in new data table component

### ISSUE THREAD

**Issue by Twixes** [PostHog/posthog#13223]
## Bug description

Noticed a few problems in the new feature-flagged events table in Persons (e.g. on [this marius@posthog.com page](https://app.posthog.com/person/pI40e5w84oZfhqdX4Sqf9XVmH5vVM3pyOMY1KRfe9XT#activeTab=events)):
1. Property value columns don't show anything
1. There's no "Time" column
1. There's a redundant "Person" column when on the person page
1. Similarly, there's no date separators
1. _Also_, the ClickHouse query made by the new UI takes very long (literally 20 s on the person page linked above for me, as opposed to 0.5 s with the old UI), because there no longer is a minimum timestamp filter to avoid going through too many CH parts in one query
1. The event buffer notice is missing ("Note that some events with a never-before-seen distinct ID are deliberately delayed by 60 seconds ..."
1. "More"/kebab button column is too wide, it should have `width: 0`

### `data-exploration-live-events` disabled
<img width="1050" alt="on" src="https://user-images.githubusercontent.com/4550621/206511932-545d39af-fdbf-43a8-9b45-39b42acb633b.png">

### `data-exploration-live-events` enabled
<img width="1033" alt="off" src="https://user-images.githubusercontent.com/4550621/206511899-f85868df-e5b3-48ac-b19b-6dd6d57bafd5.png">

**Comment by mariusandra** [comment]
I'm fixing these issues in https://github.com/PostHog/posthog/pull/13251 and have some questions.

> 1. Property value columns don't show anything

I'm not able to reproduce this

> 1. There's no "Time" column

It was also there for me

> 1. There's a redundant "Person" column when on the person page

Fixed

> 1. Similarly, there's no date separators

Do we actually want them? I fear we'll need to remove these when we move to a [virtualized data table](https://github.com/PostHog/posthog/pull/11817), so I didn't implement them yet. Not sure if we even want them in PostHog 3000. Also, if the table is not sorted by time, should there be another label for the other sort key?

Because of these questions, I decided to skip this for now, and I'd gladly just remove this. 🤔 

> 1. _Also_, the ClickHouse query made by the new UI takes very long (literally 20 s on the person page linked above for me, as opposed to 0.5 s with the old UI), because there no longer is a minimum timestamp filter to avoid going through too many CH parts in one query

Will fix.

> 1. The event buffer notice is missing ("Note that some events with a never-before-seen distinct ID are deliberately delayed by 60 seconds ..."

Do we want to show this everywhere. This events table query is used in:

- **Live events**
- Person > Events
- Action > Edit
- Feature flag > Exposures
- Event definition > View
- Group > Events
- Web Performance

I think showing it everywhere is just noise. E.g., what's the chance if you're looking at a person, you expect to see a "never before seen distinct ID" there? Educating people with this message at the live events page is probably enough. 

If we want to put this on every events table, I'd try to find a way to show this information in a tooltip, not in this wide banner.

> 1. "More"/kebab button column is too wide, it should have `width: 0`

Fixed

**Comment by Twixes** [comment]
1. As for property value columns, it seems for some reason I didn't have "Time" added in the column configurator (even though it was there for the legacy table), but still something doesn't look right:
    <img width="336" alt="Screenshot 2022-12-13 at 14 23 26" src="https://user-images.githubusercontent.com/4550621/207330792-daf95d52-3a7a-4fa5-9612-c0649ecde8c8.png">
    This is on Cloud US.

2. Date separators do feel useful. Of course they only make sense when the table is sorted by timestamp, but they give a sense of clarity, and a bit of slickness. I think it makes sense to keep them (and from the user's perspective, we're talking about _keeping_ a feature and not _adding_).

3. We really only want the event buffer notice in Live Events (since they call themselves live), though I hear Pipeline are working on making those _100%_ live, in which case we'll be able to drop it.
