### ISSUE TITLE
Screen recording does not work with shadow DOM

### ISSUE THREAD

**Issue by NathanFlurry** [PostHog/posthog#13255]
## Bug description

PostHog does not record shadow DOM elements correctly.

See a CodePen demo [here](https://codepen.io/NathanFlurry/pen/rNKbRyL).

What the user sees:

<img width="1000" alt="image" src="https://user-images.githubusercontent.com/3322446/206887249-201d627a-2cb5-4301-bf24-4229992ba37c.png">

What PostHog sees:

<img width="760" alt="image" src="https://user-images.githubusercontent.com/3322446/206887243-68dee6bd-539d-40d0-8400-c1d67b03d88d.png">

## How to reproduce

1. Visit https://codepen.io/NathanFlurry/pen/rNKbRyL
2. Replace the token with your PostHog token
3. Whitelist screen recording on `https://cdpn.io`
4. Generate a recording
5. View the recording on PostHog. You should only see two red squares.

## Environment

- [X] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: please provide

## Additional context

Only tested with Lit. Have not tried other web components.

**Comment by simonireilly** [comment]
I also can recreate this @NathanFlurry 

One thing is strange, https://www.rrweb.io/ is the basis for posthog browser recording, and it does support shadow DOM.

Is this feature disabled in Posthog - or is it just a version mismatch with [rrweb](https://github.com/rrweb-io/rrweb) ?

## Edit

It looks like the Posthog version of rrweb is the latest: 

<img width="362" alt="image" src="https://user-images.githubusercontent.com/30017294/208408382-228d2125-bb63-42e1-9245-13d56c332e96.png">

One thing is that maybe thw react web replayer does not support shadow DOM, because all the details are captured from the rendered shadow DOM in my recordings, but the replay is broken.

@NathanFlurry possibly try and recreate the issue by using rrweb with [svelte web player](https://github.com/rrweb-io/rrweb/tree/master/packages/rrweb-player/) and [posthog-react-web-player](https://github.com/posthog/posthog-react-rrweb-player)

Might just be rendering is not supported in the react version

**Comment by NathanFlurry** [comment]
@simonireilly Thanks for the help!

**Vanilla rrweb player**

I pulled in the vanilla Rrweb player and it seems to work fine.

New Lit example: https://codepen.io/NathanFlurry/pen/rNKbRyL
Rrweb player: https://codepen.io/NathanFlurry/pen/KKBvvgq

(Clip "Copy to clipboard" then go to the player and click "read clipboard")

**Styling issues**

It still fails to load the styling sometimes, but can't seem to reproduce consistently.

Sometimes it shows this:

<img width="201" alt="image" src="https://user-images.githubusercontent.com/3322446/212562372-3b3b180b-e628-4cd7-a280-0c596227be8f.png">

And sometimes it shows this:

<img width="214" alt="image" src="https://user-images.githubusercontent.com/3322446/212562410-c254fcdd-dbce-4df5-b5a9-32666c77f57d.png">

**Real world demo**

I pulled in the vanilla recorder to https://rivet.gg/home and it seems to record the shadow DOM there too, but won't pick up on styling.

The base recording size is 13 MB without any interaction, so this might not even be realistic for us to use unless there was a way of streaming events. But that's an issue for another day 😅

**Comment by romfrolov** [comment]
Recently we switched from FullStory to PostHog and our recordings stopped displaying shadow DOM elements correctly.

Actual:
![Screenshot 2023-02-13 at 10 01 32 AM](https://user-images.githubusercontent.com/23285565/218414956-5c59e02d-86d7-4ae8-ab9c-479083a9a107.png)

Recording:
![Screenshot 2023-02-13 at 9 59 26 AM](https://user-images.githubusercontent.com/23285565/218414791-a909b51a-6fb9-4574-9bbb-cc39b3b6daee.png)

**Comment by pauldambra** [comment]
The default version of rrweb is now version 2. This should resolve this, feel free to re-open or open a new issue if this is still happening for you

**Comment by YaroslavMelnyk1** [comment]
any updates on this please?

**Comment by YaroslavMelnyk1** [comment]
Wow, thanks for you answer @pauldambra, didn't expect to get it on such an old ticket.
Yeah, I see it's closed.
But actually problem keeps the same. 
Even with rrweb V2 it's not applying styles for shadow dom elements on recordings.
Let me know if you need more details on this pls.
(I don't have permissions to reopen this ticket but let me know if you want me to create a new one)

**Comment by ricky11** [comment]
I can confirm that most webcomponents (like the ones used in the web awesome UI framework) which heavily uses shadowdom are not being recorded by posthog.   sadly we've rewritten  our application is many of these components, and  since  most of the ui interactions show nothing..

**Comment by ricky11** [comment]
This has not been resolved.
