### ISSUE TITLE
Unable to play session recordings 

### ISSUE THREAD

**Issue by TobiasIgnatzek** [PostHog/posthog#13272]
## Bug description

We are unable to play some session recordings. The issue appears after watching 2-3 recordings. 
Reloading the page does not solve the issue unfortunately. 

We usually watch them on 4x speed. Sometimes, I jump to specific events. 

<img width="490" alt="Screenshot 2022-12-12 at 14 12 42" src="https://user-images.githubusercontent.com/52070588/207053696-6a0b745b-7dc0-4428-ae0a-a7ee093a136d.png">

## How to reproduce

1. Watch 2-3 session recordings
2. Watch a few more. The playback will stop at some point and a popup is shown. 
3. Reload the page and play the same session recording. It will stop at the same timecode, the error notification will appear again.

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: please provide

**Comment by benjackwhite** [comment]
Could you give us a link to the recording in question (assuming you are on Cloud) otherwise it is pretty impossible to debug 😉

**Comment by tobiasignatzek** [comment]
Absolutely, 
here are some links:
https://eu.posthog.com/recordings/184ec6fa0673fdc-0848970dbdebf68-3c62684b-13c680-184ec6fa0684da6 (none of the recordings for this user can be played)
https://eu.posthog.com/recordings/184f0e9387ef4c-010d6cb3a61726-17525635-16a7f0-184f0e9387f21fa (stops at 00:04:00)

Edit:
- it seems that for some "persons" the replay never works, while for other recordings it only stops somewhere in the middle.
- I see this error in the console: 
`Blocked script execution in 'https://eu.posthog.com/recordings/recent?filters=%7B%22session_recording_duration%22%3A%7B%22type%22%3A%22recording%22%2C%22key%22%3A%22duration%22%2C%22value%22%3A60%2C%22operator%22%3A%22gt%22%7D%2C%22properties%22%3A%5B%7B%22key%22%3A%22email%22%2C%22value%22%3A%22superchat%22%2C%22operator%22%3A%22not_icontains%22%2C%22type%22%3A%22person%22%7D%5D%2C%22events%22%3A%5B%7B%22id%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%2C%22name%22%3A%22%24pageview%22%2C%22properties%22%3A%5B%7B%22key%22%3A%22%24current_url%22%2C%22value%22%3A%5B%22https%3A%2F%2F---%2F---%2F---%22%5D%2C%22operator%22%3A%22exact%22%2C%22type%22%3A%22event%22%7D%5D%7D%5D%2C%22actions%22%3A%5B%5D%2C%22date_from%22%3A%222022-11-21%22%2C%22offset%22%3A20%7D' because the document's frame is sandboxed and the 'allow-scripts' permission is not set.` (redacted parts of the current url)
- Also, I get this second error notification sometimes: <img width="245" alt="Screenshot 2022-12-12 at 14 28 58" src="https://user-images.githubusercontent.com/52070588/207057345-66a6f9ee-0f86-4409-bbba-f41df3011e30.png">

**Comment by benjackwhite** [comment]
Managed to get to the error that is happening here. Seems to be something encoded weirdly in the recording. I'll try to debug further and figure out what specifically is going on.

**Comment by benjackwhite** [comment]
Okay I've got as far as finding it is due to some surrogate emojis being only partially encoded properly. The question is why... Got a PR going in to log some more info so I can debug a bit better (it's hard as the encoding is breaking our logs as well 😅 

Related DRF issue https://github.com/encode/django-rest-framework/issues/6895

**Comment by benjackwhite** [comment]
@TobiasIgnatzek this should be "fixed" now. I am not sure how but it looks like some non-standard emojis get tracked which was crashing the response engine from the API. Now we fallback to just return the non-standard unicode character so it _may_ break in the browser and render weirdly but I think browsers are "clever" and translate bad encoding to something correct on the fly.

If you are still seeing issues feel free to re-open. Thanks again for the detailed issue links!
