### ISSUE TITLE
Upgrading Postgres-based to Clickhouse-based

### ISSUE THREAD

**Issue by turova** [PostHog/posthog#13482]
## Bug description

First off, Posthog is incredible, thank you for for making something this good so accessible!

Not a bug, but I've spent a bit of time looking around and can't seem to find any consistent directions on migrating from PG-based 1.30.0 to a clickhouse-based instance (which is why I haven't done it yet).

What I did find was the "Array 1.31.0" product update saying I must upgrade to clickhouse first, but the migrate link it brings me to says that the version must be exactly the same for the old and the new. Obviously I could just set up a fresh instance, but it won't be very useful without the data I've collected so far so I'm hoping there's a guide I missed. Maybe it's possible to migrate from legacy 1.30.0 to a fresh 1.31.0 and go from there?

Sorry if this has been covered a bunch and I somehow missed it. I looked around the public docs and issues and didn't find anything.

## How to reproduce

1. Have a legacy 1.30.0 docker-compose install
2. ???

## Environment

- [ ] PostHog Cloud
- [V] self-hosted PostHog, version/commit: 1.30.0

**Comment by kappa90** [comment]
Hi @turova, have you seen this guide?

https://posthog.com/docs/migrate/migrate-to-another-self-hosted-instance

It should help you migrate from a PG-based instance to a new CH-based one, I hope this helps!

**Comment by turova** [comment]
@kappa90 Thanks for the response - that's the link I referenced that says 

> Your old and new instances should both be running the exact same version of PostHog (minimum 1.30.0).

So my old version is stuck on 1.30.0 and if I clone a fresh install, the docker-compose file for 1.30.0 doesn't include clickhouse, so migrating to a fresh 1.30.0 just migrates to a new PG-backed config that I still can't upgrade any further.

**Comment by kappa90** [comment]
If you want to [self-host](https://posthog.com/docs/self-host), we currently offer two options:

- For enterprise customers, we offer you support to host your own PostHog instance on a Kubernetes cluster, this comes with a 5,000$/month minimum. If that's interesting for you, [book a call with us](https://posthog.com/book-a-demo) to help you get setup
- Otherwise, we don't support community deployments anymore, and what you can do is to use [the main repository at the time of the 1.30.0 release](https://github.com/PostHog/posthog/releases/tag/1.30.0), and deploy it on your own [following our docs](https://posthog.com/docs/self-host/open-source/deployment)
