### ISSUE TITLE
Not obvious you can "pin" toolbar infowindows

### ISSUE THREAD

**Issue by mariusandra** [PostHog/posthog#1372]
## Bug description

When hovering over a page with lots of elements, unless someone tells you, it's not inherently obvious you can click on any of the elements to "pin" the infowindow to the screen. 

![2020-08-06 16 44 51](https://user-images.githubusercontent.com/53387/89545909-3cd0b100-d804-11ea-82fa-b3d512575e2d.gif)

## Expected behavior

Somehow this should be more obvious.

One idea is that the infowindow is normally not pegged to the bottom/top of the heatmap element, but is always floating right under the mouse cursor (while you hover the element).

This would make the page feel smoother and less flashy... and it would probably make the click more obvious. Maybe.

## Additional context

This came out in a toolbar feedback session with a customer

**Comment by paolodamico** [comment]
👍 I actually was going to report that you couldn't scroll down on the tooltip that popped up because when you moved the mouse to the tooltip window, the tooltip would disappear.

<img width="292" alt="Screen Shot 2020-08-06 at 12 04 29 PM" src="https://user-images.githubusercontent.com/5864173/89560743-2105e480-d7dd-11ea-9f1e-6fefbff4ab32.png">
