### ISSUE TITLE
Toolbar heatmap "yellow labels" aren't clear

### ISSUE THREAD

**Issue by mariusandra** [PostHog/posthog#1374]
## Bug description

Is this the number of clicks? Or what is this number?

![image](https://user-images.githubusercontent.com/53387/89546526-fd569480-d804-11ea-98ad-c64401edfd90.png)

## Expected behavior

It should be clear either directly or with a tooltip that this is the ranking, not a list.

Perhaps it should be "#1" instead? Or "No 1" (with "No" being in a small font). Not sure...

## Additional context

Came out of a call with a customer.

**Comment by paolodamico** [comment]
👍 I was actually going to make this suggestion. At first I thought they were number of clicks. From a UX perspective perhaps it's more relevant to have the number of clicks there and the ranking on the tooltip? We could do something like "1.5k" instead of 1,458 so the screen doesn't look crazy filled with numbers?
