### ISSUE TITLE
Posthog session recording is not supported with web-gl canvases

### ISSUE THREAD

**Issue by samtlyoung** [PostHog/posthog#13888]
## Bug description

I was watching screen recording and it's not captureing our 3D viewer which is made with web-gl canvases.

<img width="1678" alt="image" src="https://user-images.githubusercontent.com/16791348/214184875-261bec8e-986f-41d3-8360-bdf6be8fc52e.png">

**Comment by pjhul** [comment]
Hi @samtlyoung, thanks for creating an issue! 

Unfortunately, this isn't something we support right now. We use `rrweb` under the hood for session recordings, and it looks as though [playback of recordings with canvases](https://github.com/rrweb-io/rrweb/blob/rrweb%401.1.3/docs/recipes/canvas.md) is still unsafe and so isn't something we can enable right now. 

I'm tagging @benjackwhite as the feature owner of recordings in case there's any extra context here. I'm also changing this to a feature request rather than a bug as for now this is the intended behavior for the time being.

**Comment by benjackwhite** [comment]
Paul nailed it on the head. Canvas playback requires a level of script loading that ends up in a situation where PostHog app would be exposed to potential bad actors which is the main reason we can't offer it right now.

**Comment by daibhin** [comment]
We now support canvas replay so this should be fixed! See https://github.com/PostHog/posthog/issues/14555 for more context
