### ISSUE TITLE
Feature flags UI improvements

### ISSUE THREAD

**Issue by liyiy** [PostHog/posthog#14059]
- [ ] Make enable flag button more prominent on the feature flag screen and without having to go into edit mode
- [x] Multivariate code snippet instructions 
- [ ] Add more useful automatic metrics/insights on the flag
- [ ] Deleting a feature flag success toast is buggy. Also, add a double confirmation when deleting enabled flags.
- [ ] Rollouts with multiple groups should at least partially show which groups they belong to on the feature flags table
- [ ] With the addition of tags, the feature flags table is also now too long width wise
- [ ] Add "experiment" tags by default to experiment feature flags 
         - https://github.com/PostHog/posthog/pull/13879 (can be picked up)

**Comment by annikaschmid** [comment]
# QA of code snippet

## General

- [x] React is missing from the list of libraries, and we should add Flutter once we have the docs

## Design

- [ ] Position of Auto rollback in read view

In the feature flags view (read/non edit), the Auto rollback is in between the release conditions and "how to implement". Did we do this on purpose? It looks a bit weird because the Auto rollback doesn't have any content. We might not need to fix this now since it's not available, but we shouldn't forget about it

<img width="749" alt="Screenshot 2023-03-21 at 17 11 40" src="https://user-images.githubusercontent.com/14750837/226688419-b22242c0-108b-48fc-af64-d966514d41b4.png">

- [x] Hierarchy of code example headlines

If we think of the structure of the page, this is how I see it
...
X. Served Value
Y. Release Conditions
Z. How to implement
Z.1 Payloads
Z.2 Bootstrapping

The visual hierarchy currently doesn't reflect that. Z and Z.1/Z.2 are bigger than X and Y. Can we update this to match the hierarchy? If we don't have a headline smaller than what we have for "Release Conditions" at the moment, I would fall back and use it for both Z and Z.1/Z.2

<img width="912" alt="Screenshot 2023-03-21 at 16 56 14" src="https://user-images.githubusercontent.com/14750837/226684631-902521da-f673-4572-b5dc-d6d6c3b16c8f.png">

- [x] Center "Advanced settings"

On hover and when selected, the content is currently misaligned/not centered

<img width="1250" alt="Screenshot 2023-03-21 at 16 59 35" src="https://user-images.githubusercontent.com/14750837/226685377-4da1cb1f-d844-4bb7-a785-82d08deadafc.png">

- [ ] Remove box around "Permissions" and change headline styling to make it the same as "Auto rollback"

<img width="1230" alt="Screenshot 2023-03-21 at 17 09 36" src="https://user-images.githubusercontent.com/14750837/226687905-21726b00-0955-4f65-a2b7-9da580d4edc5.png">

## Wording

- [x] ReactNative -> React Native

<img width="250" alt="Screenshot 2023-03-21 at 17 10 33" src="https://user-images.githubusercontent.com/14750837/226688224-f3ed3283-1899-4c98-b442-5336db1a57a8.png">

- [x] Bootstrap / Bootstrapping
For the checkboxes, we say "Show **Bootstrap** option" When I select it, the headline then says "**Bootstrapping**". I think this should be the same and call the checkbox "Show Bootstrapping option". Same for payloads, where we currently say "Payload" / "Payloads"

<img width="830" alt="Screenshot 2023-03-21 at 17 06 51" src="https://user-images.githubusercontent.com/14750837/226687249-310a1ced-2539-44c0-bc8d-82eba1f8571f.png">

- [x] Go vs Golang
We call it 'Go' in our docs, but 'Golang' in the UI. This is super minor, but still would be nice to be aligned

Side note: I love that "Check the docs" goes to the selected SDK. Nicely done :)
