### ISSUE TITLE
Apps got disabled without my interaction on PostHog Cloud

### ISSUE THREAD

**Issue by weyert** [PostHog/posthog#14088]
## Bug description

Earlier this week together with a colleague we configured our PostHog projects with the BigQuery plugin and started the process by initiating the export job so existing events are being sent to our BigQuery dataset. Only for someone this plugin and the other configured plugins got disabled without knowledge and the steps for disabling each plugin is not showing up in the “History” tab on the Apps page. 

The last entry was from Friday/Saturday saying: `Finished exporting historical events between 2022-01-01 and 2022-01-01 (inclusive).`

Even the BigQuery plugin configuration got lost, their is an history entry from earlier this week of uploading cloud key but nothing about removing it or updating the configuration or disabling the plugin.

Did PostHog disable these apps?

## Environment

- [X] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: please provide

**Comment by fuziontech** [comment]
We spent some time debugging this just now. A few interesting tidbits from the debugging:
1. The frontend was showing that *no* plugins were configured
2. The database was showing that 4 were configured and enabled
3. The api results for `plugin_config` was showing 4 configured and enabled plugins
4. There was a reducer error on `loadPluginConfigs` when trying to get the `plugin` key from the results (code and results looked fine though)
5. Suddenly and for no apparent reason the results started to look ok on the frontend for both @weyert and I at the same time? No idea why this could have happened except for cached bad code? The last deploy for posthog was over 5 hours before this.

Effectively this is resolved, but the root cause has not been identified.
