### ISSUE TITLE
Wildcard not working

### ISSUE THREAD

**Issue by NorhanMostafa94** [PostHog/posthog#14707]
1. Go to recordings page
2. Open "Configure recordings" modal from top right "Configure"
3. Authorized domains for recordings
4. Add link with * (ex: *.domain.com)

but no records found for this link

**Comment by benjackwhite** [comment]
Can you confirm that the `decide` response in the network panel is returning false for the domain in question?

<img width="979" alt="Screenshot 2023-03-13 at 11 25 22" src="https://user-images.githubusercontent.com/2536520/224675228-6d5d7462-37ed-4015-b8ae-28f7ac3a3e9b.png">

Also could you provide as much info as possible otherwise debugging is pretty impossible 😅 
Exact domains and configuration, as well as your ProjectID would help us to have a deeper look. (You can join email support if there is anything you don't want shared publicly)

**Comment by NorhanMostafa94** [comment]
@benjackwhite Thanks for your support, decide api it was not calling but now working.
I have a question, Do I need to add the link suggestion every time?
<img width="771" alt="image" src="https://user-images.githubusercontent.com/46131227/224683115-847295be-d18d-499c-a9a4-592643223b93.png">

**Comment by NorhanMostafa94** [comment]
@benjackwhite I've tried but I think not, Thanks again for quick response

**Comment by benjackwhite** [comment]
You don't need to have the suggestions if you're wildcard works (they will keep being suggested though atm).

Wildcards only work for subdomains though as described so if your website is `myapp.com` then you could have 

1. `https://*.myapp.com`
2. `https://myapp.com`

and that would work for `FOO.myapp.com` but not for `FOO.BAR.myapp.com` as it only wildcards one sublevel
