### ISSUE TITLE
Consider integrating rrweb, for recording and replaying interactions?

### ISSUE THREAD

**Issue by kevinmickey** [PostHog/posthog#149]
rrweb (https://github.com/rrweb-io/rrweb) is an open-source alternative to Hotjar that records complete interactions during a session, and allows them to be replayed later.

Would you consider integration for this kind of feature?

PostHog would basically just need to store JSONs -- rrweb provides the data collection script, and the recording player.

**Comment by jamesefhawkins** [comment]
We're definitely interested in trying to make it easier for developers to know how their products are being used!

We were thinking of building some heatmaps functionality to help make this a little easier to visualise.

I'd love to know how this integration would help meet your use case in a bit more depth?

**Comment by allan-simon** [comment]
I totally agree that having both these feature in the same tool would be awesome for our product team

**Comment by kevinmickey** [comment]
I am interested in taking a specific user, and visually watching them interact with the website -- it really helps put you in a user's shoe, and identify UX issues.  (Heatmaps also sound nice, although as a separate feature.)

After thinking more about this, I've realized that there might be two options to getting this kind of recording and replaying of interactions.  rrweb would be easy to integrate (just store JSONs), but would be a little redundant in terms of data being stored.  A more native solution would be to offer a configuration option in JS snippet to record hover / mouse position for a particular session.  The downside to this option is that it would probably involve a lot of work to write code for replaying the session -- maybe see if there's a way to export events as compatible with [rrweb-player](https://github.com/rrweb-io/rrweb-player)?

Just brainstorming...

**Comment by jamesefhawkins** [comment]
Thanks for these points both, it is really nice to hear from both of you :)

I agree that the heatmaps need to be a specific and separate feature. I'm glad you like the sound of them. I will create a fresh issue for these + a fresh issue for user paths so you can see our thoughts on those, which I'd consider serve a similar use case "as a developer, I need to know what do most users do, so  I don't build the wrong thing next".

However, I also see the value in "exception based" tracking - ie I would want to use an rrweb's video to work out when individual users get stuck. The advantage of rrweb over paths/heatmaps would be being able to spot when a user gets stuck because the UI is broken on a half-width screen window, for example. This is specifically a good idea because it helps make PostHog better for developers who are creating new projects, that have tons of bugs and weird user behavior, with low user numbers - so you really can watch the videos. That bottoms up adoption is how this community will grow. We would gladly take a PR for an integration here - it'd need some scoping just so it doesn't create significant memory requirements from all the data.

For our internal team (me, Tim and Aaron), at the moment, we need to get the most basic principles of product tracking in place for the majority of traffic, because that will have the greatest impact (we had thousands of visitors from HN yesterday, I want to know roughly what they all did on our website, for example... and I can't quickly do this), so I'd like to focus on the heatmaps and paths in the very immediate future, but let's leave this ticket open should someone want to pick up a PR in this area, if that's ok with you?

**Comment by kevinmickey** [comment]
Totally understand, and appreciate all this work that you're sharing as open-source!

**Comment by allan-simon** [comment]
+1 that heatmap is more important than individual session recording.

**Comment by jamesefhawkins** [comment]
#171 = I added some thoughts on user paths... heatmaps to follow!

**Comment by jamesefhawkins** [comment]
As an FYI @allan-simon @kevinmickey , #741 is worth a read / weighing in on the discussion - we're going to start development on that very soon

**Comment by macobo** [comment]
This feature is very exciting for me for two reasons:

### Qualitative analysis

At my current job we do "movie nights" every so often, just looking at how users use our web or mobile app. Each time it gives us a ton of insight into what is confusing for them, what they struggle with. This is super-valuable since our users are often not computer-savvy nor technical so clear UX is key. Tools I've used for this in the past have been hotjar, auryc, fullstory.

### Bughunting

Whenever bughunting a stray bug trying to reproduce it is key to being able to fix it. Reproducing is not always easy - the error monitoring tools might have some context on what the user did, but it might not be easy to digest or complete. 

This is where recordings come in - I've spent many hours trying to track down session recordings from the above-mentioned tools to figure out what went wrong and what did the user do before. This is super valuable, but also time-consuming since by error tracking tool (bugsnag) is not tied at all with the recording tools.

**Comment by jamesefhawkins** [comment]
This is now integrated!!! @kevinmickey  and @allan-simon I know you raised this a while ago, we'd *love* any feedback as it's in beta :)

**Comment by danielolivaresd** [comment]
This is a very useful feature. Would you consider somehow using rrweb's [Real-time Replay (Live Mode)](https://github.com/rrweb-io/rrweb/blob/master/docs/recipes/live-mode.md) so we can have a Live View of our users' sessions?

**Comment by allan-simon** [comment]
@jamesefhawkins  I'm soon to start reusing posthog for my new company, and definitely having this feature will be a huge plus against falling into the darkside of hotjar etc.  , thanks a lot
