### ISSUE TITLE
Clean install on NGINX proxy not working + "posthog_action" relation error

### ISSUE THREAD

**Issue by pavitrakumar78** [PostHog/posthog#14910]
## Bug description

I'm trying to run a clean install of posthog on a subdomain: posthog.mywebsite.com. 

mywebsite.com works and has proper records on cloudflare and nginx settings on server. 

I've setup the nginx settings for subdomain like below in /nginx/site-available:

```
server {
    listen 80; 
    listen 443 ssl; 

    server_name posthog.mywebsite.com www.posthog.mywebsite.com; 

    ssl_certificate /etc/ssl/certs/cloudflare_certificate.pem;
    ssl_certificate_key /etc/ssl/certs/cloudflare_certificate_key.pem;
	
    if ($scheme != "https") {
        return 301 https://www.posthog.mywebsite.com$request_uri;
    }
    return 301 https://www.posthog.mywebsite.com$request_uri;  
}

server {
    server_name www.posthog.mywebsite.com; 

    listen 443 ssl;

    ssl_certificate /etc/ssl/certs/cloudflare_certificate.pem;
    ssl_certificate_key /etc/ssl/certs/cloudflare_certificate_key.pem;
	
        # https://posthog.com/docs/self-host/configure/running-behind-proxy
	location / {
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
			proxy_set_header Host $http_host;
			proxy_redirect off;
			proxy_set_header X-Forwarded-Proto $scheme;
			proxy_pass http://127.0.0.1:8000;
		}


    if ($scheme != "https") {
        return 301 https://www.posthog.mywebsite.com$request_uri;
    }
}
```

Issues:

1. I'm seeing errors related to `posthog_action` relation not existing
2. Checking the subdomain simply re-directs to main website - I'm not sure if PH is working or connecting to the ports/via proxy
3. I've added `IS_BEHIND_PROXY=True` and `TRUST_ALL_PROXIES=True` to global Ubuntu env - I'm assuming this should be enough since the installation picked up the former - but why is it complaining about the proxy trust settings?

## How to reproduce

1. Running the installation script via `/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/posthog/posthog/HEAD/bin/deploy-hobby)"`
4. Use default for the latest-release and insert domain: posthog.mywebsite.com
5. Wait for setup
6. Will receive error saying port is already in use from caddy since I'm trying to setup using proxy (this will exit script)
7. Open `docker-compose.yml` and delete caddy entry
8. run `docker-compose restart` - all services start without issues
9. Inspecting logs result in the following:

> docker logs posthog-db-1
![image](https://user-images.githubusercontent.com/5354407/228081953-7b2d7c71-0fc8-49c1-a861-cd1ffa8e7618.png)

> docker logs posthog-web-1
![image](https://user-images.githubusercontent.com/5354407/228082009-92a421a9-63f2-4eb9-9858-a1fa564531d3.png)

> docker logs posthog-worker-1
![image](https://user-images.githubusercontent.com/5354407/228082437-6b8d1f7f-2f3c-4b8a-960e-e03bad1ef2df.png)

I did not find any help/guide on running with nginx other than the one post here: https://posthog.com/docs/self-host/configure/running-behind-proxy. A lot of posts were made in the community support forum but all of these threads are dead without answers. 

I would appreciate any help or guidance on setting up a clean installation using a proxy on a server running behind nginx+cloudflare. 

## Environment

- [x] PostHog Hobby self-hosted with `docker compose`, version/commit: `latest-stable`

**Comment by tomasfarias** [comment]
Thanks for opening up a separate issue, this allows for better tracking.

> I'm seeing errors related to posthog_action relation not existing

This is expected. The PostHog plugin-server code starts up before the database migrations have finished, so the first few queries will fail until the migrations have finished. I'll note that the `docker-compose.yml` deployment should be extended to wait for migrations.

> I've added IS_BEHIND_PROXY=True and TRUST_ALL_PROXIES=True to global Ubuntu env - I'm assuming this should be enough since the installation picked up the former - but why is it complaining about the proxy trust settings?

No, adding IS_BEHIND_PROXY=True and TRUST_ALL_PROXIES=True to global Ubuntu env is not enough or required: the environment variables should be set in the docker container, not the host machine. It's picking up the former because [it's set to `'true'` by default](https://github.com/PostHog/posthog/blob/master/docker-compose.base.yml#L67).

This is likely also why PostHog is not working correctly with your proxy.

I suggest the following:

1. Clone the PostHog repo: `git clone https://github.com/PostHog/posthog posthog`
2. Edit the `posthog/docker-compose.base.yml` file: add `TRUST_ALL_PROXIES='true'` to the `worker` environment right after `IS_BEHIND_PROXY='true' in the service spec.
3. Edit the `posthog/docker-compose.hobby.yml` file: get rid of the `caddy` service (this file will eventually become the `docker-compose.yml` you were correctly editing, so we are just getting ahead of the script, you could still wait until it fails and do your own editing).
5. Run the `deploy-hobby` script like before.

**Comment by pavitrakumar78** [comment]
Thank you for the suggestions. I did the changes and while the installation did not result in any errors, it did not exit on its own and was stuck at the ` Waiting for Posthog web to boot` stage (I waited more than 30 minutes) and then exited manually and did `docker-compose restart`.

Checking the logs,

> posthog-db-1
![image](https://user-images.githubusercontent.com/5354407/228563088-4df8027e-1d7d-4799-9640-95ab7adeb21c.png)

> posthog-worker-1
![image](https://user-images.githubusercontent.com/5354407/228562968-ca4706d6-cbac-4b9a-b04b-1480f0b25bbd.png)

> posthog-web-1
![image](https://user-images.githubusercontent.com/5354407/228562840-a8f8e534-bef0-4276-b633-6e0ed209282d.png)

Improvement in web as you suggested fixing the env. But, I still see errors with `posthog_action`. Should the site launch even with this error? 

I tried launching `posthog.mywebsite.com`, but it just redirects to `mywebsite.com`. I have not changed the nginx settings mentioned in my original post.

Any suggestions on how I can debug this?

**Comment by tomasfarias** [comment]
The issue seems to be `posthog-web-1` is not starting as you are running a newer version of ClickHouse.

Which version of PostHog are you trying to run?

Both PostHog versions `latest` and `latest-release` (default) require ClickHouse 22, but it seems you are in an older version PostHog that requires an older ClickHouse.

**Comment by pavitrakumar78** [comment]
I'm using the script mentioned in the main post. `/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/posthog/posthog/HEAD/bin/deploy-hobby)"` and I have cloned the repo as you have suggested - this means, I should be trying to install the most recent version of posthog right? 

Or are there any other pre-requisites/requirements that I am missing?

**Comment by tomasfarias** [comment]
> this means, I should be trying to install the most recent version of posthog right?

It depends: the script asks you which version of PostHog you want to run. What did you answer?

> Or are there any other pre-requisites/requirements that I am missing?

Besides figuring out why PostHog is running on an older version, the other requirement would be to expose ports `8000:8000` in the `web` docker service. As Nginx cannot access the docker network without those. The Caddy server works as it's already in the docker network, if we remove it, we now need to expose `web`.

I managed to get a basic Nginx setup running by doing just the following:

1. Clone the PostHog repo: `git clone https://github.com/PostHog/posthog posthog`
2. Edit the `posthog/docker-compose.base.yml` file: add `TRUST_ALL_PROXIES='true'` to the worker environment right after `IS_BEHIND_PROXY='true'` in the service spec.
3. Edit the `posthog/docker-compose.hobby.yml` file: get rid of the Caddy service
4. Edit the `posthog/docker-compose.hobby.yml` file: expose ports `8000:8000` in `web` service. It should now look like:

```
    web:
        extends:
            file: docker-compose.base.yml
            service: web
        command: /compose/start
        volumes:
            - ./compose:/compose
        image: posthog/posthog:$POSTHOG_APP_TAG
        ports:
            - 8000:8000
        environment:
            SENTRY_DSN: $SENTRY_DSN
            SITE_URL: https://$DOMAIN
            SECRET_KEY: $POSTHOG_SECRET
```

5. Install Nginx and configure a server (this is just a basic config, you will need your changes to support your specific subdomain): 

```
server {
        listen 80;
        server_name _;
        location / {
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header Host $http_host;
                proxy_redirect off;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_pass http://127.0.0.1:8000/;
        }
}
```

6. Run `deploy-hobby` for the `latest` PostHog version. `latest-release` probably will not work with the changes as `git` will complain as it's trying to overwrite them. If you want to use `latest-release` instead of `latest` you can remove the `if` block that uses `git` commands (we have already cloned the repo ourselves in 1).

**Comment by pavitrakumar78** [comment]
Thanks for the detailed suggestion.

I think I almost got it to work. I'm able to see the page load up, but it's not able to fetch any of the static files:

![image](https://user-images.githubusercontent.com/5354407/228633350-db10d127-7720-44fd-bfc8-72ab3ab4ae30.png)

![image](https://user-images.githubusercontent.com/5354407/228634037-a35aa338-c273-46b8-8d33-be47b557dff9.png)

![image](https://user-images.githubusercontent.com/5354407/228635292-07309283-06e5-4414-a544-71df04ced78c.png)


SSL works, posthog.mywebsite.com launches with the above console.
However, if I launch IP:port (w.x.y.z:1234) then I'm able to see the welcome page BUT SSL does not work here
So if we can figure out how to map the static files to the nginx - that should solve the SSL+subdomain use case. 

Is there a posthog directory I can use as the `static` proxy in nginx? 

Edit: The static files actually do load, but the error I'm now getting is `net::ERR_BLOCKED_BY_CLIENT`


----

Edit: Found the solution. Just had to disable my adblocker.

----

Maybe I celebrated too early... 
The preflight check said celery was not started/failed status so I tried restarting doing `docker-compose restart`  (no issues with starting containers) and now we have another issue:

`Error: connect ECONNREFUSED 172.25.0.7:8123`

![image](https://user-images.githubusercontent.com/5354407/228639047-dd997d0c-111f-4dc0-9f30-d545521d462b.png)

Edit: Had to wait for new minutes and this was gone. But celery is still falling:
![image](https://user-images.githubusercontent.com/5354407/228639753-583af0e1-1806-4d84-981f-163d9f0bb53e.png)

Worker logs looks fine I think...
![image](https://user-images.githubusercontent.com/5354407/228639975-d2be1dfd-16fa-4e3d-9d9a-4dc822b1b6a0.png)


Is there anything I can try to restart or fix this celery issue?

worker logs related to celery: 
![image](https://user-images.githubusercontent.com/5354407/228641940-89ba1902-2fbb-43c6-8a29-3aaf0066cf21.png)


Edit: I'll just open a new issue.

**Comment by pavitrakumar78** [comment]
New issue posted about Celery issue: https://github.com/PostHog/posthog/issues/14925
