### ISSUE TITLE
Allow account deletion from setup page

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#1538]
## Is your feature request related to a problem?

I want to be able to delete my team without having to contact support

## Describe the solution you'd like

A "delete your team" button that deletes your account with associated data.

**Comment by jamesefhawkins** [comment]
Bonus points if we can ask why

**Comment by paolodamico** [comment]
Actually can we hold off on this for a couple of days? I want to plan something to be as useful as possible.

**Comment by paolodamico** [comment]
Design proposal on [Figma](https://www.figma.com/file/gtW3o3VKYvf04ws8cZM3Nr/PH-Retention-optimisations?node-id=365%3A0).

**Comment by Twixes** [comment]
An important consideration is that after #1562 Organization will become the root entity instead of Team. The Team model will get a more mundane role of a project within an Organization, so it shouldn't be that big of a deal to delete it (obviously still danger zone). Organization deletion will be the big deal, and its members will be either admin or non-admin – only the former should be allowed to delete the org, along with its data. We could also introduce the concept of an organization owner, who'd be the only member with such ultimate authority (and who could pass ownership to someone else). The admin distinction may be enough though – opinions on this structure appreciated.

**Comment by paolodamico** [comment]
Agreed! This is intended as the experience for the more dangerous deletion of the entire org. We should definitely restrict this to authorized users, I would perhaps consider having multiple owner-level users, that are the only ones than can delete the entire org and maybe manage billing details.

**Comment by J0** [comment]
Hi,

Can I take this issue? Can't quite see the Figma file though -- don't have permissions.

**Comment by timgl** [comment]
@j0 Go for it! The Figma file is attached. Please note that now we're talking about deleting an Organization, not a team.

BTW, at the moment we shouldn't worry about any permission level stuff. Anyone should be able to delete anything for now. We will add advanced permissioning to EE.

[PH _ Retention optimisations.pdf](https://github.com/PostHog/posthog/files/5340373/PH._.Retention.optimisations.pdf)

**Comment by J0** [comment]
Cool, thanks! Went dark a bit due to midterms -- will get to this issue this weekend.

**Comment by paolodamico** [comment]
+1 from a user today. Also worth noting that when the user has no organization, we redirect them to `/organizations/create` where they can set up a new org, but we should allow them to permanently delete the account from there too.

**Comment by paolodamico** [comment]
You can now delete your team & organization self-serve.
