### ISSUE TITLE
Allow internal users to be filtered out in Actions

### ISSUE THREAD

**Issue by amitav13** [PostHog/posthog#15661]
## Is your feature request related to a problem?

I want to set up Slack notifications for particular Actions as they happen real time. 

## Describe the solution you'd like

I've got actions set up for the items that I want to track, but want to be notified only when a non-internal/non-test user does it. A toggle to filter out internal and test users like the way we have it for Insights would be perfect.

## Describe alternatives you've considered

We get notifications from internal users currently as well, it's quite noisy on Slack.

## Additional context

Max seems to think there isn't a way to do this currently:
https://posthogusers.slack.com/archives/C01GLBKHKQT/p1684761753157309

**Comment by ithinkwong** [comment]
Potential related Issues / PRs:

- [Filter out internal and test users in actions](https://github.com/PostHog/posthog/issues/13114): This issue is similar to the one you've raised, as it also discusses the need to filter out internal and test users in actions. The discussion in this issue might provide some insights and alternative solutions that you can consider for your own use case.

This message was generated by AI from www.triagetickets.com
