### ISSUE TITLE
Sprint June 12 to June 23

### ISSUE THREAD

**Issue by mariusandra** [PostHog/posthog#15932]
# Global Sprint Planning

## 3 things that might take us down

1. Leaving Q3 planning to the last minute
2. Deploying too much while we have a spike in traffic
  - Ellie is working in splitting out the helm chart 
3. Retry traffic - put jitter into posthog-js

## Retro: What can we do better next sprint?

1. 
2.
3.
5.
6.

# Team sprint planning

For your team sprint planning copy this template into a comment below for each team.

```
# Team ___

**Support hero:** ___

## Retro

<!-- Grab the high and low priority items from last time and add whether that item was completed or not -->

- 

## Hang over items from previous sprint

<!-- For each item, decide to re-prioritise (and add below) or deprioritise -->

- Item 1. prioritised/deprioritise

## OKR

1. OKR, status (red/yellow/green) and action points if yellow/red


### High priority

-

### Low priority / side quests

-

```

**Comment by mariusandra** [comment]
# Team ~Froduct~ Product Analytics

🍄 Captain Toads next 2 weeks:
- @thmsobrmlr  first week
- @mariusandra  second week

It's Yakko's last spint :(

## Retro

- @yakkomajuri - a bit less support load. Hopefully because we fixed _all_ the bugs
- @thmsobrmlr - 2 weeks of non-support 🎉. Final stretch for data exploration. Sessions with @yakkomajuri super helpful
- @Twixes - got quite a bit of the 3000 ui
- @mariusandra - was fine. support rollovers & hogql related work

## Hang over items from previous sprint

- PoEv2
- Pentest (Yakko will chase)

## OKR

- 🔴 Objective 1: PostHog 3000 Hacker News launch is a wild success
   - not gonna happen in Q2
- 🟠 Objective 2: Make PostHog performance frustration free for our 10 largest customers
   - gathering data again to see if it's frustration free or not
   - doubtful for PoEv2 this quarter
- ✅ Objective 3: HogQL
   - the HogQL public beta has launched!
   - still [cleanup to do](https://github.com/PostHog/meta/issues/81)

### High priority

- HogQL post-beta [shortlist](https://github.com/PostHog/meta/issues/81) & PoEv2 [next steps](https://github.com/PostHog/meta/issues/81) @mariusandra 
- Proper `null` support and materialized columns @thmsobrmlr  ([slack thread](https://posthog.slack.com/archives/C0368RPHLQH/p1685047495690929), [older context](https://github.com/PostHog/posthog/pull/14185#discussion_r1112932704)) 
- Roll out PostHog 3000 navigation @Twixes 
- HouseWatch launch @yakkomajuri 


### Honorable mentions

- `select * from Yakko`
- Custom SQL properties (required for PoEv2) exposed to users in the UI

**Comment by benjackwhite** [comment]
# Next sprint - Team ~Fafka~ Monitoring 

**Support hero:** @pauldambra, then @benjackwhite 

## Retro

- @pauldambra breaking capture was frustrating. Frustrating is a good word - we're working well together but progress has been slow. Blob ingester work just didn't go well.
- @benjackwhite - blob ingester progress is frustrating. Feel like we are finally approaching a good solution but with pipeline/infra being super busy hard to get the brains together to do this right. Actually feel pretty good about the spread of issues we've been improving for Replay. Notebooks felt like pretty good progress.
- @annikaschmid - nice to actually have Notebooks in beta. Good to have it testable and being tested. No bookings for interviews on Notebooks but widening the funnel to try and get more qualitative feedback. 

## Hang over items from previous sprint

- Autocapture for frontend Exceptions & Improved Replay filtering (Exceptions, active time and more...)
   - 🤔 Autocapture is ready but not on (due to ingestion concerns and limited pipeline team capacity)
   - ✅ Exception view improvements and replay filtering in
- Notebooks filtering widget + feedback on Notebooks @benjackwhite @pauldambra 
  - ✅ Internal feedback from Annika - super helpful
  - ✅ Playlists can be filtered within a Notebook
  - 🤔 General filtering controls for example Queries / Insights - not there yet
- S3 Replay stuff
  - 😱 Realised chunking is the core of all of our problems - got a plan to fix this at the root which we should execute on.

## Goals
* Goal 1 : Finish the 80:20 of session recording 🟡
  * Realistically we need separate infra to do this right (Kafka + redis) and removal of chunking logic.
* Goal 2 : Notebooks MVP 🟢
  * Starting to shape up - Insights are the most painful part
* ~Goal 3 : Release MVP of Error tracking product~ 🔴
  * We have removed this goal due to - not wanting to add undue load on infra team, unclarity whether this is what people want (and if they would definitely pay for it)

### High priority
- Newer simplified blob ingestion flow using new infra (kafka + redis) @pauldambra (with Ben)
- Notebooks - inline editing of insights and queries, recording notes controls, list of mini-bugs @benjackwhite (with Paul)

### Low priority / side quests
- Remove posthog-cloud @benjackwhite 
- Get redis compression fully rolled out @pauldambra 
- Plan onboarding of David Newell

**Comment by raquelmsmith** [comment]
# "Team" Growth

**Support hero:** Me

## Retro


- [x] Make a template for empty states on any product and apply to the products.
- [x] Start experiment on signup for more generic product info.
- [x] Create a template/scene that each product can use to introduce people to the product before they start using it (eg a landing/marketing page, but in-app).
  - I think I can get this done by the end of the week, will be extending the empty state component.

## OKR

1. We can easily run experiments on pricing 🔴 
    - Won't get to this this quarter.
2. Each paid product is positioned as a first-class citizen within our onboarding and upgrade flows 🟡 
    - I think I can make good progress toward this by the end of the quarter. We’re now in a good spot to do this since the switch to separate upgrades per product is done.
    - Planning issue: https://github.com/PostHog/posthog/issues/15651

## This sprint
### High priority
- [ ] Decide on new pricing and migrate existing/prior customers who are on old pricing.
  - Make an announcement
- [ ] Experiment: Directly ask people what they are signing up for in the signup form https://github.com/PostHog/posthog/issues/15531
  - Will also give us data about who we should be tracking for activation into the products
- [ ] Mock up a product-specific onboarding flow for eg. Feature flags or Experiments


### Low priority / side quests

- [ ] Create modal for prompting to upgrade to addons when sub-ing to a main product
- [ ] Improve modal for upgrading to paid features
  - Let them subscribe in the modal
  - Tell them which product they need
- [x] fix: people can't subscribe if their instance has no license (new billing UI)

**Comment by timgl** [comment]
# Team Infrastructure + Pipeline

**Support hero:** Xavier

## Retro



- Daniel: I like this way of doing things
- James G: I like it's tactical and operational. Improvement over how we're doing things
- James G: Thrilled we got a lot of big things done: Clickhouse upgrade/postgres migration/Redis/Kafka. It's because we're prioritising
- Tiina: It's good to have more insight between infra and pipeline


### High priority

- Observability: Scale VictoriaMetrics and Grafana. @ellie 
- Great dashboards for alerts for ingestion @fuziontech 
- Ingestion throughput: reintroduce RDKafka, deploy branch images to dev @xvello 
- Splitting out helm chart @ellie 
- One app taking everything down @hazzadous 
- Ingestion person creation & updates data integrity @tiina303 
- Downscale some resources @danielxnj 


### Low priority / side quests

-

**Comment by neilkakkar** [comment]
# Team FFeature Fuccess

**Support hero:** @EDsCODE 

## Retro

1. Release surveys to beta users @liyiy -> 🟢 We'll release by Friday.

2. Dashboard templates on feature flags @EDsCODE -> 🟢 We'll release mvp by Friday.

3. Decide instrumentation for pricing @neilkakkar  -> 🟢 Should be good to go.

## Hang over items from previous sprint

Flag autocapture side-quest

## OKRs

1. 🟡 Make it easier for engineers to analyze the success of a feature
2. 🟢 Launch pricing for feature flags

### High priority

1. Polish & make ready for general availability all 4 new features we've built (flag autocapture, early access, surveys, dashboard templates) -> everyone owns their feature polishing
    1. Integrate all these new features together, make them sticky, more useful, & if they're not being used, figure out why. 

### Low priority / side quests
