### ISSUE TITLE
Google Sign-In

### ISSUE THREAD

**Issue by Twixes** [PostHog/posthog#1594]
## Is your feature request related to a problem?

Practically every active internet user has a Google account and many companies (including PostHog itself) run on G Suite. It could then be good for signups to support login with Google.

## Describe the solution you'd like

Implement Google Sign-In as an addition to the current GitHub and GitLab.

**Comment by paolodamico** [comment]
+1 definitely worth doing to make the sign up process easier too. We could even consider allowing users to sync their G-Suite directory (obviously optional) so that they can invite their teammates more swiftly.

@timgl this wouldn't affect having SSO as an enterprise feature, right?

If we prioritize this, I can work on the planning/design for the account creation process using G-Suite.

**Comment by timgl** [comment]
I think this could still be an ee feature for now, but obviously enabled for everyone on app. Should be easy to implement given we already have social django
