### ISSUE TITLE
Retro: Dashboard Templates & Next Steps

### ISSUE THREAD

**Issue by andyvan-ph** [PostHog/posthog#16253]
A quick retro on the "new and improved" dashboard templates to help improve them for the influx of GA users. Data source: https://app.posthog.com/dashboard/61137

TL;DR
- 36% of all new dashboards in the last 30 days, which is great.
- The templates pages on the website don't get many visits
- Website metrics is the most popular, despite being at the bottom of the list!
- Templates that require events to be setup don't do well at all
- Real time analytics is quite popular, though I'm concerned about the quality of experience

## Full list of current dashboards

We now have 12 templates:

- Landing pages report
- Product health metrics
- User research 
- B2C product metrics
- B2B product metrics
- Real time analytics
- AARRR pirate metrics
- B2B SaaS product metrics
- Retention comparison
- Advertising analytics
- Product analytics
- Growth dashboard
- Website metrics

This has made the menu a bit bloated, imo.

![Screenshot 2023-06-26 at 18 02 13](https://github.com/PostHog/posthog/assets/92976667/48915b46-e322-4bbd-bd8a-a4786c8e3c20)

## Most popular dashboards

Breakdown of last 30 days:

![Screenshot 2023-06-26 at 17 57 42](https://github.com/PostHog/posthog/assets/92976667/90c92ebd-65b9-40fe-9c44-a7580a57410f)

- Website Metrics is the most popular, which is impressive considering it appears last on the list.
- The worst performing ones (AARRR, B2C, Growth etc.) tend to require some event setup, which clearly puts people off.

## What I think we should do

1. Remove the following dashboards due to complex setup / lack of use:
 - B2B SaaS metrics
 - B2C SaaS metrics
 - AARRR
 - Retention comparison
 - Growth dashboard
 - Retention comparison
 - Product health metrics

2. Improve Website Metrics and Landing page reports (e.g. add more insights / bounce rate etc.) because they're very popular.

3. Improve Advertising analytics and rename it "Paid ads"

4. (Via @ivanagas) Run a survey on users who used templates to gather feedback

5. Remove real-time analytics (although it's popular, I suspect most users will underwhelmed compared to GA)

**Comment by ivanagas** [comment]
[30 day pageviews](https://app.posthog.com/insights/HGLOYfHR) for each of the template pages (or why we shouldn't get rid of AARRR).

![Screen Shot 2023-06-26 at 10 31 48 AM](https://github.com/PostHog/posthog/assets/34755028/5956b05b-823c-4039-bccb-cf15f3ff9a81)

**Comment by joethreepwood** [comment]
Disagree with this fundamentally and strongly, tbh. 

This feature isn't causing friction. No users are complaining about it, no bugs are being created, no issues are arising. So from a stability or quality POV there's no reason I can see to remove functionality. The exception here is the real-time analytics template which, sure, if we think it's bad, removing it makes sense. 

The rationale in the sprint discussion was that it's a usability issue and that the page is too crowded. However, that's not borne out by the results because (as Andy points out) it's the _last_ item on the list that is the most popular. 

The other rationale was that people may be clicking on them, seeing they require setup, and bouncing. To me that's a very strong reason to invest more time in improving these templates because that means users are showing interest and struggling with the implementation. We should make a case for improving this if that's what's happening, not removing functionality. 

The main argument for removing them that I would agree with is if we feel that there's too much overlap in some of the dashboards and that we can consolidate them down and give them more appropriate names so users can find what they need. I'd be in favour of that, but it's one thing to refine functionality and another to just remove it wholesale.

I'm _very_ strongly against the idea of removing the AARRR template.

**Comment by andyvan-ph** [comment]
I'm glad you agree. 😉

> This feature isn't causing friction. No users are complaining about it, no bugs are being created, no issues are arising.

People don't have to complain to have a bad experience. 

I spent this morning looking at some replays and my main takeaway is that people frequently quit at the event setup stage, where it exists. My hypothesis here is that new users are most likely to try the dashboards and often don't have the right type of events setup, or the events aren't relevant to their product.

> It's the _last_ item on the list that is the most popular.

Slight addendum. Based on session recordings, it looks like they appear in a different order on US vs EU. Not sure what the action here should be. Maybe we should just have them in alphabetical order? Seems the most intuitive option.

> The main argument for removing them that I would agree with is if we feel that there's too much overlap in some of the dashboards and that we can consolidate them down

Agreed.

Based on Ian's point and all the other data points, the obvious ones we actually should remove are:

- Retention
- B2C dashboard (it's basically the same as B2B and I don't think the events are relevant anyway)
- Growth
- Health
- Real time (if people agree it's a bit misleading / confusing)

Then we can focus on improving the rest.

**Comment by joethreepwood** [comment]
I can get behind this, but still think we should improve the setup flow if we think that's causing issues 😉

**Comment by ivanagas** [comment]
I think we should keep real time until someone complains about it (because there have been multiple requests for it).

**Comment by ivanagas** [comment]
Also if we delete dashboards, we need to update: https://posthog.com/blog/google-analytics-to-posthog

**Comment by andyvan-ph** [comment]
> I think we should keep real time until someone complains about it (because there have been multiple requests for it).

Works for me

**Comment by pauldambra** [comment]
We could move the event setup to the dashboard itself. Bigger investment in time but easier to see why you're choosing something if you see the impact as you choose.
