### ISSUE TITLE
Better error handling for no snippet implementations

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/posthog#1636]
## Feature description

I was on a user call yesterday. They had a superb implementation - feature flags, cohorts, actions, funnels loads of back end events, all using our JS library.

However, they had not installed the snippet.

This meant when I asked "have you used the toolbar", they said "we did, but couldn't work out what it was", because it didn't load.

They were then unusure if running the JS library and the JS snipppet would create duplicate events.

Sidenote: multiple Segment users have said "oh can I just use Segment for the snippet", so I imagine there are users in this situation due to that integration without an obvious warning in the product.

## Expected behavior

* Some way of alerting users that if the snippet were added it'd mean they could use the toolbar, and a way of showing (a link to the docs perhaps) why that's worth doing.
* Disabling the toolbar in the nav in this case.
* Explain more obviously by the snippet it can run at the same time as the JS library without duplicating events.

## How to reproduce

1. Install PostHog and don't install snippet
2. Go to toolbar
3. It doesn't work

**Comment by paolodamico** [comment]
Couple of things,
- @mariusandra mentioned that events might de duplicated when using both the snippet and the library; however, the autocapture functionality can be disabled in the library (see below). _Disclaimer: Testing locally, duplicate events were not sent, but still not recommended to have both._
```typescript
posthog.init("[your-token]", { api_host: 'https://[your-instance]', autocapture: false });
```
- @mariusandra mentioned fixing a bug to make sure that the toolbar works when using the JS library. I can confirm the toolbar indeed does work when using the JS library (tested with cloud version), likely the issue is related to some ad blocker or other extension interfering with its functionality.

With the above I think this issue could become how to address autocapture/toolbar for Segment users (as JS library users can use both).

**Comment by paolodamico** [comment]
For the toolbar issue when you are using the Segment integration I suggest something like this, when the user taps the set up button we provide instructions for adding the JS snippet. If a user is integrated through Segment they won't have autocapture, so there's no risk of duplicate events.

![toolbar](https://user-images.githubusercontent.com/5864173/92840442-b2e9aa00-f3a6-11ea-9d8a-d166716c66fa.png)
