### ISSUE TITLE
Summary weekly email

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#1655]
## Describe the solution you'd like
I would like to receive a weekly email with the most relevant highlights from last week's activity. This can help our users facilitate the process of weekly status checks which seem pretty common. In addition, it can help detect any outliers or issues requiring attention.

Design proposal https://www.figma.com/file/gtW3o3VKYvf04ws8cZM3Nr/PH-Retention-optimisations?node-id=405%3A488

**Comment by mariusandra** [comment]
Hey, regarding the two versions, my vote goes for the "non-developery version". Just because I can code, doesn't mean I want to see fixed width fonts everywhere :D. The one with the normal fonts reads better :)

**Comment by jamesefhawkins** [comment]
![image](https://user-images.githubusercontent.com/47497682/93205253-6b20a500-f74f-11ea-9bff-05d09ba78bba.jpeg) this could be a bit more concise "this contains information from" is just words :)

**Comment by yakkomajuri** [comment]
With Marius on this. Prefer the "normal" version.

**Comment by yakkomajuri** [comment]
Also, feedback-wise, having "BETA" next to PostHog seems to imply PostHog is Beta software, whereas maybe what's Beta is the report? 

Not sure if that's there because the design is a draft or because it will actually be there in the real email. If it's supposed to be there for the real thing, it really seems to indicate PostHog is in Beta.
