### ISSUE TITLE
Sprint July 24 to August 4

### ISSUE THREAD

**Issue by mariusandra** [PostHog/posthog#16654]
# Global Sprint Planning

## 3 things that might take us down

1. Clickhouse outages. Solution: we're testing Clickhouse Cloud this week
2. Clickhouse knowledge around schemas.
3. 

## Retro: What can we do better next sprint?

1. 
2.
3.
4.
5.

# Team sprint planning

For your team sprint planning copy this template into a comment below for each team.

```
# Team ___

**Support hero:** ___

## Retro

<!-- Grab the high and low priority items from last time and add whether that item was completed or not -->

- 

## Hang over items from previous sprint

<!-- For each item, decide to re-prioritise (and add below) or deprioritise -->

- Item 1. prioritised/deprioritise

## OKR

1. OKR, status (red/yellow/green) and action points if yellow/red


### High priority

-

### Low priority / side quests

-

```

**Comment by mariusandra** [comment]
# Team Pro:duck:t analyticks

**Support hero:**
- @thmsobrmlr first week
- @Twixes second week

**Vacations**
- @mariusandra off 2 weeks
- @thmsobrmlr off end of 2nd week 

## Retro

- @mariusandra and @thmsobrmlr on support
- @Twixes in 🇪🇪, and on PostHog 3000

## Hang over items from previous sprint

- Still a lot of support tickets to get through

## OKR

- 🔴 Port all our insights over to HogQL.
   - Delayed due to support.
- 🔴 Sleeker insight editor UI
   - Not started.

### High priority

- Only 1.5-2 people working this sprint.
- Get ahead of support, ensure users have a great experience with Product Analytics.

### Low priority / side quests

- [PostHog 3000 list](https://github.com/PostHog/posthog/issues/18090)
- [Data exploration list](https://github.com/PostHog/meta/issues/84)
- [HogQL list](https://github.com/PostHog/meta/issues/81)

**Comment by benjackwhite** [comment]
# Team Monitoring 

**Support hero:** @benwhite

## Retro
* @daibhin - blob ingester ended up being more than we thought - did we ever stop and say "is this definitely what we should do"? 
* @benjackwhite - blob ingester is basically production so we should treat it that way but up till now we were treating as a product
  * David somewhat on his own and I would like to change that next sprint and work together on stuff

## Hang over items from previous sprint

🟡 notebooks recording transcription mode @daibhin (with @benjackwhite)
✅ session recording user interviews @pauldambra and @daibhin 
🟢 rollout of blob ingester
  - nearly there but still some tweaks needed
  - major blocking things have been fixed
  - final minor things and then we monitor for a sprint

## Goals

 * 🎯 Goal 1 : Notebooks on ProductHunt 🟢
 * 🎯 Goal 2 : Next 5 great things for Replay 🟢
    - 🤔 Filtering and searching UX
    - 🤔 "Deep dive" e.g. Funnels -> list -> recording
    - 🤔 Clips
    - 🤔 Mobile replay

### High priority
- Insights on Notebooks properly @benjackwhite 
- Filtering / Searching UX for recordings @pauldambra @daibhin @annikaschmid 
- Recording transcription followup @daibhin 

### Low priority / side quests
- Notebooks sharing @pauldambra 
- Monitor rollout of blob ingester @benjackwhite 
- Investigate high churn users and get a sense of the key drivers @daibhin

**Comment by timgl** [comment]
# Team Pipeline

**Support hero:** Tomas & Xavier

## Retro



- Overall really positive, we got both items done
- Events still need a daily restart, not sure why

## Hang over items from previous sprint



No

## OKR

1. OKR, status (red/yellow/green) and action points if yellow/red


### High priority

- Discoverability of new exports, Bigquery as a destination, observability of the system @tomasfarias @xvello 

### Low priority / side quests

- Look into why events need a daily restart

**Comment by EDsCODE** [comment]
# Team Data Warehouse

## Retro



**Product**
- Had to slow down to ensure changes wouldn't expose vulnerabilities
- Joins working now
- [MVP for views](https://github.com/PostHog/posthog/pull/16573) in progress (saved queries). This will lead to basic modeling capabilities
- Had a [brainstorm session](https://docs.google.com/document/d/1oxuuMNfeN8MIrN-ka2qoasquM5RZaWxbHAyuQQZkGNs/edit) that landed on continuing with the current plan of relying on external s3 buckets as the query source (vs proxying completely to bigquery or analogous)

**Clickhouse**
- Data recovery with current setup is slow - working to fix this for future incidents
- We have had solid discussions about the future of CH @ PH (considering alternatives such as CH.Cloud)
- Need better visibility into what is going on with cluster - would help with confidence shipping schema changes.

### High priority

**Product**

- Release MVP for person/group modeling
- Internal use + 5 happy users for data warehouse. (Carried over from last sprint due to bug squashing and adjusted priorities -> willing to build out the product more before marketing heavily)

**Clickhouse**
- Automate backups on EU and US
- Clickhouse Copier EU -> CH.cloud for testing
- Discus ClickPipes to consume data from Kafka for CH.cloud with CH.cloud

**Comment by danielxnj** [comment]
# Team Infrastructure

**Support hero:** @ellie 

## Retro



- Good to see that PG15 does not break the app


## Hang over items from previous sprint



- Item 1. Start moving terraform deployments over, could be done in next sprint.

### High priority

- Shard kube state metrics, scrape times are high and on the way up
- Move the rest of Victoria metrics to the charts repo - vmagent is done now
- Finish splitting out loki from the chart (done in dev)
- Split out promtail and prometheus exporters from the posthog chart
- Split push gateway

**Comment by neilkakkar** [comment]
# Team Feature Success

**Support hero:** @liyiy

Neil off 3 days.
Li off 2 days.

## Retro

1. General release of surveys +  emoji / nps rating survey type: @liyiy -> All sorted, emoji/nps surveys will be released behind a flag
2. Remaining experiments fixes + decide on read replica: @neilkakkar -> All sorted! (pending new decide issues)


## Hang over items from previous sprint

---

## OKRs

1. Make it easier for engineers to analyze the success of a feature
2. Build out an excellent user feedback product

### High priority

1. Surveys: Multiple choice survey option + controlling targeting for users who've seen surveys - @liyiy
2. Make feature flag dashboard templates and flag autocapture ready for general availability - @neilkakkar 

### Low priority / side quests
