### ISSUE TITLE
Incorrect order of insights on subscriptions

### ISSUE THREAD

**Issue by andyvan-ph** [PostHog/posthog#17066]
## Bug description

As per this [user question](https://posthog.com/questions/order-of-insights-in-a-dashboard-subscription), dashboard subscriptions load the order of the insights based on a "narrow" view rather than the order they appear in the "normal" view most people are accustomed to. 

This is confusing for users and requires an unintuitive workaround to fix. Ideally, any changes to the order of insights should be respected so subscriptions always show insights in the expected order.

## Environment

- [x] PostHog Cloud US, project ID: [please provide from https://app.posthog.com/project/settings#project-id]
- [x] PostHog Cloud EU, project ID: [please provide from https://eu.posthog.com/project/settings#project-id]
- [x] PostHog Hobby self-hosted with `docker compose`, version/commit: [please provide]
- [ ] PostHog self-hosted with Kubernetes (deprecated, see ["Sunsetting Kubernetes support"](https://posthog.com/blog/sunsetting-helm-support-posthog)), version/commit: [please provide]

**Comment by benjackwhite** [comment]
This was a problem when we originally built it and the issue was - if we support two different views, how are we supposed to know which one should be used for emails? 

It might be unclear but if they change their screen to be small enough for the single width view and edit it, then they are essentially formatting the order of subscription images. I don't think we should be too clever here and try and magically determine the multiple views but rather just indicate in the UI that they should use the single column view edit if they want to change the order.

**Comment by andyvan-ph** [comment]
Yeah, I explained that to them too so short term it's all good.

I think the answer is we should just have one view, right? I don't think people expect to have separate views, it's just one view that shifts dynamically based on browser width.

In my head, it makes sense if we just have the "wide" view and that scales down to one column if you have a narrow window, with the order defined from left to right – i.e. if you have three insights on a row, the one on the left would be the first and so on.

I appreciate this very easy for me to say! ;)
