### ISSUE TITLE
Session Replay emails

### ISSUE THREAD

**Issue by NorhanMostafa94** [PostHog/posthog#17309]
## Bug description

I need to filter session replay by emails, I added **posthog.people.set({ email: this.currentUser.email });** if there is a current user as our project can go without login.
**The issue is:** emails duplicated, replaced by each other and if there is no current user logged in, it doesn't record it most of time.

<img width="452" alt="image" src="https://github.com/PostHog/posthog/assets/46131227/e11d6016-3ba9-43df-bcc4-fa061cf9a5e7">

*If I used distinct id:* it replaced all emails with recent logged in user and if there is no current user logged in, it doesn't record it all.
![image](https://github.com/PostHog/posthog/assets/46131227/47420e47-82e5-4b66-a52a-f36b8c9d9c3f)

**Comment by benjackwhite** [comment]
Hi, 

From what you gave sent it looks like you are "identifying" the user every time with the string "distinct_id". This feels very wrong 😅 

The first argument to the identify function is the ID of actual "Person" so if you always use the same string, every browser session will be merged into one person. You should make sure this is actually unique to the logged in person.

If you are testing this locally, it could be that you are also running into the issue of not resetting on logout. You should call `posthog.reset()` when your users log out so that the cached ID is reset and a new one generated.

**Comment by pauldambra** [comment]
I'll close this as it seems like an implementation issue rather than a bug report but feel free to request support using https://app.posthog.com/home#supportModal=support%3Asession_replay if you still need help
