### ISSUE TITLE
[clickhouse] Improve payload serialization

### ISSUE THREAD

**Issue by EDsCODE** [PostHog/posthog#1742]
Potentially related to an escaping issue. Some urls such as `.../demo/1` are being recorded in the db as `.../demo1`

We should improve the serialization using a library such as avro or protobuf to define structure of payloads

**Comment by mariusandra** [comment]
I think I might be to blame here.

When working on paths, I noticed demo urls events were created with `/demo/1/`, but opening that page actually gave an empty response as the real url was `/demo/1`. Same with `/2`, etc.

 I fixed it in the postgres demo script and the `base_url` given to postgres there, but forgot to look at the clickhouse demo script. 

Fixed with PR #1757
