### ISSUE TITLE
Allow user to change their email

### ISSUE THREAD

**Issue by yakkomajuri** [PostHog/posthog#1745]
## Is your feature request related to a problem?

*Please describe.*

## Describe the solution you'd like

An option on Settings to change my email.

## Describe alternatives you've considered

Manually interact with the instance if I'm self-hosting or invite myself if I'm on app.

**Comment by afarbman** [comment]
Hey, I'd like to give it a go.

**Comment by timgl** [comment]
Go for it!

**Comment by c3ho** [comment]
Hi, is it safe to assume this issue is free?

**Comment by timgl** [comment]
Yep go for it!

**Comment by c3ho** [comment]
Thanks! I have a few questions regarding this issue:
- Should duplicate emails be allowed?
- Who should be allowed to change the email of the member? The member themselves only or users with admin privileges as well?

**Comment by timgl** [comment]
1. Nope, they can't be as emails are unique
2. I think it'll be easiest to start with just the user itself, but if you feel extra motivated feel free to also do admin changes :)

**Comment by paolodamico** [comment]
Tagging @Twixes here to shed some light on the impact of this for SSO/SAML. Not sure if we use emails as keys, it might be problematic.

**Comment by Twixes** [comment]
We do use them as keys, so may be an issue indeed. Will look into it.

**Comment by Twixes** [comment]
I think I'll put this issue on the back burner for this release cycle, and tackle it in 1.22. I also have some more significant improvements to settings in mind, so that would all work nicely together. Important consideration: we should decide what way to go with #1775's experiment, as having to consider both the pre- and post-1775 PostHog experiences would significantly complicate work on revamping settings. @paolodamico

**Comment by paolodamico** [comment]
Sounds good @Twixes! We should know by release 1.22 which direction we're going, though I do hope we're able to keep the new navigation in (looks promising), but we'll see.
