### ISSUE TITLE
Sprint October 2nd - October 13th (first for Q4)

### ISSUE THREAD

**Issue by mariusandra** [PostHog/posthog#17640]
# Global Sprint Planning

## 3 things that might take us down

1. Gunicorn -> Frank looking at killing both
2. pgbouncer breaking for unknown reasons < don't know why this happened.
3. Lots of retries < posthog-js sdk timeout is increased to 60 seconds

## Retro: What can we do better next sprint?

1. 
2.
3.
5.
6.

# Team sprint planning

For your team sprint planning copy this template into a comment below for each team.

```
# Team ___

**Support hero:** ___

## Retro

<!-- Grab the high and low priority items from last time and add whether that item was completed or not -->

- 

## Hang over items from previous sprint

<!-- For each item, decide to re-prioritise (and add below) or deprioritise -->

- Item 1. prioritised/deprioritise

## OKR

1. OKR, status (red/yellow/green) and action points if yellow/red


### High priority

-

### Low priority / side quests

-

```

**Comment by mariusandra** [comment]
# Team Product Analytics

**Support hero:** Michael week 1, Robbie week 2

We're splitting work between:
- Query Engine
- NoteForce 5006
- Web Analytics

... and will update all of them separately.

# Project Query Engine

## OKR

- Project "Finish the darned Query Engine" (Tom, Marius)
  - Finish insight HogQL conversion.
  - Support non-event data sources on HogQL insights (BI tools for data warehouse).
  - Build tools to measure HogQL query performance, and catch regressions before they hit users.

## High priority

- Finish the trends & lifecycle insights
- Start the HogQL benchmarking suite by measuring wins in the [`in cohort` optimisation PR](https://github.com/PostHog/posthog/pull/17354).
- Connect other data sources to the trends query

## Low priority / side quests / next steps

- Finish the persons query (if still not done)
- Take on the next insights (funnels, paths, retention)
- Plan the quarter in more depth
- Continue down the list of [HogQL todos](https://github.com/PostHog/meta/issues/81)

**Comment by robbie-c** [comment]
# Team Web Analytics

**Support hero:** n/a

## Retro
n/a

## Hang over items from previous sprint
n/a

## OKR
n/a but for Q4 is https://github.com/PostHog/posthog.com/pull/6808

We're just getting started. There's a web analytics dashboard at https://app.posthog.com/web behind a FF but it's not ready for feedback yet (it'd be obvious stuff)

### High priority
* Add Top Sources, Top Pages, and Top Clicks to the query endpoint
* Add filters to the web dashboard

**Comment by benjackwhite** [comment]
# Team Replay

**Support hero:** ___

## Retro



- (Skipped for time)

## Hang over items from previous sprint



- ♻️ ALL IN ON NOTEBOOKS - notebooks polish polish polish - @pauldambra @benjackwhite
  - how do we know we're finished - @annikaschmid enjoys working with it
  - things in the #notebooks-feedback channel ✅
  - can edit all the things 🤔
  - undo/redo/history ✅
  - playlists experience ❌

- rewrite the Android SDKs to get the basis for mobile session replay @marandaneto
  - first v3 alphas are out 🥳

## OKR

1. NoteForce 3000 (separate comment)
2. 📱 Mobile Replay 

### High priority
- Replays in Clickhouse deprecation @pauldambra 
  - why? The legacy code is slowing us down and causing bugs
- Tests, document and release of Android SDK V3
  - why? First alpha is out - keep the momentum up and get the rewrite out

### Low priority / side quests
- Mr Blobby improved rebalancing rollout @benjackwhite @pauldambra 
- Get started with iOS rewrite @marandaneto (with help from @benjackwhite)
- Console logs searchable @pauldambra 
  - why? Use the energy of Tomas' work to make logs searchable (also informs perf events)

**Comment by benjackwhite** [comment]
# Project Noteforce3000

**Support hero:** ___

## Retro
- N/A

## Hang over items from previous sprint

N/A

## OKR

1. Project "Noteforce Exploration 3000" 
* Pair up with Team Monitoring to complete projects Data Exploration, Notebooks and PostHog 3000.
* Release new navigation and insight editor.
* Work more HogQL prompts into the interface.
* Build metrics into the system, introduce Metric Mondays.


### High priority

- UI Refresh (collapsed sidebar, dark mode, breadcrumb header, new buttons etc.)
  - Flag the new sidebar nav and default to more standard nav (posthog logo?) @Twixes 
  - Finalise V1 of the topbar area (search button? contextual icons?) @benjackwhite 
  - Unified search (cmd+k does the resource search as well as quick actions) @thmsobrmlr 

- Notebooks V1 release @daibhin @benjackwhite 
  - [Remaining top prio things here](https://github.com/PostHog/posthog/issues/15680)

### Low priority / side quests

- Dog food our whole product to get this done!
  - Early access opt in
  - Core metrics on the rollout
  - Surveys to follow up on areas we are unsure about (dark mode, search etc.)
  - Key Replays focusing on the areas
  - Notebook pulling all this together
- Metrics Monday - how can we track and validate all these things
- Question the color scheme of dark mode / choice of colors to make sure it's right.

**Comment by danielxnj** [comment]
# Team Infra

**Support hero:** @danielxnj 

## Retro
- N/A

## Hang over items from previous sprint

- [ ] Test and merge dev terraform state split [PR](https://github.com/PostHog/posthog-cloud-infra/pull/2160)

## OKR

1. Continued maintenance of systems
2. Controlling costs
3. Platform improvements
4. Clickhouse changes	


### High priority
- [ ] Try out nginx unit instead of gunicorn @frankh 
- [ ] Remove intermediate nginx ingress layer @frankh 
- [ ] Enable rack aware server config in events kafkas @frankh 
- [ ] Mate terraform plans apply to only run on updated resources @danielxnj 
- [ ] Update pgbouncer helm chart to mount a pgbouncer.ini for advance parameters @danielxnj 

### Low priority / side quests

- [ ] rotate VPN certs and delete SSO vpn

**Comment by fuziontech** [comment]
# Team Data Warehouse

### OKR Q4

### Objective

**PostHog users can effortlessly bring their business data to PostHog and analyze it**

* **Key Results:**
    * Be able to import data into data warehouse in one click from most popular SaaS tools (X, Y, Z connectors built)
    * 5 happy users/teams who have imported external data
    * Data Warehouse queries are compatible with insights hogQL

**PostHog is moved over to whatever CH infrastructure we will be using for the next 1 year (at least)**

* **Key Results:**
    * We are either on new infrastructure for EU that we host or on ClickHouse Cloud
    * Queries for large customers are performing faster
    * We can scale more easily (without James bespoke effort)
 

### Retro

*Eric Off second week of this sprint (this week)

**Product**
- [x] release datawarehouse feature flag (not views!) and monitor usage
- [ ] convert revenue dashboard to posthog
- [x] user outreach

**Infra**
- [x] Finish doc
- [ ] Make decision on CH.cloud vs hosted CH
- [x] Test ClickPipes / Setup Vector
- [x] Restore Persons table and benchmark different joins on CH.cloud
- [x] Clean up ClickHouse EBS volumes as we taper off Session Recordings


### High priority

*Eric Off first week of this new sprint (next week)

**Product**
- [ ] convert revenue dashboard to posthog
- [ ] more user outreach

**Infra**
- [ ] Finish all Vector setups (some are problematic)
- [ ] Sync all tables to be = between environments
- [ ] Optimize all tables
- [ ] Develop ability to feature flag / switch cluster a query is dispatched to based on team
- [ ] Cut costs on s3 backups (TTL/Life cycling)

**Comment by raquelmsmith** [comment]
# Growth

## Retro

- [x] Billing and "other products" onboarding steps
- [x] Feature flags onboarding https://github.com/PostHog/posthog/pull/17638
- [x] Touch up product analytics onboarding snippets
- [x] Start understanding what our real activation metric should be
- [ ] Still working on changes to messaging record so we can send multiple emails on some frequency
- [x] https://github.com/PostHog/billing/pull/365
  - Should merge today
- [ ] Change MRR per product reporting to be calculated based on usage, not invoices

## OKR

Q4 ORKs TBD!

1. Starting to use and paying for new products feels frictionless
  - 🟡 In progress!
  - [ ] KR: We have separate onboarding for each product
    - Super close to having a v1 of this, but will take more work to make it actually work for everyone / everything, and we need to make sure it won't kill conversion in some way before rolling it out to everyone
  - [ ] KR: People don’t have to “upgrade” to different products, they just turn it on or start using it in some way.
3. Customers can pay a reasonable price for the value they’re receiving
  - 🟢 Done! Unless Data Warehouse or CDP become ready for launch.
  - [x] KR: Make sure rollout of new product analytics pricing goes well
  - [x] KR: Feature Flags pricing is launched, as well as Data Warehouse and CDP, if they are ready for launch

## This sprint
### High priority
- [x] Launch new onboarding experiment!
- [ ] Get surveys ready for pricing launch
- [ ] Fix inability to delete orgs due to foreign key on old billing tables
- [x] Figure out why usage reports have been failing
- [ ] Shift usage calculations by a day for billing periods so we don't miss billing people's last subscription day

### Low priority / side quests

- [ ] Change MRR per product reporting to be calculated based on usage, not invoices

**Comment by neilkakkar** [comment]
# Team Feature Success

**Support hero:** @neilkakkar 

Li: 1 day

## Retro

1. Ensure a successful onboarding for Juraj! - @everybody -> Juraj is pretty happy xD
2. Surveys: Multiple questions - @liyiy -> Will roll over a bit, aiming to resolve by Monday/Tuesday.
3. Surveys: whatever is needed to launch surveys pricing - @neilkakkar -> pricing changes will happen; and site app migration is done
4. Team-website-and-docs support: Nicer popups for surveys - @smallbrownbike  -> making good progress, adding new positioning next. 

punting notebooks template to next ~~sprint~~ quarter

## Hang over items from previous sprint


---

## OKRs

1. Get 5 reference customers for surveys
2. Get reference customers for feature flags and experiments

### High priority

1. Survey results visualisation polish (based on Cory's mocks): @jurajmajerik 
2. Survey creation flow polish ([based on mocks](https://github.com/PostHog/posthog/issues/16018#issuecomment-1624362200)): @smallbrownbike (+ @neilkakkar on standby for any hogql / app support)
3. Tackle everything in https://github.com/PostHog/posthog/issues/17038 - @liyiy  ( + @neilkakkar )

### Low priority / side quests

templates if we're done with everything above^

**Comment by tiina303** [comment]
# Team Pipeline

### OKRs
- keep the lights on
- Batch exports migrations complete - @tomasfarias 
- Webhooks v2 @tiina303 
- PoE @bretthoerner 

### High priority

- batch exports: migrate BigQuery and PG users @tomasfarias 
- Investigate Postgres issues related to PoE @bretthoerner
