### ISSUE TITLE
Enable "Person properties on events" for everyone

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#17679]
## Is your feature request related to a problem?

We've had Persons on Events in progress for a while, and we're making progress. However, @bretthoerner pointed out that it's actually two slightly different things:
1. Replace the `person_distinct_ids2` join by putting the person_id on the event. This change should not impact users at all.
2. Replace the `persons` join by putting the person properties on the event. This change will change persons filtering from being current time to being at the time of event.

#1 is currently blocked by some performance issues of the ingestion pipeline that we're trying to figure out, and we'll need to backfill all data too.
#2 we can release separately and will require some customer communication. We'll need to point people to use cohorts if they want current properties instead of properties at event time. The data is all there, it just requires a small change in the querying logic.

Releasing #2 will get the customer communication stuff out of the way, while also giving users a decent speed up quickly.

## Describe the solution you'd like

- We add a feature flag for "person properties on events" that we can gradually roll out to everyone, without releasing "person id on events".
- User communication of above.

## Additional context

cc @mariusandra would this be something you could do as part of hogql rewrites?

**Comment by mariusandra** [comment]
> 2 we can release separately and will require some customer communication. We'll need to point people to use cohorts if they want current properties instead of properties at event time.

You can do this now:

```sql
select 
   event, 
   pdi.person.properties.email, -- current property value, fetched via a join
   poe.properties.email, -- ingestion time property stored on the event
   person.properties.email -- whatever is the default setting for your team, one of the two above
from events limit 10
```

Thus you don't really need to resort to cohorts: Once we rewrite insights in HogQL, you can just write this inside a filter and choose the property type you want: fast or current.

> cc @mariusandra would this be something you could do as part of hogql rewrites?

Currently both the person_id and person properties are controlled by one PoE setting on your team. We can split that into two. I don't think there's anything more complicated than that. I can't say if the properties stored on the event are correct or not, but we can definitely query them.

**Comment by timgl** [comment]
Nice! I think we should include this workaround in communications with customers. I do think it might be worth thinking about the naming. Maybe we keep `person.properties.` as the join, and use `person_properties` as PoE, so it's easier for people to grasp what's going on without having to read the docs?

**Comment by mariusandra** [comment]
The naming until now has been somewhat intentionally cryptic, aka not meant for end users. 

The idea was users would always use `person.properties.xyz`, and if/when we swapped the current implementation for PoE, everything would keep working as is. Changing it so that "person.properties" == always join, and "person_properties" == always on event... does makes syntactic sense, but robs us of the option to swap them later, without having users rewrite all their queries. I'd still like it that users don't need to think/care about implementation details, and things just work... versus forcing users to make an explicit choice between a `.` and `_` every time.

Thus, I'd still like to pipe everyone writing HogQL through the default `person.properties`, unless they explicitly want to choose something else. 

I'm open to naming suggestions though (`person_now` vs `person_then`? probably not)... and happy to change my mind on this if there's a compelling case.

**Comment by tiina303** [comment]
+1 to `person.properties` to be the most efficient query way that we choose internally & users to explicitly define something else based on what they need. `person.now.properties` & `person.event_time.properties` <- though event_time is not accurate as it's actually `ingestion_time`
