### ISSUE TITLE
Better initial state for shared recordings

### ISSUE THREAD

**Issue by corywatilo** [PostHog/posthog#17681]
Here's the initial state when opening a shared recording. (I thought it was broken or didn't load.)

Ideally we have a thumbnail image and a play button on the canvas. (There _is_ one when hovering, but it'd be useful to have when _not_ hovering.) If thumbnails are hard to do, auto-playing might solve this.

<img width="1342" alt="image" src="https://github.com/PostHog/posthog/assets/154479/758f0f87-599c-4088-86f4-2be2baf2341d">

I'd also like to be able to access console logs and network tab too.

**Comment by pauldambra** [comment]
Ah we just removed the play button today https://github.com/PostHog/posthog/pull/17676

I think the difference is that an unshared video buffers and shows content but the shared one waits until you press play 🤔

**Comment by benjackwhite** [comment]
Not sure if auto play is the solution tbh 🤔 especially as we will end up hammering our API which is costly for us. 

Play icon makes sense (as Paul says we changed it literally yesterday so that people could get better screen grabs without in the way, but we can change that for non-loaded replays). 

Console and network tab are (I thought) an option when configuring it for sharing already? So that's covered.

**Comment by corywatilo** [comment]
Also, just spotted [in the docs](https://posthog.com/docs/session-replay/installation):

<img width="943" alt="image" src="https://github.com/PostHog/posthog/assets/154479/66d577f1-0170-4e83-b0b9-317c402d6b51">

**Comment by corywatilo** [comment]
> Console and network tab are (I thought) an option when configuring it for sharing already

Ah, I missed this because the options are so far disconnected visually from the _copy public link_ button. Might make sense to move them up at some point.

<img width="661" alt="image" src="https://github.com/PostHog/posthog/assets/154479/4e220683-1659-4000-87e9-6c9de8766dc1">
