### ISSUE TITLE
PostHog Session Recording not working on SvelteKit

### ISSUE THREAD

**Issue by MarArMar** [PostHog/posthog#17985]
## Bug description

*Please describe.*  

I use posthog with session recording

I manage to get my session recording URL in the frontend using the posthog library attached to the window

![image](https://github.com/PostHog/posthog/assets/136232300/8ff6970f-c87b-4972-95c2-9551d7c0ae61)

It captures no session recording (but it does capture page view, leaves & manual events)

The session recording URL does not seem to exists on Posthog cloud GUI

*If you are on PostHog Cloud it would be really valuable if you can share any links where the problem occurs. This speeds up our ability to troubleshoot tremendously.* 

## How to reproduce

    Create a SvelteKit project
    Install Posthog and enable session recording
    Create Some buttons on your website
    Click on it
    Check the posthog session recording : it s empty
    

## Environment

PostHog Cloud US, project ID: 39279

## Additional context

"posthog-js": "^1.83.0",
"posthog-node": "^3.1.2",
"@sveltejs/kit": "^1.25.1",
"svelte": "^4.2.1",
"vite": "^4.4.9",

**Comment by MarArMar** [comment]
Still experiencing the problem, this is very unfortunate as it blocks a core feature of posthog

**Comment by pauldambra** [comment]
<img width="711" alt="Screenshot 2024-06-09 at 22 19 20" src="https://github.com/PostHog/posthog/assets/984817/79d52029-4661-4603-87e0-4eb2c70ddae0">

hey, sorry you've not had a response here...

that session recording URL is incorrect (you can see mine above) so I'm guessing this is a misconfiguration on the client.

i'll close this since so much time has passed, but if you're still having the same problem, feel free to re-open...

(i'll definitely ask you to update to the latest version and share your config :))
