### ISSUE TITLE
A/B Testing 

### ISSUE THREAD

**Issue by Tannergoods** [PostHog/posthog#182]
I would like to track which type of pages and or views are working for users and test them against each other

**Comment by jeremynevans** [comment]
This would be awesome. 🙌 Here's how I'd love it to work:

I assign users into groups by sending properties when I identify a user, e.g. some users get `{ newDesign: true }` and some get `{ newDesign: false }`.

I can then ask Posthog:

> "Over a certain date range, what *proportion* of users in each group triggered event (or action) X?"

The proportion (rather than raw numbers of users) is important since I might be doing a 90/10 split while trying out some new experimental beta feature.

Thanks!

**Comment by Tannergoods** [comment]
requested by:
https://app.hubspot.com/contacts/6958578/contact/39751
https://app.hubspot.com/contacts/6958578/contact/30351
https://app.hubspot.com/contacts/6958578/contact/28501
https://app.hubspot.com/contacts/6958578/contact/40302

**Comment by corbt** [comment]
Hey all, just curious if this is on the roadmap? We have our own ad-hoc internal experiments framework but would love to be able to use Posthog to track experiment conversion!

**Comment by Twixes** [comment]
This is now pretty much possible with Feature Flags! And for enhancements to the A/B testing with Feature Flags experience, we now have issue #1697.
