### ISSUE TITLE
distinct id not persisting

### ISSUE THREAD

**Issue by MarconLP** [PostHog/posthog#18260]
## Bug description

The distinct id is not persisting.

## How to reproduce

1. visit https://posthog-test-marcus.vercel.app/
2. execute `posthog.get_distinct_id()`
3. reload the page
4. notice the distinct id changes

(that website is connected to the `Test (Marcus)` project)

## Additional context

https://posthog.com/questions/posthog-init-is-creating-a-new-person-each-time

**Comment by neilkakkar** [comment]
@MarconLP this is most probably because the cookie isn't being set on the superdomain, because of a vercel configuration: https://vercel.com/guides/can-i-set-a-cookie-from-my-vercel-project-subdomain-to-vercel-app

Few ways to fix:

1. Use localstorage persistence
2. Set `cross_subdomain_cookie` config option to false

Either should work  👀

**Comment by MarconLP** [comment]
@neilkakkar, yep works on localhost 🤦‍♂️
