### ISSUE TITLE
Release 1.16.0 - 29 Oct 2020

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#1870]
# Things we want to achieve

- Session recording #1846  (@macobo)
- AWS one-click deployment (@macobo)
- Plugin infra + example plugins (Marius to come up with list) (@mariusandra #1896)
- Have great UX (@paolodamico #1694 #1775 #1841 #1875, )
- Add feature flags to all client libraries (@timgl NodeJS @fuziontech mobile, go @mariusandra Ruby, php)
- Feature flag interface @timgl #1697 
- Social auth improvements (@twixes #1888 #1594)
- Awesome guided demo + a lot more data (@Twixes https://github.com/PostHog/posthog-production/issues/18)
- Merge Organization PR (@Twixes)
- Clickhouse turned on for everyone on app + refactor(@EDsCODE (+@timgl for elements_chain))
- Every query under 5 seconds, person_id on events, backfill elements_chain (@fuziontech)

- Website refactor (@yakkomajuri)
- 5-6 pages with new components (Lottie)
- pages for new features (Lottie)

**Comment by paolodamico** [comment]
In addition to the above, I think we could work on:
- #1694. Per the off-site discussion (and based on Sep customer interviews), this can help us better position new users to get PostHog going.
- Based on the product strategy discussion, #1547 to push more custom events to reinforce the product analytics vs. web analytics mental model. We do need an adjustment to the designs first based on this new goal.
- **[UX]** Based on our desire to push amazing UX, I would try to get the design for #1775 ironed out. Implementation might not make sense yet, as we just started with the actions experiment (#1841) so we couldn't release even if we have it.
- Retention cohorts graph which will be paramount as we start actively measuring and improving retention.
- **[UX]** https://github.com/PostHog/posthog/issues/1881

I'd also like to put on the discussion floor:
- **[UX]** Do a deep dive on feature flags (#1697) to understand current usage and find potential improvements.
- **[UX]** How can we improve the toolbar UX? (see [comment here](https://github.com/posthog/posthog/pull/1841#issuecomment-707765487))
- https://github.com/PostHog/posthog-production/issues/18, as discussed before, data shows that prospective users constantly try to test the app's features and this will help showcase PostHog at its best.

**Comment by mariusandra** [comment]
I'd like to work on [plugins](https://github.com/PostHog/posthog/issues/1896). If we could get this to a stage that can land in 1.16.0 in some format (maybe disabled by default?), it would be great. I think we're almost there.

In addition it would be good to get in some cleanup, bugfixes and UX improvement for the toolbar:
- #1803 Creating actions with toolbar sometimes fails
- #1577 Heatmaps timeframe
- #1560 Add toolbar to regular navigation and change what we call it
- #1372 Not obvious you can "pin" toolbar infowindows

That and all around bugfixes and quality improvements would be great to work on.

**Comment by EDsCODE** [comment]
I've listed some key "themes" that could drive a release cycle. Many of the points with toolbar could go into UX. New features that we think are necessary can go under instrumentation and should be built if we believe it can help us understand users better. Plugins might fit under a separate block such as "**Exploration**" 

I'm not opinionated on how to split these blocks up. We could either do all 3 in a release cycle and have small groups of people tackling each or make one block a theme for 2 weeks and really hash everything out. In either case, creating a project around each block, listing all the related tasks in the task board, and hammering away at the tasks should help keep things moving quickly

**UX**—The app should be intuitive and spark joy at each click

- Redesign sidebar so it's snappier and fun to use
- Reorganize messaging around actions (in progress)
- Reduce bugginess with loading spinners (sometimes page loads with 2 loading spinners in random places on screen)
(Add the rest of the points mentioned by team into this block)

**Stability**—The app should inspire confidence behind each click.

- Reorganize tests so that unit tests and integration tests are distinct. 
- Make the tests run faster (on CI and locally) to improve development lifecycle 
- Test frontend more thoroughly (whether that's component based testing or better Cypress)
- Fail as gracefully as possible (our toast errors are fairly vague and unfriendly)
(Add more backend stability points here and some UX points are related)

**Instrumentation**—We should have a clear idea (or have the ability to have a clear idea) of when and how users use each new feature. Much of the dog fooding can happen here.

- Extend feature flags (determine how we can analyze user performance with/without the feature)
- Use more feature flags
- Reorganize current dashboards to be more informative 
- ^build out more analytics that we need to be informative
(Add more instrumentation here)

**Comment by paolodamico** [comment]
In reply to @mariusandra :+1 on toolbar improvements, happy to work together on this if you want.

In reply to @EDsCODE,
1. Already working on point 1 of UX block too (we still need to catch up on the UI side).
1. Re: Stability; 4. 👍 and happy to help on this too, I believe that with [drf-exceptions-hog](https://github.com/posthog/drf-exceptions-hog), it should also be fairly easier to improve this (just some frontend handling).

**Comment by macobo** [comment]
Not many strong opinions from me this time - still getting my feet wet.

- Session recording - we want this released so we can get some feedback!
- +1 on releasing plugins: In addition to unlocking some great use-cases in it's own right, session recording would also benefit from it. See https://github.com/PostHog/posthog/issues/1846#issuecomment-709955786 for more details.
- After testing it out, I'm unhappy with our AWS deploys. I think we could improve both the setup and documentation around it, especially around setting up TLS. 
- Related, I'd love if we could add a way to measure which deployment mechanism users are using. Paolo and I were discussing adding a DEPLOYMENT env variable and adding it as user properties our backend.

**Comment by Twixes** [comment]
Definitely agree that we should be polish the user experience here and there.
Personally, I think one quite simple thing we could do that'd definitely improve user acquisition would be making social logins a frictionless experience: creating an account from scratch simply by logging in with GItHub, GitLab or Google (#1888 and #1594) – as opposed to social login's current state, which makes it difficult to actually use.

**Comment by yakkomajuri** [comment]
A little late but I agree with most of what's been said above.

I'd like to emphasize the importance of bug squashing. Just the other day I listened to a podcast where someone was talking about bug reporting fatigue, where you just encounter so many bugs regularly that you stop reporting them. Honestly, app right now feels like that sometimes.

Beyond improving the overall UX, fixing the small bugs also lets us uncover the big ones, which is another important thing. 

And then of course it's always nice to have a cool feature being released as well, and session recording + plugins ticks that box.

**Comment by jamesefhawkins** [comment]
Thoughts:

# Core functionality

* Session recording (@macobo)

This is nice as it is going to be an instant value add for users, so would potentially help retention immediately.

* Plugins (@mariusandra #1896)

This is strategic and will set us AND users up to build something more useful long term. 

* Feature flags

These keep coming up on user calls, but we're not really analysing their usage much. If we see usage in the "power users", I'd vote to increase the backend libraries these work with. If we don't, then we could move on then loop back.

# Bugs and UX

It feels like there is a lot here. I could see @Twixes and @paolodamico doing a great job here if they focussed on it. We'd just need to list out then prioritize stuff. Specific examples of things that are logical to me:

* Menu-related changes to me make sense to reduce confusion, so more people manage to work out what "actions" are.
* The social login is currently weird. Agree with @Twixes we probably lose people here. I'd use Google or GitHub personally rather than create another password for an app like ours.
* The general sign up flow could become a lot nicer as a similar themed task to the above
* There are many random bugs but we need to grab a list of them. It is horrible to demo at the moment. I'm definitely experiencing fatigue in reporting as I feel "they're all due to clickhouse not being in cloud yet", but would happily make a push to try to list anything we've missed int he existing issues.
* Stability would prevent more bugs making into production too I imagine.
* Monitoring could be an interesting to try - "your server is too small", to improve UX / reduce people thinking it's the software's fault when it's the hosting that is inappropriate.

# Deployment options

This feels like the least likely to impact everything above (although I think I *may* be missing why this matters so will ask on the call) but could be worth doing soon - perhaps next time. When we do introduce it, I'd vote for skewing this towards making plugin development as easy as possible.

Hence I'd vote for starting to use the CLI for deployments so we can just have ```some command posthog``` for the best UX possible here.

**Comment by yakkomajuri** [comment]
So I wasn't sure of a specific "feature" to work on because I would have wanted to discuss what my priorities should be. Nevertheless, here are my thoughts so the issue can be updated, and to get feedback on it (especially from @jamesefhawkins). 

For the next 2 weeks, my goals would be:

**- A proper deep refactor of the website**

I started off thinking of a smaller refactor but think that at this point I might as well go all in and get a lot done. This is especially where I wanted feedback regarding prioritization because this can be a very long task.

**- Get more tutorials out**

To have a tangible goal, I'd say 2 more in-depth tutorials.

**- Docs Dark Mode**

Again, I think this is part of top-notch Docs, but someone might disagree. It's also not super trivial with the way the website is structured, so definitely requires some work. 

**- Improved Styling & Feel**

* Better highlighting for warnings, errors, etc. 
* Styling fixes (https://github.com/PostHog/posthog.com/issues/518)
* Search bar enhancements (https://github.com/PostHog/posthog.com/issues/521)

**Comment by paolodamico** [comment]
Released https://github.com/PostHog/posthog/releases/tag/1.16.0
