### ISSUE TITLE
Cohorts navigation is weird

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#1881]
I got confused when creating and editing cohorts for the first time. Wrote down my notes:

### Scenario 1: When creating cohorts via Cohorts page

What happens currently
1. Go to People > Cohorts
2. See that Cohorts is active on side nav
3. Click +
4. In side nav, "All users" page is now active, see list of users after cohort
5. Click x
6. Still on all users page

Proposal:
1. Open "new cohort" card in the Cohorts page always
2. When clicking x, navigate back in history.

### Scenario 2: Opening a cohort

What happens currently
1. Go to People > Cohorts, Open cohort
2. End up at `/people?cohort=ID`, with All Users page active on side nav

Proposal:
1. Show same page, but under `/people/cohorts/:id` with Cohorts active on side nav

### Scenario 3: Saving a cohort

What happens currently
1. Go to People > Cohorts, click +, enter info
2. End up at `/people?cohort=ID`, with All Users page active on side nav

Proposal:
1. Show same page, but under `/people/cohorts/:id` with Cohorts active on side nav

cc @paolodamico what do you think about these changes?

**Comment by paolodamico** [comment]
👍 This is a great @macobo! Aligned 100% on the proposed UX.

Extending this issue, I'll also add that the Create cohort button on the users page seems a bit non-intuitive too because we use a button like this everywhere else to mean that you're creating an object for the page you're in, so maybe we should change the styling and perhaps move the location to make it more clear that you're not creating a user?

![image](https://user-images.githubusercontent.com/5864173/96115394-2707f800-0ee7-11eb-961c-dd172fdc232b.png)

**Comment by paolodamico** [comment]
On second thought I think we need to revamp the cohorts page and keep it independent from the users page.

**Comment by macobo** [comment]
> On second thought I think we need to revamp the cohorts page and keep it independent from the users page.

What exactly do you have in mind here? Is it related to session recording?

**Comment by paolodamico** [comment]
This has been addressed with the cohorts refactoring in which the cohort information is now shown in a separate drawer.
