### ISSUE TITLE
Session Recordings not working in Angular 16

### ISSUE THREAD

**Issue by saadjangdaa** [PostHog/posthog#18960]
## Bug description
I am using PostHog and events are working fine with Angular 16 but the problem that i am getting
is with the Session recordings i am trying to run locally in localhost
- i have removed any ad blocker
- i have also added localhost in authorized domains in project settings 

## Environment
Angular using import posthog from 'posthog-js'

**Comment by pauldambra** [comment]
Hey @saadjangdaa it's always tricky to debug things that are running on localhost :)

Is this running against PostHog cloud?

We'd need to see what the results of the calls to our decide API made by the web sdk are. That includes whether to enable session recording. And we'd need to see how you've configured posthog-js when initialising it.

It's probably better to report this using https://app.posthog.com/home#panel=settings%3Asupport%3Asession_replay

**Comment by saadjangdaa** [comment]
No, it is not running against Posthog Cloud i am using the node js package in my angular app and 
I have intilaized Posthog in my main ts file as provided in this guide 
https://posthog.com/tutorials/angular-analytics

my main ts file 
import posthog from 'posthog-js'
posthog.init(code)

my app component file
import { PostHog } from 'posthog-node'

  client :any = new PostHog(
    'projectkey',
    { host: 'https://app.posthog.com' }
  ) 


  constructor(
    public authService: AuthenticationService,
    private router: Router
  ) {

    this.client.capture({
      distinctId: 'test-id',
      event: 'test-event'
    })
  
  }

**Comment by pauldambra** [comment]
Hey @saadjangdaa app.posthog.com is posthog cloud 😊 

> We'd need to see what the results of the calls to our decide API made by the web sdk are. That includes whether to enable session recording. 

when posthog starts it makes an API call to `/decide` the response to that includes the session recording config. If that enables session recording then you'll start to see calls to `/s/`

you can also run `posthog.debug(true)` in the browser's console and you'll see every event we send. Recordings are sent as `$snapshot`

We've found debugging problems recording from localhost very tricky because there are so many things that might get in the way. In theory session recording works from localhost but development tooling and local environment gets in the way.

**Comment by saadjangdaa** [comment]
okay thanks for the clarification but i also i have hosted the app somewhere and have this call in my network (https://app.posthog.com/s/?compress) so does that mean the session recordings are on as you said about /s/ calls

**Comment by pauldambra** [comment]
yep app.posthog.com/s is a session recording call to posthog cloud, does that call succeed?

**Comment by saadjangdaa** [comment]
yes the call is succeeding thank you so much for you time : )
