### ISSUE TITLE
Discussion: Sidebar options

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#1898]
Related to #1775, and thanks to a discussion with @Twixes, we landed on two options for the sidebar menu and we need input. **Which option should we use for the next design release?** _The only difference is the layout of the sidebar, the icons and titles are still WIP (do not consider them for this)._

## Option A
**Key benefit**: Familar layout
![wide-menu](https://user-images.githubusercontent.com/5864173/96149674-e1a8f200-0f09-11eb-8053-7bdc35379f69.jpg)

## Option B
**Key Benefit**: More screen space for the main elements
![regular-page](https://user-images.githubusercontent.com/5864173/96149681-e53c7900-0f09-11eb-97cf-fab3d5bde49a.jpg)

**Comment by timgl** [comment]
I think I prefer 2, more space = better

**Comment by EDsCODE** [comment]
RE: layout—I also prefer 2 for the same reason above. 

RE:UI—I'd suggest making the colors and texture more sleek and introduce some retro elements to create a sort of sleek retro style rather than a pure retro interface (I can try to show this better in a followup comment). I'd say the logo and posthog.com landing graphics do a fairly good job of mixing those two styles

**Comment by mariusandra** [comment]
What about both, a'la wordpress:

![2020-10-15 17 28 32](https://user-images.githubusercontent.com/53387/96151854-2df53180-0f0c-11eb-8284-d601aeb648ab.gif)

**Comment by macobo** [comment]
I really like option 2, gives the main content space to breathe :

**Comment by lottiecoxon** [comment]
I prefer the second option - it feels cleaner

**Comment by yakkomajuri** [comment]
Agree with the "Option C" people have put out where we have the second option with some sort of sub-nav. 

Also agree with @EDsCODE and I think I actually get the point. Not too big of a fan of the current design to be honest.

**Comment by paolodamico** [comment]
Thanks everyone for the quick turnaround and honest feedback! Just to be clear, Option C would be doing Option A for large screens and Option B for smaller screens, which I actually tend to agree (at least try it in practice and see how it works).

I'll also work more on the UI based on the feedback from @EDsCODE & @yakkomajuri

**Comment by Twixes** [comment]
Actually I vote B, but I'm concerned about 2 things:
1. Option "Live" doesn't seem clear (as in: as a user it's not apparent to me what "live" things can be found there) or accurate (it is live data, but it also is all historic data, so I'd also emphasize that it's not just a stream of whatever's coming in, but basically full access to event/action/session data) to me.
1. How do we lay out organization/project/user settings when they're out of the side bar? This is the crucial difference from the current layout actually, because settings pages are specifically the ones that have been removed from the sidebar in these proposals here. This also includes instance-wide Licenses.

**Comment by lottiecoxon** [comment]
I did not see the GIF of the menu that pops out when hovered over- this is cool and gives me kinda workspace vibes more than the other two - change my vote to C

**Comment by paolodamico** [comment]
Ok so we're aligned on trying option C as described above, so closing this issue to continue conversation on main (#1775). Will share updated design today. @Twixes great points, will try to address them in the updated designs + https://github.com/PostHog/posthog.com/pull/501
