### ISSUE TITLE
Allow feature flags to be for time limited

### ISSUE THREAD

**Issue by weyert** [PostHog/posthog#1903]
## Is your feature request related to a problem?

I would like to be able to automatically disable a feature flag after a specific time. For example, Halloween and Sinterklaas are coming up. I think it would be nice to be able add feature flags which are only active for like 25-31 October and after 31 October it automatically disable.

## Describe the solution you'd like
 I think we could add Start and End/Expiry Date to a feature flag which is taken into account when calling `/decide`-endpoint

## Describe alternatives you've considered
Manually enable and disable the feature flag

**Comment by paolodamico** [comment]
This sounds like a super helpful feature, go for it @weyert! Let us know if you need any guidance here. CC @neilkakkar

**Comment by weyert** [comment]
Thank you @paolodamico  :)

@neilkakkar I was thinking to add a column to the `FeatureFlag`-model named like `expires_at`, / `until` / `ends_at` or similar and then adapt the queries so feature flags aren't getting returned in the `decide`-endpoint. 

I am wondering if it makes sense to also introduce a `start`-date so you could schedule a feature flag only for the Holidays season or something. Might be useful for the A/B experiments work?

**Comment by neilkakkar** [comment]
I think having a start and end time in the model is reasonable. Then you'd modify the [query building here](https://github.com/PostHog/posthog/blob/master/posthog/models/feature_flag.py#L197) to make it work.

The part that requires a bit of thinking is: We also have a "active" field in the model, which determines which FFs are active. This now needs to respect these new fields as well. As otherwise, these two fields clash: if the end_date is in the past, how can the FF be active?

I'm not quite sure yet what's the best way around this. One option is to have an "active" property, which takes into account the logic for start/end dates, as well as the value of the active field, and then every code path using `active` now uses the property `active`.

Another option might be to set active to false once the end_date passes, but at first glance this seems problematic and messy: how & when is this triggered, such that there's no long term delays & things stay consistent?

**Comment by weyert** [comment]
I will try to work on this during my vacation

**Comment by neilkakkar** [comment]
Given we have local evaluation as well now, I don't think this feature should touch query building / what `/decide` does at all, but control the `active` parameter on the flag.

i.e. a celery task that runs every hour (maybe less) & checks if a flag is inactive but start_time has arrived & then turns it on; and conversely if flag is active & end_time has arrived & then turns it off.

**Comment by jurajmajerik** [comment]
Hey @weyert, this has now become possible with scheduling flag changes: https://posthog.com/docs/feature-flags/scheduled-flag-changes
