### ISSUE TITLE
Person_id on event table

### ISSUE THREAD

**Issue by EDsCODE** [PostHog/posthog#1929]
**Some recap points:**

- We want to put person_id onto the events table because this will allow for the most direct queries. for nearly every query we have for analytics, direct access of person_id on the event row will dramatically reduce query times.

- We don’t need to worry about storing person properties on the event row. In fact, we don’t want to because person properties change. Person property related queries can be easily dealt with by first querying the person table for person_ids that have the target property (just as we do with event properties currently). 
```
SELECT ... FROM events where person_id IN (
    SELECT person_id FROM (person_property table) WHERE (some person property)
)
```

Next steps:

**How do we efficiently make the distinct_id <-> person_id relationship for events?**

**Pre-ingestion:** We could possibly create a plugin to accomplish this. If i'm still understanding where the plugins sit in the pipeline, we could have a plugin that hits the postgres DB/wherever we decide to store the person_id/distinct_id mapping and appends that to the payload before emitting an event to be ingested.

_Benefit:_ Cleaner ingestion. Don't need to rely on replacing mergetree and possibly have a bunch of duplicate data in the table
_Risk:_ I'm not familiar with the exact read capacity of postgres but this many reads could cause a slow down and event ingestion backup. However, I'd imagine there is some configuration of multiple postgres nodes that would allow for read capacity like this

**Post-ingestion:** We could attempt to use the ReplacingMergeTree engine on the events table. The ReplacingMergeTree will automatically deduplicate rows with the same sort key (so id, timestamp, team_id etc). We could keep the ingestion we have now and have some hook on ingested events that will re-emit the event with a filled in person_id
_Benefit:_  Don't need to risk slow down for reads
_Risk:_ Could cause a mess of duplicate data.

**Comment by fuziontech** [comment]
So currently on the Postgres only setup of Posthog: an event comes in with a `distinct_id` that we haven't seen yet we create a person and add the `distinct_id` to that person. If an identify event comes in that associates that `distinct_id` with an existing person we associate the `distinct_id` with the person referenced in the indent and remove the originally created person when we saw the new `distinct_id`. This works well because we are able to combine, remove, and update people and their associated `distinct_id`s easily, because Postgres.

On Clickhouse this is a bit more of a pain. There is a lot we can do to make things faster on joins, but ideally we want to have everything as denormalized as possible. Earlier today I tried creating a materialized view that would join in the `person_id` and pin it to an event as the events were coming in. Unfortunately on Clickhouse materialized views the view is triggered on the first table mentioned in the for clause which means you can trigger the view _either_ on event creation or when a person/distinct_id relationship is inserted or updated. Meaning that the `person_id` field will not be up to date.

After having a good think on how to get the most out of clickhouse's speed, move off of postgres for storing events, and being able to mutate people on events this is the setup that I think gives us the most flexibility:

Clickhouse w/ Collapsing Merge Tree.

I know what you are thinking: James, Clickhouse with Collapsing Merge Tree is going to be terribly complicated because we will need to grab the last state of an event and re-emit it to Clickhouse to update the `person_id` on the event when it changes. And you would be right.

This means that we will not only have to store events in Clickhouse but some other storage system where we can grab events by `distinct_id` and `event_id`. This would allow us to query this system to grab the events that would need updating on Clickhouse, update the `person_id`, and emit the updated events to Clickhouse.

There are a few options for where we could store this:
- Postgres (they are there already)
- Cassandra
- HBase
- DynamoDB

The issue with keeping events in Postgres is that it's expensive and we want to store larger payloads/events and Postgres is not so great at that. Cassandra is a great option, but requires pretty significant hand holding from an ops perspective. Luckily Amazon does have a hosted version if we wanted to not get locked in and have them manage it. Costs are not the lowest compared to the others. HBase is another option if we wanted to manage something ourselves, but again it is not trivial to operate. Then there is DynamoDB.

DynamoDB would allow us to store and access events randomly. Setup with a primary key of `distinct_id` and a sort key of `event_uuid` we would be able to do the queries that we would need where we want to update the `person_id` on an event associated with a `distinct_id` that has been identified to belong to an existing person. We would then re-emit the event with the updated information and Clickhouse would collapse that data into an updated view of the events giving us the speed that we need on query time. The cost would be relatively low (~$700 / month) at current msg rates.

With this setup we might even be able to pin person properties on the event and 'quickly' re-emit events when properties are updated. Though that might be a stretch.

**Comment by fuziontech** [comment]
As an anecdote to show that we could even pin the person properties to the event here are the current stats for number of events per person on production currently:

```sql
SELECT
    count(1) AS freq,
    countDistinct(pdi.person_id) AS peep,
    count(1) / countDistinct(person_id) AS events_per_person
FROM events AS e
INNER JOIN person_distinct_id AS pdi ON e.distinct_id = pdi.distinct_id
```

There are 18.24 events per person on average. Really not a huge update when properties change.

The counter to that is the person with the most events in production has over 2 million events... That would be quite the update.

Also after tooling around with pulling events by id, Clickhouse might be an option instead of Dynamo. The only thing that would cause an issue is if an event needs updating shortly after being emitted to Clickhouse. There is significant delay (relatively) from when the event is emitted to Clickhouse and when it will be available for querying. This would cause issues with idents occurring immediately after events are created since those events won't be available from Clickhouse meaning an update would not be possible for the Collapsing merge tree update row.

**Comment by mariusandra** [comment]
Yuri pm

**Comment by mariusandra** [comment]
Here's my 0.02 CAD:

I like the idea of adding every event again to the database with a new person_id when a distinct_id is aliased to another person. It sounds bold! Will it scale though? Probably, if we just change the min number of rows on each merge (e.g. replacing the logged out person_id with 20 events and not the one with 2000 events).

That said, I'm not sure if CollapsingMergeTree is the best bet. Needing exactly the right data in the "-1" row sounds like a consistency issue waiting to happen. For example when many aliases are called quite close to each other. ReplacingMergeTree (plus loads of argMax queries) still sounds like a safer bet.

Since everything goes through Kafka, a future optimisation could be to do some stream processing on the last 30sec of events and automatically merge people before they even reach clickhouse.

**Comment by fuziontech** [comment]
>Since everything goes through Kafka, a future optimization could be to do some stream processing on the last 30sec of events and automatically merge people before they even reach clickhouse.

The big issue here is that this isn't 30 sec problem. An anonymous user could use something for days before being aliased to an existing user you will need to update that person_id on the event. I'm pretty certain that it's either the collapsing merge tree with a ton of updates (which to be fair yandex uses examples of crazy update volumes in their example of how to use them and how they use it on their video pageview and view duration table). Or we will need to stick with joins which is probably fine for now, but eventually we will want something faster I think.

>That said, I'm not sure if CollapsingMergeTree is the best bet. Needing exactly the right data in the "-1" row sounds like a consistency issue waiting to happen. For example when many aliases are called quite close to each other. ReplacingMergeTree (plus loads of argMax queries) still sounds like a safer bet.

From what I understand we will still need to re-emit the event with either CollapsingMergeTree or ReplacingMergeTree? One we just have to _also_ emit a nullifying row along with the updated state row. This isn't that much more complexity over a replacing merge tree routine. If you need to update an event, grab the even state, emit it with "-1" sign, replace the person_id, emit it again with "1" sign. ReplacingMT you just emit the row with the same sort keys and it gets replaced. There is still the issue of having to grab the previous state and re-emitting with updated state. The docs for CollapsingMergeTree make it seem like you can be crazy with the "-1" sign signal and be super sure previous state was removed. Querying it does seem like it would be a bit easier as well.

**Comment by fuziontech** [comment]
Quick distribution of events per distinct_id:
```sql
SELECT
    arrayJoin(histogram(50)(freq)) AS hist,
    hist.3 AS cnt,
    bar(cnt, 0, 2500000, 10) AS bar
FROM
(
    SELECT
        distinct_id,
        count(1) AS freq
    FROM events AS e
    WHERE e.team_id != 2
    GROUP BY distinct_id
)
ORDER BY hist.1 DESC
```
```
┌─hist──────────────────────────────────────────────┬────────cnt─┬─bar────────┐
│ (1482279.5,2446704,1)                             │          1 │            │
│ (474128.5,1482279.5,1)                            │          1 │            │
│ (420019.5,474128.5,1)                             │          1 │            │
│ (378439.25,420019.5,1.125)                        │      1.125 │            │
│ (341275.25,378439.25,1.75)                        │       1.75 │            │
│ (332374,341275.25,1.125)                          │      1.125 │            │
│ (286916.5,332374,1)                               │          1 │            │
│ (236377,286916.5,1)                               │          1 │            │
│ (219934,236377,1)                                 │          1 │            │
│ (209124,219934,1)                                 │          1 │            │
│ (205387,209124,1)                                 │          1 │            │
│ (178689.75,205387,1.125)                          │      1.125 │            │
│ (150425,178689.75,1.875)                          │      1.875 │            │
│ (145388.75,150425,1.875)                          │      1.875 │            │
│ (141775.5,145388.75,1.125)                        │      1.125 │            │
│ (138376,141775.5,1.125)                           │      1.125 │            │
│ (134548,138376,1.75)                              │       1.75 │            │
│ (127173.25,134548,1.25)                           │       1.25 │            │
│ (120067.625,127173.25,2.125)                      │      2.125 │            │
│ (116912.375,120067.625,3.375)                     │      3.375 │            │
│ (113368.25,116912.375,1.75)                       │       1.75 │            │
│ (108957.25,113368.25,3.5)                         │        3.5 │            │
│ (101324.33333333334,108957.25,3.125)              │      3.125 │            │
│ (94183.16666666667,101324.33333333334,3)          │          3 │            │
│ (89902.45833333334,94183.16666666667,3.625)       │      3.625 │            │
│ (86229.29166666666,89902.45833333334,6.75)        │       6.75 │            │
│ (83191.16666666666,86229.29166666666,3.375)       │      3.375 │            │
│ (79685.91666666667,83191.16666666666,1.875)       │      1.875 │            │
│ (74799.25,79685.91666666667,5)                    │          5 │            │
│ (69821.20833333334,74799.25,3.5)                  │        3.5 │            │
│ (66372.20833333333,69821.20833333334,3.75)        │       3.75 │            │
│ (63384.47619047619,66372.20833333333,3.625)       │      3.625 │            │
│ (60511.78571428571,63384.47619047619,6.5)         │        6.5 │            │
│ (57276.392857142855,60511.78571428571,7.875)      │      7.875 │            │
│ (53295.55,57276.392857142855,12.625)              │     12.625 │            │
│ (49347.424999999996,53295.55,11.25)               │      11.25 │            │
│ (45628.98214285714,49347.424999999996,15.875)     │     15.875 │            │
│ (41388.443349753696,45628.98214285714,21.375)     │     21.375 │            │
│ (37267.35287356321,41388.443349753696,28.125)     │     28.125 │            │
│ (33352.38125,37267.35287356321,32.125)            │     32.125 │            │
│ (29520.478219696968,33352.38125,49.375)           │     49.375 │            │
│ (25715.613636363632,29520.478219696968,76.5)      │       76.5 │            │
│ (22161.15909090909,25715.613636363632,101.25)     │     101.25 │            │
│ (19081.027993348107,22161.15909090909,124)        │        124 │            │
│ (15853.770291327912,19081.027993348107,183.125)   │    183.125 │            │
│ (12594.985669191923,15853.770291327912,356.5)     │      356.5 │            │
│ (9257.371135339885,12594.985669191923,695.375)    │    695.375 │            │
│ (5786.211289581062,9257.371135339885,2139.375)    │   2139.375 │            │
│ (2063.2178969590946,5786.211289581062,2705669.25) │ 2705669.25 │ ██████████ │
│ (1,2063.2178969590946,18915472)                   │   18915472 │ ██████████ │
└───────────────────────────────────────────────────┴────────────┴────────────┘
```

The vast majority (99.45%) of distinct_id's have 5k or lower events

**Comment by EDsCODE** [comment]
It does seem to me that the solution to aliasing is re-emiiting everything as I'm not sure if we have any other ways around it because the timing is so uncertain. I actually am pretty confident this can work because Clickhouse appears to be way more happy with eating up tons of events and deduping through aggregation rather than actually trying to update previously inserted data 

Just so we're clear on the requirements, we will need systems that can support tagging in "both directions" right?

Forward: When an event comes in, if distinct_id is already associated with a person, we need to attach this person_id to the event. The system that tracks the distinct_id<->person_id mapping will need to support super high reads. Assuming this will have to sit on postgres for the near future

Backwards (the one described above): If some aliasing happens and a person_id needs to be replaced by a new person_id, we need a system where we can easily retrieve all the events associated with the old person_id that needs to be replaced and overwrite them, leveraging Clickhouse to dedup (either through collapsingMT or replacingMT)

**RE: collapsingMT vs ReplacingMT**
I'm still unsure which is better/when you're actually supposed to choose one over the other because i nthis case it seems that they could both work. 

The CollapsingMT might be more queryable immediately because you can just directly call 
```
GROUP BY id
HAVING sum(Sign) > 0
```
However, to make either engine more queryable we might just have to use the aggregating pattern that I've been recently using. (Aggregate on the main table, then create a view to the aggregated material table so now you have an always up to date table that you can query directly without needing extra conditions to filter out the duplicates)

**Comment by mariusandra** [comment]
Re: to @fuziontech 's points:

> The big issue here is that this isn't 30 sec problem.

Totally agreed, just the 30sec buffer could be enough to prevent 90% of these cases from occurring, taking load off the rest of the database. Might be an unnecessary last mile optimisation, but good to know it's there if/when needed.

> If you need to update an event, grab the even state, emit it with "-1" sign, replace the person_id, emit it again with "1" sign. 

Here's my issue with CollapsingMT: "grab the event state" is not deterministic. 

First, CH reads are heavy AFAIK, that's why we moved away from the various small "select *" queries.

Assuming that's fine, I'm more worried of the case when we have two events that grab the same current state at the same time and emit the same "-1" event and a different "+1" event, leading to inconsistent data:

E.g.: 

```
+1, person_1, event_1, props_1

-1, person_1, event_1, props_1
+1, person_2, event_1, props_1

-1, person_1, event_1, props_1
+1, person_3, event_1, props_1
```

If it's true that: 

> The docs for CollapsingMergeTree make it seem like you can be crazy with the "-1" sign signal and be super sure previous state was removed.

then the point is moot obviously.

**Comment by mariusandra** [comment]
Re: to @EDsCODE 

> Forward: When an event comes in, if distinct_id is already associated with a person, we need to attach this person_id to the event. The system that tracks the distinct_id<->person_id mapping will need to support super high reads. Assuming this will have to sit on postgres for the near future

Can't we leverage the client libraries and just also send the `person_id` with each event once an identify call has been made? Plus I'd also send a `fresh_distinct_id` flag if the reported `distinct_id` is newly minted or if it was used previously, saving some lookup queries.

Other than that, postgres is probably fine for storing this person<->distinct mapping, though I still wouldn't rule out the option to just query this directly from clickhouse with a short lived redis cache in front of that, especially if the `fresh_distinct_id` is sent along.

**Comment by Twixes** [comment]
This was discussed elsewhere recently and I _think_ we dismissed it?
