### ISSUE TITLE
Some recordings can't be played (freezes on "Buffering...")

### ISSUE THREAD

**Issue by benone** [PostHog/posthog#19889]
## Bug description
When I try to play some recordings, I see a "Buffering..." message in the player window.

It doesn't depend on session length or device. I don't understand which sessions are affected.

## How to reproduce
1. Click on Recording
2. See infinite "Buffering..."  text.

## Environment
- [x] PostHog Hobby self-hosted with `docker compose`, version/commit: latest: a9f9a2db2ba65bcf02374f51468ac921dc1c681d

## Additional context
- I don't see any specific errors in the JS console or container logs.

**Comment by pauldambra** [comment]
Hey Benone,

Is this consistent for individual recordings. So, if you were to take a recording that buffers and wait one of two minutes does it still buffer after refreshing the page?

If it is consistent are you able to share links to the recordings? 

Thanks

Paul

**Comment by benone** [comment]
Hi Paul!

I tried to wait, but it didn't work, either, after refreshing.
Here is an example: https://ph.gomicro.xyz/project/1/replay/recent?sessionRecordingId=018d3ffe-c407-7314-bd87-224b47dafcb6

Should I check the logs?

**Comment by pauldambra** [comment]
Ah, I'd missed this was a self-hosted deployment.

We don't offer direct [support for self-hosted](https://posthog.com/docs/self-host/open-source/support). There are several moving parts to the infrastructure around recordings.

**Comment by andregerbaulet** [comment]
Just FYI,

I also have the same issue - also self-hosted.

**Comment by pauldambra** [comment]
hey @andregerbaulet @benone as I commented above we stopped offering support for self-hosted since it can be too complex to track down the difference between different infrastructures. That's not to say we wouldn't act on bugs discovered by folk that are running self-hosted deployments since we want posthog to work for y'all too.

if this was on cloud

i'd be checking the interaction on the session_recording/{id}/snapshots end point.

The UI hits that end point and the backend return the sources to request snapshot data from. Currently that will only be [blob], [realtime], or [blob, realtime] (not the actual JSON over the wire)

if there is blob as a source we load each blob source advertised
then
if there is realtime advertised as a source we load that (I actually changed this in the last couple of days so the UI now polls for realtime data)

blob is loaded from S3 
realtime is loaded from redis

if you can put more detail into what is happening for you then it might be there is a bug that is shared between self-hosted and cloud.

**Comment by marandaneto** [comment]
Similar to https://github.com/PostHog/posthog/issues/9122

**Comment by pauldambra** [comment]
self-hosted deployments stuck on buffering could be a range of issues we can't easily debug.

I'd guess some issue with redis and the blob ingester but it's impossible to be sure it isn't a different issue for every deploy
