### ISSUE TITLE
Release 1.17.0 - 12 November 2020

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#2046]
Priorities
- core analytics UX improvements
- Initial user deployment experience improvements

James G
- Documentation & runbooking
- Persons on events
  - Get events and people on dynamoDB
  - Table in ClickHouse with person_ids
- Move other topics to proto
- Feature flags client libraries

Tim
- Think/redesign actions
- ~Clickhouse query improvements/speed up~
- ~Sentry integration~
- Create an automatic rotation of customer support
- Add more 'empty states' #2091
- Find and squash UX improvements
- Clickhouse refactoring

Eric
- Clickhouse refactoring / stable
- [x]  Retention frontend improvements

Marius
- Crank out example plugins
- Security / performance of plugins
- World-class documentation of plugins (how to create your first plugin)
- Test-suite against a local plugin
- Posthog-js-lite improvements for plugins
- Create plan for moving from posthog-js to posthog-js-lite
- Moving app to typescript
- React Native bug
- Adding feature flag to php/ruby library

Karl
- Session recording
    - Focus on bugs and improving stability
- Deployments
  - Celery multiple queues: #1949 PostHog/deployment#29 PostHog/deployment#32 PostHog/deployment#27 #2135
- posthog-js:  PostHog/posthog-js#101, PostHog/posthog-js#92, PostHog/posthog-js#39
- Improve auto-generated selectors #2140 
- Improve element select toolbar #2143
- Get involved in Clickhouse

Paolo
-  ~Design #871~
- ~Address feedback for #2114 & ship.~
- ~Navigation #1775 (swapped for #2114 on release 16)~
- ~[UX] Rethink persons & cohorts UX [related to #1881].~
- [Design] Design proposal for docs dark mode.
- ~Email docs PostHog/posthog.com#487.~
- Explore & potentially implement for #2080.
- Lower priority. Activate billing for everyone & make sure people near the event limit are prompted to update.

Michael
- Smashing out as many small bug fixes as possible https://github.com/PostHog/posthog/projects/10

**Comment by paolodamico** [comment]
Using release label that we used for previous one.

Things I'm keen on getting done for next release:

### General
- Retention 100% (#1936, #1995, #2104, #1344**)
- PostHog demo https://github.com/PostHog/posthog-production/issues/18
- Capture missing data #1575

### Myself
- Address feedback for #2114 & ship.
- Navigation #1775 (swapped for #2114 on release 16)
- **[UX]** Rethink persons & cohorts UX [related to #1881].
- **[UX]** Improve toolbar UX.
- **[Design]** Design proposal for docs dark mode.
- Convert weekly email report to orgs & ship.
- Email docs https://github.com/PostHog/posthog.com/issues/487.
- Explore & potentially implement for #2080.
- Lower priority. Activate billing for everyone & make sure people near the event limit are prompted to update.

**Comment by yakkomajuri** [comment]
## Product 

I want to reiterate the need for squashing bugs, although many are indeed CH-related.

#2010, #2017, and #2047 are examples of bugs related to our core functionality that we regularly demo and "brag about".

## Myself

As for what I'll do on the next release cycle, me and @jamesefhawkins decided I should own a significant push for content creation and distribution, in order to trial different approaches and determine what works best.

That will take up the entire cycle for me, and I'm setting the ambitious goal of writing up 8 new pieces. 

I will not only be writing, but also distributing, marketing, etc.

**Comment by paolodamico** [comment]
Agree with squashing bugs, particularly related to core functionality, adding #2049, #1843, #1959, ~#1909~.

**Comment by EDsCODE** [comment]
Clickhouse is near fully deployed. There are optimizations that still need to be done bu otherwise handling our own volume is very doable. 

**My priorities/options:**
- continue cleaning up clickhouse so that it's easy to build off of
- go on bug squashing mode for 2 weeks

**General Idea:**

- I'd be a fan of revisiting the staging environment setup. Getting a really good staging environment to sit before prod would really help our process as we're starting to have a bunch of people working on a bunch of different things that should get some exposure before launching on prod

**Comment by Twixes** [comment]
I'll be off for the second half of this release, so somewhat limited, but I do have some ideas that I'd like to take care of personally in the next week:
1. Refactor `/api/user` to use DRF like the rest of our web API (backend already done in PR #2111, just requires frontend adjustments), which is a long-standing hindrance. 
2. Further demo improvements (epic #2128).
3. Smooth out the UX inconsistencies/bugs that we have, since they continue to be visible and we have a [solid list of them](https://github.com/PostHog/posthog/projects/10), also some projects/orgs UX improvements (PR #2145).

**Comment by macobo** [comment]
Input is focusing on what I can help with and am interested in. This list is too long for 2 weeks - hoping to whittle it down by discussion.

#### 1. Session recording

Session recording is live and a bunch of potential features are now [documented in our issue tracker](https://github.com/PostHog/posthog/labels/session%20recording). However instead of solving them, I'd love to wait a bit and see how customers are using the feature.

Known TODOs:
1. Set up key metrics for session recording
2. Join in on customer calls for clients who have been using the feature.

#### 2. Cloud / Self-hosted stability

Two motivators here:
- Getting more context and be of help with extinguishing fires. James is overloaded.
- My own experience with setting up and managing a self-hosted instance has been painful.

Open question: How much do we want to invest into non-cloud at this point in time?

Cloud: 
- Celery multiple queues: https://github.com/PostHog/posthog/issues/1949 

Self-hosted/Cloudformation: 
- No alerts when stuff dies https://github.com/PostHog/deployment/issues/29 
- No logs https://github.com/PostHog/deployment/issues/32 
- Automatically generate SECRET_KEY https://github.com/PostHog/deployment/issues/27 
- Fix stats page https://github.com/PostHog/posthog/issues/2135

#### 3. Posthog.js

It's an open secret the code in posthog-js is kind of :hankey:, so we need some focus to fix issues like:

- Making sure opting out works properly: https://github.com/PostHog/posthog-js/issues/101, https://github.com/PostHog/posthog-js/issues/92, https://github.com/PostHog/posthog-js/issues/39 (and a couple of others).
- Building a browser-based test suite for testing autocapture
- Refactoring things as we go along

#### 4. Misc features (feature flags & toolbar)

- Make feature flags toggleable in development/testing environments via toolbar https://github.com/PostHog/posthog/issues/1996
- Improve auto-generated selectors https://github.com/PostHog/posthog/issues/2140
- Improve creating actions within toolbar: https://github.com/PostHog/posthog/issues/2143
- Create 'stats' view: https://github.com/PostHog/posthog/issues/871

#### 5. Clickhouse

Through happenstance I now have quite a lot of clickhouse theoretical knowledge but not a lot of practice. I'd love to put some solid focus in with optimizing/building/etc, but don't have any specific tickets in mind. :)

#### 6. Tests

Our tests have been unstable. https://github.com/PostHog/posthog/issues/2136

**Comment by jamesefhawkins** [comment]
For me personally:

# Last week

* working on handing over context (!), finances, legal and HR related items so @piemets can operate autonomously. I think this is 85% done by there are a couple of bits like HMRC and hand holding needed for next week to properly complete this.
* building pipeline for the designer and full stack developer role. I've kept the bar very high but the designer role has taken more time than I had hoped as the response rate was worse than usual.

# Next 2 weeks

* Keep recruiting for these two roles. I would aim within one more week to have solid designer AND full stack developer pipelines so we realistically have the person we're going to hire for both roles talking to us.
* Make sure we properly promote plugins and session recording on Twitter / Users slack etc so we actually get usage from them so we can learn from users what the reaction is.
* Support Yakko and Lottie in going deep on understanding how to grow our audience size through content. This will be probably 25% of my time this week coming (mainly on the planning side) and more like 50% the week after (QA, building campaigns and tweaking them after go live) I would expect.

**Comment by jamesefhawkins** [comment]
> * Release Sentry js integration

To clarify, as a user facing feature right?

**Comment by jamesefhawkins** [comment]
> * make more prominent (make it feel more 'live')

We should start by looking at session recording tools and working out what their functionality is since they'll have thought hard about this. 

For us specifically, I can see a bunch of cool places:

* Somehow in feature flags (ie 'I want to watch a user using this new feature')
* In funnels 'I want to watch what went wrong when people didn't convert'
* In user profiles 'I want to watch what this user did'
* and integrated with the sentry integration perhaps 'I want to watch what went wrong when this error appeared'

**Comment by mariusandra** [comment]
next 2 weeks:
- create a bunch of plugins
- clean up and refactor plugins (interface, security, scalability, etc, [see the epic](https://github.com/PostHog/posthog/issues/1896))
- posthog-js-lite
- typescript migration
- make the frontend better
- show some love to the integrations (bug with android react native times, feature flags to things)

**Comment by lottiecoxon** [comment]
Next two weeks:
- 
- Session Recording Feature Page ([#548](https://github.com/PostHog/posthog.com/issues/548)) 
- Finish careers page ([#486](https://github.com/PostHog/posthog.com/issues/486)) 
- Plugins product image tweaks ([#505](https://github.com/PostHog/posthog.com/issues/505)) 
- Push out PR changes for team page ([#485](https://github.com/PostHog/posthog.com/issues/485))
- (please let me) redesign the landing page ?
- Slowly introduce more 8 bit style artwork into webpages so the contrast between the two art styles merges in a harmonious way. (+could also start work on animations in this style to 'liven' up the pages

**Comment by lottiecoxon** [comment]
## OH AND 

- 404 page design
