### ISSUE TITLE
Survey popup UI polish (add all issues here)

### ISSUE THREAD

**Issue by jurajmajerik** [PostHog/posthog#20851]
1.
> If no title is set, spacing is slightly off.

![image](https://github.com/PostHog/posthog/assets/22996112/bc3dc1d3-f08c-4df1-87ce-b4e4ee1fd81e)

2.
> is it not possible to change the close button text on this one?
![image](https://github.com/PostHog/posthog/assets/22996112/b932ce12-946c-4d16-be58-7cd05232eadf)

3.
![image](https://github.com/PostHog/posthog/assets/22996112/3b68f234-2d1f-48e5-8810-77f438cf9598)

4.
Emojis should be grey by default
<img width="415" alt="image" src="https://github.com/PostHog/posthog/assets/4853149/47c285b3-31cb-44f8-b9e3-f3bbacdd608a">

**Comment by dmarticus** [comment]
Howdy, I took a look at tinkering with this today, and I don't think I have enough context to move forward with fixes yet since I want to make sure I'm aligned with what the team is thinking.

> 1. If no title is set, spacing is slightly off.

![image](https://github.com/PostHog/posthog/assets/4853149/1411cb44-3ca7-404e-a27c-5674b9a8dc9b)

Is the idea here that we want the space between the top of the survey box and the first question to be the same as the space between the last question and the "submit" button?

e.g. this image

<img width="244" alt="image" src="https://github.com/PostHog/posthog/assets/4853149/3461b4e1-40cc-4d1d-91dd-ca42c5edccde">

instead of this image?

<img width="250" alt="image" src="https://github.com/PostHog/posthog/assets/4853149/eff372dd-5f43-4abe-88f4-4c28d58cfc54">

> 2. is it not possible to change the close button text on this one?

Is this just on the popup experience for the end user (i.e. the popup rendered by posthog-js)?  Because the popup rendered in the posthog app is internationalized for the close button

<img width="309" alt="image" src="https://github.com/PostHog/posthog/assets/4853149/9a9dd671-f5b5-4350-8b23-7c1be4fafdd7">

> 3. Is the survey the same width as the thank you screen?

I'm pretty sure Annika is asking about the popup showed to the end user, but this is a problem in the rendered survey in the posthog app too (see gif).  I don't have any questions about what to do here.

![2024-05-23 12 52 41](https://github.com/PostHog/posthog/assets/4853149/0a1f325d-6cac-4358-807f-90683518379e)

> 4. Emojis should be grey by default

I should've asked Juraj when we went through this, but, what color grey are we talking about here?

@annikaschmid @jurajmajerik if y'all could weigh in on these questions whenever you have the chance, I can move forward with implementing the fixes.

**Comment by jurajmajerik** [comment]
Sorry I haven't responded to your questions here @dmarticus 

1. Yes sounds reasonable!
2. I assume the screenshot shows a survey translated in the browser? The problem is that the Close button currently cannot be customized. So it's more like a feature request than a UI bug.
3. 
4. Up to you :) I thought there was already some default grey specified in the config. If not, the menu grey will work fine:

<img width="143" alt="image" src="https://github.com/PostHog/posthog/assets/22996112/f95a1a62-22fe-40dc-b94b-bc9649ff7300">

**Comment by dmarticus** [comment]
With the completion of the above MRs, this task is now closed.
