### ISSUE TITLE
Extract function is not working as expected

### ISSUE THREAD

**Issue by vanimesh** [PostHog/posthog#21029]
## Bug description
Extract function is not working as expected when the sql query used in HQL.

i am using the below sql to extract some text from current url but it gives me an error. **"no viable alternative at input 'select extract(properties.$current_url, ''"**

below is the query which i am using
select extract(properties.$current_url, '\/app\/(.*\w)\/') as app_name,properties.$current_url from events where event='$pageview' and properties.$current_url like '%rt%' limit 10

**Comment by mariusandra** [comment]
(this not yet a fix, just dumping some context)

This seems to be because the [parser is preferring](https://github.com/PostHog/posthog/blob/d946f661f2f2fb2a0832581972344ba2adce11d2/posthog/hogql/grammar/HogQLParser.g4#L106) the `EXTRACT` [keyword](https://clickhouse.com/docs/en/sql-reference/operators#extract) to a function with the same name.

<img width="1384" alt="image" src="https://github.com/PostHog/posthog/assets/53387/cb2ecc11-4c82-4efa-92cf-e392d96603b0">

**Comment by vanimesh** [comment]
When can we have this fixed ?

**Comment by vanimesh** [comment]
Hi @mariusandra any update ?

**Comment by mariusandra** [comment]
This should finally be fixed, apologies for the wait.
