### ISSUE TITLE
Stop a survey once enough responses received

### ISSUE THREAD

**Issue by jurajmajerik** [PostHog/posthog#21179]
## Is your feature request related to a problem?

*Please describe.*

**Comment by nikitaevg** [comment]
Hi @jurajmajerik, can I work on this issue?

So this requires setting a goal for a survey. I came up with [this](https://github.com/PostHog/posthog/assets/6707908/193cf0f8-7afa-4f8c-9a82-2c265c2ecb6c) design.

This also requires viewing the goal for the survey, something like [this](https://github.com/PostHog/posthog/assets/6707908/6ba5f1eb-e129-4713-a9b1-94ff4a15d10a).

From the backend pov I don't expect any challenges, but I didn't look into it. I think on every survey response I can check if the response count is above the goal and if I need to stop the survey I stop it.

There's one tricky part I see - if somebody want's to resume the survey once the goal is reached I assume it'd be better to start ignoring the goal, meaning to override the value that represents the "Stop survey on reaching the goal" checkbox from my design.

Also I wonder if you want to show the user that their survey was stopped because it reached the goal? If so I could try to come up with something, but I don't have anything good of the top of my head.

Please let me know what you think of these suggestions

**Comment by jurajmajerik** [comment]
Hey @nikitaevg! Survey responses are not submitted via the Surveys API - they're simply events sent from end users' frontends via the /capture endpoint. Because of this disconnect, I expect solving this will be more involved. I'm not sure if we support additional logic when submitting events. @neilkakkar?

As for the release cycle, we're pretty flexible. If it's a small change, ideally you would put both frontend and backend changes in the same PR. If you want to split it, implementing the backend first makes more sense.

**Comment by neilkakkar** [comment]
We wouldn't want to slow down the ingestion pipeline, so indeed this will need to happen elsewhere: Using our celery task poll for number of responses and end the survey when we hit the threshold. This means we can't exactly stop at X, but roughly X (assuming there's no huge spike of responses between two pollings, but this should be ok given its controlled by user input).

So, we'd want the UI to be mindful of this constraint^. On the UI side, I'm not sure the goal makes sense, given they can overshoot it, and then re-enable a survey when the goal is reached, thus effectively ignoring it. A config option for "Stop surveys when X [Input] responses are received" is enough (like the survey wait period setting in targeting) -and agree on this going in another section, but I'm not sure of the name yet, additional settings? Response settings? unclear what else will go in here.

**Comment by nikitaevg** [comment]
Thank you both for explaining!

> We wouldn't want to slow down the ingestion pipeline, so indeed this will need to happen elsewhere: Using our celery task poll for number of responses and end the survey when we hit the threshold. This means we can't exactly stop at X, but roughly X (assuming there's no huge spike of responses between two pollings, but this should be ok given its controlled by user input).

Yeah, that sounds reasonable. I don't see any existing task suitable for this functionality, so I would introduce a new task, sounds good?

> On the UI side, I'm not sure the goal makes sense, given they can overshoot it, and then re-enable a survey when the goal is reached, thus effectively ignoring it.

I'm a bit concerned that users won't understand why their surveys suddenly stopped, but I will trust your judgement on this.

> A config option for "Stop surveys when X [Input] responses are received" is enough (like the survey wait period setting in targeting) -and agree on this going in another section, but I'm not sure of the name yet, additional settings? Response settings? unclear what else will go in here.

Huh, I haven't seen this wait period. Yeah, it makes sense to design it the same way, thanks! Regarding the naming, maybe "Stop conditions"? @neilkakkar wdyt?

**Comment by nikitaevg** [comment]
@neilkakkar please take a look at https://github.com/PostHog/posthog/pull/21528
