### ISSUE TITLE
`posthog.get_session_replay_url()` does not include the project ID

### ISSUE THREAD

**Issue by MarconLP** [PostHog/posthog#21190]
## Bug description

We've recently implemented project ID in the URL. Url's from `posthog.get_session_replay_url()` or Sentry won't include those yet.

## How to reproduce

1. Set up PostHog
2. Call `posthog.get_session_replay_url()`
3. Realize the URL does not include the project ID

## Additional context

https://posthoghelp.zendesk.com/agent/tickets/12079

**Comment by benjackwhite** [comment]
Technically it isn't needed. It will still work as long as the project is logged in. 
Not sure if we could ever really include it as the client has no idea what the project ID is (and never should). We could perhaps look at including the project api key in the url and using that for a project switch or something but realistically that is pretty high effort for this sort of edge case issue

**Comment by lnhrdt** [comment]
Hey @benjackwhite, I'm the user from ticket 12079 that prompted @MarconLP to create this issue. I'll totally understand if it's an edge case from your perspective but I'll share some details of my use case in case it helps clarify a need.

On our team we have 5 PostHog projects. We're a small scrappy team that's trying triage operations together in Slack between people with skillsets spanning Engineer, Data Analyst, Design, and Sales. We're automating alerts that could indicate a variety of operational issues from different sources (e.g. exceptions in the web UI, unhealthy drop in a customer account's activity, failed payment method charges) into a Slack channel where we can triage it together based on who's available and the context. PostHog's been an essential tool in this effort because as our Product Analytics tool it truly can surface issues that are cross-functional concerns to our team.

Because we have 5 PostHog projects, none of the PostHog links load when you click on them unless the last project you had open was the relevant one for the link. As an engineer (and the one who chose and configured PostHog for my team) I'm capable of understanding that I probably have the wrong active project and switching it, but that's not easy for the other members of my team who are less familiar with PostHog, and possibly less technical. I've considered consolidating into one project to work around this issue but that's a fair amount of work, would result in a loss of history, and feels like the tail wagging the dog–we otherwise get a lot of value from having separate projects.

I've seen this link/project issue:
- In Slack messages sent through PostHog's webhook integration (using [a formatted message](https://posthog.com/docs/webhooks#message-formatting) in PostHog Actions)
- When manually copying a link in the PostHog UI (context menu on an event -> "Copy link to event")
- In Sentry integration's `PostHog-Person-URL` link

I've noticed and appreciated other multi-project enhancements introduced over time (e.g. switching between projects now keeps you on the same page rather than navigating back to the home page). Thank you for also considering this use case now!

**Comment by benjackwhite** [comment]
3 Open PRs that should solve every case you've mentioned so far 👍

**Comment by lnhrdt** [comment]
Absolutely incredible @benjackwhite! Thanks for taking the time here. I'll keep an eye out for the updates!
