### ISSUE TITLE
Make tests stable

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#2136]
## Severity

In the past 2 days, 44% of merged PRs have been red and of the last 200 merged PRs 54 have had failing tests (27%). I think it's fair to say our tests are really unstable.

This leads to a lot of cycles spent trying to retry tests in hopes they go green or duplicated effort towards making tests pass. I estimate I have spent up to 20% of my daily work struggling with this issue. This could also turn off potential contributors.

This issue tries to document various problems we've had in hopes to sol

## Analysis

There's no one single issue here but many. Breaking them down should help us move forward and figure out solution.

### 1. Flaky clickhouse tests

Documented under https://github.com/PostHog/posthog/issues/2126.

**Potential solutions**
- https://github.com/PostHog/posthog/pull/2116 should fix this particular issue, but is running into integration problems.
- Switching to pytest should give us better tools to run tests many times to better weed out flaky tests as they occur.

### 2. Changes to posthog-production

We run tests against posthog-production as part of our suite. I've seen at least 2 failures which were caused by changes in posthog-production which were not supported by the branch OR were not implemented as part of the core repo.

Example slack thread: https://posthog.slack.com/archives/C0113360FFV/p1603869337037700

Unclear. @paolodamico you had context on how this broke - can you link the offending PR and suggest what can we do to avoid this error in the future?

### 3. Cypress tests are not run

For some surprising reason, it seems when rebuilding not all cypress tests run?

This has led to instances where we update code -> create tests -> break tests within the same PR without the tests being run.

Example of breakage: https://github.com/PostHog/posthog/pull/2070 and https://github.com/PostHog/posthog/pull/1942

**Potential solution**: Investigate this by trying to recreate it. Perhaps cypress.io parallelism offering is at fault here?

### 4. Cypress flakyness due to timeouts (fixed?)

Tests hitting the browser can be inherently unstable - code may load at different speeds, etc. 

**Potential solution**: Turn on retries (done)

## Call to action

Seen anything else break in interesting ways? Note them down.

**Comment by paolodamico** [comment]
**100% agree with the premise**, we do keep needing to re-run tests on almost every PR in the hopes that they'll pass. However, re 2, I don't think it's really an issue. Several weeks ago we updated testing suites in both repos to make sure new changes pass the test suite against the `master` branch in the other repo (this was motivated by us inadvertently introducing some code changes that broke the other repo).

What happened in the specific instance you're referring to is that https://github.com/PostHog/posthog-production/pull/40 changed the testing requirements for the `posthog-production` repo, now requiring Clickhouse to be present (whereas previously these tests did not touch CH at all). This meant that the way we run tests changed, not the actual codebase. Tests broke because we now were running tests differently. This is why the only change required to fix them was on the Github actions config (see #2062). We could mitigate this by syncing the Github actions config on both repos for each other's tests, but it might be too complicated to be worth it, unsure.

**Comment by paolodamico** [comment]
Found an issue that should help improve tests stability for Cypress. Previously E2E tests on GH actions were using production feature flags from [app.posthog.com](https://app.posthog.com). We had two particular cases in which the flags are deployed to 50% of the user base, and when the flags were active (presumably ~50% of the time), it caused the tests to fail. #2152 addresses this.

**Comment by macobo** [comment]
For cypress (#3) I think this might be the core cause:

> Warning warning: Cypress actions use GITHUB_TOKEN to get the correct branch and the number of jobs run, making it possible to re-run without the need of pushing an empty commit. If you don't want to use the GITHUB_TOKEN you can still run your tests without problem with the only note that Cypress Dashboard API connects parallel jobs into a single logical run using GitHub commit SHA plus workflow name. If you attempt to re-run GitHub checks, the Dashboard thinks the run has already ended. In order to truly rerun parallel jobs, push an empty commit with git commit --allow-empty -m "re-run checks" && git push. As another work around you can generate and cache a custom build id, read Adding a unique build number to GitHub Actions

From https://github.com/cypress-io/github-action

**Comment by Twixes** [comment]
The situation is good enough now here. The flakiness has mostly moved to https://github.com/PostHog/plugin-server
