### ISSUE TITLE
Add `OR` option to `Filter out internal and test users` in project setting

### ISSUE THREAD

**Issue by slshults** [PostHog/posthog#21417]
## Is your feature request related to a problem?

(From: https://posthoghelp.zendesk.com/agent/tickets/11941)

I want to exclude all localhost `OR` office ip address `OR` @mydomain.com emails [when defining `Filter out internal and test users` in project settings] but currently only `AND` rules are available.

## Describe the solution you'd like

To be able to choose between `AND` and `OR` 

## Describe alternatives you've considered

Using the `OR` option in filters for cohorts, then using the cohort when defining `Filter out internal and test users` in project settings

## Additional context

![CleanShot 2024-04-08 at 15 44 35@2x](https://github.com/PostHog/posthog/assets/227448/d1c4e58c-8bbe-4285-9144-2d48a951092e)

**Comment by neilkakkar** [comment]
In this case, I think they want an AND in these filters.

It would be OR, yes, if your filter had email contains mydomain.com, but here the filter they are adding is email DOES NOT contain mydomain.com, which needs to be AND'ed, otherwise you'll be excluding valid users. 

For a condition on the same parameter, like ip_address, you can use OR by adding values to the list `ip_address NOT IN (localhost, 127.0.0.1, some other)`

Overall I think it will be more confusing to add OR filters here, since this is almost always not what you want 😅.

For example, if I had OR in the screenshot above, an event with email = 'valid_user' but sent from 'localhost' would not be filtered out, when it should be (I think? - unless the use-case is that only when ALL conditions match should they be excluded - in which case it's worth going through the alternative, since this is highly atypical)

(reopen if not the case / I'm misunderstanding :) )
