### ISSUE TITLE
Funnels have not been loading for multiple weeks

### ISSUE THREAD

**Issue by bastienbeurier** [PostHog/posthog#21658]
## Bug description

*Please describe.*
*If this affects the front-end, screenshots would be of great help.*

*If you are on PostHog Cloud it would be really valuable if you can share any links where the problem occurs. This speeds up our ability to troubleshoot tremendously.*

## How to reproduce

1. 
2.
3. 

### Debug info

```shell
Session: https://us.posthog.com/project/sTMFPsFhdP1Ssg/replay/018ef1c4-0924-7ed1-b03a-ab53e7d42749?t=1257 (at https://us.posthog.com/project/13704/insights/1PHJnPtp#panel=support%3Abug%3Aanalytics%3A)
Admin: http://go/adminOrgUS/018359c2-e0bf-0000-7e7b-3540a824b11d (Project: 13704)
Sentry: http://go/sentryUS/13704
```

**Comment by MarconLP** [comment]
Hey @bastienbeurier, [this funnel](https://us.posthog.com/project/13704/insights/1PHJnPtp) seems to fail because of the `account does not match regex: .*localhost.*` filter. You'll need to switch the type of [that event property](https://us.posthog.com/project/13704/data-management/properties/018636eb-f25c-0001-2e7a-693c84c03266) to `string` or use the person property instead.

**Comment by bastienbeurier** [comment]
That fixed it, thank you!

--
Bastien ( nango.dev ( http://nango.dev ) )
