### ISSUE TITLE
React-native sending incorrect timestamps

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#2173]
## Bug description
 
It looks like either timestamp or sent_at is being sent without timezone, causing [this issue](https://sentry.io/organizations/posthog/issues/1972106098/?project=1899813&query=is%3Aunresolved&statsPeriod=14d)

## Expected behavior

It should send both timestamps with timezone

## How to reproduce

1. 
2. 
3. 

## Environment

- PostHog cloud or self-managed?
- PostHog version/commit

**Comment by mariusandra** [comment]
I've been debugging this now for a while and I *think* there's actually no problem with react native. Two clues:

1. I'm unable to reproduce it.

2. A few of the events also come from Chrome, even if 98+% seem to be from iOS or Android:
<img width="725" alt="Screenshot 2020-11-16 at 11 37 44" src="https://user-images.githubusercontent.com/53387/99256519-d18c7700-2815-11eb-96c9-528a8bba9984.png">

3. All these 500k events in the linked sentry issue are run from the shell:
![image](https://user-images.githubusercontent.com/53387/99256614-f41e9000-2815-11eb-964c-457ea587381a.png)

4. The error is in `process_event`, but we should be using `process_event_ee` normally...?
![image](https://user-images.githubusercontent.com/53387/99257536-7a87a180-2817-11eb-95bf-fe5ab813e5c4.png)

5. There's a function `log_event` that logs events into Kafka, but omits the timezones on `now` and `sent_at` 
![image](https://user-images.githubusercontent.com/53387/99256678-0b5d7d80-2816-11eb-9522-3afc50e07b81.png)

6. This matches the format of `now` and `sent_at` in the screenshot in point 2 above.

My theory is that @fuziontech replayed the WAL at some point, but since it didn't contain timezones (even if the times themselves were most likely in UTC), it threw all these errors.

I [made a PR](https://github.com/PostHog/posthog/pull/2396) that uses `.isoformat()` instead of the `.strftime()` when logging to Kafka... and re-enables sentry logging to help narrow it down. Perhaps there is some issue with React Native as originally reported, but there's too much noise from the WAL playback to effectively debug this.

If this change has unintended consequences, I can't tell. @fuziontech what for and when is this WAL used?
