### ISSUE TITLE
Session Replay — Safari's Network Inspector does not detect Fetch/XHR Response Status Codes

### ISSUE THREAD

**Issue by maramizo** [PostHog/posthog#22309]
## Bug description
There are no status codes reported on Inspector -> Network for Safari clients.

Safari:
![image](https://github.com/PostHog/posthog/assets/7774220/d7f787dd-e731-4942-bd5b-50bcb0e59221)

Chrome (expected):
![image](https://github.com/PostHog/posthog/assets/7774220/142a26cb-495c-458f-96fe-d73d668d5f80)

**Comment by pauldambra** [comment]
Hey @maramizo 

Do you have network payload capture turned on in your account?

**Comment by pauldambra** [comment]
You can check at https://us.posthog.com/replay/recent#panel=settings

![2024-05-16 01 32 14](https://github.com/PostHog/posthog/assets/984817/32e11379-ae84-4a7d-aba9-10542e831b16)

**Comment by maramizo** [comment]
No @pauldambra

**Comment by pauldambra** [comment]
So under the hood only selecting "capture network performance" uses the browser's performance observer and all the browsers have different implementations - including not always providing the status code.

If you select "capture headers" or "capture body" then we wrap fetch/xhr and no longer rely on the browser's implementation. If you turn either on then you'll capture status

I'm actually just shipping https://github.com/PostHog/posthog/pull/22310 however, since our display of the status once captured isn't quite right at the moment - so thanks for asking the question since checking meant I spotted this but

So... short version

* turn on capture headers or body to start capturing the dataa
* wait for https://github.com/PostHog/posthog/pull/22310 before we reliably display it - I'll get this in today

**Comment by maramizo** [comment]
This has indeed been fixed by that PR. Thanks @pauldambra!
