### ISSUE TITLE
Return a nicer error when inviting someone who's already invited

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#2260]
## Is your feature request related to a problem?

Right now, if you try to invite someone who's already invited (or a user) you get the following error message:
![image](https://user-images.githubusercontent.com/1727427/98357556-adff4a80-2025-11eb-9f4d-ba748155d036.png)

## Describe the solution you'd like

The server itself does return a useful error message, so we could just display that

**Comment by Twixes** [comment]
We discussed invites with @paolodamico and I think we'll solve this in a different way: since invites now expire after 3 days anyway, we'll disable this uniqueness constraint and actually remove the invites list altogether: you'll only see the link right after creating the invite, and the teammate will receive an email if possible - basically making invites ephemeral. Much simpler UX at a slight cost of functionality.
