### ISSUE TITLE
PostHog sustained load benchmarks (requests/sec)

### ISSUE THREAD

**Issue by mariusandra** [PostHog/posthog#2262]
## Is your feature request related to a problem?

In order to know make sure plugins work the way they need to, I would like to run some tests to measure how many events/sec can posthog ingest and under which configurations.

## Describe the solution you'd like

Ideally I'd like this to be an automated test, possibly even as part of the github tests, which spins up a few instances (aws? gcloud? heroku?), sets up posthog, starts sending a lot of events (e.g. with `ab`), observes how well the system is behaving (events ingested, api errors, etc) and outputs a nice looking graph at the end.

For my use case, I'd just add a few tests to the list with plugins enabled or disabled, varying their count and weight.

How to do such tests? @macobo @fuziontech pinging you two for inspirational quotes.

## Describe alternatives you've considered

Currently I see the time it takes for a plugin to run in my localhost console and can roughly extrapolate from there (0.0003sec is good, 0.01 sec is bad), yet it'd be also nice to know the lag Celery adds, etc. This also won't help benchmark if I add multithreading.

## Additional context

It would be interesting to get a maximum events/sec limit, after which postgres is just no longer a viable solution and you have to switch to EE.

**Comment by macobo** [comment]
I have been thinking on this. Some messy late-night writing up ahead.

Every testing rig I can imagine doing this in CI seems:
- quite fragile in that it will take a lot of effort to maintain as we iterate our architecture
- noisy (how to compare benchmarks against each other, how much data do you need to ingest to keep it going?)
- generating realistic ingestion data is hard. As james pointed out the other day - it's very different if you're ingesting many events per user vs few, performance will also vary according to the op being taken (identify vs setting user props vs ingesting events).
- wouldn't reflect reality. Other factors may become bottlenecks, e.g. actions, identify calls, etc.
- the generated number might not reflect what we care about: e.g. we care about how many events we're able to ingest given X$ in setup rather than time-per-event in isolation.

We have a partial solution for all of these problems already, a perfect environment we keep up-to-date, which has realistic data and always maintained metrics: **production**. However production has one tiny flaw: we try to overprovision our ingestion as not to fall behind, accumulate a backlog. Without the backlog, trying to observe the system becomes slightly messy.

So here's my proposal, if we want to do this to leverage our production setup:
- we spin up a 'parallel' production environment for either ch and/or postgres and with workers
- with the same grafana dashboards/metrics set up
- which gets deployed to automatically as new github releases are done
- most of the time it does not ingest any data
- when we want to measure it (e.g. once per day), we automatically copy last say 100M messages from our main kafka topic to it and start consuming
- we measure throughput, other metrics as it's consuming the data

We can then compare the metrics from grafana across changes and see how we do.

Thoughts? It doesn't quite achieve the same desired goal as your problem statements ('numbers for every PR') but I don't see a clear way to achieve that goal either.

**Comment by mariusandra** [comment]
Already having something manual would be cool and the solution you describe would be good enough for me.

That said, I'd also be in favour of some form of automated testing. Thinking of [graphs like these](https://web.archive.org/web/20180324190348/http://www.isrubyfastyet.com/).

**Comment by Twixes** [comment]
In the past couple of months we've decided within ingestion to rely on Cloud metrics (which are pretty robust now) rather than artificial metrics. Hence closing this.
