### ISSUE TITLE
Funnel Actors Query Fails When Funnel Has Many Steps

### ISSUE THREAD

**Issue by webjunkie** [PostHog/posthog#22999]
When creating a funnel with a large number of steps in PostHog, the funnel actors query fails to execute successfully. This issue prevents the retrieval of actor data, making it difficult to analyze user behavior through complex funnels.

**Steps to Reproduce:**
1. Create a funnel in PostHog with a significant number of steps (e.g., 10 or more steps).
2. Attempt to query the funnel actors to analyze the users who completed or dropped off at each step.
3. Observe the behavior and note any errors or failures in the query execution.

**Expected Result:**
The funnel actors query should execute successfully, returning the actors' data for each step of the funnel, regardless of the number of steps.

**Actual Result:**
The funnel actors query fails when the funnel includes a large number of steps, preventing the retrieval of actor data and hindering detailed analysis of the funnel.

https://posthoghelp.zendesk.com/agent/tickets/14256

**Comment by webjunkie** [comment]
Another one
https://posthoghelp.zendesk.com/agent/tickets/14979 (moved to PostHog: https://us.posthog.com/project/2/support/tickets/21659)

**Comment by aspicer** [comment]
Another example: [this funnel](https://eu.posthog.com/project/19486/insights/Rv9Q8JAP) based off of [this experiment](https://eu.posthog.com/project/19486/experiments/11850) won't load actors even though it shows that people have reached the later stage.

More info:
https://posthog.slack.com/archives/C0368RPHLQH/p1719540397842309
https://posthog.slack.com/archives/C0374DA782U/p1717801112677939

**Comment by aspicer** [comment]
The other issue might actual be separate - results are just odd when there's a breakdown. Keeping it separate.

**Comment by slshults** [comment]
Another in https://posthoghelp.zendesk.com/agent/tickets/14118 (moved to PostHog: https://us.posthog.com/project/2/support/tickets/17746) (Looks like they've since reduced the number of steps in [the funnel](https://us.posthog.com/project/62972/insights/hSFi7Pxt).)

**Comment by skoob13** [comment]
Another in https://posthoghelp.zendesk.com/agent/tickets/15371. (moved to PostHog: https://us.posthog.com/project/2/support/tickets/18015) There are 16 steps in the funnel.

Separate issue and moved to #23522

**Comment by aspicer** [comment]
So this looks like it's timing out, and not in a good way. If you run the following on metabase:
[`select * from clusterAllReplicas(posthog, system.query_log) where event_date = '2024-07-03' and query like '%countIf(ifNull(equals(steps, 17), 0)) AS step_17%' and query not like '%query_log%' order by event_time desc limit 10`](https://metabase.prod-eu.posthog.dev/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7InR5cGUiOiJuYXRpdmUiLCJuYXRpdmUiOnsicXVlcnkiOiJzZWxlY3QgKiBmcm9tIGNsdXN0ZXJBbGxSZXBsaWNhcyhwb3N0aG9nLCBzeXN0ZW0ucXVlcnlfbG9nKSB3aGVyZSBldmVudF9kYXRlID0gJzIwMjQtMDctMDMnIGFuZCBxdWVyeSBsaWtlICclY291bnRJZihpZk51bGwoZXF1YWxzKHN0ZXBzLCAxNyksIDApKSBBUyBzdGVwXzE3JScgYW5kIHF1ZXJ5IG5vdCBsaWtlICclcXVlcnlfbG9nJScgb3JkZXIgYnkgZXZlbnRfdGltZSBkZXNjIGxpbWl0IDEwIiwidGVtcGxhdGUtdGFncyI6e319LCJkYXRhYmFzZSI6Mn0sImRpc3BsYXkiOiJ0YWJsZSIsInBhcmFtZXRlcnMiOltdLCJ2aXN1YWxpemF0aW9uX3NldHRpbmdzIjp7InRhYmxlLmNvbHVtbl93aWR0aHMiOltudWxsLG51bGwsbnVsbCxudWxsLG51bGwsbnVsbCxudWxsLG51bGwsbnVsbCxudWxsLG51bGwsbnVsbCxudWxsLG51bGwsbnVsbCxudWxsLG51bGwsbnVsbCxudWxsLG51bGwsbnVsbCxudWxsLG51bGwsbnVsbCxudWxsLG51bGwsbnVsbCwxMTAwXX19)

there are two exceptions that crop up

- Code: 36. DB::Exception: Query tree is too big. Maximum: 2000000. (BAD_ARGUMENTS) (version 23.12.5.81 (official build))
- Code: 159. DB::Exception: Timeout exceeded: elapsed 2850.284703422 seconds, maximum: 600. (TIMEOUT_EXCEEDED) (version 23.12.5.81 (official build))

The first one we can fix, but there's really no point, because the second one is what happens to all these 17 funnel step queries. 

It oddly lets them run for nearly an hour.

It seems like the time it takes blows up exponentially for steps. Almost exactly 2<sup>n</sup>. I ran some tests on the [insight linked here](https://posthoghelp.zendesk.com/agent/tickets/15371) (moved to PostHog: https://us.posthog.com/project/2/support/tickets/18015)
10 steps: 19 seconds
11 steps: 36 seconds
12 steps: 70 seconds
13 steps: 143 seconds
14 steps: 288 seconds
15 steps: blew up (600+)

an example of the failing query is here https://posthog.slack.com/files/U07040M78VA/F07AZ8RCD0T/scratch_20.sql

**Comment by skoob13** [comment]
Another in https://posthoghelp.zendesk.com/agent/tickets/15291 (moved to PostHog: https://us.posthog.com/project/2/support/tickets/17877) for FunnelActorsQuery: the AST length exception. Log is [here](https://metabase.prod-us.posthog.dev/question/829-failing-funnelactorsquery-ast-length).

**Comment by Twixes** [comment]
+1 from ZEN-11277
+1 from ZEN-15869

**Comment by slshults** [comment]
Another here: https://posthoghelp.zendesk.com/agent/tickets/16149 (moved to PostHog: https://us.posthog.com/project/2/support/tickets/18698)

**Comment by webjunkie** [comment]
+1 https://posthoghelp.zendesk.com/agent/tickets/15970

**Comment by webjunkie** [comment]
+1 https://posthoghelp.zendesk.com/agent/tickets/16148

**Comment by RCVZ** [comment]
When can we expect this issue to be fixed?

**Comment by slshults** [comment]
+ 1 https://posthoghelp.zendesk.com/agent/tickets/17333

**Comment by MarconLP** [comment]
+1 from https://posthoghelp.zendesk.com/agent/tickets/17539 (moved to PostHog: https://us.posthog.com/project/2/support/tickets/19710)

**Comment by MarconLP** [comment]
+1 https://posthoghelp.zendesk.com/agent/tickets/18123 (moved to PostHog: https://us.posthog.com/project/2/support/tickets/20126)

**Comment by darkopia** [comment]
+1 https://posthoghelp.zendesk.com/agent/tickets/18620 (moved to PostHog: https://us.posthog.com/project/2/support/tickets/20889)

**Comment by HaynesPostHog** [comment]
+1 https://posthoghelp.zendesk.com/agent/tickets/19437 (moved to PostHog: https://us.posthog.com/project/2/support/tickets/21339)

**Comment by HaynesPostHog** [comment]
+1 https://posthoghelp.zendesk.com/agent/tickets/19516 (moved to PostHog: https://us.posthog.com/project/2/support/tickets/21435)

**Comment by MarconLP** [comment]
+1 https://posthoghelp.zendesk.com/agent/tickets/19643 (moved to PostHog: https://us.posthog.com/project/2/support/tickets/22159)

**Comment by HaynesPostHog** [comment]
As discussed, the ability to go above 20 steps now when the rollout is complete would be great!

From: https://posthoghelp.zendesk.com/agent/tickets/19669 (moved to PostHog: https://us.posthog.com/project/2/support/tickets/21785)

**Comment by HaynesPostHog** [comment]
+1 https://posthoghelp.zendesk.com/agent/tickets/19910 (moved to PostHog: https://us.posthog.com/project/2/support/tickets/22692)

**Comment by HaynesPostHog** [comment]
+1 https://posthoghelp.zendesk.com/agent/tickets/20103 (moved to PostHog: https://us.posthog.com/project/2/support/tickets/22378)

**Comment by HaynesPostHog** [comment]
+1 https://posthoghelp.zendesk.com/agent/tickets/20284 (moved to PostHog: https://us.posthog.com/project/2/support/tickets/22393)

**Comment by 0xRaduan** [comment]
Hey, just for my visibility - is there any PR in the makings to fix this? 

Want to understand, whether it's viable to just wait another week to get this fixed, or better to change my funnel altogether for less steps. 

Thank you.
