### ISSUE TITLE
Click maps without autocapture

### ISSUE THREAD

**Issue by mayeraaa** [PostHog/posthog#23640]
### Feature request

Do you have any plans to make improvements so that we can view click maps without autocapturing? We have many of our custom click events (they all start with the “click”), we would like to be able to build a map based on them.

**Comment by pauldambra** [comment]
Hey,

We don't have any plans for that... events would need to have a strict schema so that we could match them to the HTML when generating a click map.

We currently have click maps built with autocapture, heatmap built with $$heatmap events (free), and scollmaps built with $$heatmap events (free)

see docs here: https://posthog.com/docs/toolbar/heatmaps

What would click maps from custom events unlock for you?

**Comment by mayeraaa** [comment]
Got it, thanks.
How do I enable heatmap events collection (ithout autocapture)? Is it enough to enable the heatmap feature settings in the project?

**Comment by pauldambra** [comment]
Yep, that's right... [from the docs](https://posthog.com/docs/toolbar/heatmaps#:~:text=To%20start%2C%20ensure,requires%20pageleave%20events.) (to aid the future traveller arriving here)

> To start, ensure you enable the capturing of heatmap data in [your project settings](https://us.posthog.com/settings/project-autocapture#heatmaps) or with the enable_heatmaps key in the [JavaScript Web SDK initialization config](https://posthog.com/docs/libraries/js#config). Heatmap data is captured along with other events, so it doesn't contribute to your bill, but the clickmap requires autocapture and the scrollmap requires pageleave events.

**Comment by pauldambra** [comment]
i'll close this as it's not planned and I don't want the future traveller to think we're considering it 😊
