### ISSUE TITLE
Release 1.18.0 - 27 November 2020

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#2366]
## Overall priorities

- Session recording
- Plugins

### Karl & Paolo

- Session improvements #2352 #2365 #2332
- Person improvements #2353
- Deep dive retention analysis

### Eric / James G

- Retention #2228, #1936 
- Lifecycle #1209
- Separate event ingestion from rest of the app
- Move clickhouse tables around for storage (make sure we don't run out of disk)
- Migrate everything to AWS
- Log availability
- Stretch goal: event consumption in Go

### Michael & Marius

- Enable plugins on app
- Add unit tests to plugin server
- World-class documentation and dev tools
- Scheduled plugins (fun distributed locking problem?)
- API plugins (webhook -> plugin)

### Tim
- Dedicated support/Sentry/random bugfixes/random UX improvements
- Keep a log of everything you've fixed/touched

**Comment by paolodamico** [comment]
### General stuff
- Session improvements (#2352). **Rationale** (_disclaimer: absolute numbers are still pretty low to be too significant, but should give a general idea_):
    - From customer calls, session recording seems to be a game changer, but the experience is still a bit rough.
    - As a general preamble, despite this being a beta feature that requires explicit opt-in, we're seeing steady grow in active users WoW. As additional context on WAUs, this last week we had the **same number of WAUs** that watched a session recording and created an action.
    - From users that used it on week 1, 60% were retained to week 2. From the users that were not retained in the session recording feature, 50% didn't actually come back to PostHog at all this week.
- Persons improvements (#2353). **Rationale:** Related to sessions above. The new UI/UX covers more use cases related to session recording (e.g. understanding what happened when a user experienced an error, or when they completed a purchase, ....)
- Implement toolbar improvements (#2370). **Rationale**: We have several reports of bugs (most of them coming from customer calls), and from sales calls we know that users do not understand this feature unless we walk them through it. Perhaps the most important here, we don't have this feature well instrumented to capture enough metrics to be able to make a stronger decision of pushing this forward or not.
- Improve our own tracking (#1575). **Rationale:** there's still a lot of stuff we don't have good metrics on, and it's hard to make strong product decisions without reliable data on everything.
- Retention epic (#2228), most important #1936. **Rationale:** we really need this to analyze our own data and improve our own product.
- Bug #2301. **Rationale:** part of core functionality, without it the experimentation power of feature flags essentially disappears (without being able to measure, there's no point in A/B testing).
- Cohorts improvements (#2350). Don't have a very strong argument for this right now other than the reported pain points of a couple of users and that if we work on #2352 & #2353 this will ensure consistency.

### Myself
_Will only have 4 working days in the next release cycle._
- **[UX]** Pair up with @macobo to work on improving session recording playback experience (#2332 / #2129). **Rationale:** see rationale for improving session recordings above.
- Deep dive retention analysis. **Rationale:** we need to understand retention a lot better to improve it.
- Update retention docs (https://github.com/PostHog/posthog.com/issues/654). **Rationale:** in the last week 21% of active users made use of this feature (core feature), we're introducing a ton more functionality, and it'll likely be a source of questions / confusion.
- Activate billing for everyone & make sure people near the event limit are prompted to update.
- **Stretch.** #2367 / #2336 to increase internal sign ups & indirectly retention. **Rationale:** hypothesis is that users whose team members are on PostHog retain better.
- **Stretch.** Fix weekly email reports. **Rationale:** hypothesis is that this will help retention by driving users back to the product with useful & actionable stuff.
- **Stretch; Lower priority.** Docs dark version design proposal.

**Comment by macobo** [comment]
## Topics

### Session recording

Session recording has gotten a lot of buzz, I think it's time to give it proper attention and make it great.

  - Make sure all recording data is reaching us, is valid: https://github.com/PostHog/posthog/issues/2365. Note that this is likely an ongoing thing due to amount of moving pieces.
  - Update sessions views to more emphesize session recordings https://github.com/PostHog/posthog/issues/2352
  - Create a custom session recording playback experience https://github.com/PostHog/posthog/issues/2332
    - Related tickets: Back N seconds https://github.com/PostHog/posthog/issues/2131, Skip inactive UX: https://github.com/PostHog/posthog/issues/2096, Keyboard-awareness: https://github.com/PostHog/posthog/issues/2363, Better navigation within session recording https://github.com/PostHog/posthog/issues/2129
  - (Stretch) Make sure we properly delete + allow storing session data on S3: https://github.com/PostHog/posthog/issues/2142

I'd love to work together with @paolodamico on this to have some design brainpower.

### Capture endpoint stability 
- We're seeing a lot of failures in event capture endpoint. I think I would like to focus on that since that's affecting metrics + could be affecting session recording. (No issue yet)
  - Related: We should set up proper logger + log full payloads and errors if errors occur in backend. Sentry doesn't log full payloads and out payloads are large.

Don't feel too strong of an ownership here, but this seems relatively hard but high-impact work.

### Toolbar

- Wrap up suggesting data-* selectors without introducing problems https://github.com/PostHog/posthog/issues/2140
- Showing border around matching elements (carryover from this iteration) https://github.com/PostHog/posthog/issues/2143

**Comment by mariusandra** [comment]
For me:
- Continue working on the plugins. We finally landed the plugin attachments PR, yet there's still [a lot more work to be done](https://github.com/PostHog/posthog/issues/1896#issuecomment-722357290)
  - Test plugins enough to enable them on EE
  - Scheduled plugins (fun distributed locking problem?)
  - API plugins (webhook -> plugin)
  - Maybe: frontend plugins (new scenes, world map, etc)
  - Plugin dev tools and docs
- And various odds and ends as they come in...

**Comment by Twixes** [comment]
As for me, one thing I'd like to do is focus on smashing #2128, but happy to take on something else as well – TBD.

**Comment by EDsCODE** [comment]
I will do as described at the top.
- Retention epic and lifecycle
- General analytics bug swashing and filling out (the sessions analytics could be way more built on because it's very spotty in terms of graphing ability right now)

**Comment by mariusandra** [comment]
I'd also like to add these issues:
- Expo support for React Native: https://github.com/PostHog/posthog/issues/1174
- Some bug with the RN lib: https://github.com/PostHog/posthog-react-native/issues/1
- Plus the RN timezone issue if it's still an issue: https://github.com/PostHog/posthog/issues/2173

**Comment by paolodamico** [comment]
Closing as this has been released
