### ISSUE TITLE
A lot of things are wrong

### ISSUE THREAD

**Issue by aejuice-github** [PostHog/posthog#23875]
## Is your feature request related to a problem?

*Please describe.*

## Additional context

No comparison to the previous period in web analytics and funnels.

AB tests do not display people that were in A and B separately. Let's say I want to view all recordings, I have to look for each person separately.

You write on the graph "Previous" period but it is not specified what "previous" period is. Is it previous day, week, month, year?

AB Test has no metric revenue per user. 

### Debug info

```shell
- [ ] PostHog Cloud, Debug information: [please copy/paste from https://us.posthog.com/settings/project-details#variables]
- [ ] PostHog Hobby self-hosted with `docker compose`, version/commit: [please provide]
- [ ] PostHog self-hosted with Kubernetes (deprecated, see [`Sunsetting Kubernetes support`](https://posthog.com/blog/sunsetting-helm-support-posthog)), version/commit: [please provide]
```

**Comment by aejuice-github** [comment]
Impossible to make a step optional in funnels, it makes the entire funnel feature useless.

Usecase: ecommerce add to cart, buy now button. Buy now bypasses the cart directly to checkout. 

Impossible to create cohort with repeat purchasers because it is impossible to set up 2 or more "purchase" events.

**Comment by pauldambra** [comment]
Hey @aejuice-github 

A github issue isn't the right forum for this I think since these are questions on how to use the platform.

> 1. Impossible to make a step optional in funnels, it makes the entire funnel feature useless.

it's a relatively frequently requested feature but you can use funnels without it :) At the moment you can manually work around this by creating multiple funnels, although only a workaround.

> 2. Impossible to create cohort with repeat purchasers because it is impossible to set up 2 or more "purchase" events.

I don't follow this, would be best to run through the in-app support flow and add more detail here https://us.posthog.com/#panel=support%3Asupport%3A%3Alow%3Atrue

> 3. You write on the graph "Previous" period but it is not specified what "previous" period is. Is it previous day, week, month, year?

yep, exactly that. by default it's whatever period the graph covers. recently we added the ability to choose a custom period instead

<img width="295" alt="Screenshot 2024-07-25 at 08 39 59" src="https://github.com/user-attachments/assets/ca55e5f1-4d11-4bb6-bff1-dd26b256dfac">

> 4. several questions about A/B tests

would be great to follow-up via support https://us.posthog.com/#panel=support%3Asupport%3A%3Alow%3Atrue again those look specific to how you're using A/B testing (obvs could be wrong) but if we lump all these issues together here we're not going to make progress helping you :)
