### ISSUE TITLE
Provide API for opting out (and respect DNT headers)

### ISSUE THREAD

**Issue by kasbah** [PostHog/posthog#247]
**Is your feature request related to a problem? Please describe.**
I'd like to let users opt out of analytics easily.

**Describe the solution you'd like**
- Provide API endpoints to query if the user is tracked and opting out
- Add option to respect do not track (DNT) headers (user will never be tracked and API response would reflect that)

**Comment by jamesefhawkins** [comment]
Thank you for this suggestion!

Respecting DNT headers is something we would definitely accept as a PR and should be on the roadmap. That'd help PostHog maintain user privacy.

To clarify, when you say
> Provide API endpoints to query if the user is tracked and opted out

Is what you mean that then if DNT headers are sent, then we would need some way of identifying that particular user is opted out via API? I'd love a little more context on the use case you had in mind.

**Comment by kasbah** [comment]
Sorry, I think I shouldn't have lumped these two requests together into one issue. The main thing I'd like is to have an API that will let me make an opt-in/opt-out dialog on my website (maybe this already exists but I haven't found it). 

Something like:

```
GET /user/tracked -> null

POST /user/tracked?opt=in

GET /user/tracked -> true

POST /user/tracked?opt=out

GET /user/tracked -> false
```

The DNT is only somewhat related in that I think it's actually a nice solution for people who set DNT never to have to see a dialog; so it'd be nice if Posthog was smart enough to reflect that in the API and have the option to return `false` if user has DNT set in our example API above. 

Even more amazing would be if it could detect if it was blocked by uBlock etc. and behave as if DNT was set (that's more of a "[and a pony](https://blog.codinghorror.com/and-a-pony/)" request though)

**Comment by timgl** [comment]
The JS library already has a `opt_out_capturing()` which should satisfy this usecase :-) I've updated the docs to reflect that here:
https://github.com/PostHog/posthog/wiki/JS-integration#opt-users-out

RE: DNT, it's a spec that's still under discussion. According to W3, it's meant for 3rd party tracking. We specifically designed PostHog to be first-party (hence the self hosted), which is why  DNT doesn't apply. See https://www.w3.org/2011/tracking-protection/drafts/dnt-for-users.html for more.
