### ISSUE TITLE
Organization settings appear blank for a non admin user (I think)

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/posthog#2646]
## Bug description
<img width="1600" alt="Screenshot 2020-12-03 at 10 42 10" src="https://user-images.githubusercontent.com/47497682/100999114-3e14af00-3554-11eb-9d6e-498842021d9b.png">

I suspect this is because of the permissions that I have (although I can't see them).

## Expected behavior

I'd expect either not to see these at all or _better_ for it to allow me to request admin access and then to alert the admin users to help get me unblocked if I'm trying to achieve something.

**Comment by yakkomajuri** [comment]
How did you get to this page though? You must have typed it in?

**Comment by paolodamico** [comment]
This is only happening in the new navigation (only rolled out to PostHog users), closing this issue as it's already recorded in #2545. For context this happens when clicking on Organization settings in the top right corner, fortunately it's not a permissions issue, it's just a navigation bug that we need to address before releasing `navigation-1775`.
