### ISSUE TITLE
Session loading takes a lot of time even on small databases

### ISSUE THREAD

**Issue by mlnkrish** [PostHog/posthog#2739]
## Bug description
When switching to the sessions tab. It takes a lot of time to load the session (~20s)

<img width="1440" alt="Screenshot 2020-12-11 at 1 26 19 PM" src="https://user-images.githubusercontent.com/95013/101877959-cc241180-3bb4-11eb-8561-1bed8e93edd2.png">

<img width="1437" alt="Screenshot 2020-12-11 at 1 28 15 PM" src="https://user-images.githubusercontent.com/95013/101877934-c5959a00-3bb4-11eb-8828-f4fb682f9d74.png">

## Expected behavior
Sessions should load faster

## How to reproduce
1. Switch to the sessions tab

## Environment
- PostHog self-managed
- PostHog version/commit - latest from docker. commit src - e7cf836d59a6f2af031a89a4b5efc9901baa6b5a

**Comment by jareddr** [comment]
Hello, I wanted to add onto this report as I'm experiencing the same problem only my sessions page simply never loads after I've collected some number of sessions during the day.  Please let me know if there is a better way to corroborate this report.

I get this response from the backend `/api/event/sessions/?date_from=2020-12-31&date_to=2020-12-31&offset=0&distinct_id=&properties=%5B%5D`

```
Error: Server Error
The server encountered a temporary error and could not complete your request.
Please try again in 30 seconds.
```

For scale reference, it looks like I've had around 30,000 sessions:
`select count(distinct distinct_id) from posthog_event where "timestamp"::DATE = DATE '2020-12-31';`
Result: 30,742



### Environment

- PostHog self-managed (Kubernetes deploy via Posthog helm charts, using a Cloud Postressql server that's at 20% load. I have my web and worker pods & node pools set up to auto-scale)
- PostHog version - "You're on version 1.19.0 of PostHog. This is the newest version."

**Comment by macobo** [comment]
Some optimizations have landed: 
- https://github.com/PostHog/posthog/issues/2848
- We now index session recording events in a better way.

The remaining slow query is the main sessions query + loading elements chain. On my own self-hosted instance it takes ~20s to load sessions page and it takes much much longer for larger instances.

There's several things which make it slow:
1. The amount of data returned (all events + all elements + all sessions). 
1. At larger end of things, it ends up sorting several gigabytes of data on disk 4-5 times. See query + plan for a larger user here: https://gist.github.com/macobo/7b5b00a89ddadd92d384942bfd78db5a

Some thoughts on what we can do going forward:
1. Load events for sessions asynchronously. This would speed up the query since we download less data (and events data here can be many megabytes) as well as being able to avoid populating elements chain which takes several seconds on larger instances as well. 
2. Try to optimize the query - I think we might be able to cut down some of the extra sorting down quite a bit. However this would not really help large users (e.g. with 500k+ daily events) as the sessions query needs to group everything into sessions in expensive ways.
3. Add background processing: We could add a task which calculates sessions in the background, storing them in a separate table. Effectively this would mean running the sessions query in a loop in the background, as we do with cohorts.

cc @timgl @EDsCODE @fuziontech for your thoughts - 3 would definitely speed up sessions both on cloud and self-hosted, making it usable at larger scale and making https://github.com/PostHog/posthog/issues/2595 stronger. Tradeoff is however extra complexity building it + making sure it keeps working.

**Comment by timgl** [comment]
I thought of a stupid optimization, feel free to ignore. Why don't we just get 100 unique distinct ids, ordered by timestamp desc. Then just calculate sessions for those 100 distinct ids. Should give the exact same result but should be way way quicker.

**Comment by paolodamico** [comment]
From a UX perspective and today's design, I would advocate for **not** loading all the events list in the initial sessions load, it's quite acceptable to wait a bit when expanding a row to load the session details. I also suspect (don't have my computer to verify), that not a lot of people expand the events list. 

**However**, based on the new sessions page design where the rationale is providing a ton more useful information to the user at a glance, I would try to avoid option 1 if possible.

**Comment by macobo** [comment]
@timgl could work. Not sure how that would work when you load more sessions though. 

But generally doing the processing in stages (e.g. get recent users => then query sessions) + sorting sessions by end time instead of start time could speed things along for sure! pagination remains a pain when constructing sessions dynamically this way.

@paolodamico Good points. For top events - it might make sense to again to solve this with (3 - background processing) and include the top events in the session summary.

**Comment by macobo** [comment]
I did some experiments and could get the aggregation down on my local instance from ~18 seconds to ~1.5 by doing the aggregation in python, not loading events + properties themselves and using server-side cursors in clever ways. 

This works since the current SQL is doing a ton of sorting which is not really needed [(see this query plan)](https://gist.github.com/macobo/7b5b00a89ddadd92d384942bfd78db5a) - instead, traversing events from last to more recent + hash table is enough. 

Here's the POC code: https://gist.github.com/macobo/0750fd1aeed854b4b1ebf7f242f9e8ed

The downside here is that pagination is tricky. I couldn't find a way to do this efficiently within postgres without introducing pl/pgsql or some other language - but pl/pgsql lacks hash tables and pl/perl might not be installable in all environments (RDS supports it but not e.g. postgres:alpine docker image)

Clickhouse doesn't need this since offsetting doesn't require extra sorting there + it handles IO much better so the extra inefficiency would be offset by the network cost of sending data to python.

**Comment by macobo** [comment]
The optimizations have landed! :heart_eyes_cat:
