### ISSUE TITLE
`Text` property not being set on $autocapture

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#2821]
## Bug description

We have a PostHog property called `Text` (description: _The inner text of the element._). However the property is no longer being set on autocapture events. This is happening both in Postgres and Clickhouse.

## Expected behavior

The property should be set on autocapture events that have text contained.

## How to reproduce

- You can go to [properties stats](https://app.posthog.com/events/properties) and see the property is not even listed (zero volume in the last 30 days.
- You can also see [this action](https://app.posthog.com/action/3104) that shows no events (all time). To be certain, you can go to our main home page and click on the FAQ link in the footer.

## Environment

- [X] PostHog Cloud
- [X] self-hosted PostHog, version/commit: `master`

## Additional context

Reported by [user](https://posthog.slack.com/archives/C01C93MSLBU/p1608237200002800). This user needs to be able to filter text using contains and regex expressions (because differences such as pluralization), and therefore cannot use the general text filter (the one with the checkboxes).

**Comment by macobo** [comment]
Note: From looking at the stats I think this has never worked: https://app.posthog.com/insights?interval=day&display=ActionsLineGraph&actions=%5B%5D&events=%5B%7B%22id%22%3A%22%24autocapture%22%2C%22name%22%3A%22%24autocapture%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%2C%22properties%22%3A%5B%5D%7D%5D&new_entity=%5B%5D&date_from=all&properties=%5B%7B%22key%22%3A%22text%22%2C%22value%22%3A%22is_set%22%2C%22operator%22%3A%22is_set%22%2C%22type%22%3A%22element%22%7D%5D

A naive fix here should not be too hard, but what do we expect the semantics to be re capturing text from inputs/selects or otherwise sensitive elements?

**Comment by paolodamico** [comment]
Well aren't we capturing this information already? Because on the events table you see something like "clicked button with Get Started text". This would still be a matter of using the `ph-no-capture` flag to not capture this stuff.

**Comment by macobo** [comment]
cc @yakkomajuri - probably worth picking up for extensibility team

@marcushyett-ph recently ran into this analyzing our docs usage
