### ISSUE TITLE
Release 1.20.0 - 18 January 2021

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#2842]
From last time (some of this may have been finished or not relevant anymore, lmk):

Context to decide what to work on:
- We have customers waiting for things like BigQuery and Snowflake integrations, which will require plugins to work
- We've had a few outages and in general CH performance has been lagging. We have a plan for a lot of this

Eric/Tim:
- ~Caching clickhouse #2855 ~
- ~Fixing queries, make sure funnels are quick~
- ~~Finish backend filter refactor~~
- Engagement overview
- Good error messages for timeouts (ie push to upgrade instance or contact support)
- Filter typing for frontend
- ~Consistent backend tests #2754~

Marius/Michael:
- ~~[Plugin Storage](https://github.com/PostHog/posthog-plugin-server/issues/74)~~
- Reach out to plugin users
- ~~Add Yakko's plugins to official repo~~
- ~~Touch up plugin server Kafka consumption – PostHog/posthog-plugin-server#85~~ + merge Kafka production – PostHog/posthog-plugin-server#34
- Then, improving dev experience is a great idea:
~~PostHog/posthog-plugins#2~~, PostHog/helloworldplugin#1, ~~PostHog/posthog-plugin-server#13~~, ~~PostHog/posthog-plugin-server#64~~
- ~~Rename PostHog/posthog-plugin-server#86, PostHog/posthog-plugins#1, PostHog/plugins#2 ?~~
- ~~Marius interim Chief Support Officer~~
- Make sure we have great metrics from inside the server

James G
- Performance optimization CH
- Get the CH tables distributed
- Automate above
- Migrate stuff off of Heroku
  - Plan for moving of Postgres
- Stretch goal - feature flags: Swift and Android

Paolo
- (see comment)

Karl
- Postgres sessions speedup
- Create new filtering UI for session recording
- Less priority:
  - Roll out rageclicks, segments support etc with new UI
  - Make jumping to point-in-time better
  - Improve both player sessions UX

**Comment by mariusandra** [comment]
The [plugins project](https://github.com/orgs/PostHog/projects/4) contains a few small things that I'd personally like to get in this release:

1. [Plugin Storage](https://github.com/PostHog/posthog-plugin-server/issues/74) --> a simple persistent postgres-backed json storage. We have the redis cache, but that can go *poof* at any moment. This is mostly needed to just store state for scheduled plugins, for example to keep track of "last imported user/date" for the github stars plugin.
2. Read plugin config from code --> Yakko made [a bunch of cool plugins](https://github.com/PostHog/plugin-snippets) and had to write this: "When the editor opens, paste the contents of the plugin.js file under 'Source Code' and the contents of config.json under 'Config Schema JSON'" for all of them. It should be possible to just copy one block of code and be done with it.
3. Add all Yakko's plugins into the official repository. Also add the github stargazers plugin and the google bigquery plugin.
4. API access inside plugins --> Echoing [James's wishes](https://github.com/PostHog/posthog/issues/1896#issuecomment-741729478), allowing full API access (e.g. to add new annotations, query insights, etc) from within a plugin opens up a lot of possibilities. Yakko managed to [get this working](https://github.com/PostHog/plugin-snippets/blob/master/gitlab-release-tracker-plugin/plugin.js#L64) by just `fetch`ing and requiring the user to copy an API token from one box inside posthog (setup) to another (plugin config). That's awkward. Just like `posthog.capture` "just works", so it should be possible to easily query the API.
5. Maxmind plugin update --> It should be possible to just upload the compressed `.tar.gz` file, instead of the extracted ~70MB db file that's in the archive. Heroku times out with such a large file for example.

The above is about a day of work for me I'd imagine. For the rest, I would propose that either I'm the support+bugfixes person for this sprint (would be great to get back into other bits of the product)... or then I'd put in a lot of effort to really improve the plugins interface (better dev experience, running tests on plugins with fake events from the interface, etc) and write many other sample plugins. Plus fixing/refactoring whatever is needed.

In addition to the above, I'd love it if Michael could finish up the Kafka and JS ingestions bits.

**Comment by Twixes** [comment]
1. I'll touch up plugin server Kafka consumption + merge Kafka production:
    PostHog/posthog-plugin-server#85, PostHog/posthog-plugin-server#34
1. We'll then check how that is functioning and if anything else needs to be done for *Plugins on Cloud*.
1. Then, improving dev experience is a great idea:
    PostHog/posthog-plugins#2, PostHog/helloworldplugin#1, PostHog/posthog-plugin-server#13, PostHog/posthog-plugin-server#13, PostHog/posthog-plugin-server#64
1. And I'd rename some things tbh 🤔:
    PostHog/posthog-plugin-server#86, PostHog/posthog-plugins#1, PostHog/plugins#2

**Comment by paolodamico** [comment]
## Retention Stuff (@paolodamico)

### General
* ~Wrap-up personas profiles, and derived product strategy changes [from last 2020 week].~
* ~Work out key instrumentation and finish implementation (#2787, #2811)  [from last 2020 week]. _Rationale:_ “If you can’t measure it, you can’t improve it.”~
* ~General retention strategy~

### Analyses
* ~Dormancy/churn analysis. How many users are churning after being retained for several weeks. Why? _Rationale:_ Will help determine how much impact will resurrection / and dormancy-prevention strategies will help improve retention.~
* Post-activation retention. How does retention change after a user is _activated_ (definition TBD)? _Rationale:_ Will help determine how will improvements in the activation process will improve retention.
* ~Lifecycle / Quick Ratio analysis. _Rationale:_ Will give an overall health check on our user base, make sure we're _losing_ a healthy amount of users per active user added.~
* Competitors / overlapping products deep dive. _Rationale:_ Good to keep an eye out for what other projects / companies have done to understand better how we can improve our own product.
* Engagement overview. Will probably need @EDsCODE's help here. _Rationale:_ We need to understand the engagement levels of our users as it's a key input for retention. In addition, we could have very healthy/terrible levels of engagement that hide from a retention final output metric.

### Experiments
These are some changes/improvements we can implement to gauge retention impact, and understand better where to dive further.
* Enabling & showcasing session recording on onboarding.
* After ingestion process, adding more instructions / simple tutorial to key pages (like we have for the actions page).
* Related to retention too, I would like to **pair up** with someone to work in a very, very basic (MVP) alerting / EWS feature as an experiment to see if it can help drive retention (e.g. getting an email if a basic metric [like $pageviews] falls outside a certain threshold range). My hypothesis is that this will help drive engagement (and therefore increase retention).
* ~Adding bookmarklet to the onboarding flow.~

### Other stuff
Stretch priorities?
* Would like to pair up with someone (maybe Cory and someone else) to work on designing #2760
* Release usage-based billing for new users. We'll need changes to the website too.

## General Team Priorities
Things that can either improve retention or are blocking us to measuring/improving our own retention.
* #2833. Very easy to get confused when doing retention without this.
* Retention cohorts graph (graph each cohort).

**Comment by EDsCODE** [comment]
clickhouse caching can be added to the core list for tim/eric

generally, want to improve the analytics experience for ourselves. Potentially working with Paolo to first manually dig up metrics to get a base level of understanding and then continue building out the analytic variants (such as the retention points mentioned above)

**Comment by macobo** [comment]
Session recording main things:
- Postgres sessions speedup
- Create new filtering UI for session recording

Less priority:
- Roll out rageclicks, segments support etc with new UI
- Make jumping to point-in-time better
- Improve both player sessions UX
