### ISSUE TITLE
Show properties from the person's initial event in their person properties

### ISSUE THREAD

**Issue by Twixes** [PostHog/posthog#2866]
## Is your feature request related to a problem?

The circumstances of how the user first got to your app/website are potentially valuable information (e.g. date of first event, IP address, location), but currently require searching through events. This should be visible right away on the person's page. Currently `posthog-js` sets `$initial_referrer` and `$initial_referring_domain` from the client, but we could do more, also server-side.

## Describe the solution you'd like

Select properties from the person's initial event should be added to them as person properties, so that they're readily accessible and visible on the person's page.

Inspiration from Heap:

<img width="255" alt="Screen Shot 2021-01-06 at 10 19 58" src="https://user-images.githubusercontent.com/4550621/103776879-60588b80-5030-11eb-8a1e-69c0f07e3fa0.png">

## Additional context

Requested by a user, who are ditching Heap due to cost and found this to be a useful feature.

**Comment by paolodamico** [comment]
Didn't see this before, definitely +1

**Comment by paolodamico** [comment]
For reference, attaching a screenshot from what another product (Heap I believe) does to support this, gracefully donated by a user.

![image](https://user-images.githubusercontent.com/5864173/105430904-34d1c580-5c1a-11eb-9b4a-bd10cc874ac5.png)

**Comment by akbansa** [comment]
This would be super helpful!

**Comment by mariusandra** [comment]
This has (almost) landed! It will work only when you're using ingestion via plugin server: https://github.com/PostHog/plugin-server/pull/214 ... and once the `0.11.0` version is added to this repo (autobump failed due to some CI bug, will be fixed soon).

Still to do: the `$` properties could get a 🦔 and some text cleanup:
![image](https://user-images.githubusercontent.com/53387/109289999-56305d80-7827-11eb-8502-8a40f0f8b897.png)

**Comment by timgl** [comment]
Yep I'll pick that up next!

**Comment by Twixes** [comment]
All this works now.
