### ISSUE TITLE
Insights custom icons

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#2905]
## Is your feature request related to a problem?

Related to #2899 and as we create more types of insights, we could use some custom icons that help users quickly identify each type of insight.

## Describe the solution you'd like

It'd be pretty cool if we had icons to add next to each insight title (as we already have for funnels & retention),

<img width="726" alt="Screenshot 2021-01-09 at 11 45 20 AM" src="https://user-images.githubusercontent.com/5864173/104104866-3d1c1f00-5270-11eb-9504-b1c3a3f7d892.png">

## Describe alternatives you've considered

Show only titles with no icons.

**Comment by corywatilo** [comment]
It feels a bit busy if there are icons and keyboard shortcuts also enabled. Let's backlog this until we have the Senior Product Designer role filled and see what they think.

![image](https://user-images.githubusercontent.com/154479/116854015-02464a00-abc5-11eb-93ef-eb47c5139446.png)

**Comment by paolodamico** [comment]
I agree! Though there are other places where these icons would be highly relevant (e.g. home page, docs, ...) still, but I'm okay backlogging this.

**Comment by sankalpdomore** [comment]
Adding a gist of our conversation from our Slack conversation @paolodamico : 

Keeping the local shortcuts visible all the time makes it harder to try adding icons for Insight tabs which is already busy (as suggested by @corywatilo as well). I think it's much easier to read labels if it's not being followed after an icon in a horizontal-based layout. Adding a few variations with/without icons and shortcut labels to illustrate what I mean:

### Current implementation: Tabs only with local shortcuts

The current implementation makes the section a bit busy.

<img width="1440" alt="CleanShot 2021-05-11 at 21 13 36@2x" src="https://user-images.githubusercontent.com/18334593/117848273-c6844200-b2a0-11eb-9c4b-3e87fdc56d43.png">

### V1: Tabs without the local shortcuts and icons
As a part of this, I was thinking If we remove the local shortcuts and tie it with "G" shortcut, it might make the section less busy

<img width="1439" alt="CleanShot 2021-05-11 at 21 14 12@2x" src="https://user-images.githubusercontent.com/18334593/117848256-c1bf8e00-b2a0-11eb-88e9-3fc529a4f5e8.png">

### V2: Tabs only with icons

Removing local shortcuts from the view makes room for icons. Although it looks cool visually, the section still gets heavier and the labels are harder to read because of the icons being in front of them.

<img width="1440" alt="CleanShot 2021-05-11 at 21 14 56@2x" src="https://user-images.githubusercontent.com/18334593/117848313-d00daa00-b2a0-11eb-9a0a-782341f6b28c.png">

### V3: Tabs with local shortcuts and icons

This is a mixture of V2 and current implementation. This is a big no in my opinion as the labels are now completely lost while being sandwiched by the icon and the local shortcut label - making it super hard to read. This variation also leaves less room for another tab to be added in the future for screen size of 1440px or lesser.

<img width="1440" alt="CleanShot 2021-05-11 at 21 09 33@2x" src="https://user-images.githubusercontent.com/18334593/117848334-d6038b00-b2a0-11eb-9c6d-478132c36d28.png">

## Conclusion (my opinion)

Adding icons into tabs doesn't seem like a good idea with the current setting where the local keyboard shortcuts are ever-present.

**Comment by paolodamico** [comment]
I agree with the comments here, let's not add icons to the tabs for now. However, I do still think the icons would be helpful for other places. For instance, the home page.

**Comment by paolodamico** [comment]
We now have custom icons for insights and further are used in a different way.
