### ISSUE TITLE
Feature flag log

### ISSUE THREAD

**Issue by Twixes** [PostHog/posthog#3073]
## Is your feature request related to a problem?

Feature flags are made to be configured and toggled. It's crucial to know what state the feature flag was in at which time, for the record. Currently there's no way to check that in PostHog.

## Describe the solution you'd like

Every time a feature flag is materially edited (in practice: anything changed, besides the display name), the edit should be saved to a viewable log. It should be noted who made the change and when, and what changed exactly should be highlighted (e.g. don't show all filters if only the feature flag key was updated).

Extras:
* ability to roll back with one click
* edit note – the why

## Additional context

We've noticed the need for this internally within PostHog, but this is also a user request.

**Comment by weyert** [comment]
Great! I am wondering if we could use one of the `audit trail`-plugins for Django to keep the audit trail?

**Comment by weyert** [comment]
Maybe having a webhook when a change happens would be nice to have to so then we could hook into it and store it somewhere on our side to adhere to any compliance requirements.

**Comment by nickponniah** [comment]
+1 for this feature. Regulated institutions all around the world require logs to be kept for defined periods of time (anywhere between 1-25 years) so that user actions can be re-constructed if something goes wrong. This requirement is particularly relevant to businesses who operate in the Finance and Health industries. A feature like this would help greatly for forensic purposes.
