### ISSUE TITLE
Make SMTP not set up warning more obvious when creating invite links

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/posthog#3114]
## Bug description

I sent a team invite to a user to playground.posthog.com, but it didn't arrive _and_ wasn't in their spam. [See the thread.](https://posthogusers.slack.com/archives/G01L806CX44/p1611826653006400)

However, it transpires that's because SMTP wasn't set up, but I'm not the person that deployed this so didn't realize I should have checked there

There is a warning in place, but I just missed it as I was focussed on the form - this type of UX is very common and so it's unusual for no email to get sent to a user immediately (which is unavoidable because of how we deploy). Perhaps a pop up warning or something in red instead?

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

**Comment by yakkomajuri** [comment]
There is an alert there though 
<img width="507" alt="Screenshot 2021-01-28 at 10 19 25" src="https://user-images.githubusercontent.com/38760734/106123891-671b7f80-6152-11eb-9487-72cb80a6c4ab.png">

**Comment by jamesefhawkins** [comment]
Sorry, my mistake. I just literally didn't read this as I was rushing to send this out. I think we should probably make that warning red for morons like me!

I've updated the issue above to clarify.

**Comment by paolodamico** [comment]
It got me too for a couple of mins at some point and I participated in creating the alert. Two approaches come to mind,

a) Perhaps do something like "We will not send an email automatically" in bolded red text before the current warning. 
b) Intuitively if we're typing an email is because we expect the invite to be sent, so I think the best way to avoid this would be not to ask for an email if we cannot send the invite email. Hate going back (and having two very different flows), but from a UX standpoint I think this is what makes the most sense, as option "a" is just a stronger patch.

**Comment by timgl** [comment]
Agree with 'no email' approach. It is also confusing as if you enter a different email it won't allow you to create the account which has caused confusion before. I think if the email _is_ set (if there's SMTP) we should just pre-fill it rather than ask for it again

**Comment by paolodamico** [comment]
Oh definitely! The migration of the team signup to React already includes pre-filling the email.
