### ISSUE TITLE
Migrate login & account signup to new design/component

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#3339]
## Is your feature request related to a problem?

Following #3300, the regular signup screen and login page are out of sync with the new design and components. Further, the login page is still a Django static page.

## Describe the solution you'd like
We should now migrate the regular signup screen and the login page to the new components/design.

Additionally we should improve the overall UX of invites as suggested on point 4 of @Twixes review from #3300 to only show login or signup (respectively) when accepting a user invite.

## Describe alternatives you've considered
Keep everything as is.

## Additional context
The `LoginSignup.tsx` already introduces some preparations to support these new screens/flows.

**Comment by corywatilo** [comment]
## PostHog Cloud signup page (wireframe)

This would be the page a user visits after clicking "Get started" on posthog.com. This will unify the experience between the website and signup page and push users to sign up for PostHog Cloud, while still making the options available for self-hosting.

_**Note:** This is a wireframe, not a full hifi design_

![Signup_Compact](https://user-images.githubusercontent.com/154479/108094535-ebc03600-704c-11eb-9a59-495b10af8a99.png)

**Comment by timgl** [comment]
Potentially super unhelpful drive-by comment but when I saw this I thought "ah this is a 'sign up to a demo/chat with salesperson' type form". I think it's because most of those look like this, whereas signup forms are more central and the form blends in more with the rest?

**Comment by corywatilo** [comment]
Comparison with other signup pages in our general category:

### He@p

![image](https://user-images.githubusercontent.com/154479/108094736-1e6a2e80-704d-11eb-91ea-853fa1ae7e06.png)

### Mixp@nel

![image](https://user-images.githubusercontent.com/154479/108094796-32159500-704d-11eb-88fe-3a5ef83feb98.png)

### @mplitude 

This one is sort of cool because it looks like it drops you _directly_ into the product.

![image](https://user-images.githubusercontent.com/154479/108094907-4a85af80-704d-11eb-9a9d-4dc5067d3762.png)

**Comment by corywatilo** [comment]
@timgl It may be the white background that makes it look too much like a lead form? Here's a version without the white box which actually does feel a little more natural to me. Thoughts?

![Signup_Compact less form-looking](https://user-images.githubusercontent.com/154479/108095672-1fe82680-704e-11eb-8313-526a75921889.png)

**Comment by Twixes** [comment]
This is is a sleek layout. One thing I'm missing is content in the top bar, particularly I think Sign in would best be always present there.

I think the feeling Tim got was because there's no clear separation between website and the app + the white sheet style looks salesy. Somehow out of these examples (BTW, [here's Amplitudes most equivalent signup page](https://amplitude.com/get-started), it's less in-app than the demo one), Mixpanel looks the clearest to me, though it's not the most elegant. My theory is the right side having a completely different background just makes for a feeling "here ends the marketing and starts the actual product". Dunno!

There are a few considerations that we should include:
- Social auth buttons need to be as prominent as our "in-house" Create account.
- The account creation part (right side) should be pluggable in the app into a flow intended for users joining existing organizations (both on Cloud and self-hosted).

**Comment by paolodamico** [comment]
Major things I think someone has already beaten me to it:
- My first thought was the same as @timgl, like this is a demo form, not signing up for an account.
- I also agree with @Twixes that social login should be as prominent (if not the main option) as password signup. It's faster and easier for users to do social login, and we've even talked about fetching more data (with user's consent) to help them invite their teammates faster.
- In a general sense, I like @lottiecoxon's [approach](https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf/PostHog-App?node-id=1444%3A10954) a bit better, feels like a less steep step between website and app, because the design looks more like the rest of the app. It is also more consistent with the new invite signup and with the login (once we implement it), and it's clear your signing up in the app.
    ![image](https://user-images.githubusercontent.com/5864173/108100923-2ecdd980-704c-11eb-9925-05b65bb597e9.png)

**Comment by Twixes** [comment]
This design above looks definitely less polished to me than the one up top by @corywatilo, but I really like how it says "now you're really entering PostHog"

**Comment by corywatilo** [comment]
> Social auth buttons need to be as prominent as our "in-house" Create account

Is this set in stone? I understand the potential benefits of having users auth through a provider, but there are a few reasons why I reduced their prominence here, based off my experience in designing for B2B SaaS:

- Many users, especially in our target market, don’t typically trust their authentication for sites with a 3rd party provider. It works well for DTC/B2C, but it's a very different world from B2B. Plus they'd prefer to not be dependent on a 3rd party to sign in.
- It causes challenges signing in when people can’t remember which method they used to sign up, which translates to more support tickets. (And depending on how security-conscious we are, we may not be able to display a message telling you which method you used to sign up.)
- It makes what can be a pretty simple form into a much larger decision point
- @jamesefhawkins also brought up the potential of supporting SSO. One more thing to add to this page!

**Comment by paolodamico** [comment]
Certainly not set in stone and great points @corywatilo. Let me get and bring some numbers to the conversation to better help the decision. 

* I definitely thing that sooner or later will bring on SSO so we might as well consider it. 
* I would argue that a lot of startups aren't too privacy-conscious to worry about using third-party sign on, particularly if you use Google (example) as your company tool (which also is true for a lot of companies). We've actually seen the opposite case with current customers, not only wanting to do Google sign-in but wanting to enforce it for all the users in their team. 
* My thought is that if you get to the login page and don't remember which mechanism you used, you'll probably try social logins first if your company uses them. This would work great because even if you didn't use the social login to sign up, if the email address matches the one file you'll be able to log in. As an extra safety mechanism here we could maybe include some information in the password reset email on whether you have an account with that email address and if you have a password set or not. 

Thoughts ?

**Comment by fuziontech** [comment]
I think what makes this look like a sales page is that it has 4 form fields. If you drop that to two like Email and Password and then have a follow up page that asks for account details like name, org, etc it would feel more approachable. It also lowers the friction to get people to take that first step. This would also make social auth easier since we won't need the email + password with social auth, but will still need to collect the other information like organization name etc.

**Comment by corywatilo** [comment]
Ya @fuziontech nailed it.

Without taking into account any of the other feedback yet, here's an updated form with only the essential fields.

![Signup_Simple v2](https://user-images.githubusercontent.com/154479/108153388-0f18ce80-70a9-11eb-9c86-ac691f16b75d.png)

I do also @lottiecoxon's layout - definitely not opposed there. The one thing it's missing though is the info about Private cloud and Open source. I'm not planning to keep the modal with the three options that exist today - I don't want to force a decision there. The _Get started_ button will link straight here, with the main path being PostHog cloud, while still touching on the self-hosting options.

I think next step is to lock down:

1. Required form fields
2. How we present the alternate signup options
3. General copy, supporting a user signing up

Once we have that, we can drop that into either layout fairly easily.

**Comment by corywatilo** [comment]
@paolodamico Are we able to limit the form fields on the signup page to _only_ email/pass on the initial screen like in my wire above?

**Comment by paolodamico** [comment]
Sorry for the late reply here @corywatilo, definitely can do!

FYI, some quick improvement I was planning to do in the meantime while we figure out the best design is to move the login and regular sign up to the same component we use for the invite sign up.

**Comment by corywatilo** [comment]
Idea for blending the two styles:

![image](https://user-images.githubusercontent.com/154479/109453877-13d27080-7a21-11eb-9016-693c59b1c56c.png)

**Comment by kpthatsme** [comment]
> Idea for blending the two styles:
> 
> ![image](https://user-images.githubusercontent.com/154479/109453877-13d27080-7a21-11eb-9016-693c59b1c56c.png)

I _think_ we'd want this to be email instead of first name for the required piece of info?

Love the ideas about reducing friction – I do think we could move to a single form input of email only, but I wouldn't say it's a p0 to getting this out. We can always run it as a future iteration. If the email already has a password set, we ask them to login. If they don't have one set we take them into the app and send them an email asking them to verify their email + set their password.

Overall though I think this is a good direction, most important pieces to me will be to make sure we're tracking the impact of this new flow and aren't adding any unnecessary friction or decision points where they aren't needed, which I think this flow does a good job of. 

It might be nice to highlight the social logins a bit more, but once again that's a call we can make based on how folks are interacting with this new flow.

**Comment by corywatilo** [comment]
[Here's](https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf/PostHog-App?node-id=1829%3A0) the latest:

![image](https://user-images.githubusercontent.com/154479/111648090-6d84ba00-87d9-11eb-8f9c-2c655bb93b4b.png)

The fields are wrong, but you get the gist.

**Comment by paolodamico** [comment]
Some ideas/suggestions.

- What if we dropped the description? From "We manage...." and only keep the interested in self-hosting section?
- What about using the same button components as we do in the rest of the app?
- How about keeping the social icons at the bottom but we make the look a bit more like buttons? i.e. some intermediate prominence. I do think it'll be easier for users to sign up with those if they have it.

**Comment by corywatilo** [comment]
The lines with the checkmarks are supposed to be reinforcement to users signing up. (Basically a UX best practice. See [Stripe's signup page](https://dashboard.stripe.com/register), though the do have a lot less text overall.) I'd be okay with pulling them if they're entirely offensive to our audience, but it was put there with _some_ intention. ;)

I'd strongly encourage us to use this button style, since it is part of the flow and would be weird to have super different buttons. (I see Stripe's homepage and signup form have different style buttons - I just feel like ours are _so_ different it would be sort of weird.)

Sure, we could try maybe a thin gray border around each of the alternate authentication options below. I'd just remind about my earlier comments about the potential UX challenges users will face if there isn't a _clear_ main path and you can't remember how you signed in. (I'd also be curious for more input from others on this too and their experience in using alternate auth methods on other sites, if they use them at all.)

**Comment by paolodamico** [comment]
Thanks for the thoughtful review here @corywatilo!
- Played around a bit to see why it still felt too sales-y and I think simplifying the self-hosted section helped. Wdyt? @timgl thoughts too?
    <img width="810" alt="" src="https://user-images.githubusercontent.com/5864173/111790102-1802e880-887f-11eb-9da4-796254c8691d.png">
- I'll fully defer to you on the visuals of the button, 100% your call. Just as some additional feedback on my end, would it be worth doing an in-between with the button? (e.g. keeping the shape and size but using the app color). Thinking about avoiding confusion once you get dropped into the app after this page.
- SSO. Happy to discuss this further and even A/B test this. I do think that using social logins saves you time and clicks on signup and login. When you come back I think most users will either try SSO first (if they're a typical SSO user) and if not a password. **More feedback on this, please?** 
    - One alternative with solid UX (at the expense of some security), is allowing the user type their email and if they have SSO enabled, we show them only the relevant option. CC @Twixes. **EDIT:** I'm thinking it doesn't have to be even a huge security thing, we can a) protect the endpoint with Axess to avoid brute forcing and b) only return social logins information (i.e. if you have don't have social logins enabled we return a `password` login, whether or not you have an account).
    - A second thing we should do regardless is a good password reset experience, in which you type your email address and you receive an email that a) tells you if there's no account under your email, b) tells you if you have signed in using SSO and c) lets you create a new password if you have an account.
 - One more point, font. We seem to be using a new font here "Good sans", any chance we can get away with Gosha sans and the main font we use (SF, Roboto, Segoe UI, ...  depending on OS)? Would like to avoid introducing an extra font to the bundle just for this page. If it's visually very important, we can load it just in this page, it would probably just add a little extra load time.

**Comment by EDsCODE** [comment]
RE: social logins. If we don't have features that are heavily reliant on data from the social logins, I don't think we should emphasize them. I'd even suggest reducing the amount of social login options available. I generally think those options usually confuse how the user enters the app. Also, since our app is a home base for people's data, the way to access it should be very direct and not rely on 3rd party methods.

I took a quick look around and most platforms seemed to have removed the social logins entirely (heroku, other analytics platforms, Plaid). I'm assuming they've done this because of the points @corywatilo raised about not trusting 3rd parties.

**Comment by corywatilo** [comment]
Context for having the VPC and open source options here: We're planning on killing the modal that opens when you click "Get started" on the marketing site. Since we will no longer have the 3 options (cloud, vpc, os), I thought it would still be important to include them here.

Obviously with the push toward Cloud, that's the reason we're essentially funneling people straight into Cloud signup, but the other options should be there too.

Font-wise, are we able to just include the font on the authentication views so it isn't bundled with the app?

**Comment by paolodamico** [comment]
Thanks @corywatilo & @EDsCODE for the input.
- 👍  Re VPC & open source, makes sense. Will build it that way and we can try it out and adjust.
- 👍 Gave it more thought to the social login topics and I think you make a good point, let's try that out. We can measure results and iterate from there.
- 👍 Font-wise, yes, if it's an important visual element, we can include it just in this page. Could you share the font files please?
- FYI, this signup page will also be used for self-hosted instances, I think we can use the same design and just adjust the copy. Thoughts?
- One final point, could you help me with a quick mockup of how this should look on mobile?

**Comment by corywatilo** [comment]
Fonts are available [here](https://github.com/PostHog/posthog.com/tree/master/static/fonts).

`@font-face` code [here](https://github.com/PostHog/posthog.com/blob/master/src/components/Layout/Layout.scss) 

[Here's](https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf/PostHog-App?node-id=1872%3A14892) a quick mobile mock.

Also @kpthatsme left a [comment](https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf?node-id=1829:0#69204430) about how the desktop view scales up. So some notes:

1. Columns scale up in this ~60/40 ratio
2. max-width on the _content_ in both columns at the existing width (info: ~400px, form: ~300px)
3. Center both info and form within their columns
4. We may need a max-width on the form column if we're at _huuuuge_ widths

**Comment by paolodamico** [comment]
Thanks @corywatilo, very helpful! Just to confirm, we are allowed to bundle this font too with PostHog FOSS, right? CC @piemets. FYI I'm only using the Medium version, as we're using Gosha Sans for titles.

Re large screens, agreed, think it's fairly straightforward, we can test this out on the built version.

@corywatilo one thing I need help with, seems I can't properly export the planet in svg in a way that proportions are kept, and  the visual styles too, are you able to help? _(ignore the other elements of the screenshot, just wanted to show the planet)_

<img width="1433" alt="Screenshot 2021-03-21 at 5 58 53 PM" src="https://user-images.githubusercontent.com/5864173/111929430-89a38800-8a73-11eb-8e13-8436bac89dc5.png">

**Comment by charlescook-ph** [comment]
> Thanks @corywatilo, very helpful! Just to confirm, we are allowed to bundle this font too with PostHog FOSS, right? CC @piemets. FYI I'm only using the Medium version, as we're using Gosha Sans for titles.

Yep that's right, our licence covers this.

**Comment by corywatilo** [comment]
We can probably just forego Good Sans on this page for the time being.

I think we're good on the planet situation (discussion in Figma), but lmk if you still need anything here!
