### ISSUE TITLE
Session Information

### ISSUE THREAD

**Issue by Tannergoods** [PostHog/posthog#334]
***Thank*** you for your feature request - we love each and every one :)

**Is your feature request related to a problem? Please describe.**
I can see individual users events but would like to see how long they spent on the app and from this work out averages across my user base + how many sessions a user has

**Describe the solution you'd like**
When I look at users I should be able to see the sessions they have had their average length - I should also be able to use this with cohorts or my entire user base

**Describe alternatives you've considered**
I can calculate and estimate session times from event recordings but this is quite time consuming

**Additional context**
Requested by: https://app.hubspot.com/contacts/6958578/contact/39151

**Comment by timgl** [comment]
## Defining a session

Google Analytics [defines a new session being started if](https://support.google.com/analytics/answer/2731565?hl=en)
1. It's been 30 minutes since previous activity
2. it's midnight

So we should be able to group users' events into those buckets to work out the session length and how many sessions that user has done.

## Finding the data
When filtering I want the following three datapoints, all over a given date period
1. Average session length
2. Session length distribution (0 seconds, 0-3 seconds, 3-10 seconds, 10-30 seconds, 30-60 seconds, 1-3 mins, 3-10 mins, 10-30 mins, 30-60 mins, 1+ hours)

It would be cool if we could squeeze this into /trends. At the moment we have "Actions & events". I'm thinking of having a second option that's "sessions". It'll show you a dropdown to choose between 1 and 2. It'll remove "breakdown by" and "shown as" as those aren't relevant here.

![image](https://user-images.githubusercontent.com/1727427/78898280-73233d00-7a6b-11ea-988e-92bb94b215ce.png)

(As a sidenote, probably worth removing the word "Action" in the title)

**Comment by EDsCODE** [comment]
RE: conditions for determining session
The third condition would be a $pageleave event right? So new session could be detected 5 minutes after a $pageleave event not necessarily 30 minutes. Also, is there a need for sessions to be considered ended/reset at midnight? 

RE: Data
You mentioned "three datapoints" and listed 2. Was there something else you had in mind to display? And, to clarify, average session length will default to a table view and just show an average across all sessions and the session length dist will also default to table view and show counts of each bucket?

**Comment by timgl** [comment]
$pageleave doesn't necessarily indicate the end of a session. You get $pageleave when you refresh the page or go to a new page. It just means we have a slightly more accurate measure, for example if a user only visits one page, at least we'll have an end to that session.

As you mentioned on Slack, it would be cool to see total volume of sessions or average sessions per user, maybe that's what I was thinking as I was writing that sentence. I don't think it's as crucial as session times.
