### ISSUE TITLE
Nicer fonts for funnels

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#341]
I saw this example of a funnel somewhere and thought it looked a bit better than what we have currently.
![image](https://user-images.githubusercontent.com/1727427/76556243-686a8d80-6456-11ea-82bb-6b01d1ba3d12.png)

**Comment by hacktivist123** [comment]
Hey @timgl do you have any fonts in mind? I’d like to pick this up

**Comment by timgl** [comment]
Hey @hacktivist123 Awesome! I don't necessarily want to introduce another font, but the sizing and positioning of the chart could look a lot more like the screenshot here.

**Comment by hacktivist123** [comment]
Awesome, I’ll get on it and see if I could reproduce the same thing.

**Comment by timgl** [comment]
Great, let me know if you need any help :)

**Comment by mariusandra** [comment]
Hey! If we're already talking about funnels, I'll add one point. It might be possible to tackle this point together with this issue... or maybe not.
In any case, on the dashboard, when resizing a graph with a funnel, the entire funnel chart SVG is regenerated each frame... causing the resizing to be annoyingly slow... and/or not function well:

![screencast 2020-07-03 09-38-45](https://user-images.githubusercontent.com/53387/86444493-17d2b500-bd11-11ea-8559-5ef05433db7a.gif)

It could be possible and even easier to just redo the entire funnel using regular React and some <svg> tags... instead of relying on a vanilla JS library to do the drawing... which can't be controlled well.

**Comment by Twixes** [comment]
I think we're doing okay with funnels UI.
