### ISSUE TITLE
Many error notices are suppressed after limiting error toasts

### ISSUE THREAD

**Issue by Twixes** [PostHog/posthog#3525]
## Bug description

Merging #3220 a while ago suppressed a great deal of **helpful** error messages shown on errors received from API. For instance, creating an invite for an email that already is a member of the org returns err 400 from the API with message "A user with this email address already belongs to the organization.". That message used to be shown in the error toast, which was clear UX, but since we removed that error handling, no error is shown and the user is left very confused as to what happened.

## Environment

- [x] PostHog Cloud
- [x] self-hosted PostHog, version/commit: 1.22

**Comment by mariusandra** [comment]
As I advocated (in Slack) when this was merged, I'd be in favour of reverting #3220 and blacklisting noisy errors again, instead of forcing us to add `toast.success()` in all loaders. I've run into this many times with plugins as well, where errors would just be swallowed up.

The problem with the previous system was that there were sometimes too many errors due to intermittent network issues, showing the interface as broken. A "retry 3 times with backoff" to all `api.get` calls would probably solve that.

**Comment by Twixes** [comment]
I think _most_ errors we should prefer to indicate at first sight. There are some specific endpoints where it's acceptable to fail, but in _most_ cases the user experience is impacted. And hiding notices only makes the impact worse. So maybe revert of #3220 AND an additional argument to `api.get/update/etc` that would make errors in specific calls handled internally?

**Comment by timgl** [comment]
As I mentioned in Slack, I htink most of the unhandled errors that users care about happen on POST or PATCH functions. I'm okay re-enabling errors just for those globally + selectively enable errors for certain GET requests.
