### ISSUE TITLE
Raw SQL queries support

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#3548]
## Is your feature request related to a problem? Describe the solution you'd like

This is an idea that came up in the last offsite and that we've been talking about randomly ever since. Have support for custom raw queries for users with complex analytics needs.

## Describe alternatives you've considered

For self-hosted you can connect directly to your DB and even use something like Metabase on top, but this unfortunately is not an option for the cloud version.

## Additional context

- Important to consider the role of CH so that the experience is seamless for users.
- +1 from a user who recently moved from Cloud to self-hosted to address this need.

**Comment by mariusandra** [comment]
I guess somewhat related: https://github.com/PostHog/posthog/issues/1244

**Comment by paolodamico** [comment]
+1 from a [customer call](https://docs.google.com/document/d/1762fbEbFOVZUr24jQ3pFFj91ViY72TWrTgD-JxRJ5Tc/edit#heading=h.wrp357nfyebp) today. They're considering integrating a BI tool because they're not sure PostHog's scope covers this.

**Comment by paolodamico** [comment]
Alright so I want to move the discussion on whether it's a good idea to move this forward. We know there's a clear need for metrics/analyses that our UI doesn't support (see https://github.com/PostHog/product-internal/issues/48 for instance), and we have three options to address this:

### 1. Build support in the UI
While our query building is still limited in terms of parity with other analytics tools, even with something like Amplitude/Mixpanel/Heap these metrics would be hard to build, and the UX might end up being more confusing than writing raw SQL. This option has significant challenges in design.

### 2. Provide support through a third-party service
Simplest option. We would tighten and better document integration with tools like BigQuery, Metabase, ... made for visualization (a key customer is already doing this). The problem is that then PostHog ends up being a data ingestion tool, and any meaningful analysis ends up happening outside of PostHog, greatly reducing our value.

### 3. Support raw queries in PostHog
Probably has some technical complexities to figure out. This provides the greatest flexibility for users while keeping them in PostHog. It's also related to feature parity, as at least a couple of the leading analytics tools offer this. Another downside of this, is that it's geared for technical users with SQL knowledge (I do however think that for bigger companies you either have PMs that write SQL or already work with data engineering to write out queries and build dashboards).

Thoughts? @timgl @EDsCODE @macobo .....

IMO we should go with 3), it has the clearer long-term benefits for PostHog and is aligned with a) focus customers requirements, and b) feature parity.

**Comment by corywatilo** [comment]
Are we basically thinking a giant textarea for the query (with syntax highlighting)?

Here's an option for switching into "SQL mode". 

**Dream scenario:** Takes your current query and converts it into its SQL equivalent
**MVP:** Gives you a blank input with a placeholder explaining to type your SQL query

I also left a spot for a link to a reference modal (think Github and Markdown), whether it be a generic SQL cheatsheet, or if there are specific ways they need to reference their data from within PostHog, that could live under that modal too.

![image](https://user-images.githubusercontent.com/154479/119600980-353fc000-bdb6-11eb-9bf6-92994897a7ea.png)

**Comment by mariusandra** [comment]
I love the idea of adding more developer-friendly features, though I'd be really careful with promising the raw sql feature to anyone before thinking it through.

- First, the raw SQL queries would be made to your posthog database or to your app's database? Clickhouse or postgresql?
- How do we store the credentials and limit access in a way that nobody does "select hashed passwords and other sensitive data from my colleagues in the posthog_user table". Only superusers can do raw sql?
- How to detect the returned fields to see if we should display a graph or not
- Displaying endless paginated tables might be fun
- We need solid support for long running queries (borked now) and query cancellation (not implemented) as users might do `select a billion events from posthog_event`.
- Can we put anything returned this way on a dashboard?

Not saying we shouldn't go for it (we probably should), but let's spec it out more technically.

**Comment by macobo** [comment]
My 2c on some technical aspects of this.

Assuming we'd like to run this on cloud as well (do we?), I'd decompose this problem into 3 distinct parts:

## Accessibility

Marius above is right - basically whatever solution we end up with needs to solve customer problems, so we need more info.

A good way of solving this question is documenting + "solving for" specific queries users who export to data to tools like bigquery use. 

Some questions here:
- Raw tables vs visualizations?  For reference, even a raw "events/day" graph is not always trivial to write correctly in sql, making the questions around visualization tricky.
- How to avoid needing to write boilerplate (team_id inside each where?)
- How as a user do I know what posthogs schema is and what columns to access.


## Security

On cloud, whatever solution we end up with needs to:
1. Not be able to read other customers data
2. Not be able to mess with "private" parts of our datastores (e.g. not able to read from kafka tables, not able to create/drop/alter tables, change settings, ...)

IMO this leaves us with a situation where we need to:
1. Parse the SQL user sends us into an abstract syntax tree
2. Validate it (e.g. only allow SELECT queries against a select few tables, ban other queries + things like `SETTINGS`, `SELECT INTO` etc)
3. Modify it to only allow reading your projects data (e.g. injecting `AND team_id = X` everywhere in the queries)
4. Modify it 

This however feels like it runs counter to the (Accessibility) argument - we're presenting them with a limited leaky abstraction instead of _actually_ giving them raw access.

## Performance

One users queries should not bring down anothers. It'll be "easy" to write sql that takes forever (e.g. cross join users and events) and it's natural to do so during "development" - but in production this will lead to noisy neighbor problems. 

We've also seen that sometimes clickhouse doesn't want to kill queries even when you tell it to without restarting the cluster.

**Comment by EDsCODE** [comment]
+1 to the points above. Raw queries have much more performance and security considerations than most other features we've built so far. In terms of approach, I think this feature would require a dedicated team to think through all the cases listed above + more before starting an implementation. 

Specifically, @macobo's description of building a limited abstraction would be a necessary but significant dealbreaker. Most people are probably unfamiliar with clickhouse SQL syntax and would be inclined to write queries in a way that would be column-store efficient. We would end up requiring some SQL variant that we would need to convert into a clickhouse efficient query. 

Doable, but worth really making sure this is a direction that will significantly improve our target customer experience and that we can approach it without running the team too thin

**Comment by paolodamico** [comment]
Thanks everyone for pitching in! Very valuable points to consider. I guess the way forward is understanding more about the queries that can't be run with the user interface so we can answer the burning questions and come up with a bit more detailed tech specs. I'll talk to customers to get more information on insights that can't be obtained with PH. With that we can make an informed decision on whether this is a project we should tackle.

Questions to answer:
1. Data set. Do we need to combine CH & PSQL?
2. Query syntax. Do we need an abstraction layer to convert typical SQL queries into CH-efficient queries?
3. How do we need to display the data? _We already have some context on that here https://github.com/PostHog/product-internal/issues/48, I think in an ideal scenario we would get closer to Metabase's functionality._

Obviously the points around security, data segmentation/privacy, data integrity (only SELECTs), timeouts / query run time, ... absolutely need to be considered, but I don't think we have any questions in there, it's more a matter of considering how to address those when the time comes.

**Comment by macobo** [comment]
I'd like to backpedal a bit: This might 100% make sense as a feature on _self-hosted_ where the security/isolation/performance issues are not that important.

Also after sleeping on this issue for a bit, there's this: https://clickhouse.tech/docs/en/operations/access-rights/, specifically https://clickhouse.tech/docs/en/sql-reference/statements/create/row-policy/.

In theory we _could_ create team-specific accounts in clickhouse which are only allowed to select from select tables and restrict them to rows with matching team_ids. This could help side-step needing to parse/validate queries in app code.

But even with that, it might make sense to start with self-hosted if we do this.

> Data set. Do we need to combine CH & PSQL?

I'm not sure we do. Ignoring self-hosted postgres for a bit, clickhouse contains all the analytical data in two tables - events and person. It seems reasonable that these would be sufficient for analytical purposes. :)

**Comment by paolodamico** [comment]
That is super helpful @macobo, thanks for spending more time thinking about this! Will update the issue with more information from users too and we can discuss next week if it's worth moving this forward and if so, who would own this? Probably core analytics team?

**Comment by timgl** [comment]
Genuine question: why should we build this instead of pointing people to metabase? It already does everything well, it's easy to set up and hook into clickhouse.

**Comment by Twixes** [comment]
Well, I wouldn't advise to build this querying option now, as that seems pretty complex to pull of well, and risky. But generally we'd prefer people to use and pay us instead of Metabase for analytics (and this is about data ingested by PostHog – as noted by @paolodamico, as just a data ingestion tool we're less valuable than as a versatile analytics suite) so may be good to entertain the concept.

**Comment by paolodamico** [comment]
Based on the discussions that have happened recently, and particularly the input we got from the key focus customer that prompted this discussion (see https://github.com/PostHog/vpc/issues/98) I believe we can table this, at least for the time being. For customers with data warehouses, it'll make more sense for them to run analytics in their DW as they a) will be able to run more complete/complex insights, b) can incorporate data from other sources and c) likely have the expertise to run analytics with raw SQL.

Users on self-hosted can always integrate something like Metabase quite easily and for users on Cloud the UI will cover most cases. Further, the particular complexity of doing this for Cloud doesn't seem to outweight the benefits.

Anyone please feel free to disagree, moving on otherwise.

**Comment by EDsCODE** [comment]
(Please ignore notifs everyone! testing....)

@posthog-bot please summarize this

**Comment by EDsCODE** [comment]
(Ignore messages below!)

**Comment by EDsCODE** [comment]
@posthog-bot Please summarize this

**Comment by EDsCODE** [comment]
@posthog-bot Please summarize this
