### ISSUE TITLE
Break down more than 20 values

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#3589]
## Is your feature request related to a problem?

Right now we artificially limit the number of values a breakdown returns to 20, partly for performance.

## Describe the solution you'd like

 We should be able to either paginate this or export a full list. 

## Describe alternatives you've considered

There's no real way of getting say the number of events per user right now.

## Additional context

The query right now is kinda weird, we do one to get the values and then do a second query filtering by those values. Can probably be optimised.

cc @EDsCODE

**Comment by sharon-john** [comment]
## Further context ##  

-  This is pertaining specifically to the number of breakdown values appearing on the Insights -> Trends -> breakdown values by cohort/properties, an example of this is shown below: 
![image](https://user-images.githubusercontent.com/23110520/111559208-54362c00-874d-11eb-91f1-3c10b689b2ec.png)
 
- This is artificially limited to 20 primarily for performance. PostgreSQL is retrieving all the values but the query is only then sending the top 20 to posthog/api because Line 99 in posthog/posthog/queries/trends.py (`len(cohort_keys) > 20`) picks the top 20 values and returns that dataarray. Graphs of sizes even as small as 50-80 breakdown values take between 5-10 seconds time to load their respective graphs. 

## Thoughts ## 

1) Batch process large numbers of breakdown values on the server

- (queries/trends.py). build_dataarray() can be modified to return lists of dataarrays, and cohort keys as follows: 
![image](https://user-images.githubusercontent.com/23110520/111558923-dd009800-874c-11eb-9954-efb78991014c.png)

- update the other callers of build_dataarray() to accordingly accept list of list of objects rather than lists of objects.

 - Need a mechanism for the /api/insight.py to send one batch at a time from calculate_trends() so one batch of size <= 20 is processed. This will reduce the payload size and enable graph processing speeds equivalent to the current system. 

2) Frontend 

The trend-legend feature flag is useful beyond this step to receive breakdown values and display them. The checkboxes allow users to add that breakdown value to the graph and deselection removes from the graph. 

Either pagination can be used so the next batch of <= 20 items are displayed upon a user click, or all values can be displayed allowing the user the autonomy to pick and choose without sets of data being necessarily grouped. Continually send the data from API to insights page every few seconds, and only display upon pagination. Actually requesting the resource itself at pagination click would be too slow.

**Comment by EDsCODE** [comment]
#3782 implements a paginated solution for now
