### ISSUE TITLE
Archiving old data

### ISSUE THREAD

**Issue by adamwaterhouse** [PostHog/posthog#3604]
Hi,

I'm looking for a way to archive old data and wondered if there's a recommended way to do this?

**Comment by mariusandra** [comment]
Hey Adam, I assume you're self-hosting?

If so, then since you have access to all the postgres tables with the raw data, one approach could be to archive them like you would archive any other postgres database.

Another approach is to use plugins to get data out of the system. For example there's a [bigquery export plugin](https://github.com/PostHog/bigquery-plugin) that sends all events to Google's BigQuery. We're thinking of adding support for other export destinations like [S3](https://github.com/PostHog/plugin-repository/issues/12), [Postgres](https://github.com/PostHog/plugin-repository/issues/11), etc. 

Hope this helps and happy to clarify further
