### ISSUE TITLE
Add trailing DAU/WAU/MAU

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#3638]
## Is your feature request related to a problem?

I'd like to have a daily graph of the trailing DAU/WAU/MAU (so that eventually I can see percentage of DAU/MAU for example)

## Describe the solution you'd like

In the maths dropdown add DAU/WAU/MAU options.

## Additional context

I don't think this'll be super easy. In clickhouse we have the process_math() function, but obviously you'd actually need to extend the timerange to be able to do this I think.

**Comment by macobo** [comment]
Just to understand from the users perspective: What does this feature gain them, why is it important to analyze?

**Comment by timgl** [comment]
The specific stats someone was interested in was seeing the percentage of DAUs of MAU so you get a sense of what percentage of users come back every day (using formulas)

**Comment by paolodamico** [comment]
I believe this can be closed now @EDsCODE ?

**Comment by EDsCODE** [comment]
We'll need to eventually release flag but yes

**Comment by Hum4n01d** [comment]
Not sure if this is the right place to ask, but where can I access a trailing DAU? I'm trying to calculate DAU / MAU over time but I only see weekly and monthly available

<img width="584" alt="image" src="https://github.com/PostHog/posthog/assets/17228477/4e5695c6-64c7-4cca-a7ff-95b374ca8077">

Using "unique users" doesn't work because then I can only calculate for one particular day

**Comment by Twixes** [comment]
Hey @Hum4n01d! We only have WAU and MAU split out, as for DAU we typically recommend creating an insight aggregated by day. Can you share a bit more about your analysis to guide us in terms of when standalone DAU would be useful?
BTW this issue's three years old, so I think it'd be easier to chat about this in a new one created for the purpose. 😄
