### ISSUE TITLE
Download CSV of users from a datapoint on graph

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#3949]
## Is your feature request related to a problem?

I want to be able to download a CSV of users when I click on a datapoint in a graph

## Describe the solution you'd like

![image](https://user-images.githubusercontent.com/1727427/114418453-cd8d3700-9bb2-11eb-906d-8aa424f48500.png)

When I click on a datapoint I'd like to be able to download a CSV as well as create a cohort from it.

**Comment by c3ho** [comment]
Hi, can I take on this issue?

**Comment by timgl** [comment]
Go for it!

**Comment by c3ho** [comment]
Thanks! @timgl I have two questions regarding this issue:

There already exists a button to save the cohort. However it will only appear if there's a feature flag enabled called `save-cohort-on-modal` and the insight chosen is `Trends` or `Stickiness`, did you want to remove the condition requiring the feature flag? 

Secondly regarding downloading a csv for the event, what information should be exported? Whatever is shown in the event `Email` and `ID`?  I'm asking about this because there's a similar feature at `http://localhost:8000/events` and the data exported is more than what is shown in the table on posthog.

**Comment by EDsCODE** [comment]
1. We're still testing that feature so we will keep the feature flag for now!
2. I'd say that downloading the emails and ids would be good to start with. We can add flexibility of fields later as needed

**Comment by c3ho** [comment]
@EDsCODE Thank you for clearing everything up!

**Comment by c3ho** [comment]
Hi @EDsCODE, I've submitted PR #4175 to fix this issue. Please let me know if there's any changes I need to make to the PR!
