### ISSUE TITLE
Design request - Empty state for graphs

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#3982]
This issue is to request some help from the design team.

## What do you need designed and why?

- Empty state for insights when you don't have any events in your app. Call to action would be something like go to event ingestion process.  Check out #3981 for more context.
- Empty state for when there is no data to show based on your current filters (e.g. you selected a timeframe for which data is not available, or filters exclude everything). Call to action (not really a button or anything, more of an explanation) would be something like adjust your filters. (screenshot of current empty state shown below).

<img width="1347" alt="" src="https://user-images.githubusercontent.com/5864173/114732775-a7bd7a80-9cf7-11eb-86e6-3a3db170d65c.png">

### Why?
These serve edge cases where we can't show data to the user either because they don't have any data or they're doing an invalid query. Our current display makes things look broken or can give the sense of an incomplete product.

## What is the deadline?
If we can get it by early next week, we can consider the implementation on this release cycle, but not critical.

## Additional context
- It'd be great if we could keep this simple in terms of the elements we have on the screen to simplify implementation and maintenance.
- Useful to consider the design of dashboards empty states to maintain the same language / look-and-feel.

**Comment by sankalpdomore** [comment]
Based on my observation and the context above, I went ahead and tried a few variations:

### Variation 1:
Base assumption: When the code snippet is not yet added / detected, there could be a dummy graph present and on top of it, we can put the same helper text with "Go to wizard" CTA inside. Note that the "Go to wizard" CTA inside the graph area is deprioritized by treating it with a "bordered-style" CTA - reason being too many solid/filled-style CTAs in the viewport and I think the yellow banner on top should be taking attention until closed. 

<img width="1440" alt="Desktop  App - Empty State - V 1" src="https://user-images.githubusercontent.com/18334593/116533244-c8dcb880-a8fe-11eb-9ed8-59514c17234e.png">

If the user chooses to close the yellow "Go to wizard" banner on top, then the CTA in the graph can be prioritized again i.e. making the background filled & text+icon white.

https://user-images.githubusercontent.com/18334593/116538370-0cd2bc00-a905-11eb-8682-c3617b854fb7.mp4

Empty state's content layout here is:  **Graph-emoji > Section header > Helper text > CTA**
Trying a graph-emoji as it might add a bit of color/playfulness and context that a graph will appear when data is available.


### Variation 2:
Same as variation 1 (after you close the yellow "Go to wizard" banner) but with the same star icon present in the banner instead of a graph-emoji

Empty state's content layout here is:  **Icon > Helper text only > CTA**

<img width="1440" alt="Desktop  App - Empty State - V 3" src="https://user-images.githubusercontent.com/18334593/116533979-9f705c80-a8ff-11eb-9a3b-20e609955f11.png">


### Variation 3:
Exact layout as variation 2 (without a section header) but with the graph-emoji instead of the star icon.

<img width="1440" alt="Desktop  App - Empty State - V 4" src="https://user-images.githubusercontent.com/18334593/116534709-7ef4d200-a900-11eb-856f-75c146cd265a.png">


### Variation 4:
Exact layout as variation 3 but with a bit of copy change in the 1st line of the helper text. i.e. "Seems like there's no data to show this graph yet." instead of "We haven't received any events on this project." from variation 3. + trying a shortened width of the container so it's easier to read vertically vs. scanning longer horizontally. 

<img width="1440" alt="Desktop  App - Empty State - V 5" src="https://user-images.githubusercontent.com/18334593/116535074-f75b9300-a900-11eb-9864-2530639ee1b5.png">


### Variation 5:
Exact layout as variation 4 but taking into @paolodamico 's feedback of keeping the look-and-feel of the dashboard UI. The white background also has a blur effect compared to the other variations. (I like the blurred state better)

Empty state's content layout here changes to:  **Dummy graph line (from dashboard) > Helper text only > CTA**

<img width="1440" alt="Desktop  App - Empty State - V 5" src="https://user-images.githubusercontent.com/18334593/116536935-34288980-a903-11eb-9e20-a17f09e12bd3.png">


### Empty state when there's no data to show based on your current filters
Building on the variations above and keeping the background style of Variation 5 i.e. blurred,
- I've added an eye emoji as it looks to the left naturally indicating to tweak the filters 
- the explainer text not only explains the empty state but also has a CTA to help remove all the filters with just one click vs. individually removing them.

<img width="1440" alt="Desktop  App - Empty State - V 6" src="https://user-images.githubusercontent.com/18334593/116537722-37704500-a904-11eb-9299-dddd1bf18a1b.png">

Clicking the CTA "clear all filters" will restore the graph.

https://user-images.githubusercontent.com/18334593/116538570-53281b00-a905-11eb-9410-34d2ff00f6f8.mp4


### Some pointers:
- I prefer the emoji version (variation 1) of the empty state for the reasons mentioned above but it'd also make sense to choose the dummy graph version (variation 5) as it resembles and retains the dashboard UI.
- The white translucent cover on top of the graph requires added work but worth considering as it builds anticipation of a graph.
- The copy for different pages can be tweaked a bit but the layout can remain the same. i.e. emoji/icon to add color/playfulness, 1-2 lines of explainer text, and a CTA to rectify the empty state.

Apart from this, I've also made some UI tweaks in those mockups for better readability, improving contrast & accessibility, and some general padding/spacing work to make the UI more fleshed out. I'll be logging those in a separate issue.

++ in case anyone wants to dig into the design file, here's the [link to the Figma file](https://www.figma.com/file/HjzusAHEwIsdMw0PlnbDIP/PostHog?node-id=33%3A714).

Let me know what you guys think. Happy to take any questions.

**Comment by paolodamico** [comment]
Thanks for taking the time to explore this @sankalpdomore and apologies for the delay sharing feedback. Some thoughts, @corywatilo might be worth picking up internally too?

- While I like the emoji approach, I don't think it fits with the design language we have in the app. I think using some icons (maybe custom) would work better here. Perhaps the biggest challenge in this overall task is making this look visually attractive.
- Most of the time the problem with an empty data set will not be that the user hasn't ingested events but rather that the filtering is excluding all available data. I think therefore the most useful call to action will be around adjusting filters (e.g. expanding the timeframe, removing restrictive filters, etc.). Think we could be a bit more detailed here too. Particularly reference to relevant docs too.
- 👍 on taking the user to the ingestion wizard for the edge case of not having ingested any events in the project.

**Comment by clarkus** [comment]
While working on nailing funnels, I put together a design for a very targeted empty state. The core problem is that funnels require two steps to calculate and display a meaningful visualization. The goals for this empty state:
- Strongly emphasize the recovery action - adding another step
- Communicate what happens when you add more than two steps
- Give a large, redundant, call to action that triggers the step adding workflow
- Secondarily link to supporting assets on how to use funnels

<img width="1280" alt="empty state - need more steps" src="https://user-images.githubusercontent.com/254612/124973365-49472600-dfe0-11eb-9aa2-e6a96844da84.png">


The solution is available in figma at https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf/PostHog-App?node-id=2903%3A5559. Note that there are more cases to handle for empty states. While this could be a good baseline pattern, I need to do more research to make sure this is applicable to all cases.

**Comment by alexkim205** [comment]
> While working on nailing funnels, I put together a design for a very targeted empty state. The core problem is that funnels require two steps to calculate and display a meaningful visualization. The goals for this empty state:
> 
> * Strongly emphasize the recovery action - adding another step
> * Communicate what happens when you add more than two steps
> * Give a large, redundant, call to action that triggers the step adding workflow
> * Secondarily link to supporting assets on how to use funnels
> 
> <img alt="empty state - need more steps" width="1280" src="https://user-images.githubusercontent.com/254612/124973365-49472600-dfe0-11eb-9aa2-e6a96844da84.png">
> 
> The solution is available in figma at https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf/PostHog-App?node-id=2903%3A5559. Note that there are more cases to handle for empty states. While this could be a good baseline pattern, I need to do more research to make sure this is applicable to all cases.

**Comment by paolodamico** [comment]
Implemented on funnels, keeping the issue around to implement on trends too.

**Comment by clarkus** [comment]
Related error states - https://github.com/PostHog/posthog/issues/5076

**Comment by paolodamico** [comment]
We now have a really cool and standardized empty state for all insights.
