### ISSUE TITLE
Command-line interface (CLI) to manage PostHog

### ISSUE THREAD

**Issue by buwilliams** [PostHog/posthog#4025]
## Describe the solution you'd like

Newcomers to PostHog may struggle with the variety of our tech stack: docker, django, node, clickhouse, etc. For me, PostHog did not work out of the box and there was a lot to learn. I'd like to have (1) a single tool `ph` which enables users to manage PostHog in one place. (2) Serve as a teaching tool.

At a high-level, what's most important about PostHog is what it can do for our users not how it works. Currently, PostHog requires a high-degree of tech stack mastery, at least this is my experience. I'd like to shift the focus from how it works to what it can do for you. I believe a CLI could make learning PostHog's features and contributing the natural focus.

## Describe alternatives you've considered

It's possible that such a tool would not be worth the development effort.

## Additional context

An experimental project has been created [https://github.com/posthog/ph](https://github.com/posthog/ph) which has more information.

**Comment by Twixes** [comment]
Pretty cool idea! Let me just shed some context. :D

We actually did develop a CLI once upon a time – https://github.com/posthog/posthog-cli – it was built during the October hackathon as part of the plugins project (BTW for more context, there were three teams all starting from scratch delivering an MVP in a few days: 1. session recording 2. command palette 3. plugins). That project is now completely deprecated as plugins were heavily reworked after the hackathon and the CLI's original MVP purpose was voided, while the original, broader idea of a PostHog CLI (which was floated before the hackathon) that could be used for spinning up production instances of PostHog (think Heroku) was deemed unfeasible (it would basically entail the self-serve VPC idea) and management of a dev instance of PostHog was thought to be not worth the effort.

Personally I think dev assistance should be a part of this repo (npm scripts as the interface) and an actual CLI like `ph` would be better reserved for interfacing with PostHog Cloud or other production PostHog instances (which may or may not ever happen, as a CLI does not appear _really_ useful - or requested - for our product the way it is now). Happy to hear other opinions on a CLI though.

**Comment by mariusandra** [comment]
Great summary @Twixes . Indeed for managing posthog running on the cloud or somewhere, the CLI approach doesn't make that much sense due to the plethora of options in the deployment buffet.

For local dev, well, at the end of the day such a script would just be a wrapper around other scripts... that we already have under `bin` and can call as needed. We could consolidate all of the dev scripts into `./bin/posthog start` or whatever, but again I'm not sure of the big win compared to `./bin/posthog-start`. We will still have to muck around with pip, virtualenv and all other things that make each setup slightly different.

That said, I like scripts. I'm often deep in the plugin server code and I constantly run [these scripts](https://github.com/PostHog/plugin-server/blob/master/package.json#L32-L39) to accomplish whatever dev env setup I need. There's some point to consolidating and simplifying all of this..

**Comment by buwilliams** [comment]
Thanks @Twixes and @mariusandra! I'm in awe of the kindness in your both your feedbacks. It's clear you do this a lot.

A CLI is *not a hill I wish to die on*. My aims are to (1) consolidate and (2) teach.

I believed a nice CLI was a step in that direction but I'm open to alternatives. I'm wondering at a base level if we see the same problems. Since we plan to add more developers to PostHog I see our product in danger of becoming overwhelming and confusing. There isn't a clear interface into PostHog. Our most successful first users of PostHog is Heroku since we do everything for you. That's how I first used PostHog. What's happens when 50+ devs are working on it?

Premise: If we want to become the most loved Analytics platform, we will need to do **a lot** of hand holding.

@Twixes thanks for history of the hackaton, it's always fun to learn what's happened. I did know about posthog-cli though which made me feel good about doing my homework. I agree that having the tool inside PostHog is beneficial. I put it in a separate repo to (1) think about it separately (2) have a playground for the experiment (3) has the advance of being able to do other types of DevOps work.

@mariusandra I do not think pip/virtualenv are required since we have docker. Did you have any success with [Remote Debugging for Pycharm](https://www.jetbrains.com/help/pycharm/remote-debugging-with-product.html#remote-debug-config)? Studying docker taught me about macOS's memory virtualization which gave me much more confidence in Docker's performance for localdev once I understood it's real memory usage. I agree with you that the CLI would, in the beginning, mostly be a wrapper. I'm honestly *not convinced* a CLI is the right solution but it could be.

Symptoms of the problems I see:
- First uses are via Heroku
- Onboarding a new developer is requiring a lot of hand holding
- Often our product is not working out of the box
- There doesn't seem to be a clear way to learn PostHog for developers

My questions are:
- How could we create a streamlined interface?
- Most importantly, how do we teach our product to users and developers?

Personally, I've seen CLI's be too good to ignore. The proof was in the pudding. I do not think you'd be able to convince me otherwise. I'm am sensitive that it may not be worth the effort or even the right solution. I do think the core problems exist and are worth solving.

**Comment by mariusandra** [comment]
Feel free to experiment and keep improving with `ph`. If it helps and makes your life better, that's wonderful. I can't have anything against that :). I'm just not sure it will fully fit into my established workflow, which I'm reluctant to change just for change's sake. 

The original CLI we built during the hackathon was more of a solution in search of a problem. If you feel strongly that this one is actually solving real problems, keep at it.

Since you asked, I haven't tried remote debugging for PyCharm. The great thing of PyCharm and other JetBrains tools is that you explicitly don't have to mess with stuff like that. It knows your environment, autoconfigures all python/pip/virtualenv/etc doohickies and lets you hit one fat debug button next to any "py" file and do the most productive work of your career. Swapping that out for a workflow that adds a few layers of abstraction for unclear purposes, not to mention issues with port mapping when debugging a few things at the same time, etc, is not what I'm going to spend my time on :).

**Comment by buwilliams** [comment]
I'm going to close this issue for now since a prototype has been made and it's unclear how useful it will be. I'll keep it as a side project in the back of my mind and revisit as time provides. The general goals of streamlining and teaching are still at the forefront of my mind. Thanks for everyone's feedback!
