### ISSUE TITLE
Improve / standardize legends for lifecycle graphs

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#4041]
## Is your feature request related to a problem?

The new lifecycle toggles functionality is amazing and quite helpful, however the way we show it is not very standardized with the rest of the app.

## Describe the solution you'd like
 I would like us to have the same layout as we do for trends in which you have the series list below and you can toggle each series with checkboxes (see below). As per feedback today from @jamesefhawkins, it'd be great if we can also add a helper icon with a description of each element.

<img width="906" alt="" src="https://user-images.githubusercontent.com/5864173/115319345-751ae400-a134-11eb-8a86-1b1b670466e1.png">

## Describe alternatives you've considered

Keep it as it is?

## Additional context

CC @liyiy

**Comment by liyiy** [comment]
I agree with the feedback for a standardized style and tooltip/helper icon updates :D I’m thinking of color corresponding them and making the format more similar to trends

I do like the toggles over checkboxes for this though, it feels more fluid/inviting for users to play around with toggles since there’s only four set options, unlike in trends where you can add or remove options. What do you think? @paolodamico 

Also, a side note! I’ve noticed that these colors are part of a beautiful pastel palette but they’re not very color-blind friendly, see the screenshot below for the comparison of colors just for the lifecycle graphs. You can see some of the colors start to blend together / don't stand out very well

<img width="602" alt="Screen Shot 2021-04-19 at 10 20 38 PM" src="https://user-images.githubusercontent.com/25164963/115401592-90c7ce00-a1b8-11eb-84f2-178b919dda70.png">

Is there a specific rule for how we’ve set the color palettes for these graphs/charts or can I adjust them for the above reason?

**Comment by mariusandra** [comment]
With #4152 and #4174 in, is there still something to do in this issue?

**Comment by paolodamico** [comment]
Yes, the intent of this issue was actually having the toggles not at the control bar at the top but as legends at the bottom (for consistency). The extra information of the table could also be quite useful, particularly for exporting, sum/averages and screenshots.

**Comment by clarkus** [comment]
Related https://github.com/PostHog/posthog/issues/4076
