### ISSUE TITLE
Charts/Graphs are not colorblind friendly 

### ISSUE THREAD

**Issue by liyiy** [PostHog/posthog#4076]
Chart colors do not stand out enough for those with color blindness or other forms of vision impairment

**Example: the colors on the lifecycle charts** 

<img width="933" alt="Screen Shot 2021-04-21 at 5 54 13 PM" src="https://user-images.githubusercontent.com/25164963/115625804-97466a80-a2ca-11eb-9aa5-beecffe5cee9.png">

As you can see below, some of the colors look really similar there and start to blend together, we can probably improve the accessibility experience of our chart color palettes

<img width="533" alt="Screen Shot 2021-04-21 at 5 55 11 PM" src="https://user-images.githubusercontent.com/25164963/115625910-b9d88380-a2ca-11eb-9702-fc85c02fe2a9.png">

https://davidmathlogic.com/colorblind/#%2399C5FF-%23C277CF-%2371B96B-%23F86234

## Describe the solution you'd like
- Update our chart colors to be more accessible
- Allow for users to select colors themselves

## Describe alternatives you've considered 
- Do nothing

**Comment by stefanovic80** [comment]
I would like this to be my first GitHub issue. For this purpose I forked the entire project, I cloned it onto my computer (clone git path) but now I fill myself a little disorientated. How could I figure out this specific issue from the entire project? 
Sorry for it, but practically I am a GitHub beginner

**Comment by corywatilo** [comment]
There's more discussion about colors in #3679 and closed by #3775.

Is what we have now a result of that PR?

**Comment by clarkus** [comment]
I used the Viridis palette documented at https://cran.r-project.org/web/packages/viridis/vignettes/intro-to-viridis.html for a 20-option palette. While this might clash with our product palette now, it could inform an alternate palette that works well for both needs. Per the source:

> Use the color scales in this package to make plots that are pretty, better represent your data, easier to read by those with colorblindness, and print well in gray scale.

![Data Palette](https://user-images.githubusercontent.com/254612/123493102-54f22000-d5d0-11eb-9bae-47951a17e5f7.png)

**Comment by clarkus** [comment]
There is a really wonderful article about how a team navigated this process at https://medium.com/carbondesign/color-palettes-and-accessibility-features-for-data-visualization-7869f4874fca. It's all about developing the system and guidelines for Carbon (https://www.carbondesignsystem.com/data-visualization/getting-started/). I'm putting some time in today to work through palettes for our visualizations. I'm going to primarily document my work in figma under our design system, but I will cross-post the solution here as well.

**Comment by clarkus** [comment]
OK after a bit of research, I took our existing high contrast palette and added a few additional steps. This is a categorical data palette. All that means is that the colors must be applied in the sequence set out here in order to ensure contrast and easy differentiation. This should be applied to distinct categories of data. If we want to apply any relationship or correlation between data points, this is not the palette to use. I'm working on palettes for other scenarios next. They're just extensions of this palette so it should be quick to put those together. /cc @corywatilo for feedback.

![Categorical Data Palette](https://user-images.githubusercontent.com/254612/124332982-c50c2300-db47-11eb-885d-0835e01cc8ff.png)

**Comment by clarkus** [comment]
I've added some updated palettes and general usage guidelines to our figma design system at https://www.figma.com/file/Y9G24U4r04nEjIDGIEGuKI/?node-id=0%3A1. Here are exports of each palette with hex codes applied to the core categorical palette. The monochromatic palettes are stepped versions of 4 colors from our main data palette. I need to redraw our core insight chart patterns using these updated colors. I am planning to do that as part of other [consistency work](https://github.com/PostHog/posthog/issues/2656) I have queued up for charts. I will continue to update the design system, but this seems like enough for this issue to move over into a feedback phase. 

![Categorical Data Palette](https://user-images.githubusercontent.com/254612/124819414-1427ce80-df21-11eb-833a-19ff6dd472a8.png)
![Sequential Data Palette](https://user-images.githubusercontent.com/254612/124819417-14c06500-df21-11eb-846d-63ad737f79cc.png)

Edit - here's the categorical palette applied to our update funnel designs with breakdowns applied. 

![C stacked](https://user-images.githubusercontent.com/254612/124820619-906ee180-df22-11eb-833f-cdef62145302.png)

**Comment by corywatilo** [comment]
First, thanks for tackling this (and for mocking at all the different widths)!

My only "direct" feedback (that I'm not entirely sure is actionable) is that they're just sort of ugly.

Is there a way we can use a "brighter" palette and still retain the distance between colors, or is the very reason they're dark is because it's better to solve this challenge? (For example, there are no basic, brighter shades like `#f00`, `#00f`, etc, which I'd imagine are slightly easier on the eyes.)

I'm also thinking about how the default color would be a dark purple for even simple visualizations. Maybe another solution would be to set the first color to be PostHog app blue, then follow up with the rest of these?

**Comment by clarkus** [comment]
> Is there a way we can use a "brighter" palette and still retain the distance between colors, or is the very reason they're dark is because it's better to solve this challenge? (For example, there are no basic, brighter shades like #f00, #00f, etc, which I'd imagine are slightly easier on the eyes.)

💯 

Colors are hard™. I'm trying to find a happy medium between not ugly and visually discernible. I'm going to keep working on this, but wanted to share sooner than later just to get input. 

> I'm also thinking about how the default color would be a dark purple for even simple visualizations. Maybe another solution would be to set the first color to be PostHog app blue, then follow up with the rest of these?

Yeah the categorical data palette would apply when you have multiple categories. Otherwise, PostHog blue would be the default. I will clarify that.

**Comment by liyiy** [comment]
I think we talked about having a colorblind-friendly mode toggle on our app before, perhaps this could allow us to stick with our current color palette while still considering colorblind accessibility? In that case we can think about each color palette set as its own, without having to mix or "sacrifice" one for the other?

**Comment by clarkus** [comment]
Yeah we can absolutely have themes that adjust the interface to a user's preferences. Light themes, dark themes, high contrast, etc. There's also a case for themes specific to a visualization. I do think we should try to be inclusive by default. I'm going to hold off on this issue for the time being, but want to circle back to try a few other palette options once some higher priority issues are shipped.

**Comment by clarkus** [comment]
Cross-linking https://github.com/PostHog/posthog/issues/3679 for a more complete history of this work.

**Comment by mariusandra** [comment]
There's also https://github.com/PostHog/posthog/issues/1763

**Comment by clarkus** [comment]
Closed by https://github.com/PostHog/posthog/pull/9517#event-6588841919
