### ISSUE TITLE
Show only login options if account exists when accepting an invite

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#4077]
## Is your feature request related to a problem?

We already knew this was an improvement we needed to make, but a user reported frustration today on this. If I already have an account with PostHog and I receive an invite link to join a new org but open the invite link while logged out, I'll just won't be able to do anything. If I try to create an account I will get an error, and while there's a link to the login page, it's not obvious.

## Describe the solution you'd like

When you open an invite link, if you already have an account in that instance, we should tell you and just take you to the login page.

## Describe alternatives you've considered

Keeping as is.

**Comment by Pranavb333** [comment]
In posthog/api/organization_invite.py
```
def create(self, validated_data: Dict[str, Any], *args: Any, **kwargs: Any) -> OrganizationInvite:
        if OrganizationMembership.objects.filter(
            organization_id=self.context["organization_id"], user__email=validated_data["target_email"]
        ).exists():
            raise exceptions.ValidationError("A user with this email address already belongs to the organization.")
```

When trying to create a new invite, it raises an error if the user is already a part of the organization. When/how is an invite sent to a user who is already a member of the organization?

**Comment by Twixes** [comment]
Hey Pranav! Members of the organization don't have this problem. The issue comes up for those who have been earlier removed from the organization and are trying to rejoin it. Their account in the PostHog instance still exists, but people sometimes forget that, in which case they get an error when trying to sign up from the invite page.
The solution here is to:
1. When the invite URL is opened, the server should check if there already is a user in the PostHog instance that has the same email as the invite.
2. If there is such a user, the server should issue a redirect to `/login?next={that_invite_path}` so that the user has to log in first (as we know they can't sign up twice).

**Comment by Justicea83** [comment]
I've made a PR for this issue, but i get permission denied when I try to create a push for a PR. Can I be added as a contributor?

**Comment by Justicea83** [comment]
@neilkakkar can you assist?

**Comment by neilkakkar** [comment]
Hey @Justicea83 did you create a fork, or are you trying to push to a branch in this repo? - Just create a fork, push there, and make a PR from your fork to posthog :)

**Comment by Justicea83** [comment]
PR is ready, waiting for reviews and suggestions

**Comment by cvan** [comment]
@Justicea83 Now that PR #17917 is merged,  is this issue safe to close?

**Comment by Justicea83** [comment]
Not sure if there's supposed to be another secondary test. But if not, then we're all good!
