### ISSUE TITLE
Release 1.25.0 2/2

### ISSUE THREAD

**Issue by mariusandra** [PostHog/posthog#4089]
Priorities
- Core experience: Work towards parity with Amplitude, UX improvements
- Deployments & Infrastructure: Get 1-2 self hosted clients online & happy.
- Extensibility: See below

Support hero: Yakko

**Comment by mariusandra** [comment]
## Team Extensibility

Link to our internal planning issue: https://github.com/PostHog/plugin-server/issues/330

Big goals:
- Michael: Action/Event mapping in plugin server. Also webhooks and `onAction` https://github.com/PostHog/plugin-server/issues/235
- Marius~~Yakko~~: ~~Create async `onEvent` and `onSnapshot` functions for plugins, in addition to the sync `processEvent` https://github.com/PostHog/plugin-server/issues/328~~
- Marius: ~~Stabilise retry queues for production~~, add S3 and CH backends, retry `onEvent` and `processEvent` automatically https://github.com/PostHog/plugin-server/pull/325, https://github.com/PostHog/plugin-server/issues/273

Side quests:
- Michael: ~~Activate sample plugins (e.g. GeoIP) during onboarding PostHog/posthog#3764~~
- Michael: Help make some of the plugins from below.
- Yakko: add retries to the **javascript** library (for shaky internet connections, etc) https://github.com/PostHog/posthog-js/issues/199
- Neil~~Yakko~~: ~~Improve the **python** library, add $set_once and sentry PostHog/posthog-python#23~~ PostHog/posthog-python#13
- Marius: Improve the **ruby** library, add feature flags, basic autocapture, bring to parity with the rest
- Marius: ~~get a handle on all the "Still running "capture". Timeout warning after 30 sec!" errors that we get. I suspect kafka rebalancing causes this.~~

Plugins to create or improve:
- ~~Downsampling PostHog/posthog#3365~~
- ~~PostHog to PostHog export PostHog/plugin-repository#19~~
- Postgres export PostHog/plugin-repository#11
- Fix rudderstack export and document best practices (concurrency issues) PostHog/plugin-repository#15
- Solidify first time event tracker and/or add to core? https://github.com/PostHog/plugin-server/issues/315
- Add session end to session tracker plugin (via retry queues) PostHog/session-tracker-plugin#1

**Comment by EDsCODE** [comment]
**Core Analytics:**

**Buddy**: Rework how postgres [funnels query](https://github.com/PostHog/posthog/issues/4067) work and propose better querying pattern overall. Apply this across app if it seems necessary
**Eric**: Investigate data quality issues. Atleast finding answers to what might be happening to
- [Funnels inconsistent data ](https://github.com/PostHog/internal/issues/237)
- [duplicated users beyond just non merged users](https://github.com/PostHog/internal/issues/236)
- [Retention computation issue](https://github.com/PostHog/retention/issues/20)

**Li**: Begin first part of [dashboard sharing feature set](https://github.com/PostHog/posthog/issues/3551)
**Paolo+Sam**: Tackle this [UX improvement](https://github.com/PostHog/posthog/issues/4050) set. Increase/improve typescript coverage

Putting [group level analytics](https://github.com/PostHog/posthog/issues/2247) on the backburner dependent on how Eric and Buddy's work gets along. We're going to target insight usability improvement first and then push for more parity because group level analytics will require changes on frontend and backend

**Comment by fuziontech** [comment]
**Infra & Deploys:**

**Top priority for next week**
Onboard and support customers that JamesH throws our way for on-prem deploys.

**Side Quests**
- Story for backups for on-prem (MVP could be just EBS backups, but something more portable would be nice)
- Migrations for Clickhouse (Blocking team Extensibility)
- Test Clickhouse Operator horizontal scalability

Also should figure out whether we'll be focusing on GCP or AWS, which set of tradeoffs. @jamesefhawkins perhaps can help?

**Comment by jamesefhawkins** [comment]
> Also should figure out whether we'll be focusing on GCP or AWS, which set of tradeoffs. @jamesefhawkins perhaps can help?

My first reaction from customer calls is Bigquery comes up more often, and in that case they always want it in GCP to avoid data transfer costs.

I have asked someone at GCP about whether Redshift is more or less popular than Bigquery, to. 

We should do quick check of user notes to get this right too. + quickly ask paying customers if we don't have it in their notes

**Comment by timgl** [comment]
Retrospective

Extensibility
Went well, got the big things done

Core exp
overall good, still have to ship some stuff

Infra & deployment
- everyone was onboarded or opted out themselves
- Didn't get backups side quest done
- Got migrations done
- Didn't get scalability done
- Lots of stuff came in through the side door (AWS billing, instrument clickhouse cluster/fixing it)
- Need to get people Clickhouse Certified (TM)
