### ISSUE TITLE
Export CSV of user data from cohorts

### ISSUE THREAD

**Issue by Tannergoods** [PostHog/posthog#411]
***Thank*** you for your feature request - we love each and every one :)

**Is your feature request related to a problem? Please describe.**
I'd like non-technical people to be able to easily export cohorts data 

**Describe the solution you'd like**
Within the PostHog UI I'd like to export data as a csv from Cohorts specifically - this would take the Cohorts data so user id, perhaps I'd have to define the elements and properties that would go along with this as I might not want a users entire event history.

**Describe alternatives you've considered**
Copy and paste would work with small cohorts but I expect this to be larger

**Additional context**

**Comment by timgl** [comment]
Was this requested by anyone specifically? I'm trying to understand whether it's just about getting a list of users with their properties, or if it also needs to have an export of the events that belong to that user?

**Comment by Tannergoods** [comment]
Apologies - yes - https://app.hubspot.com/contacts/6958578/contact/43351

It only explicitly mentions "easily export CSVs of user data from the cohorts feature"

**Comment by Tannergoods** [comment]
Further context in response to do you want users event history?

"Yes, very. This is annoyingly hard to do in Mixpanel – in Mixpanel you have to a list of users first, then query the events API again for each user. The fact that this is a relative pain to do means we do it less often than would be ideal.

For us the most important thing is just easily getting the list of users who did X (with all their user traits), but the ability to get all the event data would definitely be a useful addition.

A concrete use case that’d be valuable for us: our 1-1  team prioritises leads partly based on their website engagement. It’d be great if we could query for all users that did event X more than 10 times, and then get a list of all the matching users plus all the event Z’s they did. Event Z might be our “read page” event, which has the particular page URL as a property"

**Comment by timgl** [comment]
## Backend

I'd be great if we could do something like `/api/cohort.csv` to get an automatic CSV. [There's a package for django-rest-framework](https://github.com/mjumbewu/django-rest-framework-csv) that will serialize into CSV, but I'm not sure how this handles the csv side of things.

## Frontend
Pretty simple, just an export button that links to the csv.

**Comment by anoopemacs** [comment]
@timgl  Which of the two would be a better choice for a backend endpoint:-

`/api/cohort.csv` : Since we already have a `/api/cohort` endpoint, this would require choosing the serializer class dynamically based on `request.accepted_media_type`. This can be done easily by DRF `get_serializer_class` method on the viewset

`/api/export` :  Define a new endpoint which delivers the csv

Just needed a RFC on dynamically choosing Serializer v/s defining a traditional new endpoint

**Comment by timgl** [comment]
`cohort.csv` would be much better as we have a lot of endpoints like that we could easily export

**Comment by anoopemacs** [comment]
Since we are always exporting a list of `person` for each cohort's `PeopleTable`,
IMHO `/api/person.csv` might be a better choice for this endpoint.

This would turn out analogous to the way we are currently fetching data from `/api/person` 
[from the frontend](https://github.com/PostHog/posthog/blob/master/frontend/src/scenes/users/People.js#L18-L21) for each cohort's detail view

That said, if end users are explicitly typing out a url to fetch a cohort csv file, then `/api/cohort.csv` is more intuitive. This shouldn't be of concern if they are always using it by clicking an export button.

**Comment by timgl** [comment]
Done!
