### ISSUE TITLE
Cannot search for new events/properties in events page

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#4114]
## Bug description

I recently added a new event type I want to track to make sure I receive.

Going to the events page I can see that event sometimes in, but can't:
- Find it in event search box
- Find unique properties to it in the filter box

## Expected behavior

Events show up immediately in search box

## How to reproduce

1. Send a new custom event
2. See it in events view
2. Try search for it, fail

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

## Additional context

cc @paolodamico - might be related to event type/properties caching?

**Comment by paolodamico** [comment]
Yeah I think this is something we were anticipating it would happen for a couple of days until https://github.com/PostHog/plugin-server/pull/331 gets merged. Problem is the sync task runs on every `Team` model update (with a signal) that happens on the web or worker, but because these properties are updated from the plugin server, sync might be delayed. Though I hope the PR lands soon as this won't be a problem anymore.

**Comment by paolodamico** [comment]
I think this has been addressed now? @macobo
