### ISSUE TITLE
When removing the default 'pageview' action, dashboard items fail.

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#412]
**Describe the bug**
When creating a team, we automatically create a 'pageview' action. If that gets removed, the corresponding dashboard item fails.

**To Reproduce**
1. Create new team
2. Remove the pageview ction
3. go to dashboard

**Comment by manuelfcreis** [comment]
## Issue
The issue here seems to be two-fold:

1. The error message when the dashboard item fails to get the necessary data isn't very clear.
2. When deleting an action, the associated dashboard items are not affected in any way, when they should be either deleted or updated accordingly


## Solution
I propose the following:

1. Separate the *delete* and *update* functions for actions.
2. When deleting an *action* check which dashboard items use it and update them accordingly.
3. Update error messages when dashboard items fail to load

@timgl Does this seem reasonable to you?

**Comment by timgl** [comment]
I'm actually okay for the dashboard items _not_ to be updated when you delete an action, as I think that logic could get complicated. For example, if there's a dashboard item with 2 actions, and you delete one of them, do you delete the entire dashboard item or just silently update it?

Just having a better error message I think would be enough.

Also could you elaborate on point 1 of your solution?

**Comment by manuelfcreis** [comment]
> If there's a dashboard item with 2 actions, and you delete one of them, do you delete the entire dashboard item or just silently update it?

If we delete an action that affects an item with 2 actions the dashboard item stops working all together. In terms of experience I think it would be better that it continues working, with the deleted action removed rather than stop working altogether.

> Also could you elaborate on point 1 of your solution?

Typically **Update** and **Delete** functions are separated. Specially since they may require different processes being activated. i.e. Deleting a user can trigger a lot of cascading effects on the database but doesn't a lot of validations. Updating a user shouldn't impact other tables but does require validations to ensure that the data is correct.

This doesn't need to be done in this particular bug fix but it's something to consider

**Comment by timgl** [comment]
> If we delete an action that affects an item with 2 actions the dashboard item stops working all together. In terms of experience I think it would be better that it continues working, with the deleted action removed rather than stop working altogether.

I agree with this! I think it might be easier to just ignore that action rather than update it, but I am happy to let you make a decision here on what you think is easiest/best

> This doesn't need to be done in this particular bug fix but it's something to consider

The reason for this pattern is it allows you to undo a deletion using that toast-popup, which is much better from a UX point of view. It's also another reason I'm in favour of not updating dashboard items, as that's hard to undo.

Again, up to you how you want to tackle this!
