### ISSUE TITLE
Update design of tooltips

### ISSUE THREAD

**Issue by corywatilo** [PostHog/posthog#4156]
EDIT: This issue now encompasses only the UI/implementation for tooltips only. The main chart components are encompassed in #4758.

At @paolodamico's request, I put some thought into making graphs more visually appealing. After some [research](https://docs.google.com/document/d/1pHshHgMQYs14xLd24s5L4z6ouEv1fjnL3qAt4RjMXl8/edit?usp=sharing), I landed on this:

![image](https://user-images.githubusercontent.com/154479/116491587-3ab5f300-a868-11eb-8fad-e1bae7247dda.png)

**Comment by paolodamico** [comment]
I absolutely love this!! CC @samwinslow @EDsCODE, what are your thoughts on this? We could add this next.

**Comment by samwinslow** [comment]
I don't think it would be too hard to add a gradient to the graph shape, but if we're changing it anyway, this library looks super cool: [https://airbnb.io/visx/gallery](https://airbnb.io/visx/gallery) — it's also very declarative in its code style.

**Comment by EDsCODE** [comment]
I think this would be a great improvement! The one thing I would anticipate is slightly tricky is the tooltip styling and maybe the vertical line on hover but I could be mistaken. (Just inferring from the limitations we have using chartjs). 

One extra thing we could have a better visual of is this case when there are a ton of lines. We have the legend that allows you to toggle lines on and off but when you're hovering perhaps we should hide/grey out lines that aren't in focus? 
<img width="611" alt="Screen Shot 2021-04-29 at 9 44 00 AM" src="https://user-images.githubusercontent.com/13127476/116560690-9d8ea500-a8cf-11eb-84b9-547ffd7306e5.png">

**Comment by samwinslow** [comment]
Tooltips + vertical line actually seem [pretty easy](https://airbnb.io/visx/areas):

<img width="860" alt="Screen Shot 2021-04-29 at 9 52 16 AM" src="https://user-images.githubusercontent.com/4645779/116562548-3ffb5800-a8d1-11eb-9e60-de68a1a40176.png">

**Comment by EDsCODE** [comment]
Ohh if we're keen on changing libraries for sure

**Comment by samwinslow** [comment]
Sub-issue: #4344

**Comment by samwinslow** [comment]
Progress update: Managed to get this going without switching chart libraries!

<img width="992" alt="Screen Shot 2021-05-25 at 12 08 55 PM" src="https://user-images.githubusercontent.com/4645779/119531652-22939f80-bd52-11eb-85b2-b474c170b071.png">

TODO (somewhat of a note-to-self):

- [ ] Day format on axis labels & tooltip
- [ ] Icon on "Click" CTA
- [x] Add `PropertyKeyInfo` so that tooltip doesn't show things like `$pageview`
- [x] Bugfix overlapping chart series for "predicted" values — shows duplicate entries in tooltip
- [x] Revert to small inline numbers
- [x] Add Tags (Unique Users, Total [shown only if multiple series])
- [x] Table revamp (separate issue)
- [ ] Max-height and scrollable box

**Comment by paolodamico** [comment]
Love this, looking great @samwinslow! Wonder if we can add the subtle background too with this library.

**Comment by samwinslow** [comment]
@corywatilo Do you have any advice for how to make this look better at a very high data density?

Eric suggested having each line isolate itself by reducing the opacity of the _other_ lines on hover; but this isn't an ideal approach IMO because it kind of defeats the purpose of the scrubber bar, which is great for comparing data.

From user feedback, it was annoying to mouse over different specific areas of the screen such as individual points; having each line have a separate hover-scrubber interaction would introduce this same problem again.

For example, pretend all these datasets have different filters.

<img width="1230" alt="Screen Shot 2021-05-25 at 3 48 04 PM" src="https://user-images.githubusercontent.com/4645779/119559463-b5dbcd80-bd70-11eb-8b26-a3551012f8a9.png">

It starts looking ugly when more verbose filters are applied... would you mind mocking up a typography treatment with this in mind?

<img width="367" alt="Screen Shot 2021-05-25 at 3 52 12 PM" src="https://user-images.githubusercontent.com/4645779/119559865-369ac980-bd71-11eb-8532-3aa98237b626.png">

**Comment by paolodamico** [comment]
For starters I think we can simplify the text (e.g. "Pageview ($current_url ..."), I was actually going to work on an issue today just to work out how to improve that copy in a way that makes sense for non-technical users too. If you can give me a couple of hours here, might be able to help.

**Comment by samwinslow** [comment]
@paolodamico Just pushed another commit which makes the filter property keys human-readable; that part is pretty simple.

Previously I introduced the `disableIcon` prop for PropertyKeyInfo, so can render `<PropertyKeyInfo disableIcon value={someString} />` and it will humanize the text if such a value is known.

I wonder if there's a better way to represent the string `Event Title (Aggregation) (Key = Value, ...)`. Maybe [antd Tag](https://ant.design/components/tag/) instead of parentheses?

**Comment by paolodamico** [comment]
Which branch/PR? But yeah, let me explore a little bit and get back to you on this.

**Comment by samwinslow** [comment]
> Which branch/PR? But yeah, let me explore a little bit and get back to you on this.

`4156-improved-graphs` is the branch and `4156-new-graph-ui` is the feature flag to enable.

**Comment by paolodamico** [comment]
Here's my stab at tooltips following the proposal on #4492 in terms of series naming conventions. I also account for the possibility of having a ton of different series in the same graph. [Figma](https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf/PostHog-App?node-id=2207%3A16554).

### Simple breakdown
<img width="1152" alt="base" src="https://user-images.githubusercontent.com/5864173/119718644-aa45e080-be1c-11eb-8dee-5ec25a8e230a.png">


### Multiple series
<img width="1152" alt="multiple-series" src="https://user-images.githubusercontent.com/5864173/119718652-ac0fa400-be1c-11eb-9d3c-c1e5e3c3116c.png">

### Multiple series with breakdown
<img width="1152" alt="multiple-series-breakdown" src="https://user-images.githubusercontent.com/5864173/119718663-b2058500-be1c-11eb-93b5-2c6f1e3c1637.png">

**Comment by corywatilo** [comment]
Related: Mocked up a version with multiple plotted lines in #4514, each with a fill being a gradient using the primary color of the line. ([Figma mock for reference](https://www.figma.com/file/9yWtngNb1AIuf6KmXaEPJA/App-doodles?node-id=80%3A172))

Note: Probably use new line styles, not specific colors from this linked conceptual mock.

**Comment by samwinslow** [comment]
Screenshot showing tooltip and legend adjustments, including Series badge. Almost all of this can be reused regardless of charting library -- Check out branch `4156-improved-graphs` and feature flag `4156-new-graph-ui`!

![Screenshot from 2021-06-03 20-34-56](https://user-images.githubusercontent.com/4645779/120728571-415d0900-c4ab-11eb-8ed2-ec7edb542eb1.png)

**Comment by paolodamico** [comment]
Released FF right now for **users only in PostHog Cloud**: PostHog Team, Beta Users & 20% of user base.
