### ISSUE TITLE
Allow Trend break downs by DOM element properties/attributes

### ISSUE THREAD

**Issue by alex-ketch** [PostHog/posthog#419]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to break down a Trends report by the DOM properties found, and already captured, in the event.

**Describe the solution you'd like**
Exposing a DOM element filter in the `Break down` section would allow for a high-level overview, but allowing for combinatorial selectors (similar to the `Filter` section with multiple dropdowns) to select which property/attribute to use for bucketing would enable more focused views.

**Describe alternatives you've considered**
- Alternatively using the full `$event_type` string as shown in the Actions view for comparison (`click` vs `clicked <option> with text "Python"`)
- Currently it would be possible to create a different event for each variant to be tracked, but this would require manual updates each time a new option is added.

**Additional context**
In my current case, I have a custom action tracking when a user selects on option from a dropdown. 

![Screen Shot 2020-03-30 at 11 54 58](https://user-images.githubusercontent.com/1646307/77934383-00051400-727e-11ea-9576-7c59b8771a01.png)

Ideally I would like to generate a report showing a comparison between the frequency of each option without having to create a separate event for each.

**Comment by timgl** [comment]
@alex-ketch thanks for raising this. I agree we should do this.

## Solution 1

We just query the elements directly. 

Annoyingly I did not create a direct relationship between an `ElementGroup` and an `Event`, I just text-match the hash. Otherwise we could have done `element_group__element__text` in `properties_to_Q`. Now, this will probably involve doing a subquery.

When we hit `/api/event/properties/`, we'd now have to stuff in the possible element properties, which also doesn't feel right to me.

## Solution 2

We could save some of the crucial attributes, like 'text' of the first element, against the event. This might actually @alex-ketch 's specific use-case. I'm struggling to work out whether there's any other attributes that we'd need to store?

This would be a lot easier to implement, but might not hit some future use-cases

**Comment by timgl** [comment]
@alex-ketch Do you have an opinion on the above? Would you only be interested in the text or do you think you'd want any other properties?

**Comment by alex-ketch** [comment]
Hey @timgl, I think in the long run more properties would streamline trend report generation, but I'm not sure what your product thinking is and if you want to enforce users define a custom _Action_ for each type.

What I mean is, personally I would find it easier to make sense of the data if I could do some exploration at the _Trend_ creation stage, rather than having to go back to the _Actions_ to define a data point before I could visualize it.
For example, having an action for Anchor links/Button clicks, I can see myself wanting to visualize breakdowns for the `href` tag, or even class/ID to see if a certain color style is having an impact on click rates at the Trend report view, keeping only a generic "Button Click" event around.

Let me know if this makes sense, of you'd like me to elaborate further.
Thanks for taking all of this into consideration btw!
