### ISSUE TITLE
Insights UI improvements based on user feedback

### ISSUE THREAD

**Issue by samwinslow** [PostHog/posthog#4341]
## Is your feature request related to a problem?

Users have described some simple requests with the new design (#4050):

1. Save to Dashboard button is unclear, small; should be more prominent
2. Clear Query would be nice, especially for unsaved queries. Resetting everything is a pain.
3. Reorder property, operator, and value selectors based on @kpthatsme's input and user feedback

<img width="1145" alt="Screen Shot 2021-05-13 at 2 46 51 PM" src="https://user-images.githubusercontent.com/4645779/118172177-10cd0680-b3fa-11eb-8db6-cc71c9d6b389.png">

I intend to add to this issue as we continue interviews, but generally more complex features/fixes will get their own issues.

**Comment by kpthatsme** [comment]
> I intend to add to this issue as we continue interviews, but generally more complex features/fixes will get their own issues.

@samwinslow  I hope it's okay if I add a thought I had here, let me know if I should make a separate ticket.

One thing for me, I've noticed I continuously expect the Event to be the first thing in the UX when modifying the query.

The flow of picking an event --> choosing a property agg --> having the property box pop in between event type and the query type toggle is a little jarring. 

I think if we could always have the event selector in the same place and fill in things to the right of it would be a smoother UX.  Especially since we still have the rest of the filter options on the right side of the event.

**Comment by samwinslow** [comment]
Totally @kpthatsme! We heard 2 potential users give essentially the same feedback. Will reorder these elements.
