### ISSUE TITLE
Formulas + breakdown doesn't work.

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#4399]
## Bug description

See [this graph (internal link)](https://app.posthog.com/insights?insight=TRENDS&actions=%5B%7B%22id%22%3A4912%2C%22math%22%3A%22dau%22%2C%22name%22%3A%22Discovered%20Learning%22%2C%22type%22%3A%22actions%22%2C%22order%22%3A0%2C%22properties%22%3A%5B%7B%22key%22%3A%22realm%22%2C%22type%22%3A%22person%22%2C%22value%22%3A%5B%22cloud%22%5D%2C%22operator%22%3A%22exact%22%7D%5D%2C%22math_property%22%3Anull%7D%2C%7B%22id%22%3A7307%2C%22math%22%3A%22total%22%2C%22name%22%3A%22Insights%20Error%20or%20Timeout%20-%20Cloud%22%2C%22type%22%3A%22actions%22%2C%22order%22%3A1%2C%22properties%22%3A%5B%5D%2C%22math_property%22%3Anull%7D%5D&display=ActionsLineGraph&formula=B%2FA&interval=week&date_from=-90d&filter_test_accounts=true&properties=%5B%5D&breakdown=realm&breakdown_type=person#fromItem=190864&fromItemName=%23%20Errors%20Seen%20%2F%20Activated%20User%20-%20Cloud&fromDashboard=3346)

Using formulas + break down doesn't work.

## Expected behavior

Should work.

## How to reproduce

1.
2.
3.

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

**Comment by macobo** [comment]
Might be solved by https://github.com/PostHog/posthog/pull/5444 - will need to test after merging.

**Comment by macobo** [comment]
This is a different breakdowns bug than the above-linked one. 

Sentry issue: https://sentry.io/organizations/posthog/issues/2491253352/?project=1899813&query=is%3Aunresolved+assigned%3A%23team-core-analyticshttps://sentry.io/organizations/posthog/issues/2491253352/?project=1899813&query=is%3Aunresolved+assigned%3A%23team-core-analytics

```
ServerException
Code: 47.
DB::Exception: There's no column 'sub_B.data' in table 'sub_B': While processing sub_B.data. Stack trace:
```

**Comment by Twixes** [comment]
I see what this is about. We've already got combinations of breakdown + formula tested in https://github.com/PostHog/posthog/blob/master/ee/clickhouse/queries/trends/test/test_formula.py#L162-L187 (partly thanks to #5444), but not this one:

When one of series (in this case B) has 0 events in the period, a formula without breakdown returns "We couldn't find any matching events." as expected. But a formula WITH breakdown doesn't cope with this, and the formula subquery (`sub_B`) for the eventless series is a wrong `SELECT 1` (due to the way breakdown determines this subquery based on top breakdown values), and this is where `There's no column 'sub_B.data' in table 'sub_B'` comes from. I'm fixing this.

**Comment by macobo** [comment]
@Twixes I had a minor bit of work done but feel free to take over. Assigned to you :)

**Comment by Twixes** [comment]
Oh, wasn't In Progress so I just took it.
