### ISSUE TITLE
Audit of App homepage UX and Design

### ISSUE THREAD

**Issue by lottiecoxon** [PostHog/posthog#4479]
In response to the board meeting discussion and our new aim of delighting 5 companies, I have taken it upon myself to take a look at our apps look and feel. Focusing on design mostly and a small bit of UX.

**Comment by lottiecoxon** [comment]
I have spent today working on [this](https://www.figma.com/proto/gQBj9YnNgD8YW4nBwCVLZf/PostHog-App?page-id=978%3A0&node-id=2170%3A1&viewport=-576%2C226%2C0.13269060850143433&scaling=min-zoom) - researching into our design as well as our customers dashboards. Through doing so I wanted to see what issues we have with our design and how our customers design their dashboards, allowing us to improve our design. I would love any ideas or suggestions if you have any! At the moment this is purely a discussion just to see what the design team should focus on  in order to help us 'delight'.

**Comment by corywatilo** [comment]
I think there some great UX points in here. Worth considering for anyone already planning a cycle on the Home tab.

For now I think we should decouple the visual design elements from the UX issues. @paolodamico and I were working on some visual concepts recently (seen below - still needs _a lot_ more though - it's just a proof of concept).

So for now, it would make sense to keep the focus on issues that will make users more successful. Definitely a lot of opportunity on the visual front when it makes sense!

![new ui](https://user-images.githubusercontent.com/154479/119531838-5242a780-bd52-11eb-81b1-47efcb652781.png)

**Comment by joethreepwood** [comment]
@lottiecoxon I was thinking about this topic today while doing some research too. I was wondering if we have looked at all at how the focus customers are using the app in particular, even if only from interviews. 

@paolodamico Is there any chance you've recorded interviews with the focus customers? That may help add to my research and the above.

**Comment by paolodamico** [comment]
It's great that you took the time to go through this @lottiecoxon! Particularly the analysis of these customer's platforms provides super valuable insights! Already grabbing some takeaways to improve the insights experience. My biggest takeaway too is on the dashboard & graphs colors, which is something that really needs some improvement. Hoping to work on that with @corywatilo too.

Re @joethreepwood unfortunately I don't think we have any recorded calls, though we have notes from all calls centralized in Hubspot.

**Comment by samwinslow** [comment]
@paolodamico Customizable colors in graphs could add a lot of value — since I'm working on graphs this cycle anyway, I could see about fitting that in. Seems like almost every user of the Insights tests had something to say about that.

**Comment by paolodamico** [comment]
Totally agree is worth considering! Perhaps the biggest challenge here is coming up with the colours. @corywatilo maybe you could help with this ?

**Comment by kpthatsme** [comment]
Hey @lottiecoxon great analysis!

So in general, project home has been a good experiment that drives positive outcomes, but I don't think we should invest in another iteration of the same page – I think we should try to take our learnings and apply them into a better page thats part of a more holistic navigation (the work @corywatilo shared is exciting!). 

I think project home has been serving mainly as a bandaid to some onboarding and navigation problems in our app. We see new users engage with it a fair amount, but over time as people become familiar with our application, the page becomes less and less relevant and at some point it probably crosses the threshold from helpful to friction – since most people, at the point of familiarity probably know where they want to go in our application, and currently the experience doesn't do a good job for those people (for example, do they _really_ need the individual analysis type buttons? Probably not –especially if we have a revamped main nav) 

I'd love to get your thoughts on what a revamped page could look like, or even work together to put some different mocks together and see how we like them. 

For general contents of the page (just the contents– not necessarily organized like this), I'm thinking:
- A section for Pinned dashboards 
- An insights section – an area to access saved charts and recent unsaved work 
- A smaller feature flag section – an area on the page that shows how many feature flags are enabled and maybe some additional info ie.the time your feat flags were last updated
- A smaller plugins section - an area on the page showing how many plugins you have running – maybe additional info such as errors, last successful run time
- _maybe_ something around community / tutorials 

For the feature flag and plugins – they don't need as much visual real estate as the insights sections since there is a lot less to consume but we _probably_ want them to be ever present or at least above the fold in what we come up with.

In my opinion we can focus here first, create a version we're happy with for engaged users and then incorporate those into the version for new users. I'm less concerned about the new user version right now since the page is pretty oriented to onboarding and does a decent job at that – also that state is not that relevant for the focus users.

@lottiecoxon sorry this was a lot – let me know if i should file a more specific ticket where we can iterate through some flows or anything else that would be helpful!

**Comment by paolodamico** [comment]
A lot has changed since this review and @clarkus is already working on newer designs, think it's fine to close this for now. Feel free to reopen if you disagree.
