### ISSUE TITLE
Using TimescaleDB

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#458]
We keep running into various issues with super slow Postgres queries. Mike from TimescaleDB reached out to me and I'm going to have a chat with him this afternoon, but wanted to do a bit of exploring before.

## Nested loops

A lot of our problems seem to come from doing nested loops. For example, in a cohort we want to know which People have done a certain event. We can actually get a list of those events once, but then the checking of that still causes an index scan that takes a long time: 
![image](https://user-images.githubusercontent.com/1727427/78553801-d447d800-7801-11ea-9c56-376d5756d475.png)

I wonder if TimescaleDB has a solution for this kind of problem or not?

**Comment by arianitu** [comment]
So any analytics system that I've used that does not support downsampling usually runs into slow queries eventually. It's usually fine for the first couple of million events (10 million) and then everything breaks (around 100m - 1 billion events). Analytics systems designed with 1 table do even worse (and it appears this one is done that way using an Events table)

```
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(blank=True, max_length=200, null=True)),
                ('properties', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('elements', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posthog.Team')),
            ],
        ),

```

I searched "downsample" in this project and I see nothing which means that it probably won't scale that well (from my own experience.) I've experienced this with every system I've used so far and I am actually not sure of an analytics system that supports it out of the box correctly. InfluxDB kind of does, but you write your own downsampling queries (annoying, should be automated.)

I am unsure why most analytics systems don't inherently support some downsampling system that takes the aggregation queries and runs them daily saving the previous results. I know it's easier to have all date ranges but when you're inserting 1M events / day, your yearly queries breakdown horribly and the system craps out. 

Do you guys have plans to support downsampling? I saw this project and was excited that someone took a shot at an open analytics system since I'm sick of implementing them on projects or using 3rd parties, but it appears the database layer maybe be naive as it stands.

**Comment by timgl** [comment]
@arianitu Thanks for your comment!

Downsampling makes sense for something like Google Analytics as there you really only care about topline numbers (like total visitors, session length etc).

The problem with product analytics is you want to be able to dig into each individual user to work out what they're doing and how they're using the product. Downsampling means you'll be throwing away some of this data at random.

Re: the one table architecture, this was actually part of the reason for looking at TimescaleDB, as they have this concept of "Hypertables", which are composed of many smaller tables subdivided by time. In theory using that should alleviate some of those concerns.

That being said, Postgres, even in it's current one-table architecture, is the right choice for the vast vast majority of people. For anyone going beyond what Postgres can handle, we do plan on integrating other databases. We already did ClickHouse as a PoC a while ago.

**Comment by 14MR** [comment]
I have some experience with ClickHouse and I'm sure that it will perform well on this kind of task. 

Where can I take a look at the PoC?

**Comment by timgl** [comment]
@14MR [It's here](https://github.com/PostHog/posthog/compare/WIP-clickhouse-integration?expand=1#diff-6896d517c56f5677f72af3ce0d0bf933), though it's very far out of date with the current codebase and we'd basically have to start from scratch.

The nice thing however is that ClickHouse does have a Django ORM, so that makes life quite a bit easier.

**Comment by 14MR** [comment]
I've found only [1 library](https://github.com/carrotquest/django-clickhouse) offering an interface similar to Django ORM and it has only 15 stars and only 1 contributor. Isn't it too risky to build new functionality on top of it?

**Comment by timgl** [comment]
Fair point! In fairness all this library has to do is convert some Python into SQL so I'm not too worried. But as mentioned this was a PoC and this isn't at the top of our todo list at the moment. If someone in the community wanted to pick this up that'd be awesome!

**Comment by 14MR** [comment]
Actually, implementing Clickhouse support will depend on implementing delayed processing of events mentioned in #455 since you have to insert into Clickhouse via batches not row by row. So, probably it's better to discuss implementation after implementation of workers.

**Comment by Twixes** [comment]
We're already invested into ClickHouse (#1590), so this matter has been pretty much settled. :)

**Comment by tucnak** [comment]
@timgl Pardon me asking, but where's that screenshot of yours is coming from? I would assume that is some kind of  pg_stat_statements based GUI however I would really, really like to know what it is and for sure. We've longed for something like it but never quite found the suitable tool.

/offtopic
