### ISSUE TITLE
Disable/de-emphasize toolbar, autocapture and session recording

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#4588]
## Is your feature request related to a problem?

The type of user we are focussed on right now will get bad results from using any of those 3 features as we aren't supporting them as well. We should be super focussed on having a great experience for core insight views, but these features will make the product feel more broken.

## Describe the solution you'd like

- [ ] Disable toolbar by default
- [ ] Remove toolbar from navigation (hide somewhere else?)
- [ ] Disable autocapture by default (probably in /decide endpoint, will need to add a boolean in team.py)
- [ ] Remove the "Play recording" column from Sessions if not turned on

## Additional context

cc @paolodamico @jamesefhawkins

**Comment by neilkakkar** [comment]
About autocapture: I find it to be a great way to get started, without setting anything up yourself (except, well, the snippet). I think it's cool to focus on core insight views, but maybe not make it harder for new users to get onboarded?

I.e: keep autocapture on by default so people who just join don't see empty data points vs some $pageviews.

Another alternative here is to disable it by default, but make it extra clear for first time users to enable it in the documentation: make it a part of onboarding with the snippet.

Actually, this alternative feels like the best of both worlds -> ensures focus customers with their own analytics don't get autocapture noise, and new users who don't. have data are told to turn it on so they get *some* data thanks to autocapture.

**Comment by mariusandra** [comment]
@timgl @jamesefhawkins Please correct me if I'm terribly wrong somewhere.

My worry is that we are going too far with the "delight these 5 big customers and these 5 customers only" mentality. I know that nobody explicitly said "**only and exclusively** these 5 companies", but what seems to be happening is that with the current attitude we're moving further from our open source "product analytics for the little guy/gal" and "no-brainer" roots. 

This is to say I'm hesitant to do breaking changes for other users in (blind?) service/delight of the big 5.

Regarding the four points:

> Remove the "Play recording" column from Sessions if not turned on

Makes sense. This is the wrong place to teach people that session recordings are a thing.

> Disable autocapture by default (probably in /decide endpoint, will need to add a boolean in team.py)

Autocapture it is still really really useful. I'm super happy that I can effortlessly observe traffic for kea.js.org without any setup. I'll instrument the code with custom `data` attributes when I want to make an action (better in-place docs needed), but the wow effect of just having this visibility to your traffic with no setup can not be overstated.

That said, toggling autocapture via posthog (not via flags in the JS snippet) is something that I've heard requested before. Could we have this as a opt-in during project setup, like we do with session recording? I'd still default it to "enabled". Customers who want to only send custom events, will disable it, the little guy/gal with his/her tiny webshop will leave it at the default "wow" setting.

> Remove toolbar from navigation (hide somewhere else?)
> Disable toolbar by default

Disagree with removing the toolbar from navigation. While it's used by a bit less than <10% of users, and is slightly broken, it still serves a purpose and should accessible when you need it. For kea I don't check the heatmap all the time, but every few months it's valuable to look at. Removing this feature altogether or making it really hard to find seems to be a bad move.

**Comment by paolodamico** [comment]
Great that we're thinking about this!

1. Re session recording, I would've agreed one week ago, but the strategy has evolved since and focus on this will be important to make funnels more successful (see https://github.com/PostHog/product-internal/issues/86). I do agree, this is not the place to prompt users to activate the feature, but until we bring back the setup page (or something that fulfills this function) I think it's worth keeping.
2. Re autocapture, I agree with Marius. The feature is still quite powerful and quite widely used. We just had for instance [a customer call](https://docs.google.com/document/d/1762fbEbFOVZUr24jQ3pFFj91ViY72TWrTgD-JxRJ5Tc/edit#heading=h.jseqiobq2847) with someone who would fit our target persona and they were very keen on autocapture. I also think that other than UX concerns around actions, the experience is pretty solid.
3. Re toolbar, I agree with disabling it by default as it's still not strong enough. Particularly if we keep the menu item, as it's quite easy to enable if you have a use for it.
    3.1 Re the menu item, I'm on the fence. I think what I'd do here is switch it to something like "Heatmaps" which is the core value of the toolbar, and will also increase discoverability for that feature. When using the toolbar to add actions you will either access it through the actions page, or go directly to your website if you already know what you're doing. Thoughts here? CC @corywatilo @marcushyett-ph  too.

**Comment by marcushyett-ph** [comment]
I'm not sure I fully understand 3. Can you explain what "being disabled by default" would actually mean? e.g. how would they learn about it to turn it on?

I'm not sure I have quite enough context about the toolbar today to give opinions on 3.1

**Comment by mariusandra** [comment]
3. Re: renaming. Currently the toolbar provides two core values: 1) heatmap and 2) selecting elements when creating actions. The idea was to have more things, e.g. in-page stats, feature flags you can toggle on/off, etc. If we'd have them, it'd make sense to teach users about "the toolbar" as the place where you access all of posthog's "on-site" content.

If we'll build some of the other toolbar development in the next months, I'd keep the menu element as "toolbar" to avoid the confusion in renaming it for a release or two. And otherwise, there are still actions.

---

@marcushyett-ph disabling by default means that the "hedgehog floaty button thingie" won't automatically show up on mysite.com, but you'll have to click the link in the sidebar first... and enable it. Then it'll automatically show up on mysite.com next time you visit.

**Comment by marcushyett-ph** [comment]
@mariusandra thanks for the context - "hedgehog floaty button thingie" is definitely the best description of anything I've heard at PostHog so far.

**Comment by paolodamico** [comment]
Re @mariusandra agree with the premise but I realistically don't see us adding a new feature in the next ~2 months. We're focusing on funnels at least until early August.

**Comment by mariusandra** [comment]
@marcushyett-ph I aim to omit needless words

**Comment by timgl** [comment]
There's actually no point in doing this PR. The toolbar doesn't automatically appear, it'll only appear once you've clicked Toolbar in the sidebar and selecting a URL.

![image](https://user-images.githubusercontent.com/1727427/122758210-d1b39000-d298-11eb-8bf3-c52cb5b10c2b.png)

Sorry for the confusion!

**Comment by paolodamico** [comment]
I think we can close this now. We've refreshed focus on session recording & toolbar (currently used by a couple of focus customers).
