### ISSUE TITLE
Concept - Aggregation plugins 

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#4613]
## Is your feature request related to a problem?

Plugins are pretty powerful to manipulate data coming in, yet I may want to extend this functionality to get more robust analytics that I can share on other places (see examples below). The key thing to consider here is that I may want to run analysis on a larger scope than a single event.

## Describe the solution you'd like

For instance, I may want to have in my CRM information around how many days has the user been active in the last week. Or information on my customer support platform around the last session duration. Or the number of `$exception` events in the last 3 days. 

Another interesting thing to consider is whether it might be useful to have that information both available as user properties, dynamically-calculated properties for internal analytics. 

## Describe alternatives you've considered

I could build my own service that processes by continuously hitting PostHog's API or DB and then updating the downstream app.

## Additional context

Suggested by a Big 5 (not a request, just a suggestion to consider).
Related to #3357

**Comment by mariusandra** [comment]
The issue here is that all those "data aggregation" use cases are very specific and each require a slightly different way of aggregating data.

> For instance, I may want to have in my CRM information around how many days has the user been active in the last week.

Here I'd make a plugin that takes the user's properties, checks `$active_on = ['2021-05-11', '2021-05-18', ...]` and either adds today if missing, or trims it to just the last 7 days.

> Or information on my customer support platform around the last session duration.

This requires the [session tracker plugin](https://github.com/PostHog/session-tracker-plugin) and then a custom plugin that emits whatever is needed when getting the "Session end" event.

> Or the number of $exception events in the last 3 days.

We can tally them as they come in, or make an API call to get the count. The latter is probably more accurate and fast enough in this case.

....

This is all to say: I'm not sure what common abstraction we can build to help users, other than the one that we have already built (called plugins :D).

Since nobody really asked for anything explicitly tangible here, I propose we punt :).
