### ISSUE TITLE
"Can't find DragEvent" error on mobile web

### ISSUE THREAD

**Issue by andyzg** [PostHog/posthog#4671]
## Bug description

We've been getting a lot of errors from Sentry with the following
![image](https://user-images.githubusercontent.com/3849459/121405241-a84a4a00-c911-11eb-99cd-360ab3db0c2a.png)

Upon saving the client side source code, I grep'ed DragEvent and could only find an instance of it from posthog's source code. This only happens on certain mobile browsers.

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  

## Expected behavior
DragEvent shouldn't be accessed as a variable unless it's defined.

## How to reproduce

Unable to reproduce given that I don't know the code path that triggers DragEvent. I currently get it via Sentry.

## Environment

- [X] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

**Comment by mariusandra** [comment]
We also have [one such report](https://sentry.io/organizations/posthog/issues/2449319322/?environment=production&project=1899813&referrer=alert_email) in our sentry.

It seems the bug comes from the the session recorder (`recorder.js`). Possibly updating `rrweb` in posthog-js might fix it... To be continued.

**Comment by andyzg** [comment]
Hey @mariusandra , any ideas on whether this would break the web app? We're still seeing the error pretty frequently and aren't sure how to reproduce on our devices.

If you know when this would get resolved, that would be great!

**Comment by studious** [comment]
We are also getting a lot of these errors since we deployed the posthog client today. They are all from TouchMove on devices where DragMove doesn't exist.
```
t instanceof MouseEvent
? e.IncrementalSource.MouseMove
: t instanceof DragEvent
  ? e.IncrementalSource.Drag
  : e.IncrementalSource.TouchMove
```

**Comment by mariusandra** [comment]
Hey, it seems that this issue is fixed upstream by https://github.com/rrweb-io/rrweb/pull/630 and https://github.com/rrweb-io/rrweb/pull/652 . Unfortunately those changes are not yet released in a new 1.0.3 version of `rrweb`.

@Yuyz0112 I see you made a commit to release 1.0.3, but then it was never published. Is there any way to get this version out? :)

**Comment by Yuyz0112** [comment]
@mariusandra 1.0.3 has been published now.

**Comment by Twixes** [comment]
Thank you @Yuyz0112!
