### ISSUE TITLE
Add delays to tooltips

### ISSUE THREAD

**Issue by yakkomajuri** [PostHog/posthog#4683]
Every time I'm using PostHog I'm swamped with tooltips that make it hard to navigate:

https://user-images.githubusercontent.com/38760734/121522278-5108b000-c9cb-11eb-9792-13f085223375.mov

I'd love for these to have a delay (e.g. show tooltip after 1sec hovering). Antd tooltips support `mouseEnterDelay`, but I guess the problem is then about how will the user know there's a tooltip at place X. Could be something to think about, and potentially add more info icons in different places?

**Comment by mariusandra** [comment]
This is my favourite in-ya-face tooltip:
![2021-06-10 14 21 56](https://user-images.githubusercontent.com/53387/121524106-3fd59880-c9f7-11eb-98f2-6b3b0ed27b9d.gif)

**Comment by alexkim205** [comment]
This recently got marked stale but it's still an app-wide issue it seems. @clarkus is there a better way to make these tooltips less intrusive? I feel like users will able to discover delayed hoverable tooltips without an indicator because it's a common pattern in our app, but wanted to ask if you see a better way to do this

**Comment by clarkus** [comment]
> This recently got marked stale but it's still an app-wide issue it seems. @clarkus is there a better way to make these tooltips less intrusive? I feel like users will able to discover delayed hoverable tooltips without an indicator because it's a common pattern in our app, but wanted to ask if you see a better way to do this

In this example, things look mostly right. I think context matters a ton with tooltips... the component being described, its place in a list, it's proximity to viewport edges, etc. The thing I think that needs to be changed is placement. Generally users will start by scrolling down a page. If we place tooltips below the thing they describe, we obscure subsequent content. I think a better default placement would be above the item being described. That's an area that has already been traversed, so overlaying it with extra info _should be_ less intrusive. The exception here is when there isn't sufficient space between the item being described and the viewport boundaries to display the tooltip. For example, an item near the top of the viewport won't have sufficient space to show a tooltip above, so depending on position we'd show a tooltip below or to one side. 

The other thing to consider is disabling cursor events for the tooltip component. Unless there is something actionable in there that the user can act on, there's no reason to maintain cursor events. The problem we're trying to avoid is a user mousing over that tooltip and the tooltip display persisting. Events on the thing being described should drive the view of that tooltip. 

I think the delay you have is fine. It's not immediate, so you won't see it as you quickly scrub through a list of items. Thoughts?

**Comment by clarkus** [comment]
Another thing to consider - if we find that we have to describe almost everything in a list with tooltips, we should probably bake those descriptions into the list. It's hard to summarize complex things with one or two words. This has recently come up with funnel visualization types and in a couple other places I'm forgetting. I think it's fine to put in extra descriptions where they add value. Said another way, we don't have to use tooltips to describe everything.

**Comment by alexkim205** [comment]
Thanks! That makes a lot of sense. I'll think about what baked in tooltips would like bc it's context specific, but these are the things that you brought up that I can implement today:

- [ ] Hover over tooltip doesn't persist tooltip
- [x] Smarter tooltip placement dictated by viewport boundaries - Already happens natively in antd with `autoAdjustOverflow`
- [x] Add arbitrary delay onMouseEnter

I also think we nixed any kind of tooltip hovering in the new taxonomic filter, which should reduce popup overload that existed when this issue was made.
