### ISSUE TITLE
Cypress `ospath` tests caching bug

### ISSUE THREAD

**Issue by mariusandra** [PostHog/posthog#4685]
## Bug description

I've often come across something like this:

![image](https://user-images.githubusercontent.com/53387/121524474-a5c22000-c9f7-11eb-89c1-c4d9e70cbf1f.png)

![image](https://user-images.githubusercontent.com/53387/121524521-af4b8800-c9f7-11eb-9e5f-8d9b931a333e.png)

This makes the tests rather worthless. I believe this was introduced by some caching in https://github.com/PostHog/posthog/pull/4357 or https://github.com/PostHog/posthog/pull/4418 . 

Because `$slow_tests > $broken_tests`, then for at least cypress (other tests seem unaffected), we should disable this caching or find another solution.

## Expected behavior

Tests should not flake

## How to reproduce

Not exactly sure. It's *possible* force pushing to a repo causes this bug, as *mostly* everything works very well.

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

**Comment by alexkim205** [comment]
+1 This can be a blocker for deploying with confidence.

There seems to be a pattern here where failing e2e runs always run the `Yarn install deps` step while successful ones don't. I suspect this command might be overwriting cypress's dependencies, which is why we get dependency errors like `Error: cannot find module X`. It could possibly be a red herring 🤔 

**Fail**

<img width="544" alt="Screen Shot 2021-07-02 at 9 57 47 AM" src="https://user-images.githubusercontent.com/13460330/124285600-e860af00-db02-11eb-9a24-28acad6f8b3b.png">

**Success**

<img width="436" alt="Screen Shot 2021-07-02 at 10 02 02 AM" src="https://user-images.githubusercontent.com/13460330/124286068-6a50d800-db03-11eb-89c2-83040e5fa929.png">

**Comment by mariusandra** [comment]
Closed with https://github.com/PostHog/posthog/pull/5014
