### ISSUE TITLE
Add event name to events filtering and cohort selection

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/posthog#470]
**Is your feature request related to a problem? Please describe.**

"We're looking to replace Mixpanel, we have a lot of custom events (so not the autocapture ones, but specific ones we send with posthog.capture) and often we want to check, e.g. when did user do this or that. Since there are so many events coming in, the only way to do this is to filter by events."

"Second (and probably more common) use case is we want to find all the users who did specific event. I guess we would use cohort for that, but again, we can't filter by event there."

It currently is possible to filter by event type, but there may be many events within this.

**Describe the solution you'd like**
* The ability to filter events list by event name
* The ability to filter cohorts by event name

**Describe alternatives you've considered**
There isn't a workaround for this.

**Additional context**
Feature requested by Filip in the PostHog user Slack.

**Comment by DannyBen** [comment]
I second this feature request - I was sure I misunderstood something in the filter UI when I could not find way to filter by name.

**Comment by filipkis** [comment]
Thanks for implementing this. It's already a great help. However, I wonder why adding it as a different filter, instead of just adding `Event name` to the list of Event properties under the new `New filter` popup? 

Additionally, when there are new events this filter is not applied.

**Comment by timgl** [comment]
The reason for not adding it as a property is partially technical, partially to avoid confusion. Technically we don't store event names as a 'property' but as a completely separate field, which is why it doesn't make sense to add it there. In terms of confusion, everywhere else in the system the workflow tends to be that you explicitly select an event first (like in trends or funnels) and then filter that event by a property. Having the event name filter in the property filter could cause confusion as you end up with `$pageview` selected but then filtered on `$identify`, which means you get 0 results.

You're right re: new events. It also doesn't seem to work with the back button. Will fix those!

**Comment by jetaggart** [comment]
If you have a custom event such as `onboarding_started` how do you filter on an insight by that name? The only way I see how is to use sql expressions which is hard to use for the team.
