### ISSUE TITLE
custom BASE_URL for non root installations

### ISSUE THREAD

**Issue by kilianc** [PostHog/posthog#4714]
## Is your feature request related to a problem?

My installation of posthog runs at https://a.foo.com/posthog and all absolute links are broken. This is odd because the `SITE_URL` is correctly set.

## Describe the solution you'd like

use `SITE_URL` as prefix for all links

## Describe alternatives you've considered
none

**Comment by mariusandra** [comment]
@kilianc Thanks for the issue and apologies for the situation, but due to the added complexities[*] we won't be supporting subfolder URL installations of posthog for now. 

[*] There's [a draft PR](https://github.com/PostHog/posthog/pull/4656) that is taking first steps towards enabling a potential solution, yet this to fully have subdomain-based posthog installations, we need coordination between 1) webpack static assets, 2) frontend/routing logic, 3) backend endpoints, 4) the toolbar with its separate logic, 5) all the glue connecting things together --- overall a lot of work for an unclear aim and we're stretched thin as is :).
