### ISSUE TITLE
Hide events in event select box with no usage data in last 30 days

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#4791]
## Is your feature request related to a problem?

We for example have 177 events. It's pretty overwhelming trying to find the event you want. Plus it's confusing when you select an event and get 0 results. 
![image](https://user-images.githubusercontent.com/1727427/122422905-cfe28780-cf8d-11eb-8abd-ddf26fa11944.png)

## Describe the solution you'd like

I'd add another category (like 'Suggested for you', 'actions' and 'events' in the screenshot above) called "Dormant Events" that's automatically collapsed. Put every event in here that hasn't had any events in the last 30 days (based on `volume_30_day`). Make sure we only do this if `preflight?.is_event_property_usage_enabled`.

**Comment by liyiy** [comment]
Relevant to #4502

**Comment by paolodamico** [comment]
I think we could potentially show these events grayed out and/or with a "stale" label, wdyt @clarkus ?

**Comment by clarkus** [comment]
> I think we could potentially show these events grayed out and/or with a "stale" label, wdyt @clarkus ?

Sure, but I think we'll need to describe the freshness of these items a bit more. What if on hover we could show a "last seen" date or something that describes why it's dormant or stale. I don't think we should group by dormancy (at least initially) because it might make it harder to find events. I'd rather optimize for making it easy to find the event. Another option would be alternate sort attributes - for example sorting the list by freshness, alphabetically, most used, least used, etc.

**Comment by paolodamico** [comment]
- Agreed on showing details on the staleness as a secondary measure (e.g. on hover)
- I don't think it makes sense to add more complexity to the box (and another decision to the user) by allowing multiple sorting, but rather prioritizing results that are used more often (as they're probably more relevant) and deprioritizing stale events.

**Comment by macobo** [comment]
Related: https://github.com/PostHog/posthog/issues/7315

**Comment by mariusandra** [comment]
Because we have everything in tabs, and there are already too many tabs, I wouldn't add another one for "events, but not recently used" as asked the initial task. If we move away from tabs to something else, it'll become an issue again.  

PR #7426 orders the list by "last 30 day volume", which I think is enough to effectively demote useless events and properties for now.

**Comment by paolodamico** [comment]
Agreed, will only add the indicator, will not separate stale events into their own tab.
