### ISSUE TITLE
Handle repeated event steps in funnel

### ISSUE THREAD

**Issue by EDsCODE** [PostHog/posthog#4813]
## Is your feature request related to a problem?

*Please describe.*
Currently, if you create a funnel with the exact same events in multiple steps, the funnel returns trivial results. If step_2 is $pageview and step_3 is $pageview, it doesn't find a later pageview but just counts the same step_2 pageview as a step_3 pageview. This is solved with `windowFunnel` because they added a `strictly_increasing` [parameter](https://clickhouse.tech/docs/en/sql-reference/aggregate-functions/parametric-functions/#windowfunnel). However, it's on a later version of clickhouse and we're looking to use the new query anyway.

## Describe the solution you'd like
The new step query should look for a later pageview. This will require some query wrangling

**Comment by neilkakkar** [comment]
Doesn't this become a non-issue with https://github.com/PostHog/posthog/issues/4812 ? Since that will ensure the new step time to always be greater than previous step time?

Or is the crux here that when dealing with different kind of events, they don't have to be strictly increasing?

I think we can reasonably relax that constraint, such that all events follow a strictly increasing order, instead of just an increasing order?

Am I missing something?

**Comment by EDsCODE** [comment]
Query here: https://metabase.posthog.net/question/85
