### ISSUE TITLE
Bugs/improvements on better sessions

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#4960]
Some late feedback on #4840.

1. After I've opened a person page, the back button on the browser doesn't work, it keeps me in the person page but with some weird behavior going on. I'd expect to be able to get back to the person list if I click back.
2. Related to the above, if I click back to insights the person modal is closed when I get back.
3. The "matches" terminology seems a bit confusing. I don't know what I'm matching against. Maybe we should specify the exact event/action, or say something like "matches your trend query", not sure. CC @clarkus 
    <img width="222" alt="" src="https://user-images.githubusercontent.com/5864173/124134850-8c0a7a80-da83-11eb-9759-d57150a1b6d8.png">
4. The hover background color is very unintuitive, color should probably be a darker shade of yellow. You can try yellow 100 or darkening 10% the highlight color, but tagging @clarkus who will probably have a better idea.
    ![image](https://user-images.githubusercontent.com/5864173/124135140-d3910680-da83-11eb-9894-c594d2d09b66.gif)
5. I don't think expand all sessions should be a toggle but rather a button, because you can change the state of the sessions manually and then the toggle will show incorrect information. I would have here an "Expand all sessions"/"Collapse all sessions" button.
6. Something weird going on with the play all button, spacing is off.
<img width="113" alt="" src="https://user-images.githubusercontent.com/5864173/124135473-1fdc4680-da84-11eb-944d-0b6ca78dab12.png">

**Comment by clarkus** [comment]
> The "matches" terminology seems a bit confusing. I don't know what I'm matching against. Maybe we should specify the exact event/action, or say something like "matches your trend query", not sure. CC @clarkus

Good catch. We're matching against filters, so something to the effect of "N events match your event filters". 

> The hover background color is very unintuitive, color should probably be a darker shade of yellow. You can try yellow 100 or darkening 10% the highlight color, but tagging @clarkus who will probably have a better idea.

In this case, we're highlighting matched events within a session. It looks like the default hover treatment for a row is overriding that on hover? What problem are we trying to solve here? I think that the yellow is noticeable, but we might benefit from layering in some other affordance for the matched state. We could reuse the same events icon and use it as extra visual weight for identifying events that match. We could also add emphasis to the text values in the row. In the attached example I gave the event name bold weight to stand out even more. 

<img width="358" alt="Screen Shot 2021-07-01 at 10 19 27 AM" src="https://user-images.githubusercontent.com/254612/124164700-d2e17b80-da55-11eb-9f35-9e72507e299f.png">

**Comment by alexkim205** [comment]
>  It looks like the default hover treatment for a row is overriding that on hover?

Correct me if I'm wrong @paolodamico but I think this is the reason for the unintuitiveness? I think it makes sense to incorporate both of your feedback though! I pulled up the yellow hover color over a matched event just a bit and added some more emphasis. Let me know what you think of this-


https://user-images.githubusercontent.com/13460330/124173769-5acc8300-da60-11eb-86bf-adf12d44f0c4.mov



@clarkus Would it make more sense to have the event icon be a single square instead of a stack of squares?

**Comment by alexkim205** [comment]
https://user-images.githubusercontent.com/13460330/124179305-869f3700-da67-11eb-874a-cf5100ab1128.mov

**Comment by alexkim205** [comment]
I think bugs 1-2 have to do with the way that kea-router `actionsToUrl` and `urlToActions` work. It looks like whenever that triggers we perform a silent `history.push` of the next url. 

Me just pressing the back button after navigating to sessions page from the persons > events page. It takes a few clicks to get back to `persons`.



https://user-images.githubusercontent.com/13460330/124180353-e9dd9900-da68-11eb-85d9-60ea548ca2f1.mov




This means that you need to click the back button several times to get back to the page you were actually one. @mariusandra do you have any pointers here on how to perform a correct `back` action when kea-router is doing this?

Edit: Might be related to decoupling state from url #4329.

**Comment by clarkus** [comment]
I see now. I think the direction to darken the yellow slightly on hover for highlighted rows makes sense. We would just limit that to highlighted rows only. 

I keep thinking about this event icons at the event level and it feels off to me. We really just need a simple means of indicating a match regardless of types. The event icon with summary count at the session level still makes sense to me, but I wonder if a simple text mark / badge would be more meaningful. This would reiterate that highlight color (yellow) and give a simple visual label for indicating matches. What do you think?

<img width="881" alt="Screen Shot 2021-07-01 at 12 44 17 PM" src="https://user-images.githubusercontent.com/254612/124181208-0fb76d80-da6a-11eb-96c1-e7ef0248dceb.png">

**Comment by alexkim205** [comment]
I love it, implementing now

**Comment by alexkim205** [comment]
<img width="1077" alt="Screen Shot 2021-07-01 at 4 18 07 PM" src="https://user-images.githubusercontent.com/13460330/124184687-c9b0d880-da6e-11eb-9638-5bdfe0212f5e.png">

**Comment by mariusandra** [comment]
Hey @alexkim205 , this PR should fix the back button issue: https://github.com/PostHog/posthog/pull/4966

**Comment by macobo** [comment]
What usecase does "expand all" serve? In a realistic scenario it just makes the whole page unusable due to the amount of noise. It also adds a ton of load to our servers to send megabytes of raw event data from the API.

Meta: It's worth keeping https://github.com/PostHog/posthog/issues/4884 top of mind as doing sessions page fixes.

**Comment by alexkim205** [comment]
> Hey @alexkim205 , this PR should fix the back button issue: #4966

Thanks @mariusandra! :verynice:

> What usecase does "expand all" serve? 

I think the expand all option is especially useful when it's used in tandem with the show only matches toggle, since there are times when you'd want to look at all the matching events in a given day regardless of which session it's in. 

> It also adds a ton of load to our servers to send megabytes of raw event data from the API.

I actually think we query for all events already upon first load of the sessions page, so expanding all sessions won't incur any more network costs than we already have. However I think this is only true for our Clickhouse users and not our SH users. We could also hide the expand all button behind a `is_clickhouse_enabled` check? 

@macobo & @paolodamico  what are your thoughts?

**Comment by clarkus** [comment]
> I think the expand all option is especially useful when it's used in tandem with the show only matches toggle, since there are times when you'd want to look at all the matching events in a given day regardless of which session it's in.

I agree that the view when all sessions are expanded is pretty overwhelming. The `show only` option helps, but when the list of events is long it can quickly become unwieldy. I need to better understand how users are using this page. My assumption is that users are looking for the events in common across sessions so they can better understand how users are alike and different. Expanding all and only showing matches would allow a user to scroll through the page and see what events are recurring. Another way would be exposing the common events as suggested filters or even in some secondary area that describes the filtered set. There's a related conversation at https://github.com/PostHog/product-internal/issues/92#issuecomment-872602869. The takeaway there is "how do we expose common events from the list of sessions and make them more actionable and obvious". 

Not really an answer, but it might get us closer to focusing on the core job to be done for users here. Thoughts?

**Comment by macobo** [comment]
> However I think this is only true for our Clickhouse users and not our SH users. We could also hide the expand all button behind a is_clickhouse_enabled check?

Yup, Clickhouse loads all events currently and postgres does not. Both did initially - we turned it off to make sessions page usable on postgres, but similar performance overhead exists on clickhouse to a smaller extent - I am sure we'll move to all events being fetched from endpoint at some date.

**Comment by alexkim205** [comment]
Got it, thank you both for the context. I definitely agree there needs to be a way for users to view common events across sessions. 

Given that this is still an open question design-wise, and not to mention the performance tradeoffs and future direction of the endpoints, I'll hide the expand all button behind a feature flag for the time being so that we can better understand use cases via user testing. 

cc: side note but @paolodamico do you think this might be a good candidate for your upcoming user testing initiative?

**Comment by paolodamico** [comment]
This is looking awesome, thanks for the quick turnaround @alexkim205 & @clarkus. Very small feedback pieces,

1. I would consider keep the font weight normal as there's already enough emphasis from the yellow background. Thoughts?
2. Agreed on hiding the expand sessions button for now and testing (particularly because there's so many conversations going on that could make this a moot point). One thing to consider though is I really think this should be a single button (or even separate buttons, not a huge fan but could work) but not a radio group button. Reason is that there's no two single states of everything expanded or everything collapsed, you can be somewhere in the middle and therefore having a radio option could be misleading.
