### ISSUE TITLE
Include dashboard name in page title

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#4987]
## Is your feature request related to a problem?

It takes too long for me to open the dashboard I'm checking out daily. I need to open posthog dashboards -> find the right one -> click. I'd like to get there fastest.

## Describe the solution you'd like

Include dashboard name in page title. This way my URL bar and page history will suggest it when looking for the dashboard.

## Describe alternatives you've considered

Using bookmarks.

**Comment by kejsitake** [comment]
Hello! I am interested in working on this issue. I am not sure but I think I need to extend https://github.com/PostHog/posthog/blob/master/frontend/src/scenes/sceneLogic.ts#L299. Perhaps when `values.scene === Scene.Dashboard`?

However, I am still trying to understand how to fetch the dashboard name. My initial instinct is to use `params`. Could anyone point me in the right direction?

**Comment by manish001in** [comment]
Hello everyone.

I have tried to work on this feature request. This is my first time contributing to Posthog.
I believe I have completed the task and have provided the information of the dashboard name as page title.

@timgl , I saw that it is recommended to tag you for the QA. 
@paolodamico  Tagging you here since you are a participant in this issue.

Please let me know if I have made any mistake and if anything needs rectification or updation.

#5822 is the Pull Request

**Comment by paolodamico** [comment]
Thanks @manish001in! Continuing the conversation in the PR
