### ISSUE TITLE
Session page is not loading

### ISSUE THREAD

**Issue by jredl-va** [PostHog/posthog#5045]
## Bug description

We are new to post hog scale and have just started our posthog rollout. Sessions are not loading for one of our web properties as the server just seems to timeout on the session query.

![image](https://user-images.githubusercontent.com/2300103/124943107-6fad9700-dfc9-11eb-9f69-86e608fcf44d.png)

Resources don't seem to a constraint:
![image](https://user-images.githubusercontent.com/2300103/124943148-7d631c80-dfc9-11eb-9ba1-3bd17ad3f093.png)

## Expected behavior

Sessions load. 

## How to reproduce

I don't have reproduction steps unfortunately. I'm assuming something about the event data coming from this web property is causing issues?

## Environment

- [ ] PostHog Cloud
- [x] self-hosted PostHog:  posthog/posthog:release-1.26.0

## Additional context

For fun I deleted the project in post hog that was exhibiting this behaviour last night and I created a new one.
I replaced the tracker identifier within our web property and re-deployed the application sessions started funnelling in correctly last night.

I also bumped the timeout on the load balancer by 30 seconds but that still resulted in a timeout. 
However, upon arrival in the office today sessions are no longer loading for this property. I’m assuming some of the data is perhaps bad but I don’t see any errors within the corresponding posthog pods.

**Comment by macobo** [comment]
There are a few suspects here in order of suspicion:
1. Are we sending too much data from BE -> FE. We currently send _all_ events to FE on clickhouse unlike on postgres when data is fetched when session is opened.
1. Is the "load sessions in chunks instead of one query" causing issues
1. Is the query to load sessions performing fast enough 
1. Is the query to load session recordings performing fast enough

There are a few internal slack threads as well on this:
- https://posthog.slack.com/archives/C02283301EK/p1625779207078000

cc @paolodamico @fuziontech - let's keep this issue as our central hub.

**Comment by macobo** [comment]
This should now be solved on the latest master. Let me know if that's not the case!

**Comment by jredl-va** [comment]
@macobo thanks for the quick response!
