### ISSUE TITLE
Stop reseting Device ID 

### ISSUE THREAD

**Issue by Tannergoods** [PostHog/posthog#509]
**Is your feature request related to a problem? Please describe.**
If we want to know what users are most likely to do after logging out this is hard as the ID would reset

**Describe the solution you'd like**
I'd like to "detach" an identifier wihout resetting the underlying device ID. Similarly, as a client device can be forcibly logged off by the server (ie. session cookie invalidated due to password reset), there is oftentimes not a client action to call `posthog.reset()`  after. So it makes sense to have a call to something like `posthog.clearAllCustomIdentifiers()` for all logged out users, whilst not resetting the device ID itself. 

**Describe alternatives you've considered**

**Additional context**
Requested by a user

***Thank*** you for your feature request - we love each and every one!

**Comment by timgl** [comment]
Done!

**Comment by dazbradbury** [comment]
Thanks @timgl - super speedy update! I just tried this out, but not sure that's quite what I anticipated. 

For example we have a user with Distinct ID: 1 (posthog assigned) and 2 (app assigned), Device ID: A

If we call posthog.reset(), we end up with a user with Distinct ID: 3 (posthog assigned), Device ID: A. 

That's fine, so we'd need to find the device ID, and then lookup based on that to find subsequent actions. It's a little clunky though because the UI mainly cares about Distinct IDs over the Device ID. 

However, in the scenario where a user does a password reset and has multiple device IDs - we'd want to log the user out and call reset() on all those clients. This is hard, because we don't necessarily have a link to all those clients, and are waiting for the next request to tell them in fact their session has expired. So there is no point to call reset() on the client in a guaranteed fashion.

What I envisage is a set up where on every page either the user is logged in and you say: 

posthog.identify(...)

Or the user is logged and out and you say:

posthog.clear_custom_ids(...)

clear_custom_ids() would remove all Distinct IDs created by the app. It would leave in tact the posthog Distinct ID, and device ID. 

I see a use case for a reset() function too, and that makes sense where you want a new PostHog Distinct ID and Device ID.

**Comment by timgl** [comment]
Thanks for the detailed explanation!

If I understand correctly, could you achieve what you're trying to with
```js
if(user) {
  posthog.identify(user.id)
} else {
  posthog.reset();
}
```

This would mean that unless a user is specifically identified, they'll be an anonymous user and have a posthog-assigned random ID. Is that what you meant?

You might have to do this code before you call `posthog.init` as that fires off a pageview request with whatever ID it has in persistence

**Comment by dazbradbury** [comment]
That's correct. However, by doing that, each page load would create a new Distinct ID for the user, which is a little confusing from the PostHog UI as it would look like a new user each time (even though I appreciate the device ID will remain consistent). 

So if you wanted to analyse behaviour of logged out users, it would be made a little more difficult by the constantly switching Distinct ID value.

**Comment by timgl** [comment]
Doh, you're right, clearly end of the day here. What about

```js
posthog.init('[key]', {
  api_host: '[instance]',
  loaded: function(posthog) {
    if(user) {
      posthog.identify(user.id)
    } else {
     if(posthog.get_property('$user_id'))  posthog.reset();
   }
}})
```

`$user_id` is set to the same thing as the distinct_id if you call identify, so anonymous users wouldn't have this. Once you call reset `$user_id` will be removed so the new anonymous distinct_id will persist.

Also the loaded callback will make sure this happens in the right place

**Comment by dazbradbury** [comment]
Ok cool - I hadn't seen the `$user_id' property / getter. Will give this a go, thanks! 

Out of curiosity if `.identify()` is called a second time, does it add a second Distinct ID value, or override the original? Just wondering how '$user_id' will respond if multiple IDs have been set (as the UI implies), but can also test and find out. Thanks for your time.

**Comment by dazbradbury** [comment]
Just to clarify - this works, but it still resets the distinct ID. So you'd have the flow of:

1) User Visits Site, appears in Posthog UI with ID "A"
2) User Logs In, .identify(1) called, appears in Posthog UI with ID "1"
3) User Logs out, .reset() called, appears in Posthog UI with ID "B"

The device ID would be consistent, but the PostHog UI would make it hard to determine if this was a new user or the original. My suggestion would be for a way to re-assign the ID in (3) to the same as was set in (1).

**Comment by paolodamico** [comment]
@yakkomajuri do we want to move forward with this?
