### ISSUE TITLE
Add instructions for install with Helm charts to docs

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#516]

**Comment by mariusandra** [comment]
Hi, I added a section to the docs: https://github.com/PostHog/docs/pull/10
After the next release on Wednesday, I should make a new chart and then we can merge the docs.

However, I'd like to configure a Helm Chart Repository using Github Actions, so that whenever we release a new chart, anyone can directly download it.

Currently the repository url, e.g. for gitlab, is just the git url with a specific chart version in the URL, such as: `git+https://github.com/posthog/charts@posthog?ref=1.0.3&sparse=0`. 

It would be much better to actually publish a real repository, where people can just download whichever version they ask for. Then I wouldn't have to update the docs for every version either.

I'd like to use https://github.com/helm/chart-releaser-action for this. However for that I will need more access to the https://github.com/PostHog/charts repo --> to configure secrets and add deploy keys. 

@timgl can you give me this access plefase?

**Comment by timgl** [comment]
Done!
