### ISSUE TITLE
New Funnels UI not legible on dashboard

### ISSUE THREAD

**Issue by samwinslow** [PostHog/posthog#5171]
## Bug description

Funnels UI is not optimized for a small container.

<img width="321" alt="Screen Shot 2021-07-16 at 11 52 09 AM" src="https://user-images.githubusercontent.com/4645779/125975109-900754bf-0de4-41e7-bc72-b08e4605d643.png">

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

**Comment by clarkus** [comment]
I was just looking at this as well. It looks like the dashboard-level controls for configuration aren't working as expected either. 

- Gray background color persists through dashboard color options. I will work on updates for this. 
- Funnel layout doesn't work. Despite settings on the saved insight, funnels are always shown left-to-right on dashboards. 
- Regarding resizing - funnel steps in the left-to-right layout are fairly constrained at a minimum width (roughly 160px). We should be able to fit 2-ish steps in a 320px viewport. On resize, we might consider showing more steps instead of trying to adjust bar step sizing. 
- We could also change our precision formatting for rates of change in the chart. It should scale to 5 characters per rate of change `nn.nn%`... 7 if you count the parens :)
<img width="339" alt="Screen Shot 2021-07-16 at 10 37 17 AM" src="https://user-images.githubusercontent.com/254612/125987382-40195136-9f8b-4e54-834f-90cc24acadd7.png">

**Comment by clarkus** [comment]
Attached are updated color schemes for the latest funnel visualizations on dashboards. These are available in figma at https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf/PostHog-App?node-id=2903%3A5558

**Purple**
![purple](https://user-images.githubusercontent.com/254612/125990787-6e051b9a-6721-4f9f-9876-52de46cb5012.png)
**Blue**
![blue](https://user-images.githubusercontent.com/254612/125990791-6a2f9c96-3892-4418-9332-20aace52bab5.png)
**Green**
![green](https://user-images.githubusercontent.com/254612/125990793-6c5473e2-908c-4dcd-976a-d20a034fbf7b.png)
**Black**
![Black](https://user-images.githubusercontent.com/254612/125990795-e00794b3-97bb-4b26-8dc0-7fafc7869d97.png)
**Default - White**
![Default - White](https://user-images.githubusercontent.com/254612/125990796-547493b5-8de7-44fa-aa38-3f0a4f08f42b.png)

**Comment by samwinslow** [comment]
> * We could also change our precision formatting for rates of change in the chart. It should scale to 5 characters per rate of change `nn.nn%`... 7 if you count the parens :)

100% (or should I say 100.0000%).

Implementation detail: `humanizeNumber` has built-in support for toFixed

**Comment by Mentioum** [comment]
> https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf/PostHog-App?node-id=2903%3A5558

The response to this new Funnel design from our Marketing team was "Oh my god, that's so much better"... "So nice!"

**Comment by samwinslow** [comment]
Some users are also reporting completely blank funnels on dashboard.

**Comment by paolodamico** [comment]
Yeah I noticed something broke in a merge or something, I'm actually fixing that right now
