### ISSUE TITLE
Improve funnels graph type selector

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#5235]
I'm pretty unconvinced with the current graph type selector component. It feels too cramped, hard to communicate what each option is easily, and doesn't play nice in some screen dimensions. Here's a proposal to improve it. Thoughts @clarkus ?

**Current**
<img width="379" alt="" src="https://user-images.githubusercontent.com/5864173/126405957-a6af4613-5824-4dd8-9795-5a29995af67c.png">
<img width="265" alt="" src="https://user-images.githubusercontent.com/5864173/126405964-dcb0e2ab-ad09-4954-a5d4-930543f5ddb7.png">

**Proposal**
<img width="1280" alt="" src="https://user-images.githubusercontent.com/5864173/126405990-863702ad-ad47-4a5b-8f9f-aaefdf4c5b85.png">

**Comment by clarkus** [comment]
I think your changes make sense, but the placement is what's throwing me off. I've been seeing the query builder as  "this is the structure of my data that I want to analyze". I'm building a set based on events, filters, etc. Once I have that query built, I'm just moving between visualization types. We can't cover every type of insight analysis in one visualization so we break it into multiple visualizations. It feels like that component belongs in the visualization area adjacent to the layout control because it changes how you're consuming the data, not the structure of the data itself. 

Secondary to that, we might be able to drop the descriptions from the selected state. They help a user understand what the visualization does, but I'm not sure they always need to be shown. Dropping the description would also let that control better summarize the selected state in a more constrained area. Thoughts?

**Comment by paolodamico** [comment]
Aligned with dropping the descriptions (or at least testing both options). Not sure about visualization though, you're changing much more than what you're visualizing, you're actually getting more / different data by switching. How about A/B testing this after the initial experiment is run?

**Comment by clarkus** [comment]
> Aligned with dropping the descriptions (or at least testing both options). 

To be clear, I do think the descriptions add value when the dropdown is open and the user is choosing an option. Just not sure we have to show them in the selected state. 

> Not sure about visualization though, you're changing much more than what you're visualizing, you're actually getting more / different data by switching. How about A/B testing this after the initial experiment is run?

Do you see this as a different discussion from #4654? The visualization type here is more than just layout or orientation, it's a different structuring of the query results. I see insights as categories of analysis and within that there could be one or more visualizations options that represent various aspects of that analysis. I totally see your point, but thinking about it from a systems level and the way visualization options are handled in other insights, it feels more appropriate if we place it in that visualization area. 

I think testing it is a great idea. 💯

**Comment by paolodamico** [comment]
Definitely what I was thinking around descriptions. As per our discussion in our last standup we’ll start out keeping the selector in the current placement and once the funnels experiment is over we can test moving it around. Will work on this today.
