### ISSUE TITLE
Visualize a session based on paths

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#5241]
## Is your feature request related to a problem?

Raw idea related to https://github.com/PostHog/posthog/issues/4884

Goal is to:
- Support detective work around what users did in a session
- Be possible to grasp in seconds when familiar with that feature - compared to the "slow" watching of recordings or scrolling event lists

Target persona: qualitatively 

## Describe the solution you'd like

- Display a colored bar underneath or next to every session, showing what parts of the product user spent the session
- The color is based on the autocaptured current URL
- Highlight searched and key events/actions in the bar (e.g. exceptions)
- Allow users to "expand" the bar to explore it
- When expanded, when hovering over a "part" of a session we show the specific URL user was on
- User can click the part to assign their own custom color to that path

We initially automatically assign colors to different parts of their app, but users can change the colors via the expanded version.

If we wanted to make the display even more busy, we could also highlight searched and key events/actions in the bar when expanded. Related: https://github.com/PostHog/posthog/issues/5240

## Describe alternatives you've considered

Listing key events

## Additional context

See a user request in a similar vein: https://github.com/PostHog/posthog/issues/2335

cc @marcushyett-ph @paolodamico @clarkus

**Comment by marcushyett-ph** [comment]
Thanks for sharing @macobo 

It's a really interesting problem space - and don't think there are any particularly good solutions on the market today.

I think it would be great to overlay a number of users sessions to understand what happened in common between them - although I think this is going to be a particularly difficult design problem (cc: @clarkus)

I think it would be really powerful to visualize an aggregated and be able to see how individuals differ similar to below:

<img width="664" alt="image" src="https://user-images.githubusercontent.com/85295485/126474264-ff6dba66-b410-4a96-bfef-fa6a2fbfcc3d.png">

I think the colors for different pages could be valuable but perhaps that will be too high level to get meaningful information from, maybe we could use certain events or actions combined with to determine the colors? It might be good to use brightness or some other dimension to highlight the intensity of what the user is doing - e.g. dark if they're not doing much, bright if they're triggering a lot of events etc.

@joethreepwood previously suggested we could even try overlay recordings like this game: https://www.transformice.com
(which is a cool idea - although I'm sure there would be a lot of complexities in making something like this work)

Would really love to hear @clarkus's thoughts

**Comment by clarkus** [comment]
Sorry I haven't responded to this yet. I lost track of it along with some other sessions responses, so I thought I had already gotten to it.

Highlighting events in common makes sense to me. I'd need to work through some ideas to figure out scale, but it seems very feasible. 

What if we could take it a step further? What if we could apply a "type" or "category" to actions so that we can later gather them into meaningful groups. We can bake in a lot of structure with our default events, but if a user is already using actions, classifying them into types would make it easier to find them in selection lists, but would also give us a meaningful starting point to give those groups some distinct visual representation. Some ideas could be "high friction" events, "transactional or retail" events, management (settings, user profile actions, etc), etc. With some classification of events and actions, we can show the commonalities between sessions, but we can also give some secondary means of visualizing types. 

This same idea could apply to summarizing sessions / session records outside of a comparison context. I think this idea could help a user jump to a specific point on a recording timeline where there are a high concentration of "high friction" events. 

Edit - the issue at https://github.com/PostHog/posthog/issues/2334 does a good job describing this idea.

**Comment by marcushyett-ph** [comment]
This makes sense to me.

I wonder what categories we can infer without much effort (e.g. Bad stuff = errors, rage clicks, etc, User triggered = clicks, UI events etc...)

**Comment by paolodamico** [comment]
This is now a moot point due to the removal of the Sessions page.
