### ISSUE TITLE
Introduce "conversion windows" to step funnels 

### ISSUE THREAD

**Issue by kpthatsme** [PostHog/posthog#5290]
## Describe the solution you'd like
We've introduced conversion windows to historical funnels, we need to add this to step funnels as well.

Conversion windows are a critical piece of defining a funnel– without the ability to define them we end up just looking at funnels over all time (or maybe not - it isn't clear on the UI what the conversion window is, if any).

## Additional context
Funnels can be misleading without this.

**Comment by paolodamico** [comment]
I'm not sure what's the current support for this in the backend, maybe this is another thing that we're just missing support for in the frontend. @neilkakkar @EDsCODE ?

**Comment by neilkakkar** [comment]
We do support this on the backend now! https://github.com/PostHog/posthog/issues/5367

**Comment by paolodamico** [comment]
For the benefit of whomever implements this here's the latest design that shows these filters/options in the configurator options.

<img width="601" alt="" src="https://user-images.githubusercontent.com/5864173/127719701-acf45866-ed9f-4fad-8c17-bc964773540d.png">

**Comment by kpthatsme** [comment]
Just wanna give my 2c around prioritization - I feel like we should make this part of "nailing funnels", IMO doesn't feel finished until this is implemented.

**Comment by paolodamico** [comment]
FYI @kpthatsme we do have it prioritized for this sprint, we're just getting through some bugs first.

**Comment by kpthatsme** [comment]
Got it - thanks @paolodamico!

**Comment by paolodamico** [comment]
This is now implemented 🎊

**Comment by neilkakkar** [comment]
Feedback: When closing issues / making PRs - would be super nice if we mention the PRs. This ensures it's easy to track what's going on and where to look.

For example, if somehow conversion windows got borked on the app, and all I'm subscribed to is the issue, I come here, try to figure out where the change happened, and I'm lost 😅.

Wasn't much of an issue here, since I was a reviewer on the PR itself: https://github.com/PostHog/posthog/pull/5453 - but you get the idea. For, say, someone not in the loop subscribed to the issue, it's nice if they can follow the link from the issue to the code.

**Comment by paolodamico** [comment]
Definitely @neilkakkar! We should also try to make sure we link the issue in the PR automatically.
