### ISSUE TITLE
Funnel calculation bug on Postgres / empty state

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#5298]
While testing other PRs, I noticed two unexpected behaviors in funnels.

1. When the state of the funnel is changed in Postgres, we no longer show an indicator asking you to recalculate, which leads to confusion. Something like what Metabase does, adding a blurry overlay with a huge calculate button could be an option. An alternative would be to show some banner instructing the user to recalculate. CC @clarkus for input.

![image](https://user-images.githubusercontent.com/5864173/126693871-ae219885-d7e7-4c3a-b418-1fcd8caeb87b.gif)

2. Empty state is maintained when the funnel has 1+ steps, but no action/event selector. While having an "empty"/error state is helpful for this case, the message is not useful.

    <img width="1312" alt="" src="https://user-images.githubusercontent.com/5864173/126693751-42ca6fe8-5cb2-4a9a-aa53-ef7416eeae9f.png">

**Comment by clarkus** [comment]
>     1. When the state of the funnel is changed in Postgres, we no longer show an indicator asking you to recalculate, which leads to confusion. Something like what Metabase does, adding a blurry overlay with a huge calculate button could be an option. An alternative would be to show some banner instructing the user to recalculate. CC @clarkus for input.

This could be reflected in the button state for the `Calculate` button. I'm not a fan of disabled elements at all, but we could reinforce state there by disabling the button when the query definition hasn't changed since the last calculation. Secondary to that, some kind of transitional, less-intrusive alert like a toast could be a means of prompting for a recalculation. While blocking out the screen with an overlay would no doubt get the user's attention, it feels a bit too intrusive for this case. What if we took the alert idea and isolated it to that button. Maybe an actionable tooltip that points to the button and prompts the user to re-calculate?

<img width="519" alt="Screen Shot 2021-07-22 at 12 54 09 PM" src="https://user-images.githubusercontent.com/254612/126701331-4bc0e908-2dce-4880-875b-3896983f3db7.png">


>     1. Empty state is maintained when the funnel has 1+ steps, but no action/event selector. While having an "empty"/error state is helpful for this case, the message is not useful.

Technically that funnel has 0 steps defined. A valid step requires an event or action to be selected. Maybe we should include that steps require a valid selection? Or maybe some kind of error state on the steps to highlight where you can resolve the issue?

**Comment by alexkim205** [comment]
+1 on less intrusive tooltip. I can start implementing that first.

> Technically that funnel has 0 steps defined. A valid step requires an event or action to be selected. Maybe we should include that steps require a valid selection? Or maybe some kind of error state on the steps to highlight where you can resolve the issue?

~Does it make sense to even let the user add more than one empty funnel step? Maybe we should prohibit the user from doing this in the first place (would save us some design/design work too 😊)?~

Didn't read your comment carefully @clarkus 😅. I agree that it would be clearer if the user isn't allowed to create more than one empty step

**Comment by alexkim205** [comment]
Hmm after testing out (1) a bit, in practice it seems a bit tedious to click the "Calculate" button after already having clicked "Add step." It was also confusing to show one bar after having clicked "Add step" because the empty state had been telling me that it was impossible to a show a funnel with one step. Perhaps the most straightforward (and easiest to implement) solution would be to perform the calculation immediately after leaving the empty state? 

For any other subsequent step modifications that dirty the filters, I think the tooltip would be super helpful. Implemented a demo below. What are your thoughts @paolodamico @clarkus?


https://user-images.githubusercontent.com/13460330/126726678-1a8d0f92-da7a-452c-bbbe-e430900ab9ee.mov

**Comment by clarkus** [comment]
👍 for trigger a calculation once a valid funnel query is defined and the empty state is removed. 

That tooltip definitely makes you notice the button, but I think it's going to get annoying if it keeps popping up. Maybe we can figure out some threshold for triggering it. Maybe we delay the display if the user hasn't completed any significant events on the page (especially hit calculate) for a 7 seconds or so? That's a completely arbitrary number, but it would make that tooltip less intrusive for users who know to hit calculate. And we'd maintain that state management aspect where it only shows when the query definition has changed since the last calculation.
