### ISSUE TITLE
Align time and date formatting across instances

### ISSUE THREAD

**Issue by clarkus** [PostHog/posthog#5328]
## Is your feature request related to a problem?

Our time and date formats are inconsistent across features. This is mostly a result of the recent funnels work. 

## Describe the solution you'd like

Formats:

1. **Dates** - `DD-MMM-YYYY` For example 10-Jul-2021. This seems like it'll work well across locales.
2. **Elapsed time / Duration** - `DD:HH:MM:SS` For example 12:15:02 or 12 hours, 15 minutes and 2 seconds. This formatting is effective in scenarios where time is used to communicate position - session recordings come to mind here. Context and continuity matter, so the same format should be used across instances for the given context. For example, we wouldn't want to use `05:15` to communicate 5 hours 15 seconds in one case and `04:14` to communicate minutes an seconds in another.
3. **Absolute Time Units** After some research I think this is going to be a more obvious format for the "time on step" scenario in funnels. There's a wide variety in time lengths in this interface, so labeling units is going to give us the most accurate and succinct representation. Time units are as follows:
  - Seconds `s`
  - Minutes `min`
  - Hours `h`
  - Days `d`
  - Weeks `wk`
  - Months `mo`
  - Years `y`

## Describe alternatives you've considered

Doing nothing

**Comment by corywatilo** [comment]
Some other inconsistencies:

_Current -> Proposed_

- 2hours 42mins 30 seconds -> 2:42:30 (spacing, abbreviations)
- 53d 20hrs -> 53d 20h (differing abbreviations)

**Comment by alexkim205** [comment]
Would it be helpful to provide a tooltip of some sort explaining this format? Do think it'd be useful since time length and time formats are pretty similar.

**Comment by clarkus** [comment]
I updated the original description clarify - I don't think the colon-delimited format is going to scale well for funnels. Those steps can have large deltas between values, so we'd be left summarizing position with meaningless characters. For example:
```
Step 1 - Avg time --
Step 2 - Avg time 01:01:15:01
Step 3 - Avg time 00:01:45:03
```
Step 3 is much much smaller than step 2. To ensure comparisons are straightforward, we'd have to show those `00` values to reinforce that there is a 0 values for days. The flip side is translating to the most common unit (hours in this case). 
```
Step 1 - Avg time --
Step 2 - Avg time 25:15:01
Step 3 - Avg time 01:45:03
```
Here step 2 is using hourly units to format the time value. While this makes it easier to compare hours, it makes it less obvious this step took over a day to complete. 

If we compare this to labeled units, we can see a much more succinct character length for each value:
```
Step 1 - Avg time --
Step 2 - Avg time 1d 1h 15min 1s
Step 3 - Avg time 1h 45min 3s
```
If we round to the closest minute, we get even simpler values:
```
Step 1 - Avg time --
Step 2 - Avg time 1d 1h 15min
Step 3 - Avg time 1h 45min
```

Thoughts?

**Comment by clarkus** [comment]
> Would it be helpful to provide a tooltip of some sort explaining this format? Do think it'd be useful since time length and time formats are pretty similar.

Possibly, but I think we can make this more obvious with the value shown directly in the page. The time unit key might be handy to show for users less familiar with time abbreviations. The colon-delimited value seems most appropriate for session recordings because they're usually shown in isolation and they align with video patterns used in a variety of other products.

**Comment by alexkim205** [comment]
Thank you for the detailed explanation. I like the idea of standardizing the way we display datetimes based on context, but I'm having trouble understanding what differentiates a duration from an absolute time unit. In both session recordings and funnels, we're dealing with units of time that describes the duration a user spent on the product. Is the distinction then made between standalone durations (i.e., screen recording table, avg time to convert dropdown) and multiple durations on an axis (time on x-axis of funnels histogram)? 

Also, I tried to compile a comprehensive list of screenshots where we have these datetime instances so that I can knock these out one by one in my PR. Please free to edit this comment if I'm missing any! 

### Dates in Graphs

<img width="1572" alt="Screen Shot 2021-07-26 at 2 14 10 PM" src="https://user-images.githubusercontent.com/13460330/127060056-1d3a4ec6-3e68-4d3f-a3d4-48335f3b4a68.png">


### Screen Recordings

<img width="445" alt="Screen Shot 2021-07-26 at 11 47 12 AM" src="https://user-images.githubusercontent.com/13460330/127042836-40c977ef-47de-4bbd-9576-0ad0d3f5756a.png">

### Funnels

<img width="352" alt="Screen Shot 2021-07-26 at 11 47 52 AM" src="https://user-images.githubusercontent.com/13460330/127042865-766d0542-7ba5-4a08-9c70-6139da6ec20d.png">
<img width="1092" alt="Screen Shot 2021-07-26 at 11 47 56 AM" src="https://user-images.githubusercontent.com/13460330/127042868-227f2b34-9b04-4371-9dff-6e5259b35956.png">
<img width="589" alt="Screen Shot 2021-07-26 at 11 48 10 AM" src="https://user-images.githubusercontent.com/13460330/127042871-105e1f0a-5ac4-4911-b513-45539b7817b2.png">
<img width="344" alt="Screen Shot 2021-07-26 at 11 47 48 AM" src="https://user-images.githubusercontent.com/13460330/127042877-5bda3236-d3a9-4437-b3da-f55346dce3f4.png">

**Comment by clarkus** [comment]
To clarify, session recordings could be isolated to that colon-delimited pattern. The reason for this is we're not in a comparison context. We're just indicating place or context via time values in the bottom left. I think for anything outside this context where time values are shown for multiple distinct items, we should label the units for clarity. Those values can vary a lot, so unit labels help us ensure a meaningful summary across a variety of contexts. 

<img width="809" alt="Screen Shot 2021-07-26 at 12 07 43 PM" src="https://user-images.githubusercontent.com/254612/127044764-a2d9615f-85c7-46c0-b9f1-bdb2511c2503.png">

Also, we do not need to pluralize time units. It's fine to say `1d 13hr` instead of `1d 13hrs`.
