### ISSUE TITLE
Don't show "forgot password" if email is not set up

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#5464]
## Bug description

@tiina303 reported we show "forgot password" link when user has not set up email env variables

## Expected behavior

Don't show this flow

## How to reproduce

1. Set up a new posthog instance
2. Click "forgot password"
3. Fail

## Environment

- [x] self-hosted PostHog

**Comment by tiina303** [comment]
Related: can we show a nice error when there was a problem with the e-mail credentials, rather than 500 (so self-hosted folks won't think it's a Posthog bug, though the info is in the web pod logs) and maybe in addition to the exception we can print a nice warning like we do for google auth disabled if no licence.
