### ISSUE TITLE
Don't allow identifying "non-anonomous" user -> "non-anonomous" user

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#5527]
## Is your feature request related to a problem?

Currently users can end up with massive merged users if they do something like "posthog.identify(null)" or something for logged-out users. Worse, it can lead to data corruption if in a B2B product one user logs in as another.

## Describe the solution you'd like

Proposal: 
If user has been "identified"/is non-anonymous, don't allow them to be merged again into another user.

Posthog-js has this guard: https://github.com/PostHog/posthog-js/blob/cd9ec768d0662a82469d200eb7ff23a9dcda7c98/src/posthog-core.js#L842-L864

However other libraries and integrations (*cough*rudderstack*cough*) does not

## Describe alternatives you've considered

Teaching all users how to use tools perfectly from day one.

## Additional context

Related issue: https://github.com/PostHog/product-internal/issues/132

cc @timgl we discussed this in meeting yesterday
cc @yakkomajuri for ingestion woes
cc @EDsCODE who created the linked issue

This was also a pain at other companies with similar apis - teaching users is impossible

**Comment by macobo** [comment]
Note: Implementation-wise we already have the `is_identified` flag accessible in plugin server. If we decide to do it it's as easy as just leveraging that flag :)

**Comment by yakkomajuri** [comment]
Ok so let me think through the impact of this here. 

Let's think of a scenario where for whatever reason some team is double identifying users in a "legitimate" way i.e. not `posthog.identify(null)`. Let's say they're using both usernames and emails to identify users, so Yakko the person is both `yakko@someemail.com` and `yakkoisthecoolest`.

## 1. Identify an identified user with a new distinct ID

Let's say I'm identified as `yakko@someemail.com` and now I'm suddenly identified as `yakkoisthecoolest`. This is fine as we just pop that new distinct ID in to the existing `yakko@someemail.com` person.

## 2. Identify an identified user with an existing distinct ID

This is where the problem lies with `posthog.identify(null)`. If the `yakkoisthecoolest` exists, we go ahead and merge them with  `yakko@someemail.com`.

## What happens with the solution?

So if we don't merge them once they're identified, what are we going to do when that identify call comes in? Nothing? Keep the two people around?

Then when a new anonymous ID is identified with `yakkoisthecoolest` we'll be adding on data to two different people who in reality are the same? This will lead to data integrity issues as you'll have more users than you actually have. 

## Next steps

Would love to hear a more clear solution of what you propose happens in scenario 2. Docs certainly can be better here and we should teach people about using `alias`. As of right now we essentially infer the dev means an alias when scenario 2 happens, which is somewhat reasonable, but definitely problematic with misuse like what team 1221 does and also `posthog.identify(null)`

**Comment by macobo** [comment]
To start from the basics - the semantics of things are kind of up to us and identify _can_ mean whatever we intend for it to mean if we are clear around documentation.

Let's assume the following scenario:
```
posthog.capture('event1')
posthog.identify('user1')
posthog.capture('event2')
posthog.identify('user2')
posthog.capture('event3')
```

My proposal is that `event1` and `event2` end up under `user1` and `event3` and onwards under `user2`. Basically the behavior if you called .reset() before subsequent identify calls.

What this wins us?
1. `posthog.identify(null)` does not destroy data. If you start using the api correctly afterwards, _new_ data will end up under the right accounts
2. IMO this might be the shortcut we need to get `person_id` onto `events` table due to limiting the amount of merges going on. We could short-term buffer events until `identify` happens, if id is non-anonymous we can cache the lookup in ingestion. :) cc @fuziontech @EDsCODE

**Comment by fuziontech** [comment]
After thinking about this for a while I think you are 100% correct here.

 **We should only merge anonymous -> identified.** 

This basically protects users from accidentally shipping a bug that might completely soil their collection of persons by identifying each to some constant string, like you said `null`. You can either attribute the anonymous properties to an already identified person or a new person. That makes the most sense as the identifier for a user should not change. This might be something that we have to educate users about. Like only identify users using some super constant ID like email or username. Something that really should never change, and if it does, semantically means that it really is a new user.

Well done thinking about how this should work. I 100% agree with you here.

**Comment by EDsCODE** [comment]
Overall, agree with the approach because it will protect against bad posthog.identify calls. Is there any other consequence that's different? I was looking through out identifying process and atleast for us, 

```
if (
    posthog.get_property('$device_id') !== posthog.get_distinct_id() &&
    posthog.get_distinct_id() !== user.distinct_id
) {
    posthog.reset()
}
```
This _should_ be ensuring "different" users don't get merged together.

RE: 2) Super interesting. Worth giving the architecture some thought and see if we can make it happen. Person_id on events is still the key improvement that will provide dramatic performance improvement. Backfilling might be a headache though

**Comment by macobo** [comment]
Re the guard on distinct id in posthog-js: Yes, posthog-js has this, and this was mentioned in the original post, however this doesn't apply for any other client libraries (e.g. py, ruby, mobile, rudderstack, etc).

I think we have enough voices here now - will open a PR once wrapped up existing work. :)

**Comment by macobo** [comment]
Related-but-not-really:

If we're implementing this, worth considering a similar blacklist from He@p

![image](https://user-images.githubusercontent.com/148820/132221107-2303e3b5-fb97-4268-8012-3e0fa35a8248.png)

**Comment by mariusandra** [comment]
+1 for blocklist. This came up in support today, where one customer just got users identified into `undefined`. The reason is still to be determined, but we just shouldn't have mangled them up like that.

**Comment by hazzadous** [comment]
@mariusandra do you have a link to the support issue?

**Comment by Twixes** [comment]
Blocklist is being added in https://github.com/PostHog/plugin-server/pull/564.

**Comment by mariusandra** [comment]
> @mariusandra do you have a link to the support issue?

https://posthogusers.slack.com/archives/G01JXEDAL22/p1631431019000100

**Comment by yakkomajuri** [comment]
Done
