### ISSUE TITLE
Make events/properties definitions editing less obscure

### ISSUE THREAD

**Issue by liyiy** [PostHog/posthog#5546]
## Is your feature request related to a problem?

*Please describe.*

How can we make this feature less obscure? Does the "events stats" name make sense for it?

note: This is an EE feature only currently

https://app.posthog.com/events/stats

<img width="1358" alt="Screen Shot 2021-08-11 at 12 15 47 PM" src="https://user-images.githubusercontent.com/25164963/129065504-dacececc-13c1-4dd1-9ae9-531f9742e289.png">

**Comment by clarkus** [comment]
Looking at this today. I am not super familiar with this feature, so please correct me if anything I propose is off target. 

- "Stats" isn't super meaningful here. What if it was "Usage". These are all usage metrics. 
- I think we would benefit from more obvious actions in each event or property in the list. Instead of an arrow, we could name the action the user is taking.
- The form for editing could improve from some alignment changes. I can put something together for that. 
- Most of this feedback is applicable to property stats, too.

Is there anything else we could improve?

**Comment by paolodamico** [comment]
Agree with all proposed changes! Though I'm not sure this will address the underlying issue around discoverability. I was thinking that maybe we could have a CTA on the main event/property taxonomic filter prompting you to add taxonomy for events that don't have it.

**Comment by liyiy** [comment]
What is a CTA?

**Comment by clarkus** [comment]
> What is a CTA?

Call to action. 

Agree that the actions need to be more obvious. I can spend some time on that as well.

**Comment by clarkus** [comment]
Related question - we use modals and panels interchangeably in the product. There isn't really a pattern as far as I can see. Moving forward, it'd be nice to make this consistent. I tend to reserve panels for when the panel contents need to immediately affect content in the underlying page or when I need a large container for an isolated, more critical case. Modals are pretty common and we use some simplified forms as dialogs. Either will work, but it'd be nice to get to a consistent pattern.

**Comment by paolodamico** [comment]
Agreed @clarkus, happy to defer to whatever you think is best!

**Comment by clarkus** [comment]
I think modals are a better pattern for these generic transitional use cases. They're easier to adapt to mobile viewports, you can shove them right into the prime real estate of the browser, and changing sizes is pretty easy. Panels absolutely have their place, but I would like to reserve that as much as possible for primary navigation, global actions, or super important stuff like editing insight queries.

**Comment by clarkus** [comment]
I'm tracking the design work for this issue at https://www.figma.com/file/9yWtngNb1AIuf6KmXaEPJA/?node-id=1084%3A136531. Will post back here once I have something specific to share. :)

**Comment by clarkus** [comment]
Bear with me because this is a bit concept-ish and exploratory. This idea addresses this issue as well as #5240. I'll need some feedback on the scope, feasibility, and practicality of these changes. 

**Summary of changes**
- Drops panels and modals in favor of expandable table rows
- Makes use of inline editing as much as possible
- Unifies filtering and searching components across tabs
- Prominent placement of a new action CTA across all event tabs
- Cross-links events and properties (where appropriate) to their corresponding usage summary

**Event Log**
A near-real-time event listing. Event names are linked to their corresponding usage view - For example if I click on "action created" I am taken to the event usage tab filtered to the "action created" event which is expanded automatically to show top properties. Expanding an event log row will show the properties, json, and elements information where applicable The properties list will cross-link properties to property usage views. 
![Events](https://user-images.githubusercontent.com/254612/130522734-4503a8b7-dead-4e66-a78e-b1cd773239a1.png)

**Event & property usage**
I would also like to be able to link back to the event log in some meaningful way. The gist is I want to link to "recent events that match this event type" or "recent events sent with this property" from an event or property row. I am still working on this idea. 
![Event Usage](https://user-images.githubusercontent.com/254612/130522739-ae81c0b5-9eef-4282-bd1c-1c7e14c57cf9.png)
![Property Usage](https://user-images.githubusercontent.com/254612/130522740-cbddb882-4aa3-47fa-8ba5-c12782dd4491.png)

**Actions**
I didn't change much here other than to align it with the updates in the adjacent tabs. 
![Actions](https://user-images.githubusercontent.com/254612/130522738-6c6cc79d-3651-4216-8905-6c68283938eb.png)

Thoughts on these changes so far? I'm trying to simplify things and reduce the number of screens needed to communicate this information. All of this is in figma at https://www.figma.com/file/9yWtngNb1AIuf6KmXaEPJA/App-doodles?node-id=1112%3A137679

**Comment by liyiy** [comment]
I like all of this 🤠 Most of it appears to be rearranging of parts, so I think it'll be do able

**Comment by paolodamico** [comment]
Love this! Some feedback (feel free to disregard)
- Maybe if you hover the event name you get a simple popover (like we do in funnels) showing you the event taxonomy & stats?
- I'm not sure about the way we filter events. Users have reported it's confusing and easy to miss. Users have also requested the ability to exclude events so maybe we can consider a way to better support this?
- What happens if you have a ton of filters or are in a small screen?
- Not sure if we should have less emphasis in the export & configure columns button, maybe links instead?
- The arrow icon to indicate an event can be expanded can be confused with the list being sortable.
- Your mock-ups actually bring up a very interesting use case. When you have an extra long URL (probably due to long query strings), should we consider trimming query strings in this view?
- Not sure if the main action button in the events view should be to create an action. If you're not using autocapture this can be a bit meaningless.
- +1 on having recent events in the events stats page.
- Although this exposes event taxonomy better (particularly considering comment 1 above), I don't think it fully addresses the problem of making this super accessible. Thoughts?

**Comment by clarkus** [comment]
> I'm not sure about the way we filter events. Users have reported it's confusing and easy to miss. Users have also requested the ability to exclude events so maybe we can consider a way to better support this?
> What happens if you have a ton of filters or are in a small screen?

I'm not sure about scale here, either. Our filters can be very complex and verbose. I have some other ideas for this, but I'll need a bit more time to draw them out. There's enough complexity that it's probably worth separating filter composition from table viewing a bit more. That would let us prioritize each view for the task at hand, but it would add a few more clicks to see everything. 

> The arrow icon to indicate an event can be expanded can be confused with the list being sortable.

Understood, but I think the plus icon is equally flawed in that it communicates "adding" in other contexts. Our sort indicators could be updated to resolve this conflict. Generally we can communicate sortable on hover or some other cursor / keyboard event. We should also communicate a default sorting for each table - the result would be one prominent indicator of which column is affected and which direction it's sorted. This is all great background for an updated data table pattern. 

> Your mock-ups actually bring up a very interesting use case. When you have an extra long URL (probably due to long query strings), should we consider trimming query strings in this view?

Yes. The trick is going to be truncating in smart ways to obscure repeated values and focus on the unique portions of each. Secondary to that, we should make the full URL discoverable on hover or some other event. 

> Not sure if the main action button in the events view should be to create an action. If you're not using autocapture this can be a bit meaningless.

The secondary placement would be adjacent to the table in the actions tab. I was trying to make actions the most prominent thing here. Totally OK to lower its priority a bit. 

> Although this exposes event taxonomy better (particularly considering comment 1 above), I don't think it fully addresses the problem of making this super accessible. Thoughts?

Can you elaborate on what you mean by accessible? Dropping the intermediate screens and placing editing inline in the table was an attempt at making things discoverable and more immediately accessible. Is there more to the problem that I'm missing?

**Comment by clarkus** [comment]
![Events](https://user-images.githubusercontent.com/254612/130657386-afb42d3c-2b8d-4673-befe-51ad21197a2d.png)

Here's a quick update to illustrate taxonomy overlays on hover. I also indicated a table sort option here. I am redrawing the filtering now and should have something today for sure.

**Comment by clarkus** [comment]
Here's one idea on how we might expose filters when they're needed and hide them otherwise. The filters would tile left-to-right, top-to-bottom as they're appended to the set. Note I'm repeating some filters values here to save time... in a real scenario we'd see more variation in filter composition. 

<img width="977" alt="Screen Shot 2021-08-24 at 10 54 27 AM" src="https://user-images.githubusercontent.com/254612/130665779-28823219-6ea3-4900-a8b5-e59519dcaf62.png">

**Comment by paolodamico** [comment]
Thanks @clarkus! I think this latest design address most of my feedback. Particularly loved how we handle the multiple filters thing. A couple of minor additional things I would consider:

- Re accessibility I guess it's not clear how you can edit event/properties taxonomy from this view. The popover shows you the taxonomy but can you change it quickly from there? Also does it show on events too?
- Should the titles of the tabs still be "{Event|Property} Usage" ? Maybe we can communicate better you can do taxonomy here too. 
- Maybe worth keeping the avatar-like indicator which tells you if the user is identified or anonymous? Could be another useful data point.

**Comment by paolodamico** [comment]
This is now happening with the data management page @alexkim205 is building.
