### ISSUE TITLE
Reconcile dashboard vs. item level tags

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#5550]
#5480 in now introducing tags to individual insights (whether standalone saved or on dashboards).  As we also have tags on general dashboards, I'm wondering if having both levels of tags could lead to confusion. For instance, I wonder if on the dashboard list I would expect to see the list of tags inside the dashboard each individual insight as opposed to the tags I manually set.

Honestly not sure if this is actually a problem or not, but I think it's worth bringing forward so you can have a think about.

**Comment by liyiy** [comment]
Hmm for me I wouldn't expect to see insight tags on dashboard tags, with the saved insights flow it feels like the models are different enough to not confuse the two. But I also agree with you that a solution that can encapsulate the two could be helpful too, because a user might want to mass set tags for saved insights or something? 

I think it's hard to tell for now though without user input

**Comment by clarkus** [comment]
I'm not sure this is a problem either. I think one thing to consider is exposing the distinct list of tags from the insights on the dashboard at the dashboard level. Something else to think about exposing at the insight level is the list of dashboards that contain the insight.

**Comment by paolodamico** [comment]
Alright super valid points, thanks! Will close this for now, we can improve later based on user input.
