### ISSUE TITLE
Insight history is created when it shouldn't

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#5551]
## Bug description

Pretty much an insight is loaded we create an insight history record, yet this leads to some confusing stuff. For instance, when opening a saved insight or an insight from a dashboard I wouldn't expect these to create an insight history record, as they're already saved in a different scope. It's also confusing as these are saved without all the metadata and context (e.g. insight name, description, ...)

## Expected behavior

Only create insight history records when working on "scratchpad" mode (i.e. when not working with saved insights).

## How to reproduce

1. Open any saved insight or insight from a dashboard.
2. See insight history be created.

## Environment

- [X] PostHog Cloud
- [X] self-hosted PostHog, version/commit: _please provide_

**Comment by liyiy** [comment]
Yep, in #5416 I'm making a change so that we're **not** creating a new insight every time we open a dashboard item. But it definitely would be helpful to understand the different scenarios of when we actually want to create a new insight. This also reminds me of our `versioning` idea a little while back

**Comment by paolodamico** [comment]
I think for now just removing the insight creation when we open a saved insight (either from clicking on a dashboard), via long link or short link, it's already a huge improvement. I think another thing we may want to do is cleanup the insight history so we keep maybe only the last month or something?

**Comment by mariusandra** [comment]
The bugs mentioned in the issue here got fixed with the recent insight refactors.

However, without the "saved insights" flag, when you open a insight history item, any changes you make (e.g. changing a filter) will be persisted into that history item.

Since we're going to delete the entire page real soon, I propose not to add a "if you make a change on a loaded insight which has come from the insight history view, and you edit something, then create a new insight history entry" exception to the code right now, and just focus on getting saved insights out. It'd probably lead to the reappearance of this issue anyway.

**Comment by Twixes** [comment]
I believe this is irrelevant since we removed insight history (unless there's some leftover code?)
