### ISSUE TITLE
Funnel dropoff rate and trend change alerts

### ISSUE THREAD

**Issue by dknowles-vsk** [PostHog/posthog#5589]
## Describe the solution you'd like
Our teams have built a number of funnels and trends to establish user behaviour baselines. What would be *extremely useful* would be to trigger an alert when a trend or funnel dropoff increases or decreases suddenly. We use DataDog for this purpose in our backend, but we don't have an equivalent tool for the frontend. Having this functionality would, for example, let us quickly detect if our signup process suddenly broke or a change to onboarding caused excess churn.

## Describe alternatives you've considered
Manual monitoring of dashboards, manual spot checking workflows (more than we already do). In other words: maintain the status quo.

## Additional context
Frontend performance alerts are great yet rare to find in analytics tools. We likely would have caught major system outages in the past had some tool existed with this capability. Definitely hoping you can add this one!

**Comment by marcushyett-ph** [comment]
Thanks for sharing @dknowles-vsk. To try and understand your workflow a little better - would you want to pick certain insights to run anomaly detections on - or receive insights for anything that goes up or down suddenly?

cc: @kpthatsme I know we've spoken a bit similar(ish) concepts in the past.

**Comment by mariusandra** [comment]
Related issue: https://github.com/PostHog/posthog/issues/2773

We even had a call about it back then (by @paolodamico) in the context of "anomaly detection", and decided that we don't have the free engineering resources and we're not in a place where we can reliably separate anomalies from noise, hence the effort was paused. 

Happy to revisit, though implementing this properly will tie up someone for at least a sprint or two, even if we can get quick wins early on.

**Comment by clarkus** [comment]
@marcushyett-ph @mariusandra What if this were more of a "subscription" or "watching" solution. You could get close to the same goal by repurposing filters to define a meaningful threshold to trigger an alert. A basic workflow might be something like:

- Create an insight
- Subscribe to, or Watch that insight
- Define data triggers that will fire off alerts. For example, anytime pageviews == 0, send an alert email to some distribution list.
- Define time triggers to fire off alerts. Push an email to a distribution list that contains a snapshot of the insight data every N days, weeks, months, the last friday of the year, etc. 

It's essentially the same component used to build an insight with the exception of the distribution list / emails to be notified. It's also probably easier to build because users would be specifying the rules directly as part of subscribing to an insight.

**Comment by paolodamico** [comment]
So to bring some more context on this @clarkus @marcushyett-ph, I think the problem we landed on is that we need a strong engine that ignores noise data. For instance, it can be the case that there are 0 pageviews at a point in time (even if it's just a short fluke), or it could be that the threshold you set (cause you wouldn't use 0, but rather +/- 5% for instance) would easily register noise at some point. Software where this is part of their core offering (NewRelic comes to mind) had/has this problem, requiring more complex solutions to tackle it.

Receiving the snapshot of an insight periodically I think is not susceptible to this problem and could provide some significant value to users. For instance, users concerned with a metric but aren't actively on PostHog (e.g. a Head of Product, CEO, ...).

**Comment by dknowles-vsk** [comment]
@clarkus 's solution will work for our needs. As another analyst I 100% agree that anomaly detection can be hard and frustrating to tune, so having simple "Alert" and "Recovery" thresholds would make me happy. If metric dips below X in period Y then send notification.

**Comment by macobo** [comment]
Since this might take a while to research and implement, this might also be a good usecase for a home-brew plugin for your team.

We created https://github.com/PostHog/posthog-pagerduty-plugin for something similar in the past.
