### ISSUE TITLE
celery_app.send_task() - "posthog.tasks.process_event.process_event_with_plugins" doesn't exists files.

### ISSUE THREAD

**Issue by housekorea** [PostHog/posthog#5829]
## Bug description

```python
# posthog/api/capture.py 
def capture_internal(event, distinct_id, ip, site_url, now, sent_at, team_id):
    event_uuid = UUIDT()

    if is_clickhouse_enabled():
        log_event(
            distinct_id=distinct_id,
            ip=ip,
            site_url=site_url,
            data=event,
            team_id=team_id,
            now=now,
            sent_at=sent_at,
            event_uuid=event_uuid,
        )
    else:
        task_name = "posthog.tasks.process_event.process_event_with_plugins"
        celery_queue = settings.PLUGINS_CELERY_QUEUE

        celery_app.send_task(
            name=task_name,
            queue=celery_queue,
            args=[distinct_id, ip, site_url, event, team_id, now.isoformat(), sent_at,],
        )

```

## Expected behavior

Hello, I'm a very new this posthog project. I trying to understand posthog source-code. 

When I checked celery_app.send_task() function their task_name(**"posthog.tasks.process_event.process_event_with_plugins"**) doesn't exists file in "tasks" directory.(Even, all directory have neither "process_event" or "process_event_with_plugins")

I wonder how this code possibly executes. Is there any file which define ("posthog.tasks.process_event.process_event_with_plugins") task?

## Environment

- [ ] PostHog Cloud
- [O] self-hosted PostHog, version/commit: _please provide_

- Ubuntu 20.04(WSL2)
- Python3.8.5
- Using PostrgresSql (with Docker)

**Comment by timgl** [comment]
Hey @housekorea, our ingestion pipeline is separate from the rest of the codebase and lives in the 'plugin server'. The tasks [gets registered here](https://github.com/PostHog/plugin-server/blob/master/src/main/ingestion-queues/queue.ts#L105). The naming convention is confusing but it's because of backwards compatibility.

Closing this as it's more of a question than an issue and I think I've answered it, but let me know if you have any other questions.
