### ISSUE TITLE
[API] create/assign actions on capturing events

### ISSUE THREAD

**Issue by wppd** [PostHog/posthog#587]
**Is your feature request related to a problem? Please describe.**

we are using posthog for our backend.

for example, there are many events emitted when making paypal payments.

1, prepare data
2, calling paypal api
3, log paypal api response
4, user authorized the payment
5, execute payment
6, log payment result
we currently group these events into the same "topic": paypal payment

from the docs, I think the "action" is the "topic" for us: grouping events.

**Describe the solution you'd like**

maybe an extra field in the catpure api endpoint: "action": "paypal payment"

**Describe alternatives you've considered**

none

**Additional context**

none

***Thank*** you for your feature request - we love each and every one!

**Comment by timgl** [comment]
Actions kind of work the other way around: they're meant to allow you to retrospectively group events so you can use them easily in things like funnels, the trends page etc. That way you can fix things like having two events that basically mean the same thing.

I don't think this is actually what you want, because these events are very different, and you don't care about "how many payment events did we do yesterday".

Is this purely so that in the dropdown (on /trends for example) you can more easily see what are payment events and what are other events?
