### ISSUE TITLE
Expand `filters` object before passing it to query objects

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#5877]
## Is your feature request related to a problem?

When writing queries there are a lot of edge cases that need to be thought about for every query. Some of these are:
1. Making sure test account filters are supported
2. Do we detect if to join properly even if using cohort or action filters https://github.com/PostHog/posthog/issues/5876 https://github.com/PostHog/posthog/issues/5854
3. Detecting what columns need to be fetched for subqueries
3. Making sure we recurse properly around e.g. cohort filters (which can also contain other cohort filters, etc)

Our current solution has been to embed this logic (via some shared helpers) into every query.

## Describe the solution you'd like

Let's reduce the surface area of our Filter objects.

To do so, implement `Filter.expand(team)` method, which:
- For every action entity filter, replaces it with the equivelent event object filter (taking into account properties)
- For every cohort filter replaces it with an appropriate other filter https://github.com/PostHog/posthog/issues/5854
- Includes test account filters (if needed) under filter.properties
- Is idempotent, calling .expand(team) multiple times is cheap and efficient

Now in entry points to various queries/column optimizers we can call `.expand(team)` and not need to worry about some corner cases.

This can be done step-by-step (e.g. handling cohorts separately).

## Additional context

https://github.com/PostHog/posthog/issues/5876 was the original issue which made me think of this - yet another corner case in one query.

This would also simplify https://github.com/PostHog/posthog/issues/5850

There are some extra cases worth figuring out here though - e.g. actions needs to somehow result in an `OR` statement of N entities, which we currently don't allow. These make this a non-trivial change.

cc @EDsCODE @neilkakkar thoughts around query building

**Comment by EDsCODE** [comment]
Yep, I like this push. A lot of the filter processing is still scattered or repeated. Combining categorically similar looksup like you mentioned would be much clearer. 

I think the filters themselves could be reorganized in a way to be more useful too. Also, some of the core parameters that would relate across queries could be bundled together and the insight specific parameters could be separate. Just a quick thought because our EventQuery classes all share very similar requirements in terms of the filtering parameters. But overall, yes, I think we should move as much parameter handling logic into the filter object rather than having it hang out in query classes
