### ISSUE TITLE
Automate Docker Clickhouse multiarch builds

### ISSUE THREAD

**Issue by mariusandra** [PostHog/posthog#5963]
## Is your feature request related to a problem?

My laptop has an `arm64` chip, but my server is an `amd64`. Practically speaking I need to **compile and run** [my own version of Clickhouse](https://github.com/PostHog/posthog/pull/5215) to get everything to work.

## Describe the solution you'd like

I'd like a Github Actions powered multiarch clickhouse autobuilder, which would build from source and then upload to Docker Hub a multiarch `posthog/clickhouse` image, which could be pulled down by `ee/docker-compose.ch.yml`, and we wouldn't need an extra `ee/docker-compose.ch.arm64.yml` file nor need to spend 2h compiling Clickhouse from source.

## Describe alternatives you've considered

Keep using multiple dockerfiles, one for ARM one for AMD.

## Additional context

We might want to publish and consume our own patched fork of ClickHouse one day. This would solve that as well.

**Comment by hazzadous** [comment]
For this, it might be worth considering:

 1. forking the clickhouse repo and adding in the action. I can see that they have already been playing around with github actions, perhaps we could help out there and get it submitted up stream
 2. rather than building clickhouse within the docker build stage, just build an image and run a container to compile, using ccache (persisting to github actions cache) to ensure we don't have to build everything every time.
