### ISSUE TITLE
Funnels UI minor improvements

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#6109]
## Is your feature request related to a problem?

While using funnels I noticed a few things to improve on the new layout.

<img width="1311" alt="" src="https://user-images.githubusercontent.com/5864173/134848856-f67b03ec-ab12-458b-8e51-2186bb1e4de8.png">

## Describe the solution you'd like

Edit: I'll address this in a separate issue.
- [ ] The tooltip is hard to read as there's a ton of stuff going on, maybe we can add some icons, a bit more spacing and then maybe things on parenthesis could have a smaller font and muted color. CC @clarkus for thoughts.

Edit: Below addressed in #6133

- [x] The checkbox has a foreign blue hue, ideally we would want to match the series color.
- [x] We've changed the main bar color from the main primary color but I think this helped make more obvious that you can click on the bar.
- [x] We use "Comp. rate" & "rate" interchangeably in the table header.
- [x] The average time can get into 2 lines in some cases which doesn't look great.
- [x] The tooltip's title shows a "None" (probably a breakdown value) but it doesn't make sense in this context.
- [x] The "Baseline" label can be confusing if you don't have a breakdown. 

## Describe alternatives you've considered

Not applicable.

## Additional context

CC @alexkim205

**Comment by clarkus** [comment]
> The tooltip is hard to read as there's a ton of stuff going on, maybe we can add some icons, a bit more spacing and then maybe things on parenthesis could have a smaller font and muted color. CC @clarkus for thoughts.

I have some in-progress work on tooltips that I haven't finished yet. It is mostly focused on breakdown cases, but there is a basic rework of the tooltip pattern, too. The important parts are the table-like alignment of labels, values, etc. Note that each row has some visual separation (borders) as well. Also worth noting that tooltips should describe the thing the cursor is hovering over - the information summarized differs when looking at an entire step or a specific item within a step. 

<img width="363" alt="Screen Shot 2021-09-27 at 10 05 51 AM" src="https://user-images.githubusercontent.com/254612/134954102-092bcea1-ce2e-44ac-902f-e8ed4914bb49.png">

Here's a quick redraw of the information shown for a specific funnel item. Note that we can't possible show all of this information when breakdowns are applied, so we will have to rely on the table below the charts to fully describe. Quick note we might be able to simplify the tooltip by saying comparison are based on `previous steps` instead of `compared to step [N]`. 
<img width="415" alt="Screen Shot 2021-09-27 at 10 18 51 AM" src="https://user-images.githubusercontent.com/254612/134955778-1922a68e-5275-4dc1-95b5-acb7fe2a4af9.png">

**Comment by alexkim205** [comment]
This looks really cool! Just a quick question - which part of the table will you have to hover over to activate the table tooltip?

**Comment by clarkus** [comment]
Oh sorry for the confusion, this is for hovering over the visualization not the table. The table will show all this information already. The specificity issue with tooltips has to do with hovering over the step "container" or an individual step item. When hovering over the container, we describe all items in the container with their primary details. When there's one item in the container or you're hovering over a specific item, we can describe all the aspects of the step item.

**Comment by alexkim205** [comment]
Ah got tripped up by the naming, but makes sense 👍. Thanks for clarifying

**Comment by alexkim205** [comment]
Addressed the small fixes in #6133 and will take on the tooltip redesign in a separate issue once @clarkus's designs are good to go.
