### ISSUE TITLE
Add integration tests for most important paths

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#612]
**Is your feature request related to a problem? Please describe.**
We want to avoid really basic functionality (signing up -> loading trends page) failing unnoticed.

**Describe the solution you'd like**
Integration tests that test really basic functionality

**Describe alternatives you've considered**
Manual QA.

**Additional context**
Based on [this](https://github.com/PostHog/post-mortem/blob/master/2020-04-16%20users%20unable%20to%20sign%20up%20to%20team.md) post-mortem

***Thank*** you for your feature request - we love each and every one!

**Comment by mariusandra** [comment]
We had various integration tests in my previous job. We were using Ruby on Rails, so the tools were different, though similar things might exists in the Django world... or they might be easy to build.

Our stack basically consisted of [cucumber](https://cucumber.io/) + [capybara](https://teamcapybara.github.io/capybara/) + [site_prism](https://github.com/site-prism/site_prism).

This combination worked really well for us in the end. Here's a brief overview of the trio:

## Cucumber

Cucumber is a DSL for describing actions [like so](https://cucumber.io/docs/guides/browser-automation/):

```cucumber
# in file: cheese.feature
Scenario: Finding some cheese
   Given I am on the Google search page
   When I search for "Cheese!"
   Then the page title should start with "cheese"
```

Then this file is linked to a bunch of code that looks like this:

```ruby
require 'rubygems'
require 'selenium-webdriver'

Given(/^I am on the Google search page$/) do
  driver = Selenium::WebDriver.for :firefox
  driver.get "http://google.com"
end

When(/^I search for "([^"]*)"$/) do
  element = driver.find_element(name: "q")
  element.send_keys "Cheese!"
  element.submit
end

Then(/^the page title should start with "([^"]*)"$/) do
  wait = Selenium::WebDriver::Wait.new(timeout: 10)
  wait.until { driver.title.downcase.start_with? "cheese!" }
  puts "Page title is #{driver.title}"
    browser.close
end
```

Whenever cucumber encounters one of these plain-text lines, it looks for a matching Given/When/Then block and runs the code behind it.

It's just a nice way of abstracting over the steps.

There are some versions of this for python as well: [aloe](https://aloe.readthedocs.io/en/latest/), [behave](https://behave.readthedocs.io/en/latest/tutorial.html#features).

In the `Given` blocks you set up your environment (`Given I have a dashboard with three random items` and `Given I'm on the dashboard page`), in the `When` blocks you click things and in the `Then` blocks you assure things happened or not.

## Capybara

Capybara is just a wrapper over selenium that makes it a bit easier to write logic that interacts with a browser.

Instead of `page.find("div[text=Sign in]").click()` you write something like `click_button "Sign in"`.

It also abstracts away the differences in browser implementations.

Here's a sample of its code in ruby:

```ruby
    visit '/sessions/new'
    within("#session") do
      fill_in 'Email', with: 'user@example.com'
      fill_in 'Password', with: 'password'
    end
    click_button 'Sign in'
    expect(page).to have_content 'Success'
```

There are [versions](https://elliterate.github.io/capybara.py/#id3) of capybara also for python.

## Site Prism

This is where the real magic happens. It uses a concept called "[Page Objects](https://martinfowler.com/bliki/PageObject.html)" to abstract the details in a page.

Here's code copied from their [readme](https://github.com/site-prism/site_prism):

```ruby
# define our site's pages

class Home < SitePrism::Page
  set_url '/index.htm'
  set_url_matcher(/google.com\/?/)

  element :search_field, 'input[name="q"]'
  element :search_button, 'button[name="btnK"]'
  elements :footer_links, '#footer a'
  section :menu, Menu, '#gbx3'
end

class SearchResults < SitePrism::Page
  set_url_matcher(/google.com\/results\?.*/)

  section :menu, Menu, '#gbx3'
  sections :search_results, SearchResults, '#results li'

  def search_result_links
    search_results.map { |result| result.title['href'] }
  end
end

# define sections used on multiple pages or multiple times on one page

class Menu < SitePrism::Section
  element :search, 'a.search'
  element :images, 'a.image-search'
  element :maps, 'a.map-search'
end

class SearchResults < SitePrism::Section
  element :title, 'a.title'
  element :blurb, 'span.result-description'
end

# now for some tests

When(/^I navigate to the google home page$/) do
  @home = Home.new
  @home.load
end

Then(/^the home page should contain the menu and the search form$/) do
  @home.wait_until_menu_visible # menu loads after a second or 2, give it time to arrive
  expect(@home).to have_menu
  expect(@home).to have_search_field
  expect(@home).to have_search_button
end

When(/^I search for Sausages$/) do
  @home.search_field.set 'Sausages'
  @home.search_button.click
end

Then(/^the search results page is displayed$/) do
  @results_page = SearchResults.new
  expect(@results_page).to be_displayed
end

Then(/^the search results page contains 10 individual search results$/) do
  @results_page.wait_until_search_results_visible
  expect(@results_page).to have_search_results(count: 10)
end

Then(/^the search results contain a link to the wikipedia sausages page$/) do
  expect(@results_page.search_result_links).to include('http://en.wikipedia.org/wiki/Sausage')
end
```

Instead of running `page.find('button[name="btnK"]').click` you just run `@home.search_button.click`. 

Instead of `page.find("#results li").map { |result| result.title['href'] }.include?("http://en.wikipedia.org/wiki/Sausage")` you can write `@results_page.search_result_links.include?("http://en.wikipedia.org/wiki/Sausage")`

When you combine this with cucumber you can write pretty neat code that lets you test your app in a very joyful way.

I found a few libraries doing that in Python: [page-objects](https://page-objects.readthedocs.io/en/latest/), [webium](https://wgnet.github.io/webium/).

### `data-attr`

A pattern that worked well for us with site_prism was to use something called `data-attr` to mark elements in React that we could then refer to in the tests. 

What I mean is that we often have code that's just a tangled mess of `<div>`s. in the end, like:

```jsx
<Header> // it's a <div>
  <UserMenu> // it's a <div>
    <Logout /> // it's a <button>
  </UserMenu>
</Header>
```

Those might be random `antd` Menu elements or who knows what under the hood.

Instead of adding a new `className` to the `Header`, `UserMenu` and `Logout` elements (and their specific children that need to be clicked or checked) that does not change styles, just so we could target the elements, was a losing battle.

So instead we added `data-attr="header"` (or `dataAttr="header"` in JSX) where it was needed. Then we could continuously link to the header, no matter if the underlying implementation changed.

For elements like <header> it's perhaps an overkill to add markup like this, but imagine trying to reliably refer to a select field in a list of filters that is nested inside a huge group of elements. For those cases adding `data-attr` was real joy-sparker.

...

That's a quick overview of what we used. I believe something like this could work quite well for PostHog's integration tests as well. I don't know enough of the ecosystem to recommend specific tools to use, but this is already a good start for further investigation.

**Comment by EDsCODE** [comment]
Draft of what should be covered. Heavy focus on trends page and key elements of other pages

In order of priority what to cover:

0. Visit every single page (this is essentially a unit test to check that an frontend changes don't cause something to crash)
1. Sign up 
  a. Enter info into every field and submit
2. Login 
  a. Enter valid info into field and submit
  b. Enter invalid info and submit
  c. reset password link?
3. Trends (Do actions below and check if anything causes crash/doesn't return from server)
  a. Default load with element
  b. Filter an event
  c. Filter an action
  d. Apply an overall  prop filter
  e. apply a breakdown
  f. apply stickiness
  g. apply a date filter
  h. apply an interval filter
  i. display table, chart
  j. switch to sessions
4. Funnel
  a. create funnel
5. Dashboards
  a. create a dashboard
6. People
  a. create a cohort
