### ISSUE TITLE
AND cohort filtering

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#6186]
## Is your feature request related to a problem?

Currently you can filter cohorts based on either:
1. User has done $ACTION in $timerange
2. User has property

A cohort can have both filters, but they are combined with an OR.

[User](https://posthog.slack.com/archives/C01F31E9PRD/p1632942932038500) asked to have ways to combine these filters as AND statements

## Describe the solution you'd like

Allow toggling AND/OR in a clean way

## Describe alternatives you've considered

Workaround: Create one cohort for action, another filtering on property and user belonging to the first cohort.

**Comment by weyert** [comment]
Yes, this would be nice to have for the feature flags too. 

Now if you want to assign a user to a feature flag if they have any of 17+ specific user properties, you need to add 17 group filters. E.g. visited_store/1 OR visited_store3, OR visited_store4 etc

**Comment by kpthatsme** [comment]
Bumping this up - would be a great help to some of our pipeline work too that I'm doing with @charlescook-ph  :) 

@EDsCODE Do you have an idea of the complexity / scope to introduce this?

Specifically just need the ability to create dynamic cohorts based on 'AND' in addition to 'OR' i.e. person is in cohort if they did an action _and_ have a property value set.

**Comment by clarkus** [comment]
Related https://github.com/PostHog/posthog/issues/2273

**Comment by clarkus** [comment]
I spent a little time thinking about this after chatting with @kpthatsme. I think short term we could remove the logical operators between criteria blocks, and instead place a `match any / all` select prominently at the top of the criteria list. Match any would be a logical or scenario, while match all would be logical ands. Thoughts on these changes?

Note this is a quick redraw of cohort creation and includes more updates than necessary for this specific issue.
https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf/PostHog-App?node-id=5399%3A34436

<img width="1152" alt="all cohorts" src="https://user-images.githubusercontent.com/254612/142923353-3704347f-67bf-4b81-a976-8a61da658c9d.png">

**Comment by EDsCODE** [comment]
> Bumping this up - would be a great help to some of our pipeline work too that I'm doing with @charlescook-ph :)
> 
> @EDsCODE Do you have an idea of the complexity / scope to introduce this?
> 
> Specifically just need the ability to create dynamic cohorts based on 'AND' in addition to 'OR' i.e. person is in cohort if they did an action _and_ have a property value set.

Pretty straightforward implementation will just require a bit of effort and double checking on performant the queries are. Absolutely want to prioritize this though

**Comment by clarkus** [comment]
There is a quick update at https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf/PostHog-App?node-id=5399%3A34436 that moves away from a global logical operator and instead moves to operators between matching criteria. Still rough, but wanted to put something together to give us more options for implementation. 

One thing to consider is that the repetition of operators will increase the height requirements for this form. Sufficiently complex cohort matching criteria could justify the use of a full page as a container instead of a modal. A modal could be considered for spot editing or otherwise editing a cohort without having to leave your current context. 

<img width="565" alt="Screen Shot 2021-12-16 at 10 39 01 AM" src="https://user-images.githubusercontent.com/254612/146429480-070e2eb5-6236-4a57-81e9-ce51983b695b.png">

**Comment by camerondeleone** [comment]
+1 on this, it came up for [this](https://app.hubspot.com/contacts/6958578/deal/7695203370/) user today (and several others in recent memory)

**Comment by macobo** [comment]
Related ticket: https://github.com/PostHog/posthog/issues/5854

**Comment by EDsCODE** [comment]
Closed after cohort revamp
