### ISSUE TITLE
More closely associate actions loading spinner with table

### ISSUE THREAD

**Issue by corywatilo** [PostHog/posthog#6192]
When creating an Action and after saving the definition, it isn't clear that a query is being run. This makes it hard to tell if the definition is incorrect, or if a query is actively being run.

### For several seconds, you get this:

![image](https://user-images.githubusercontent.com/154479/135484146-83827fa7-40d8-48c6-8b94-5c8457b590d3.png)

### Clicking (browser) refresh, I see a loading icon just below the action name:

![image](https://user-images.githubusercontent.com/154479/135482919-7dd6bdf0-f137-4c1f-9547-db32f652a0cb.png)

## Two UX issues:

1. After a few seconds, the table below _does_ end up populating, but there's no spinner in the area, so unless you know where to look for the spinner (just under the action name), it looks like the definition doesn't return any data
2. After initially saving a definition, it doesn't appear the query is being run. I had to refresh the browser to get the spinner, showing me _something_ was happening

(This is on Cloud)

**Comment by mariusandra** [comment]
@pauldambra I'll assign this one to you as well, as it's connected to the events table, just this one is shown under the "actions" page. It's also a great opportunity to learn about the difference between actions and events under clickhouse... and actions and events under postgres :).

**Comment by pauldambra** [comment]
There are three "loading" states for the page

1) under the action name we display `This action matches 199 events` the spinner under the action name is only for the call to count the matching events
2) "calculating action, please hold on" which shows when saving/loading the action itself
3) and then also loading the events to populate the table, this doesn't have a loading state wired up in the page

The slower the network the clearer it is what is happening

1) a whole page spinner
2) then the form loads in and the loading state for 2 shows
3) the action loads and the loading state for 1 shows as the count call can be made now the action is loaded
4) then the events are loaded and there is no indication in the UI that is happening

The mouse tries to highlight the loading states in this gif (simulating a very slow network connection so the events table takes a long time to load)
![slowloading](https://user-images.githubusercontent.com/984817/136025156-6c9697b4-8391-4ca8-9f45-a265d50b167d.gif)

The quickest fix is to have the events table show a loading state

Ideally (IMHO) there would be one place on this page to look that would show all of these loading states so that once you know where to look you keep getting feedback from the same place

**Comment by pauldambra** [comment]
so as an example (without making sure that there is enough vertical space for the loader)

![slowloading2](https://user-images.githubusercontent.com/984817/136026453-c7995b14-ad72-42fc-adba-2ba560537a25.gif)

That also has a change to the events table to not show the "you have no events" text until it has finished loading and knows if there are any events

@corywatilo would a tidy version of that spinner work for you?

**Comment by pauldambra** [comment]
opened pull request changes the events table loading so that it looks like this
![slowloading3](https://user-images.githubusercontent.com/984817/136033637-5f9cfca2-994a-4687-a62f-a61d74a09109.gif)

**Comment by pauldambra** [comment]
you can better see the before and after of the events table here:

## before

![events-loading-before](https://user-images.githubusercontent.com/984817/136034829-8bdf3290-6838-4986-b579-7d4645044fa5.gif)

## after

![events-loading-after](https://user-images.githubusercontent.com/984817/136034860-52c375f8-d1a4-4375-a312-45467c93f51f.gif)

**Comment by clarkus** [comment]
related https://github.com/PostHog/posthog/issues/5411 - spinners can be great, but a skeleton screen might improve perceived performance here.

**Comment by corywatilo** [comment]
Much better, thanks!
