### ISSUE TITLE
Investing in our developers: Should we move to Open API?

### ISSUE THREAD

**Issue by kpthatsme** [PostHog/posthog#6211]
**Context**
We know our API and SDK support is not perfect. We are missing key functionality in core SDKs as well as general support for certain libraries.

There are 3 buckets of issues developers encounter today:
1. Lack of library support (we don't support the SDK they need)
1. Lack of functionality support (we have a library, but it doesn't support certain functionality i.e. feature flags)
1. Lack of correctness (our API docs are out of date with how things currently work)

**Proposal**
- Rewrite our API to match the [Open API](https://swagger.io/specification/) spec. 
- Use this process to address any inconsistencies in our API definitions.
- Use our Open API spec to update our SDKs and rollout new SDKs.

**Pros**
- We would have a uniform, high level way to plan and discuss our APIs
- We could utilize services to generate SDKs based on our open API spec
- A single investment helps us tackle all 3 issues mentioned above

**Cons**
- It's an investment to rewrite and port our APIs, we would need to be strategic and careful with the work.
- Auto generated solutions are never turn-key, I'm sure there will be some things that we need to do manually to create a good SDK experience
 
 
This is a bit pie-in-the-sky, I want to get everyone's thoughts and pushback. Where does this proposal break down? Am I underestimating the effort to move to OpenAPI? Am I over inflating the power of SDK generators?

The goal here is to think about what investments we can make today that will have an outsized impact in what they open up for us and our community.

cc: @marcushyett-ph @leggetter @timgl @yakkomajuri

**Comment by yakkomajuri** [comment]
I definitely like the idea of a more standardized API that in turn is also better documented.

_However_, I don't feel like this would be worth the investment now. At least regarding the problems you mentioned, 1 and 2 can be addressed without this. We can also address 3 without this but indeed adhering to the OpenAPI spec here would give us more power to auto-generate updated Docs with existing tooling. 

**So ultimately, I see this as something that could be very valuable, just not right now.**

One short term approach here could be more investment in the SDKs and plugins. This way we can cover a lot of use cases for getting data in and out of PostHog without people having to interact with the API themselves. This is certainly limited in scope, but could be a way of addressing some of this while moving fast as we're still limited by engineering resources.

**Comment by Twixes** [comment]
We've actually talked about this with @guidoiaquinti the other day in the context of libraries being all over the place (in terms of features) right now. That's a pain for some users. OpenAPI definitions would make it easier for us to eliminate the pain, and we probably don't need to _re_write anything since we already use an API framework – DRF – almost everywhere. That should make deriving OpenAPI specs pretty straightforward: https://www.django-rest-framework.org/topics/documenting-your-api/.
I can see the value in that, but like @yakkomajuri I'm not sure about whether we'd be able to make the most of it right now. I'm not convinced by autogenerated SDKs, and while this would be amazing for Docs and manual SDK work, that'd need quite a Docs makeover.

**Comment by leggetter** [comment]
+1 on there being no requirement to re-write the APIs. We can document the APIs as-is. OpenAPI provides a way of describing your API it does prescribe your API structure.

In the longer term, we should discuss an API Design First over a Code first approach ([good discussion article](https://apisyouwonthate.com/blog/api-design-first-vs-code-first)). However, a Code First and auto-generating our OpenAPI specs probably aligns well with the way we currently work. This can be achieved via the tools @Twixes pointed to in the DRF docs (annotations).

My personal opinion on auto-generating SDKs: I haven't tried out tools related to this for a few years but it used to be that you'd still have to spend a lot of time creating wrappers on the auto-generated codebase to make the SDKs feel natural to use (provide a good developer experience). So, it may be worth doing some investigation since the tooling may have improved. 

I'll pose some questions to help better understand if it'd be worthwhile creating OpenAPI specs now:

- Are our API docs out of date?
- Is it important that our APIs are accurately documented?
- Do we occasionally make breaking changes to our API and not notice until after a release?
- Do any of our customers or potential customers use Postman, Paw or other tools to evaluate and explore our APIs?
- Do our customers ever want to do testing against our APIs and ask for a Sandbox environment?

If the answer to any of these is "yes", then it may well be worth creating OpenAPI specs.

There's further discussion to be had here about how we approach this. For example, should we auto-generate for each release and run a suite of tests to detect changes? But that's a discussion to be had if we decide there is value in OpenAPI specs now.

**Comment by paolodamico** [comment]
Agree that we're better off holding off on this right now as there are more important things to focus on, and based on user conversations this hasn't seem to be an issue. My proposal:
- @leggetter maybe we can invest time updating our API docs for key endpoints? I don't think we have a ton of outdated info but some relevant endpoints are missing. Also, incorporate @Twixes changes.
- Let's start tracking some key API requests so we know how the API is being used. Probably Core Experience should own this, @mariusandra?

If we agree, think we can close this issue.

**Comment by marcushyett-ph** [comment]
Thanks for the Proposal @kpthatsme - this is quite close to the conversation @mariusandra  and I had last week around data trust.

This is definitely an issue - likely not as urgent as some of the other data trust issues. I think the first step which could be a quick win though is to actually define the API we need (even if we don't support it today) - so we can work towards something more consistent and reliable.

>  I'm not convinced by autogenerated SDKs

Perhaps we might not use Open API for code-gen but it would be great if we could test every library against our Open API spec to ensure it behaves as we and our clients would expect it to.

**Comment by leggetter** [comment]
> Perhaps we might not use Open API for code-gen but it would be great if we could test every library against our Open API spec to ensure it behaves as we and our clients would expect it to.

Yes, this is the biggest benefit I can see us getting right now.

There are probably a few ways of automating the testing. The tool I've used previously is [prism](https://github.com/stoplightio/prism) which allows you to spin up a [validation proxy](https://github.com/stoplightio/prism/blob/master/docs/guides/03-validation-proxy.md) based on your API spec. You then make requests against the proxy and it ensures that the requests and responses match the spec.
