### ISSUE TITLE
E2E tests don't work on contributor PRs

### ISSUE THREAD

**Issue by Twixes** [PostHog/posthog#6347]
## Bug description

Our Cypress suite fails on contributor PRs – see https://github.com/PostHog/posthog/pull/6214#issuecomment-939258093. Looks like test "Sessions Table highlights matches" in `session.js` is the main culprit.

## Expected behavior

All tests should be green if no actual bug was introduced! The current situation makes both contributors and us less confident about PRs.

## How to reproduce

1. Open a PR from a fork.
2. See all E2E checks going red.

**Comment by hazzadous** [comment]
I'm getting a failure for https://github.com/PostHog/posthog/pull/6339/files as well. I guess you don't have any more ideas past "Sessions Table highlights matches" being the culprit?

It looks like it could be that we are relying on `GITHUB_TOKEN` being set, which will not be the case for forks (?)

See here for usage: https://github.com/PostHog/posthog/blob/6bc3a80dca46e0a30e0ec1c640037cf3d14bf0c0/posthog/plugins/utils.py#L41:L41

**Comment by tiina303** [comment]
Related (potentially) https://github.com/PostHog/posthog.com/issues/2129

**Comment by banagale** [comment]
I authored PostHog/posthog.com#2129.

It appears employee-granted write permissions are required for direct clone PRs and CI is broken for fork-based PRs on both `posthog` and `posthog.com`.  

The impact is contributor PRs appear to have check failures which discourage review. 

When reviewed, I presume PRs are less likely to be approved for merge because outwardly they appear to fail CI checks. ([posthog.com/#2126](https://github.com/PostHog/posthog.com/pull/2126) is an example of documentation of a merged feature that has been reviewed but appears to fail CI checks)

For this issue, I've opened #6418 which updates the E2E checkout step to use `checkout@v2` and specify `GITHUB_REF` as per explanation [here](https://github.com/PostHog/posthog.com/issues/2129#issuecomment-931911438).

I can't say for sure this is the issue for E2E, because at the moment, contributors can not unblock CI check bugs.

Unraveling expected contributor workflows has been my focus as I [began researching a PR](https://github.com/banagale/posthog/issues/1#issuecomment-912693068) for my first product issue and could not discern the organization's preferences for PRs.

Given PostHog is intended to be an open source project and with a goal of attracting contributions from the community, I thought clarifying this point was the most important work I could do for the company.

I outlined the need to explicitly define development workflow for contributors in [posthog.com/#2129](https://github.com/PostHog/posthog.com/issues/2018). In that issue, I recommend auditing all posthog CI/CD workflows for behavior that matches the above preferences. Such an audit should have caught this bug in E2E.

I have an open PR, [posthog.com/#2119](https://github.com/PostHog/posthog.com/pull/2119) that closes this documentation gap, specifying organizational preference along with an reworking of contributor documentation.

**Comment by Twixes** [comment]
These tests still aren't 100% reliable, but it seems the issue with PRs from forks is gone.
