### ISSUE TITLE
Remove Insights History

### ISSUE THREAD

**Issue by Twixes** [PostHog/posthog#6478]
## Is your feature request related to a problem?

Well, actually this is removal of a feature. We currently have something called "History" on the new insight screen. It shows all insights that were calculated, drafts AND saved ones. But it just isn't useful – it's way too noisy. Seeing that it's used by just ~2% of active users of Insights ([funnel](https://app.posthog.com/insights?insight=FUNNELS&date_from=-30d&actions=%5B%7B%22id%22%3A%227165%22%2C%22name%22%3A%22Discovered%20Learnings%20-%20extended%22%2C%22type%22%3A%22actions%22%2C%22order%22%3A0%7D%5D&events=%5B%7B%22id%22%3A%22insight%20history%20item%20clicked%22%2C%22name%22%3A%22insight%20history%20item%20clicked%22%2C%22type%22%3A%22events%22%2C%22order%22%3A1%7D%5D&display=FunnelViz&interval=day&properties=%5B%5D&filter_test_accounts=true&funnel_viz_type=steps&exclusions=%5B%5D&funnel_from_step=0&funnel_to_step=1#fromItem=459518)), I think it's more confusing than valuable.

## Describe the solution you'd like

For users with Saved Insights rolled out, let's make the History button non-functional, adding a tooltip pointing to Saved Insights as a better way to view a list of insights. When Saved Insights gets un-feature-flagged, we'll be able to remove History from the code base as well.

CC @paolodamico @clarkus 

## Additional context

This can be closed with History removal: https://github.com/PostHog/posthog/issues/5551

**Comment by mariusandra** [comment]
💯 , it's been causing some bugs recently (possibly [clearing saved filters](https://github.com/PostHog/posthog/issues/6439) on dashboard items, yet there was [another new bug](https://github.com/PostHog/posthog/pull/6470) there as well) and its existence requires workarounds in otherwise smooth looking code.

More support for removing it here: https://github.com/PostHog/posthog/issues/5747#issuecomment-921011517

That said, I wouldn't disrupt things more now and remove it once we launch saved insights.

**Comment by Twixes** [comment]
Done!
