### ISSUE TITLE
Showing/hiding other breakdown in funnels is buggy

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#6560]
## Bug description

When showing/hiding the "Other" property breakdown in funnels, all "Others" are selected which is confusing. Also, depending on ordering it may lead you to think that colors are wrong because you select a "Other" with a color but another color pops up.

![image](https://user-images.githubusercontent.com/5864173/137995181-db83d962-5a69-4f85-a53c-074bb0189355.gif)

Bonus, this general checkbox has a weird blue, should be the default primary color.

<img width="509" alt="image" src="https://user-images.githubusercontent.com/5864173/137995228-e0069b06-9506-4037-b5cc-bcf50fab8e90.png">

## Expected behavior

Only the line I show/hide should change.

## How to reproduce

See recording above.

## Environment

- [X] PostHog Cloud

**Comment by neilkakkar** [comment]
The root cause here I think is ~~core-analytics~~ the query:

Our logical inferred property called "Other" (grouping remaining low value properties) coincides with the actual property value called "Other" (for some unfortunate reason, this property is set to the same value).

So, on the front end, both rows have the same key, which turns messy. We should probably have a non-clashing key for the logical "Other", and name it something else on the FE.

**Comment by neilkakkar** [comment]
I expect persons modal to be the same for both, because of this same issue (which is wrong).

**Comment by paolodamico** [comment]
Thanks for that context @neilkakkar! Bumping this to P1 then based on the persons modal.

**Comment by pauldambra** [comment]
@alexkim205 I've moved this to you after sprint planning earlier. Feel free to unassign if I've misunderstood :)

**Comment by alexkim205** [comment]
This seems to have been fixed when we started returning arrays for `breakdown` and `breakdown_value` as part of the multiple property breakdown project. There's some mopping up to do which I'll consolidate in #7415
