### ISSUE TITLE
[Epic] Self-serve PostHog Demos

### ISSUE THREAD

**Issue by kpthatsme** [PostHog/posthog#6583]
### Overview
A key component to any product-led growth or sales funnel is the ability to try the product before using it. 

Right now, teams can get a feel for the product by ingesting their data and getting events in, but it's high effort and may not lead to the best, most accurate experience of the product due to their taxonomy.

#### Motivations
1. Provide visitors with a self-serve experience where they can see the value of PostHog with relevant use cases without ingesting any data 
1. Help our Sales team scale by first routing prospects through self-serve demos 
1. Tighten up our self-serve funnel - we can use marketing to drive towards demo entry and demo entry to mark the start of our sales funnel.

##### _What about focusing on demo videos instead?_
   - Since this is going to be a living, breathing, org with real data constantly flowing into it we don't need to worry about updating our videos anytime the UI changes.
   - Interactivity generally wins. For folks that want a demo they will still have the same ability they do today to self-select into one.
   - Videos and a demo environment aren't mutually exclusive, they attract different personas and long-term there's room for both. 

#### Goal 1: Develop an excellent taxonomy and a system that perpetually seeds data from it into a PostHog org
Summary:
- Develop an excellent taxonomy. An excellent taxonomy...
   1) Makes it easy to demonstrate the value of core analytics functionality (for example, funnel breakdowns) while feeling sufficiently random (the way a real product would)
   1) Is comprised of events and paths that are commonly understood and applicable to industries

- Build out a process that perpetually seeds a PostHog org with data given a taxonomy

_Open question: Which industry should we base our first dataset on?_
  - Based on usage data, we have strong usage from SaaS companies (not very granular) and Fintech after that. 
  - My suggestion would be our first taxonomy be around typical SaaS use cases– maybe our own version of Coinbase (i.e. CoinHog)?

#### Goal 2: Expose the demo data project to the public
Summary:
- Surface demo org behind a url we can route to (e.g. app.posthog.com/demo - today HogFlix lives there)
- Email gate to get into the demo
- Demo is fully interactive. Users are allowed to save content in their session but it doesn't persist or show up for others. 

_After Goal 2: Demo can be sent directly in Slack and sales conversations at this point._

#### Goal 3: Build CTAs into demo environment, AB test demo signups
Summary:
- Build out CTAs in the demo environment to get started with self-hosted or cloud
- Run an AB test: Swap out primary website hero CTAs with the new demo flow

_After Goal 3:  Wait for learnings from the AB test and optimizations into core experience before investing into further datasets._

#### Goal 4: Build out additional datasets
Summary:
- Build out additional datasets for other industries (i.e. e-commerce, healthcare, media)
- Build out functionality for demo users to hop between relevant datasets (maybe each is a project?)

@samwinslow I'd like to get your thoughts on this and chat about it later this week. Seeing how @jamesefhawkins' time looks I think it would make sense for us to prioritize some of this work before the work around expanding our pipeline. So I'm thinking this could be the next project after usage reporting (and before Next Steps - or @smallbrownbike  takes Next Steps).

**Comment by camerondeleone** [comment]
I am pretty regularly running into missing data issues using the Demo (Calls) project during demos. The main project obviously has good, usable data, but am not comfortable demoing from there (especially when many calls are recorded/distributed, etc). 

It makes sense for live demos to be on a dataset that users can then try out themselves, recreating the analyses they are shown. Here is a list of the features I hit during a demo / where I expect to see what data, in case it's helpful for ongoing work on this — basically, here is my wishlist 🙏 

**Events**
- Custom events (eg insight viewed/analyzed)
- Autocaptured events (specifically, pageviews and clicks, since these are concrete and easy for users to understand) attributed to both anonymous users and identified users. Need this for toolbar demo.
- event stats, ideally showing at least a few events' usage for the past 30 days ('how do i track my usage?' comes up often on calls)
- Perhaps most importantly importantly, events are attributed to groups ('Organization' 'Instance' and 'Project' are great). Currently demo data does not have group id, so it harder to upsell on this feature when some visualizations appear empty.
- At least enough events with feature flag data to show a breakdown on trend/funnel

**Persons**
- Anonymous users 
- Identified users (preferably identified have multiple IDs so I can talk about how identification works)

**Recordings** 
- currently use production data and navigate to my person object for this, but better not to. (They can be short/limited but should at least contain a few events each beyond simple pageviews)

**Groups**
- A few test companies, with fake metadata


@simfish85 if you have any suggestions or things you'd like to see, feel free to add.

**Comment by simfish85** [comment]
I've been basing my demos around showing off various aspects of an AARRR funnel so we'd need the right data to show:
1. An acquisition trend chart (sign-ups)
2. An activation funnel
3. A retention insight
4. Ideally Revenue and Referral would be on a dashboard with the other parts of the funnel to wrap the story up nicely.

**Advanced but awesome stuff to show**

- A session recording where we see a user fail to convert
- An in-flight experiment

**Comment by Twixes** [comment]
https://demo.posthog.com is now available. :)
