### ISSUE TITLE
Support auto-capture on long-form content

### ISSUE THREAD

**Issue by marcushyett-ph** [PostHog/posthog#6604]
## Is your feature request related to a problem?

To measure interactions on long-form content e.g. a blog article I'd like to understand how long someone spends on a page, how far they scroll, mouse-movements to indicate reading content, etc.

## Describe the solution you'd like

* I'd like to auto capture scroll, mouse-move and time spent as events

## Describe alternatives you've considered

* Manually instrumenting events based which are triggered when a user scrolls or sends a certain time period on the page

## Additional context
Tagging @rcmarron since you've been focussed on session recording recently and I believe we capture some kind of scrolling / mouse moment events for that. Perhaps it's unrelated but thought you might have some useful context.

**Comment by rcmarron** [comment]
I used to work on a news product, and there we tracked "article engagement" based on a couple of things:
1) Every page leave event had:
    * Time spent on page
    * Active time spent on page - meaning <1m between interaction events (mouse moves, scroll etc.)
2) We tracked article sections as they came into the viewport (e.g. 'section entered viewport', and 'section left viewport' events). The article section events also had the same timing properties as page views (total time and active time). This was the best approximation of 'how far did the user read'. Using pure scroll position wasn't too interesting because it varies based on the device/window width.

For our purposes, I could definitely see adding timing information to pageleave events, and maybe some helper functions to allow users to easily track how long things are in the viewport.

**Comment by marcushyett-ph** [comment]
Great context @rcmarron thanks for sharing - curious - did you (your organization) instrument these extra properties on events yourself or did the analytics product you used automatically add them?

**Comment by rcmarron** [comment]
We instrumented them ourselves. There are some news specific analytics providers that I think provide these analytics out of the box ([ChartBeat](https://chartbeat.com/) is the big one), but they were lacking in other areas, so they wouldn't work for us.
