### ISSUE TITLE
CI actions should run in our container environment

### ISSUE THREAD

**Issue by guidoiaquinti** [PostHog/posthog#6605]
## Is your feature request related to a problem?

While working on an unrelated task, I found that CI actions like `benchmark.yml` and `ci-backend.yml` are currently not using our containerised environment that already defines dependencies and has those already installed.

This creates (at least) 2 issues:

* CI needs to run `pip install` to install the dependencies at every execution
* CI task definition needs to explicit OS dependencies for ☝️   

## Describe the solution you’d like

CI actions should run in our container environment

## Describe alternatives you’ve considered

Do nothing. There’s a risk of doing that as OS dependencies in the containerised VS non-containerised env can diverge.

**Comment by neilkakkar** [comment]
I know atleast `benchmark.yml` needs additional dependencies. I'm guessing in that case we can still start from our defined base (assuming it has capabilities to add more deps), and just add the new deps, so we reduce the build time?

I wouldn't want to do this for `benchmark`, since I'd like the dependencies to not drift under us, as this destroys benchmarks. Regarding speed, it's a slow action that's not run on every PR anyway, so it should be fine.

**Comment by guidoiaquinti** [comment]
> I know atleast `benchmark.yml` needs additional dependencies. I'm guessing in that case we can still start from our defined base (assuming it has capabilities to add more deps), and just add the new deps, so we reduce the build time?

This is my suggestion. Best practice is to define a set of common dependencies and then built on top of them case-by-case. In this scenario, we will start from a PostHog “base image” to then add/modify all the custom dependencies we might need as part of the benchmark suite. Does it make sense?

**Comment by neilkakkar** [comment]
Hmm, actually, the benchmarks wouldn't run at all if they're missing a dep, so we can't protect against the dependency drift anyway. Your suggestion sounds reasonable. cc: @macobo for thoughts too.

**Comment by guidoiaquinti** [comment]
> Hmm, actually, the benchmarks wouldn't run at all if they're missing a dep, so we can't protect against the dependency drift anyway. Your suggestion sounds reasonable. cc: @macobo for thoughts too.

For dependencies drift I mean something like:

https://github.com/PostHog/posthog/blob/8d217415844994571c3159459be40101238cac68/.github/workflows/ci-backend.yml#L78-L79

where we install random version of packages that we also install/manage into our container images -> what we test here might be different than what will end up in the container image we distribute and run.

**Comment by macobo** [comment]
For benchmarks there's two different considerations:
1. where does the test code run
2. Where does the test db run

For 1, we can do anything there as long as it has access to the db hosted outside CI

For 2 this needs to be a stable environment with enough resources- we should not run the db in ci for benchmarks because the added noise would make them useless.

**Comment by macobo** [comment]
Note on the ticket itself: I suspect pulling a base image and pip installing from gh actions cache is generally faster than building and pulling the docker image on branch tests.
