### ISSUE TITLE
[insight] trends cumulative persons does not match

### ISSUE THREAD

**Issue by EDsCODE** [PostHog/posthog#6802]
## Bug description

*Please describe.*  
- number of persons does not match insight graph number when cumulative chart is applied

## Expected behavior
- number should match

## How to reproduce

check this[ internal graph](https://app.posthog.com/insights?insight=TRENDS&actions=%5B%5D&events=%5B%7B%22id%22%3A%22insight%20analyzed%22%2C%22name%22%3A%22insight%20analyzed%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%2C%22math%22%3A%22dau%22%7D%5D&properties=%5B%5D&filter_test_accounts=true&exclusions=%5B%5D&funnel_from_step=0&funnel_to_step=1&compare=false&new_entity=%5B%5D&breakdown_type&date_from=dStart&interval=hour&display=ActionsLineGraphCumulative#personModal=%7B%22action%22%3A%7B%22id%22%3A%22insight%20analyzed%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%2C%22name%22%3A%22insight%20analyzed%22%2C%22custom_name%22%3Anull%2C%22math%22%3A%22dau%22%2C%22math_property%22%3Anull%2C%22properties%22%3A%5B%5D%7D%2C%22label%22%3A%22insight%20analyzed%22%2C%22date_from%22%3A%222021-11-02%2006%3A00%3A00%22%2C%22date_to%22%3A%222021-11-02%2006%3A00%3A00%22%2C%22filters%22%3A%7B%22insight%22%3A%22TRENDS%22%2C%22actions%22%3A%5B%5D%2C%22events%22%3A%5B%7B%22id%22%3A%22insight%20analyzed%22%2C%22name%22%3A%22insight%20analyzed%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%2C%22math%22%3A%22dau%22%7D%5D%2C%22properties%22%3A%5B%5D%2C%22filter_test_accounts%22%3Atrue%2C%22exclusions%22%3A%5B%5D%2C%22funnel_from_step%22%3A0%2C%22funnel_to_step%22%3A1%2C%22compare%22%3Afalse%2C%22new_entity%22%3A%5B%5D%2C%22breakdown_type%22%3Anull%2C%22date_from%22%3A%22dStart%22%2C%22interval%22%3A%22hour%22%2C%22display%22%3A%22ActionsLineGraphCumulative%22%7D%2C%22saveOriginal%22%3Atrue%2C%22pointValue%22%3A62%7D)

**Comment by EDsCODE** [comment]
This might be considered a presentational/definition issue. If there's a unique user that performed an event on day 1 and the same user did the event on day 2. When you select cumulative, should it be accumulating unique users over the time period (a) or unique users per day (b)? Because if (a), the scenario would mean that day 2 should show a value of 1 but if (b), the value should be 2 (even though it's the same user, the user performed a the event atleast once each day. 

@paolodamico @kpthatsme

**Comment by kpthatsme** [comment]
I think the right behavior here is for the Cumulative chart calculation to follow what is used in the chart definition in terms of Total Count / Unique Users.

So for example, if the chart is Pageviews by Total Count – then I think the Cumulative view would show all page views done across all users over all time. So someone who has used PostHog weekly since the start of the year would be counted multiple times in this view.

If it were Pageviews by Unique users– I think the cumulative view would be total number of users that have ever done a pageview event– so someone who has used Posthog everyday from the start of the year would only count once in the cumulative unique users chart.

**Comment by paolodamico** [comment]
I agree with @kpthatsme, we should mirror what the graph shows. If Day 0 shows 5 users and then Day 1 shows 10 users (5 from Day 0 and 5 new ones), the person modal should show the 10 users for Day 1. Maybe we add an info label at the top to  clarify when you select cumulative.
