### ISSUE TITLE
Write up guide to deploying on AWS ECS

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#694]
**Is your feature request related to a problem? Please describe.**

I want to know, step by step, how to deploy PostHog on AWS ECS (Fargate probably?)

**Describe the solution you'd like**
A guide in our docs walking me through it

**Describe alternatives you've considered**
Figuring this out myself.

**Additional context**

***Thank*** you for your feature request - we love each and every one!

**Comment by fuziontech** [comment]
After spending a bit on trying to sort out the VPCs I realized that a doc to get this done will end up being harder to use than just setting up a turnkey CloudFormation manifest. These are great because we can parameterize them to allow users to build out the infrastructure that works out best for them.

Check it out
https://github.com/fuziontech/posthog/tree/master/deployment/aws/ecs

If everyone is onboard I can update the docs today to be how to deploy this as a CloudFormation.
![Image of Infrastructure](https://raw.githubusercontent.com/fuziontech/posthog/master/deployment/aws/ecs/combined-designer.png)

I still need to figure out why their reference ECS design for CloudFormation has two public and private subnets. I'm guessing it is just for example, once I confirm that I will pare this down to only have 1 subnet for public and private.

**Comment by timgl** [comment]
Yep that sounds super sensible!

**Comment by fuziontech** [comment]
Doc PR is ready to go:
https://github.com/PostHog/docs/pull/23
We need to figure out where this will live:
https://github.com/fuziontech/posthog/blob/master/deployment/aws/ecs/combined.yaml

@timgl - When you get a chance can you review the [YAML config for CF](https://github.com/fuziontech/posthog/blob/master/deployment/aws/ecs/combined.yaml). If you dig it can you throw it into some S3 location so I can update the docs to reflect using an S3 location vs downloading the YAML as an alternative.

Alternatively it might just make sense to keep docs as they are and host the YAML in one of the repos. It keeps everything nice and transparent in that case.

**Comment by SanketDG** [comment]
@fuziontech Just a suggestion, could we also do a terraform recipe? IMO Terraform is much more widely used than CF (as its not locked to AWS)

**Comment by timgl** [comment]
@fuziontech Great! I've created a new repo where we can store various bits of deployment config: https://github.com/PostHog/deployment.

We're moving all the docs to https://github.com/posthog/posthog.com so might be worth creating the PR against that (sorry about that!)

@SanketDG Agree. We had an immediate need for CF but I'd love to have terraform too.

**Comment by fuziontech** [comment]
https://github.com/PostHog/posthog.com/pull/39 <= docs updated on posthog.com
