### ISSUE TITLE
Sprint 1.31.0 1/2 - 15 Nov - 26 Nov

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#6984]
Note: We'll try a new format where we split off into breakout rooms for the teams, then come back and the team leads will pitch their ideas in this meeting. We'll only do a super quick retrospective.

# Global Sprint Planning

## Plan: Proposed Goals for Next Sprint 

Each goal should have a single owner. Owner can only be an engineer.

1. Deploy groups
2. Increased number of discoveries of retentions

3. e2e helm chart testing set up for GCP/AWS/DO
4. MVP big migration support
5. Fix all the known person data integrity issues

6. Collaboration: Sharable urls (with team_id) @Twixes 
7. Perfect discovery and playback experience for session recordings @rcmarron 

# Team sprint planning

For your team sprint planning copy this template into a comment below for each team.

```
Team ___

## Retro

<!-- Talk about what went well, what didn't go well and any actions to improve next time -->

- 

## Hang over items from previous sprint

<!-- For each item, decide to re-prioritise (and add below) or deprioritise -->

- Item 1. prioritised/deprioritise

## Planning

<!-- Each item should have a single owner. Owner can only be an engineer. -->

### High priority

-

### Low priority / side quests

-

```

**Comment by fuziontech** [comment]
# Platform team

# Goals
- @guidoiaquinti e2e helm chart testing set up for GCP/AWS/DO
- @yakkomajuri MVP big migration support
- @tiina303 Fix all the known person data integrity issues

## Retro

- Guido says being support hero has been super chaotic and a learning experience. A lot of conversations had not been closed so that was a bit of a headache. Most customers were super happy to have the followup on close.
- Yakko mentioned that his sprint was hectic with a number of outages both real and imaginary. Somehow still managed to get everything done that he was looking to get done
- Tiina - Pretty decent sprint. Wasted some time with tests turned out having posthog (plugin server) running while running tests is a bad idea.
- Jaes - Hectic but somewhat productive week. OSA talk went really well. Slowly becoming more organized which feels quite nice.

## Hang over items from previous sprint
- TBD

# [Board](https://github.com/orgs/PostHog/projects/10?card_filter_query=label%3Ap0)
![image](https://user-images.githubusercontent.com/391319/141348128-e07d76d5-4fe5-42aa-9db9-a6439131c3d4.png)

**Comment by mariusandra** [comment]
# Team Core Experience

## What we will be working on

Collaboration.
- Finally finish project-scoped permalinks (team_id in the URL). @Twixes
- Figure out, validate and prioritise tasks 2, 3, 4, 5 within the collaboration project. @paolodamico 

Session recordings. @rcmarron (also support hero next week) & @alexkim205
- Crosslinking insights to the recordings. (In the people modals, e.g. funnel dropoff, trends persons, etc)
- Support for playback of recordings where the user used multiple tabs. (Currently we get HTML/CSS glitches)

[Saved insights continuation](https://github.com/PostHog/posthog/issues/6513#issuecomment-963001437) @mariusandra
- Fix insight URLs (`/insights/123/edit`)
- Ensure all insights and their empty + loading states are in storybook, and look consistent
- Stretch: [Insights many-to-many Dashboards](https://github.com/PostHog/posthog/issues/6712)

Other important work @pauldambra
- [Breakdown by multiple properties](https://github.com/PostHog/posthog/issues/938) for trends (continuation from last sprint)
- Scope event properties autocomplete to properties of selected event. 
  - [This customer report](https://github.com/PostHog/posthog/issues/6762)
  - [This issue](https://github.com/PostHog/posthog/issues/4936)
  - and [in this issue](https://github.com/PostHog/posthog/issues/4166)
  if someone is adding a filter to $pageview they should only see properties that have been seen on pageviews
- [Support time units in filters](https://github.com/PostHog/posthog/issues/6619) - a key customer and many others are struggling with this

## Retro

- Rick: clickhouse -> postgres test change screws up everything
- Alex: I'm on pycharm, so no dev environment issues... good otherwise
- Paul: cypress takes too much time, took down the plugin server
- Paolo: trying to work less hours
- Michael: rolled out a lot of really good ui changes, so been pretty good. Lowlight: should have messaged Chris earlier for tables
- Chris: been going pretty well, out for a week, looking at the user slack to see the stuff we're releasing and going "holy crap"... Lowlight: hard time reviewing stuff (slow laptop issues)
- Marius: saved insights out, happy with all progress, lowlight - sick for part of the sprint, also trying to work less hours

**Comment by EDsCODE** [comment]
## Core Analytics

### Goals:

**Group Analytics — Karl (Li, Eric/Neil)**

Goal: Get it ready for release, alpha users are happy

Tasks:

- Feedback from alpha users, make them happy.
- Groups pages
- Feature flags
- Remaining insights work
     - “Person modal” support
     - Lifecycle, etc
     - Test_account_filters
     - Stretch: sessions
- Design iteration w/ Chris
- Stretch: Partially updating group properties (depends on where tiina&yakko are with person updates)
- Docs & upsell & blog post work


**Retention — Harry (Eric)**

Goal: Questions to answer
Follow up usage engagement
Does general usage increase

Tasks:

- breakdowns
- N day vs rolling retention
- person URL changes
- stronger retention criteria. multiple events can determine retention or a funnel
- number table 
- per entity filtering

### Retro:

Eric: Some speed ups, worked with harry on restructuring the payloads
Harry: Test improvements everywhere. New person structure for correlations
Karl: Groups working in prod. Basic filtering on insights. Ingestion work
Li: Groups pages started
Neil: Wrapped up correlations. Worked on groups
