### ISSUE TITLE
Dashboards - timezone conversion

### ISSUE THREAD

**Issue by guidoiaquinti** [PostHog/posthog#7009]
## Is your feature request related to a problem?
No

## Describe the solution you'd like
We currently let our users to specify a default timezone at the project level. This information is then used to calculate timezone conversion suggestions in the dashboard view.

<img width="362" alt="Screenshot 2021-11-10 at 10 08 08" src="https://user-images.githubusercontent.com/4038041/141083930-e5e6373b-d78d-4d7e-a652-25f6d3e64bce.png">

It could be nice to have the charts directly converted to the same timezone specified at the project level.

## Describe alternatives you've considered
Do nothing.

## Additional context
See this Slack [thread](https://posthogusers.slack.com/archives/C01FKPGG5U6/p1636128681087300)

**Comment by timgl** [comment]
User who's had this issue: https://posthogusers.slack.com/archives/C01GLBKHKQT/p1646837650581099

**Comment by timgl** [comment]
I've dug into this a little bit, it's not impossible to do but will add complexity. Rough steps:

- Everywhere we use `{trunc_func}(timestamp)` we'll need to add the team's timezone: `{trunc_func}(timestamp, %(team_timezone)s)`
- It's basically impossible to test this with 100% certainty without rewriting a test for all insights and a lot of permutations within (filtered by DAU, WAU, breakdown etc)
- Once we enable this, or if people change their timezone, we'll need to clear the cache of all results for a team as otherwise you get inconsistent results
- How should we communicate to users that this has happened? I worry people will get confusing results.

**Alternative solutions**
- A materialized view with a timestamp field that is set to the correct timezone for each team. Not sure about the feasibility of this
- Rewrite all trunc_func and toDatetime functions in sync_execute. Kind of weird magic so not a huge fan of this.

**Comment by ShadowySpirits** [comment]
We are facing the same problem. Is there any progress now?

**Comment by timgl** [comment]
@EDsCODE Any thoughts about my proposed solution/how to generate confidence in testing this?

**Comment by EDsCODE** [comment]
What about doing this on the frontend level? It seems overkill and inconsistent to change query implementations for timezones as it's a very presentation layer piece. From a developer POV, it will be less overhead to know that everywhere we deal with times in the system is UTC based and that the display functions right before a user sees the time will converted the information into the appropriate timezone

There's an opportunity here to formalize all our date handling on the UI which will allow us to adapt to different cultural standards too such as the ordering in which we display year, month, day.

**Comment by pauldambra** [comment]
+100 to @EDsCODE suggestion 🌈

**Comment by timgl** [comment]
@EDsCODE the biggest problem/use case is intervals which you can't solve in the front end though

**Comment by EDsCODE** [comment]
Hmm, what's the issue with intervals? i'm missing something

**Comment by timgl** [comment]
If you're in US/Pacific and you want to know how many people signed up during _your_ day, there's no way of doing this in posthog as all of the intervals are based on UTC days.

**Comment by Twixes** [comment]
Yeah, we can easily move things around in the frontend for insights aggregated by hour, but anything larger than that (day, week, month) has to be done in or before the `GROUP BY dateTrunc(unit, timestamp)`.

**Comment by abrambailey** [comment]
> If you're in US/Pacific and you want to know how many people signed up during your day, there's no way of doing this in posthog as all of the intervals are based on UTC days.

Is this still the case?

**Comment by jacksontriffon** [comment]
Perhaps I'm the only one, but this would be an awesome feature to have!
