### ISSUE TITLE
Add annotations

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#708]
I want to be able to annotate when important things have happened (big launch, redesign, getting featured somewhere) so that if I see spikes in the data I can remember why that happened.

**Comment by EDsCODE** [comment]
Any preferences on how the annotations should be emphasized on the chart? 

One of the more subtle ways I'm experimenting with would be to inflate the bubble that has annotations
<img width="901" alt="Screen Shot 2020-05-26 at 12 09 56 PM" src="https://user-images.githubusercontent.com/13127476/82924110-e0baf800-9f49-11ea-9209-7e9ab01a8a5d.png">

**Comment by EDsCODE** [comment]
@mariusandra Looping in Marius for this question: I think it's time for the trends page to be refactored to be a model like funnels are and probably saving filters. With annotations there's going to be a lot more associated data that shouldn't be held within the URL. What do you guys think?

**Comment by timgl** [comment]
What I've seen before is a line through the graph. Then when clicking on the (1) you see all the annotations/discussions. It makes sense b/c it indicates that from that moment onwards there's "something" that's changed (big release, HN launch or whatever). I do also like your inflated bubble though I think it should then also be indicated at the bottom of the graph
![image](https://user-images.githubusercontent.com/1727427/82930836-e92d2600-9f7d-11ea-96e6-87d11dc3d20b.png)

Re trends, I don't think any of this should touch the /trends models? This really is only applicable to LineGraph.

**Comment by EDsCODE** [comment]
Oh i like that format a lot. Will work on something like that UI wise. 

Re data handling: Yeah, the annotations should only be on the line graphs. Without a table to store data, where will the annotations live? Right now the trends graphs are saved only when a dashboard item is created and they're stored as a filter blob within the dashboard model. Is the idea to save all the annotations on the dashboard model in the db? Or are the annotations universal across the app so they can be queried like we query people when you click on a datapoint.  I'm assuming we don't want to track annotations in the URL along with filter properties as that could get unbearably long and ugly.

**Comment by mariusandra** [comment]
Hi both!

I like the look/functionality expressed in @timgl 's screenshot!

I also think the annotations should be universal - so that no matter the graph, you have access to them. I wouldn't want to write the same "big HN launch" note on multiple different graphs.

The next step from here would be to automatically get an annotation for each deploy/commit on Github/Heroku... and all sorts of other automatic feeds we could pull in.

It makes total sense to store the annotations on a "model", which for us means a logic that is just there no matter what scene you are on. We'll often have multiple graphs on the screen (dashboards) and it doesn't make sense to query for the same time range multiple times per page. A common "model" will help with that.

Ideally I'd envision a smart model, which caches all the fetched annotation ranges and provides tools to help get the selected ranges in the logics that connect to it (either response actions or selectors + utility functions), including grouping (what if there are 6000 commits in a month and all are as annotated because why not).

**Comment by mariusandra** [comment]
Regarding annotations in the URL, the only thing I can imagine is if we group annotations (e.g. 20 deploys on Wednesday), clicking on the day's icon should open the list, probably in a popup. That should go in the URL, as on mobile you will always click the back button to escape such a dialog.

**Comment by jamesefhawkins** [comment]
> other automatic feeds we could pull in

There's *so much* powerful stuff in this. Totally think Heroku/GitHub etc make sense to start.

Beyond this, could see:

* Part of app has errors: Sentry / New Relic
* Paid ads: Adwords / Facebook / Twitter etc - changes to campaigns (this would be very valuable but very complex)
* Email marketing: Mailchimp (email goes out)

**Comment by EDsCODE** [comment]
Awesome clarification. I think the indepdently existing annotations and just applyin them to line graphs makes a lot of sense. Will dig deeper into the implementation of the various parts tomorrow. @jamesefhawkins yeah definitely. Ideally going to standardize a way to flexibly add in more and more feeds as necessary
