### ISSUE TITLE
Set a usage cap on cloud

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#7083]
Some users might want to avoid unpleasant surprises with high bills. It'd be nice to have a way to add a usage cap after which we either lock the interface or stop ingestion (former probably better).

**Comment by paolodamico** [comment]
Very related to #3127

**Comment by samwinslow** [comment]
I'd also like to mention that, if we build this, the UI of #7511 should be updated to indicate where the current month's usage stands in relation to that cap.

**Comment by aantn** [comment]
Just to comment from the perspective of a user, I held off on entering my credit card for a very long time because you can't set a cap.

I'm more than happy to pay for Posthog, but there is something incredibly scary about entering a credit card and not knowing the maximum amount you can be charged.

**Comment by mariusa** [comment]
Dupes:

https://github.com/PostHog/posthog/issues/3127

https://github.com/PostHog/posthog/issues/9338
