### ISSUE TITLE
Showing the differentiating property of an event in Funnels Insights

### ISSUE THREAD

**Issue by savy-91** [PostHog/posthog#7102]
## Is your feature request related to a problem?

When creating a conversion chart with events of the same type (like `$screen`) with different parameters (like the screen name) only the event type is displayed and this makes it very hard to understand where the users are dropping off.

![image](https://user-images.githubusercontent.com/6215122/141483112-8bca1b73-4ebf-4707-9980-bd992fcbd12c.png)

## Describe the solution you'd like

Amplitude shows the event parameter in parenthesis so that it's easy to see where the user is dropping off.

![image](https://user-images.githubusercontent.com/6215122/141483679-cd7e430d-c6d7-4e58-9e24-8c53aeed44c3.png)

**Comment by yakkomajuri** [comment]
Thanks for this @savy-91! Makes sense to clean this up

**Comment by savy-91** [comment]
I have been thinking on how it would be best to proceed to improve this (I was thinking of creating a PR for it) and here are a couple of options (not mutually exclusive):

- Allow users to set a custom name for the step regardless of the event that is being tracked
- Display all filters (if there are) in the step either as a popover or text
- Only display filters if there is just a WHERE clause (like the Amplitude example)

**Comment by yakkomajuri** [comment]
Oh that's awesome, thanks for the interest!

Tagging @alexkim205 who did some similar work to provide more guidance

**Comment by alexkim205** [comment]
Hi @savy-91 glad you asked! There is a new feature that we're rolling out that allows you to give filters/steps custom names which I think will solve your use case here. 


<img width="468" alt="Screen Shot 2021-11-15 at 8 18 15 AM" src="https://user-images.githubusercontent.com/13460330/141816510-183dc62d-8c5b-4229-837e-bc51614a9889.png">

<img width="969" alt="Screen Shot 2021-11-15 at 8 17 52 AM" src="https://user-images.githubusercontent.com/13460330/141816454-701ba576-056d-4ecc-93c1-f36e96e731b3.png">


We can add you to our beta testers if you'd like to try it out? If so, just let me know what your email address is so that I can add you.

**Comment by savy-91** [comment]
> Hi @savy-91 glad you asked! There is a new feature that we're rolling out that allows you to give filters/steps custom names which I think will solve your use case here.
> 
> <img alt="Screen Shot 2021-11-15 at 8 18 15 AM" width="468" src="https://user-images.githubusercontent.com/13460330/141816510-183dc62d-8c5b-4229-837e-bc51614a9889.png">
> 
> <img alt="Screen Shot 2021-11-15 at 8 17 52 AM" width="969" src="https://user-images.githubusercontent.com/13460330/141816454-701ba576-056d-4ecc-93c1-f36e96e731b3.png">
> 
> We can add you to our beta testers if you'd like to try it out? If so, just let me know what your email address is so that I can add you.

This is exactly what I had in mind! I'd be glad to test it out. My account on Posthog-cloud is saverio.murgia@risecard.eu

**Comment by alexkim205** [comment]
Awesome! I've added you to our beta list and you should be able to see this feature on your end :) 

I'll close this issue as it seems this feature should help out w your use case
