### ISSUE TITLE
Are `event.properties.$active_feature_flags` correct?

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#7150]
## Bug description

There's two suspicious code segments in our code:
https://github.com/PostHog/posthog/blob/16062a0fc9271e263ad0ccaab02acfbd9bebee9f/posthog/api/capture.py#L138-L140

And 
https://github.com/PostHog/posthog/blob/16062a0fc9271e263ad0ccaab02acfbd9bebee9f/posthog/api/decide.py#L137-L138

The two methods have different call paths, one accounting for overrides and the other not. 

Based on this it's my sneaking suspicion that $active_feature_flags on events don't reflect reality any more, but I am not confident in this.

## Additional context

Cc @rcmarron I think you refactored this last and have best context. https://github.com/PostHog/posthog/pull/5824  

cc @mariusandra who worked on overrides

Can you confirm this issue? Happy to ship a fix myself.

Aside: The /decide API does (I think) 2-4 extra sequential SQL queries now every time for the overrides. Given how performance-critical the endpoint is (can lead to data loss) this might cause us trouble down the line :sweat_smile: A _naive_ fix here might also bring down event ingestion in a similar way.

**Comment by mariusandra** [comment]
I guess this is a bug. I don't see why we wouldn't want to add overrides in `capture.py`.

**Comment by rcmarron** [comment]
Yeah, this looks like a bug. I think this should fix it: https://github.com/PostHog/posthog/pull/7173

On the topic of overrides adding complexity here, I'm generally in agreement that making the query on each `/decide` and some `/e` calls seems expensive . Outside of caching feature-flags, I'm struggling to think of an approach that would support this feature and reduce the perf hit. (small aside, it should just be adding 1 query because it uses subqueries).
