### ISSUE TITLE
Flexible cohort timeframe selection

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/posthog#722]
**Is your feature request related to a problem? Please describe.**

When defining user cohorts, it's currently only possible "in the last day / 7 days / month"/

**Describe the solution you'd like**

Flexible date filtering the same as in /trends

**Describe alternatives you've considered**

There isn't a way to do this without writing SQL.

**Comment by paolodamico** [comment]
+1, yes we could definitely use this to help deep dive on retention. Use case: Create a cohort of users that have for instance used heatmaps, and then seeing how these users retain versus all the user base (i.e. helps answer the question, does using heatmaps correlates with higher retention?

If we additionally extend this, to allow users who did action X (equal/greater than) times in Y timeframe, the realm of opportunities greatly expands, because we can now measure engagement levels and obtain even better information on how to improve retention.

**Comment by paolodamico** [comment]
We now support engagement cohorts, for the timeframe extension, some relevant context, https://github.com/PostHog/product-internal/issues/239

**Comment by pauldambra** [comment]
<img width="707" alt="Screenshot 2022-08-15 at 13 45 22" src="https://user-images.githubusercontent.com/984817/184638283-1b8d3a79-7207-44aa-9b16-8798a46abe4e.png">

Cohort creation is flexible now \o/
