### ISSUE TITLE
Recordings table query is slow

### ISSUE THREAD

**Issue by rcmarron** [PostHog/posthog#7247]
## In what situation are you experiencing subpar performance?

When you open the recordings page in the posthog account, the median time for the recordings query is 4.4s. And for some of our larger customers, it's even worse. For our biggest customer on cloud, the median response time is 12.1s! Way too slow! Additionally, some self hosted users are hitting a 504 on this page - presumably because this query is so slow.

I think there are a few reasons for this:
1) The query extracts `has_full_snapshot` from the json object inside the `snapshot_data` column, and this column can be very large. We should either materialize this column or pull this field out into its own column. While I can't easily test the perf improvement from materializing this column, if I remove the `has_full_snapshot` check, the query that is normally ~12s, it drops to ~3s (as checked by running the new query several times in metabase). And if I do the same test on the posthog account it drops from 4.4s to around 2.3s

2) The query unnecessarily joins with the events table - even when there are no entity filters. It does this to get the start/end urls, but it slows the base query down too much. If we're smart about when we join the events table + take care of issue # 1, the 12s query drops down to ~1.2s and the 4.4s query drops to ~0.6s.

3) The query has a "30 days ago" filter which doesn't really make sense. For clickhouse we only store 21 days of recordings, and it's unlikely that someone is paging back further than a few days. We should make this a shorter time range.

**Comment by rcmarron** [comment]
Fix for issue # 2 is here: https://github.com/PostHog/posthog/pull/7248

**Comment by rcmarron** [comment]
Fix for issue # 3 is here: https://github.com/PostHog/posthog/pull/7249

**Comment by macobo** [comment]
Rather than jumping onto fixing things, I'd like for this to take an approach that leverages benchmarking and understanding why the query might be behaving badly. After all, the client having performance issues here is relatively small, indicating problems with the query.

While the ideas mentioned in the ticket are all valid, there are other equally valid approaches. Benchmarking gives us capability to compare apples to apples.

Also if you haven't read this already, check out https://posthog.com/handbook/engineering/query-performance-optimization If possible, try out these approaches on the clients hardware to get better insight into what clickhouse is doing with the queries.

I've updated the benchmarking server with relevant data and am building a slim benchmarking suite. Also proposed in slack to chat face-to-face about this issue and how to tackle it.

---

Here's some of my hypothesis for problems looking at the query building:
- Always querying events
- Person queries requiring event filtering - you want to be minimizing the amount of rows being read, which this makes impossible. The previous sessions page solved this by having person filters also be exposed at top level as they're more common for filters than events.
    - Related: Person property matching is not done in the person subquery as it should, cc https://github.com/PostHog/posthog/issues/6382
- Only thing limiting the rows being read is the `LIMIT` at the outer layer. This results in all sessions for $timerange being queried every page even though clickhouse discards 99% of the work every time. The previous `sessions` page solved this by doing two separate queries.

The key rule here is that the only way to really speed up the query is reading less data from disk and reading it in a nice sequential way. There's no query optimizer doing this.

---

Regarding your points:
1. Materialized columns are at best an incremental speedup - while useful it won't fix the fundamental issues with the query. 
2. :+1:
3. The 30 day filter absolutely makes sense to retain, given that session recording retention is a problem we'll soon need to solve. The 3 week limit is a historical accident I'd expect your team to soon be tackling.

**Comment by rcmarron** [comment]
Resolved with https://github.com/PostHog/posthog/pull/7281 and https://github.com/PostHog/posthog/pull/7248
