### ISSUE TITLE
Can we get rid of the toolbar authorize page?

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#7273]
## Is your feature request related to a problem?

The toolbar authorization page seems to cause confusion because you don't really know what you're authorizing or if there are any risks. From a UX perspective, adding an authorized domain for the toolbar should be authorization enough.
- Are there any security considerations I'm missing?
- Can the tokens be used for read-only stuff? Maybe we need to be more vocal about risks in the authorized domains section?
- What happens when switching projects?

## Describe the solution you'd like

No toolbar authorization page. It launches my website directly.

## Describe alternatives you've considered

Making the authorization page nicer, but seems like we might not needed.

## Additional context
- User report on #5541 (a bit of a painful experience).

CC @mariusandra for thoughts.

**Comment by mariusandra** [comment]
I think the authorisation page does not add much, and could be removed. But there's a but.

At the end of the day, the toolbar is just another client of the PostHog API, and must communicate with it like all other clients. This means somehow we should get a key that we can use to get authenticated API responses. Using Personal API keys sounds like a suitable fit, but I'm a bit scared of storing a never-expiring token on an external site with injected client-side JavaScript. Especially if that token gives access to everything in your account, even if the "external site" is your own.

To limit what is exposed, we currently have a custom `temporary_token` system that's only used by the toolbar. This token is a char field on `User`, which gives every `ViewSet` that uses `TemporaryTokenAuthentication` access to enabled resources. Currently these are `api/feature_flag.py` (read-write), `api/action.py` (read-write) and `api/element.py` (read-only).

Every time you re-authenticate, the token is changed on the user, and when that happens, all running clients (toolbars) using this key will stop working. This might include you in a different tab on a different site tracked by the same PostHog organisation, which sounds like what's happening here: https://github.com/PostHog/posthog/issues/5541

If we do remove the authorization page itself, the authorization flow itself won't change. We'll just redirect the user directly, instead of asking to click a button. This will still cause problems if you try using the toolbar on multiple sites/domains at the same time, or even sequentially. It'll be less annoying, but still not the true solution.

A real solution would be to implement a better (and expiring!) token system that can be used on many sites and pages simultaneously. A new table with "user_id", "temporary_token" and "timestamp" might be enough, but we should aim for something like JWT through personal API keys for a more "industry standard" solution.
