### ISSUE TITLE
Nomenclature discussion: Users, persons, people?

### ISSUE THREAD

**Issue by clarkus** [PostHog/posthog#7643]
I'm not sure we've ever reached consensus on this topic, so I wanted to file an issue to make a decision and schedule work to clean this up in the product. Anyway, what should we call "person entities" in the product. The feature is named "Persons and Groups", so I have been pushing to align with that. I've heard other strong justification for "users". Thoughts?

**Comment by pauldambra** [comment]
Users is so widespread as to be almost meaningless now. Since we have groups, why not "individuals"? 

Other than that people or persons is clear.

**Comment by corywatilo** [comment]
## Problems with every name

- _Users_ doesn't differentiate well enough between _internal users_ (users in your org) and _your app's users_
- _Customers_ doesn't work, since some tracked users are prospects and not yet actual _customers_ of an app
- _People_ is straightforward, but if we want to think really deep about this, a single person might have multiple accounts, so this is less clear in that case
- _Accounts_ is pretty clear, though what happens when you have multiple users from an org? Because they're not technically each an account - they're users _within_ an account

The least problematic of above are _Users_ and _People_, since you'll get the hang of it once you see it.

I'd vote to use _People_ for user records and _Users_ for internal/org members. And _People_ over _Persons_ since it's just friendlier (and more common)!

**Comment by joesaunderson** [comment]
Some feedback from our usage of PostHog - users would best suit us (and we have both internal and client users). 

Could this become potentially configurable (in the UI) and the end user (of PostHog) call it whatever they like!
