### ISSUE TITLE
Add support for IPV6 

### ISSUE THREAD

**Issue by guidoiaquinti** [PostHog/posthog#7834]
## Is your feature request related to a problem?
PostHog doesn't work with ipv6. From a technical standpoint it is because [we bind](https://github.com/PostHog/posthog/blob/189ebf649792bcc5b534d005aef98b906e54e994/bin/docker-server#L6) `gunicorn` to an ipv4 address but there are anyway some things we need to check before changing that: 

* make sure IPV6 parsing works correctly
* make sure allow/block list functionality works with IPV6 addresses
* make sure all our components (app, ingestion, plugin-server) works correctly with IPV6 addresses 
* ....

**IPV4**
```
➜  ~ curl -v -4 http://app.posthog.com
*   Trying 3.213.127.190...
* TCP_NODELAY set
* Connected to app.posthog.com (3.213.127.190) port 80 (#0)
> GET / HTTP/1.1
> Host: app.posthog.com
> User-Agent: curl/7.64.1
> Accept: */*
>
< HTTP/1.1 302 Found
< Date: Thu, 23 Dec 2021 10:53:48 GMT
< Content-Type: text/html; charset=utf-8
< Content-Length: 0
< Connection: keep-alive
< Server: gunicorn
< Location: /login?next=/
< X-Frame-Options: DENY
< X-Content-Type-Options: nosniff
< Referrer-Policy: same-origin
<
* Connection #0 to host app.posthog.com left intact
* Closing connection 0
➜  ~
```

**IPV6**
```
➜  ~ curl -v -6 http://app.posthog.com
*   Trying 2600:1f18:189c:8300:be43:f067:a35:6d84...
* TCP_NODELAY set
```

## Describe the solution you'd like
PostHog works with both ipv4 and ipv6 addresses 

## Describe alternatives you've considered
Do nothing

## Additional context
See internal [thread](https://posthog.slack.com/archives/C01MM7VT7MG/p1640212597225700)

**Comment by martinezleoml** [comment]
Hi!

I just got redirected to this issue by the PostHog support.

I figured out a couple of days ago that PostHog events where not reported for some of our mobile app users using their 4G LTE connection (our mobile app is using the PostHog Rect Native SDK). 

After further investigations, it seems that one of the major mobile career in France (Orange France) is using IPv6 (with IPv4 support as a fallback for websites that doesn't support IPv6).  

Unfortunately, the SDK is not falling back to IPv4 because your DNS configuration contains AAAA records for app.posthog.com: 
![2022-01-03 at 09 58 34@2x](https://user-images.githubusercontent.com/759215/147913526-a89bfabe-e458-401f-bb4d-03e931821b60.png)

I suppose a security group is dropping IPv6 traffic, resulting in SDK being stuck trying to reach the API on IPv6 and analytics events not being reported.

A temporary solution would be to stop serving AAAA records when resolving app.posthog.com while you're ensuring that everything is working correctly with IPv6. What do you think of?

**Comment by guidoiaquinti** [comment]
@martinezleoml I've just changed the PostHog Cloud config to stop publishing the IPv6 record. It might take a bit to fully propagate due to DNS caching. 

Let me know if it fixes your issue. Thank you!

**Comment by martinezleoml** [comment]
It works like a charm now, thanks a lot. :)

![19F4DBF6-CFFD-49C6-8FF5-2F04995AFBA7](https://user-images.githubusercontent.com/759215/147916536-60ce91fa-8739-4d7e-8a7d-c67cbf29f961.jpeg)

**Comment by guidoiaquinti** [comment]
Thank you @martinezleoml and sorry for the hiccup! We'll re-publish the IPV6 records once our stack will fully supports it

**Comment by samarpanB** [comment]
@guidoiaquinti Is there any chance that this gets a priority ? We need support for ipv6 urgently.

**Comment by guidoiaquinti** [comment]
@samarpanB it is not atm but we appreciate pull requests.

**Comment by samarpanB** [comment]
@guidoiaquinti if you can guide me a bit in the code, I can try doing it. I am new to this codebase and python.

**Comment by guidoiaquinti** [comment]
Unfortunately it's not a trivial task and I'm also not sure where to start. I would need to dig into the code as well how we configure the infrastructure.
