### ISSUE TITLE
Dashboard does not load properly after self hosted hobby deployment

### ISSUE THREAD

**Issue by mochicode** [PostHog/posthog#7836]
## Bug description

I have used the [Hobby Deployment](https://posthog.com/docs/self-host/deploy/hobby) in order to set up and test PostHog, the installation process itself went smoothly, the endpoint to track events also works and returns a 200. 

The only thing that is not working is the dashboard:

![firefox_NIpmJJNQf6](https://user-images.githubusercontent.com/3835873/147245640-70e79009-3c59-411c-abf8-9b59a2c0eeff.png)

I always get a generic `server_error` as a response when trying to load data.

## Expected behavior

Load and show data

## How to reproduce

1. Use the hobby deployment
2. Open the dashboard

## Environment

- [ ] PostHog Cloud
- [X] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

**Comment by marcushyett-ph** [comment]
Hey @mochicode, 

- Can you quickly run `docker ps` on that machine and let us know what services are running?
- Also what spec machine are you running this on?

**Comment by fuziontech** [comment]
👋 @mochicode - Did you happen to throw a Sentry DSN into the install wizard when you built this? If not can you run the `curl` again and set this up with Sentry so that we can capture what errors are being thrown on the backend? Would be super helpful for debugging quickly.

Sorry for the inconvenience here!

Also approximately how many events have you thrown into your instance?

**Comment by guidoiaquinti** [comment]
👋 Hey @mochicode, were you able to fix the issue? I'm closing this as stale but feel free to reopen or jump in our Slack community workspace if you still need help. Thank you!
