### ISSUE TITLE
UX Q: Clarify $time vs $timestamp

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#7876]
## Bug description

We have two time parameters (as described in `PropertyKeyInfo` below). This can be confusing as if you want to filter based on a timestamp you don't know which one to use. Further, from user feedback we now the existence of both is not obvious and `$time` appears to be not being set for all events.

- `$time`: Time as given by the client.
- `$timestamp`: Time the event happened.

## Expected behavior
- Remove one of the options?
- Clarify in more detail what each one represents and prioritize one of them in taxonomy filters.

## How to reproduce

1. Search for `time` in taxonomic filter.

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

## Additional context

Originally reported [here](https://app.papercups.io/conversations/all/fb245faa-910c-4946-894c-38add0ce2250)

**Comment by Twixes** [comment]
Seems like the only clear difference between `$time` and `$timestamp` is the format (Unix timestamp vs ISO date). I'm in favor of removing `$time` from libraries and only sending `$timestamp` – unless there's some context to this that I'm not aware of? (perhaps CC @mariusandra since you got a lot of libraries in a long time ago)

**Comment by mariusandra** [comment]
I have no idea what the libraries send to be honest. Most libraries I think send the timestamp not in the event properties, but as a separate timestamp field, this one: https://github.com/PostHog/plugin-scaffold/blob/main/src/types.ts#L70

In the plugin server, when implementing its local `posthog.capture`, [we use a custom `timestamp` property](https://github.com/PostHog/posthog/blob/434e379f9a8c91d0f95ae32de31bc22080543278/plugin-server/src/worker/vm/extensions/posthog.ts#L69) (without the `$`), which gets taken out of properties and put directly into the event.

This should really be standardised across all of the integrations... but I'd need to check each one individually to give more context on how they all work.

**Comment by macobo** [comment]
Related: https://github.com/PostHog/posthog/issues/7810

This is not a real property that should be relied upon. We should instead figure out a better way for virtual properties like timestamp or distinct I'd to work.

**Comment by paolodamico** [comment]
Given the plugin server uses timestamp to store events, could a low hanging fruit be just hiding the `$time` property on the frontend?

**Comment by mariusandra** [comment]
Instead of throwing all this data into the event's properties, what about adding another "pill" to the taxonomic filter with the name "Event metadata" (in addition to e.g. "event properties", "person properties", "cohorts", etc). This pill would contain the [`distinct_id`](https://github.com/PostHog/posthog/issues/7810) and ["timestamp" fields](https://github.com/PostHog/posthog/issues/7810#issuecomment-998886232) from [PluginEvent](https://github.com/posthog/plugin-scaffold/blob/main/src/types.ts#L61) that are **not** in properties, but one level higher. Perhaps this can even contain `ip`, `team_id`, `site_url` and some of the other fields?

**Comment by clarkus** [comment]
> Instead of throwing all this data into the event's properties, what about adding another "pill" to the taxonomic filter with the name "Event metadata" (in addition to e.g. "event properties", "person properties", "cohorts", etc). This pill would contain the [`distinct_id`](https://github.com/PostHog/posthog/issues/7810) and ["timestamp" fields](https://github.com/PostHog/posthog/issues/7810#issuecomment-998886232) from [PluginEvent](https://github.com/posthog/plugin-scaffold/blob/main/src/types.ts#L61) that are **not** in properties, but one level higher. Perhaps this can even contain `ip`, `team_id`, `site_url` and some of the other fields?

This is an interesting idea. I think we'd need to help less technical users understand how these things are different and where to look for which items. Probably something to consider for the taxonomy project, too.

**Comment by Twixes** [comment]
`$time` is now marked very explicitly as deprecated, and no longer in use.
