### ISSUE TITLE
Manual Taxonomy V1 Tasks

### ISSUE THREAD

**Issue by alexkim205** [PostHog/posthog#7991]
Task items todo coming out of meeting with @rcmarron and @alexkim205. Shamelessly copied over from Rick's notes.

@clarkus for design guidance. @paolodamico for context.

Initial wireframe: https://www.figma.com/file/JqnVX6NLmnPnqa4D4rHepw/Alex's-Scratchpad?node-id=416%3A619

* Event + Event Property Descriptions are visible + editable throughout app
	* Display descriptions in taxonomic filters
	* Link to edit event/property description accessible from taxonomic filters
	* Drawer to edit descriptions is accessible everywhere
* Actor property descriptions are visible + editable throughout app
	* Actor property definitions are stored somewhere
	* Display descriptions in taxonomic filters
	* Link to edit property description accessible from taxonomic filters
	* Drawer or modal to edit actor property descriptions is accessible everywhere
* Data Management tab
	* Events + Action tabs remain as is. Clicking an event/action would open the new drawer
	* [Open question] Where do actor properties go? Are they a new tab that just shows the contents of the drawer?

Open questions:

* Do people use events/property tags? How do they use them?
* Decide where property descriptions live. Are they at the event level, are they global or both?
* Should actions be given descriptions to make it consistent with events? Should you be able to verify/archive them?

Next work:

* Incentivizing manual taxonomy
	* Alerting when new events are seen.
	* Signaling incomplete definitions.

**Comment by mariusandra** [comment]
> Decide where property descriptions live. Are they at the event level, are they global or both?

I'd suggest going global now, and not making any decisions that would lock us out of local overrides later. From prior experience, most people want global property descriptions most of the time. `customer_id` and `product_type` are the same, no matter if it was on the custom event `user signed up`, `user added to cart` or `user purchased a wookie`.

However, as we grow, unique user demands will grow and I'm certain we'll find a customer who wants the property `type` to show a different description for the `user purchased` and `newsletter sent` events. Since implementing this brings a lot of complexity (e.g. what to show as the description popup in the taxonomic filter event properties tab, if you edit global filters on a funnel with 4 different event types?), we want to avoid working on this for as long as we can. In the mean while we can suggest just writing all in one box, or push them to use better properties like `newsletter_type` and `puchase_type`.

> Should actions be given descriptions to make it consistent with events?

Makes sense for me to do so.

**Comment by paolodamico** [comment]
- Agreed with @mariusandra's points.
- Added some feedback on your wireframes. 
- I think we should prioritize thinking about how to incentivize users to actually fill taxonomy details. UX will be key here.

**Comment by clarkus** [comment]
Very related - https://github.com/PostHog/posthog/issues/5546

**Comment by alexkim205** [comment]
### Meeting Notes 01/18/2022

Defining event completeness:
- Type
	- Opens can of worms
- Tag
- Description
	- Edited by _______
- Freshness
- Verification
	- Helps users pick the right/verified/trustworthy event
	- Deprioritizing/Unverifying
- PII

Data Management
- Bulk actions
- Tradeoff between automated/manual work user has to do to get started
- Default events

New event shows up -> email, notification
	- preferences to configure email settings

Allowlists/Blocklists
Roles/Permissions

Which ones do I use first? -> Verification
What is it? -> Definition metadata

- List of places we need to show taxonomy (Taxonomic filter, events page, etc.)

### Next Steps 01/18/2022

Short-term goals
- Centralized place to manage events & actions
- Contextual management of single event
	- Value in showing flat list of events and properties, but list of properties has no value elsewhere in the app
	- Important to make it clear that editing a property will affect it globally
	- List all events using that property in properties stats
- Where to show this stuff?
- Incentivization: how to incentivize engineers to actually document things

Long-term goals
- PII
- Verification
- Strict completeness
- Event audit history

Open Questions
- Events vs. Actions???
- Manual vs. Automatic (i.e., Paul updated this event 3 mo ago...)
- Optional and Required fields
- Local vs. Global event properties

**Comment by alexkim205** [comment]
Related: 

How do we sort items in the taxonomic filter based on new taxonomy 
- https://github.com/PostHog/posthog/issues/8119

**Comment by alexkim205** [comment]
Closing this out in favor of #8203
