### ISSUE TITLE
Document how to build a scene

### ISSUE THREAD

**Issue by mariusandra** [PostHog/posthog#8019]
In [this comment](https://github.com/PostHog/posthog/pull/7993#issuecomment-1010989361), @Twixes wrote:

> Besides that [I added] a few minor UI updates to fully align the style with our new design language,

Let's document this somehow. I wouldn't know how to write code to "align the style with our new design language", nor what to look out for when reviewing someone's code to know it's in the wrong style and increases our bad-css-debt. Taking this a step further, it's also not obvious how to use and nest antd components (should everything be in a `<Row>`? why?), which components to avoid if any (e.g. use our tables instead of theirs), etc.

**The goal:** *Tom Selleck*, our fictional engineer on the platform team who knows basic CSS and React, but has never touched PostHog's frontend, should be able to rebuild a basic insights list scene without looking at any of the existing scenes, without making any mistakes, nor breaking any undocumented guidelines.

**Comment by Twixes** [comment]
In that case the minor updates were:
- relaxed spacing between icons and text
- only `<LemonButton>`s in tables
- only Material icons in tables
- "Created by" comes before "Created at"
- "Created at" should use relative time when convenient
- table empty states should be left-aligned (I find that more intuitive to read as plain text doesn't draw enough attention for my eyes to go to the middle to the page naturally + minimizes breaking barriers between columns)

**Comment by mariusandra** [comment]
I would like to prioritise this for the next sprint, so we could improve our quality faster.

We have recently built a few new scenes:
- Web Performance @pauldambra 
- Experiments @liyiy @neilkakkar 
- Async Migrations @tiina303 
- Recordings @rcmarron

How was the experience? Was everything clear on how all the pieces fit together, or did you have to reinvent things from scratch, trying to piece together the little information you had from other new-ish looking scenes?

I'd like to capitalise on this recent work and help us come up with basic frontend scene-building guidelines. 

More specifically, here's my proposal. @Twixes if you look at the experiments page, is this in line with the unwritten "this is how you lemon" guidelines, all the way from CSS usage to how the edit page's logic is connected. If not, what documentation should exist to bridge the gap?

The goal would be to come up with some set of guidelines that'll help frontend code reviewers with getting the basic steps right. Something, that you could depend on when reviewing someone else's frontend PR as well.

Perhaps it's worth having a call with interested parties (cc @clarkus @paolodamico) on how to best build and present such guidelines, what has worked in other companies you've been at, etc.

Happy to discuss async, and/or ultimately defer to the small teams offsite as well.

**Comment by neilkakkar** [comment]
Great question!

Some things I had to figure out based on patterns in existing code: Like how a scene works, and which part instantiates a scene (which was pretty obfuscated / going through hoops that didn't make sense apriori). Would be nice to have information about how scenes are generated & how scene props are passed to them. ([specifically, getting to this bit](https://github.com/PostHog/posthog/blob/master/frontend/src/scenes/App.tsx#L82))

The specific scene code was different enough that I didn't have to think of how it all comes together, but some basic actions I did invent from scratch: like having an extra selector for "new experiment data" while you're creating a new experiment, but this was kinda messy, as on "edit", we'd repopulate "new experiment data" since that's what was powering the creation/edit screen, while saved experiments are powered by "experiment data". Quick guidelines on how to add edit functionality would be marvellous!

Another place that threw me off a bit (and might be a reason for not-too-specific-guidelines) was how we have "delete with undo" in most places. @liyiy called me out on not adding this in, but in the end we decided not to have undo because it made things pretty annoying for experiments: An experiment is linked to a FF, and deleting an exp deletes the FF as well, so undo became a bit more complicated than a soft-delete on one model. I didn't want to add this complexity early on, and we've opted to not have this functionality.

Also, I've no clue if there's an unwritten css files guideline, I just tend to put them together with the component files.

---

Hmm, although, Li did most of the work for experiments FE, so she probably has more concrete stuff to say here! :)

**Comment by liyiy** [comment]
It's traceable/understandable for the most part on how to build a new scene but even though I've done it a couple of other times before I still always forget exactly what I need and still end up digging around to find the missing piece to the puzzle, so a document on which files are part of scene building would definitely make the process faster. 

Adding on to neil's comment on `deleteWithUndo`, it's just little things like that I notice in our app that I'm not sure if we should be implementing as standard practice or not?

**Comment by pauldambra** [comment]
I had quite a bit of copy pasta to get going. And then found the storybook docs confusing when I needed help from them.

Things I've seen elsewhere:
* https://static.coop.co.uk/experience-library/ (although aimed at a communicating to more developers and more than only them)

**Comment by tiina303** [comment]
> How was the experience? Was everything clear on how all the pieces fit together, or did you have to reinvent things from scratch, trying to piece together the little information you had from other new-ish looking scenes?

A bit of a struggle. I only knew I should use lemon tables & get product design to do a design because I happened to have a pairing donut come up with Marius. What would be lovely is if we had a page that explained getting started with UI/UX which really only needs to have 3 things: 1. link to KEA 2. link to storybook 3. Do/Don't (https://posthog.com/docs/contribute/coding-conventions#do-s--dont-s#frontend already have this likely should be expanded on the Storybook part).  The Kea docs are pretty great already, unfortunately storybook a lot of things don't render. For example when I was looking for how to do the status rendering on async migrations I ended up asking Michael, but instead a better way would have been if I could have just looked at some examples of what we have available in storybook and been able to copy the code from there. Maybe also a page that has all components together, so I can faster find what I'm looking for.

**Comment by Twixes** [comment]
Thanks all for chiming in! I will try to write some base documentation of this next week, if no one objects. As for presenting the concrete components available, Storybook is definitely the best way. It should probably include some guidelines section in addition to the raw component examples that are there now.

One issue I've ran into with Storybook though is operating with Kea. The reason why many of the existing examples are broken are inconsistencies in the Kea state available to components, which sometimes results in just no data, and sometimes in crashes. This is an area where I need to request your help @mariusandra – how to provide state in a fail-safe way?

**Comment by Twixes** [comment]
I'd actually say this is done with https://storybook.posthog.net/?path=/docs/how-to-build-a-scene--page.
