### ISSUE TITLE
Event filters search sorting could be more helpful

### ISSUE THREAD

**Issue by tiina303** [PostHog/posthog#8119]
## Bug description

<img width="536" alt="Screen Shot 2022-01-18 at 21 23 56" src="https://user-images.githubusercontent.com/890921/150013280-1749b430-6bab-4eed-b4e2-8a72dbc0a323.png">

## Expected behavior

Not sure if we should be seeing the `changed_hiddenLegendKeys` values, but regardless I'd like to see shorter exact matches earlier for my sort key, e.g. `email_service_available` that's also a seen property.

## How to reproduce

1. create new insight
2. use "insight viewed" event
3. search for "email"

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

**Comment by mariusandra** [comment]
Well, this is sort of... expected. 

This `"insight viewed"` event has a lot of `changed_` properties ([added here](https://github.com/PostHog/posthog/blob/05c5471f7c863f62a46244ecf4577d660b303a00/frontend/src/scenes/insights/insightLogic.tsx#L527)). We sort items by popularity and then alphabetically.

This `email_service_available` property [is only added](https://github.com/PostHog/posthog/blob/365d7b27fc2e81d62be296174c5c707f5aaa7ba9/frontend/src/scenes/PreflightCheck/logic.ts#L87) if you're on the preflight check page, so it makes sense for this property to not be on as many events, and show lower down the list.

Not sure how to improve this 🤷, but happy to if anyone has some ideas.

**Comment by tiina303** [comment]
Thanks for the context, I'm not sure then either, feel free to close. To provide more background on user experience: I was looking for the user property `email` and because I saw all these `changed_*` I thought that we were just sorting badly and I need to scroll. But maybe being able to switch the sort between popularity and length (i.e. shortest exact match first) could be useful?

**Comment by clarkus** [comment]
What are the other possible sorting options here? We can sort by best match, alphabetically, last seen, recently used, etc. @alexkim205 @rcmarron this is probably something to consider as part of taxonomy - what attributes could be considered here to help a user find that best option they're looking for?

**Comment by alexkim205** [comment]
+1 those are all good parameters to sort by. We can probably also sort by whether: 
- an event has been documented (given description/definition)
- is verified
- 30d trailing volume
- complete/incomplete volumes
- stale/freshness. 

I feel like there's a bunch of ways we could design a sorting algorithm, but the easiest most intuitive approach to me would be to take the most important N parameters, order them in priority, and sort by those. The ones that stick out to me are `recently used`, `verified`, `recently defined`, `alphabetical`, `30d query usage`

I'm not sure length is the right parameter here because its equally likely you're looking for a longer event name. Also another thing that comes to mind is that having the ability to ignore/hide certain events/properties that the team doesn't care about may solve this use case here, or at least incentivize users to hide things/document more.
