### ISSUE TITLE
Session Recordings Autoplay

### ISSUE THREAD

**Issue by marcushyett-ph** [PostHog/posthog#8181]
## Is your feature request related to a problem?

When our users watch sessions, they tend to "binge them" watching one after the other (like Netflix), however to go to the next video you need to go back to the index page and find it. We should auto-play the next recording (like Netflix).

## Describe the solution you'd like

- Autoplay next video when current video has finished
- Provide a "next video", "previous video" navigation within the recording payne

## Describe alternatives you've considered

None

## Additional context

None

**Comment by rcmarron** [comment]
I definitely feel the need for this. I had been thinking about a side-by-side view for recordings. Where you would have a list of recordings on the left and then the player view is on the right. That way you can quickly click through the recordings on the left without going back and forth.

I think the list might be an interesting way of approaching the issue because it removes some of the questions a user might have around "wait why are they showing me this recording next?".

**Comment by pimpedro** [comment]
This would really help to optimize my daily investigations!

**Comment by clarkus** [comment]
Duplicate at https://github.com/PostHog/posthog/issues/8950

**Comment by daibhin** [comment]
Autoplay exists in playlists
