### ISSUE TITLE
Stratified Recordings

### ISSUE THREAD

**Issue by marcushyett-ph** [PostHog/posthog#8182]
## Is your feature request related to a problem?

When I watch recordings, I don't just want to see what people did in the last few hours, I'd like to see a sample of people over the last few days / weeks. So I'm not affected by any biases in that smaller time period (e.g. specific region awake at this time, a single user is very active so represents most recordings)

## Describe the solution you'd like

I'd like a way to stratify recordings, e.g. "Show me 2 recordings with this event in, from each day in the last 7 days"

## Describe alternatives you've considered

Lots of scrolling and pagination

**Comment by rcmarron** [comment]
This is really interesting!

Technically, it's pretty easy to do, but I think the trick would be in how we describe what's happening to a user.

It's almost like "shuffle" on a playlist.

@clarkus curious if you have any thoughts here.

**Comment by clarkus** [comment]
I like this idea. I think this feels like a natural evolution of the filtering capabilities for recordings. We knew we were going to have to circle back to improve filtering, so this is a good example that will help us know how to structure the updated filter. 

This is a particularly interesting case because we're sampling in uniform sizes, across a time range, in set units of time. It's a very specific scenario compared to our current filtering structure.

**Comment by pauldambra** [comment]
cc @daibhin  as another form of clustering we could do
