### ISSUE TITLE
Backend events and auto-capture not filtering events correctly

### ISSUE THREAD

**Issue by marcushyett-ph** [PostHog/posthog#8183]
## Is your feature request related to a problem?

This is kind-of a bug kind-of a feature request so feel free to reclassify I you see fit - and I'm not 100% sure the issues are related

**Backend**: When watching session recordings, I often want to filter by events that happened on the backend (e.g. payment validated), however these filters return no results.
**Autocapture**: When I filter by an auto-capture action, e.g. "page view on a specific url", the list is not filtered at all, I just see all events

## Describe the solution you'd like
I'd like to be able to filter by backend and autocapture (events / actions) when searching for recordings

**Comment by rcmarron** [comment]
> Autocapture: When I filter by an auto-capture action, e.g. "page view on a specific url", the list is not filtered at all, I just see all events

@marcushyett-ph Question on this one, I'm assuming you meant "I just see all recordings" instead of "I just see all events". If so, I'm struggling to repro it - can you share a link to the recordings page that shows the problem?

> Backend: When watching session recordings, I often want to filter by events that happened on the backend (e.g. payment validated), however these filters return no results.

Good point on this one! It's kind of tricky. To explain the scenario a bit: it's possible for a user to have overlapping recordings (e.g. they could be on their phone and computer at the same time). When we query the recordings with an event filter, we say "give me all recordings where I can see this event happen", meaning we aren't returning a recording where the event happens on a different device. (this is done by using the `session_id` property that's shared between recordings and events - more on it [here](https://github.com/PostHog/posthog/issues/6522#issuecomment-949876971)). 

Because backend events don't share this `session_id`, they're not included in that query, hence, the problem. [This PR](https://github.com/PostHog/posthog/pull/8276) updates the logic, so if an event doesn't have a `session_id`, the query matches it based on timestamps (not `session_id`).

This bring up another issue though. In the event list in the playback experience, we don't show events that don't match the `session_id`/`window_id` of the recording, so these backend events wouldn't appear there. The logic in the event list is a bit more complicated because our player handles multiple tabs/windows, so player time isn't necessarily linear... so it isn't obvious where in the event list these backend events should go. I'll need to put some more thought into how to solve this part of the issue.
