### ISSUE TITLE
Event table does unneeded work in the background

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#8191]
## Bug description

When there are new events, events table displays this:

![image](https://user-images.githubusercontent.com/148820/150535409-07245dfe-4b41-4adc-9312-c6df228c92c8.png)

In the background, we continually continue polling our APIs

## Expected behavior

Pause once that banner is shown

## How to reproduce

1. Go to events

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

## Additional context

cc @pauldambra and @mariusandra who have been doing work on this table recently.

**Comment by Twixes** [comment]
It's been like that for a long time because the button used to show the number of events that would be added to the view on click, but recently that's not been the case. I think it'd be a nice experience if the number was added back, but I'm not sure exactly how taxing is this polling for ClickHouse.

**Comment by timgl** [comment]
> It's been like that for a long time because the button used to show the number of events that would be added to the view on click, but recently that's not been the case. I think it'd be a nice experience if the number was added back, but I'm not sure exactly how taxing is this polling for ClickHouse.

Easiest solution might just be to count the results in the API call and if it's 100 just display "100+ events"

**Comment by pauldambra** [comment]
Weirdly the code to show the length is there... https://github.com/PostHog/posthog/blob/master/frontend/src/scenes/events/EventsTable.tsx#L116

We added pausing for polling when the page is in the background recently. So I've used that to propose we pause when there are new events.

It does change the behaviour (slightly) in that before this when you clicked the show more button. You caught up to within 5 seconds of "now" because of the background polling behaviour. Now, you click the button, are shown the events, polling restarts, and you may very quickly be shown the button again
