### ISSUE TITLE
User A's Id of client 1 A was linked to User B's recording of our internal web app (client 2 say).

### ISSUE THREAD

**Issue by jashjain98** [PostHog/posthog#8217]
I was looking for a recording on Posthog. When I checked in recordings, the recording for that action by this user (Person) was not there.

There is another 'Action' recorded for that user, on a similar time stamp, but the recording linked to it is of another Person.

I looked at the recording through both. Went to that specific person and filtered through an action using url. Both led to the same incorrect recording.

This bug can be identified through front-end

Acc to this screenshot the recording is there. This recording that is captured has the details of the user actions that we are looking:

<img width="1416" alt="Screenshot 2022-01-24 at 4 53 20 PM" src="https://user-images.githubusercontent.com/98319476/150774276-8f9e7458-3bee-4aa7-ba02-4ca87894f829.png">

However, when I am checking the video from here, I see a recording from someone from our own team using the product:

<img width="1419" alt="Screenshot 2022-01-24 at 4 54 20 PM" src="https://user-images.githubusercontent.com/98319476/150774427-cb15bdee-2e54-4c84-9442-d636c6e895a6.png">

## How to reproduce

1. Get on a call with me or try checking on my postHog account for similar recording <--> Id mismatch
2. Go through multiple records and check whether the 'Person' does not match with the 'Recording'.

Environment: self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_
Deployment: simple aws ECS deployment

**Comment by jashjain98** [comment]
Yesterday I was checking for another issue and I found that the events and actions for that user's usage were captured but there was no recording linked to recorded events there. These bugs and issues are preventing us from being able to use PostHog. Please push for the resolution on these for us. Thanks!


<img width="1440" alt="Screenshot 2022-01-27 at 2 44 05 PM" src="https://user-images.githubusercontent.com/98319476/151328370-01e86626-46c8-4ba2-9feb-012ef8a7abe3.png">

**Comment by neilkakkar** [comment]
Thanks for reporting this Jash! @rcmarron bumping this up your radar (or @alexkim205 ?) as secondaries :)

**Comment by jashjain98** [comment]
thanks man. let me know if you need any help here. any timeline on by when can we have this resolved?

**Comment by jashjain98** [comment]
Following up on this issue.

**Comment by jashjain98** [comment]
@rcmarron @alexkim205 any update here?

**Comment by jashjain98** [comment]
Anyone here can help? Help a fellow PM aspirant out here 🥲

**Comment by timgl** [comment]
I think what's happening here is that you're logging in as your users or otherwise incorrectly identifying them. That means that the recordings etc all get mixed up.

Click on the +4 here to see all the distinct ids.
![image](https://user-images.githubusercontent.com/1727427/152969210-fc8ed7df-d9eb-46ec-afce-9b92e555c69a.png)

Make sure you call `posthog.reset()` when logging in as a user and check your `posthog.identify` calls.

**Comment by jashjain98** [comment]
I checked through all the distinct IDs. Earlier there was a wrong recording linked to the ID(s), now there is no recording linked to any of the IDs. Also the ID problem has been rectified and users are identified by their email ID.

Just curious: even if there are multiple identifiers, shouldn't they be linked to one recording only?

**Comment by jashjain98** [comment]
by 'we' are logging in as our users do you mean logging into this from our superadmin to the product? or something else?

**Comment by timgl** [comment]
> by 'we' are logging in as our users do you mean logging into this from our superadmin to the product

Yep that's where we often see issues like this.

**Comment by jashjain98** [comment]
Okay, why though? just curious

**Comment by benjackwhite** [comment]
Closing this as a stale issue.

@jashjain98 definitely sounds like you need to ensure that any impersonated sessions (like a superuser login) call the reset / identify logic as Tim mentioned. Otherwise PostHog JS will detect the new ID and merge the two users (e.g. your superadmin user with the impersonated user).

You can always un-split users to undo this work but of course any team members impersonating your users will re-trigger this merge
