### ISSUE TITLE
Display pie charts and bar charts as percentage

### ISSUE THREAD

**Issue by SimonFuet** [PostHog/posthog#8270]
## Is your feature request related to a problem?

No

## Describe the solution you'd like

In the pie charts and bar charts, be able to switch between absolute values and relative values (percentage).

## Describe alternatives you've considered

None, except visually estimate the percentage on pie charts.

## Additional context

Description fells a bit light, but I feel like everything's here :-)
Feel free to ask for additional information.

**Comment by sameer-s-b** [comment]
Hi, I'm interested in working on this. I'm new to PostHog.

**Comment by gracebir** [comment]
@SimonFuet , I think a figma design can be helpful for this issue

**Comment by nizarmah** [comment]
It seems like something that aligns with this issue is now available for Pie Charts. It was implemented in #11842 

<img width="661" alt="image" src="https://github.com/PostHog/posthog/assets/5631091/af972756-aa68-4bba-ad2c-a180107c9918">

---

Making similar changes for Bar Graphs will require either separating them from Line Charts, or adding ugly exceptions.

https://github.com/PostHog/posthog/blob/a3f21fd92128744654939b68d7d451732559efdb/frontend/src/scenes/insights/views/LineGraph/LineGraph.tsx#L446

Also, there's an issue to convert charts to D3, https://github.com/PostHog/posthog/issues/4568, which might make this change easier.

**Comment by Twixes** [comment]
I'm going to close this since the pie charts use case is solved now, but if the topic of bar charts comes up again, feel free to open an issue about those specifically.
