### ISSUE TITLE
Dumb events service

### ISSUE THREAD

**Issue by yakkomajuri** [PostHog/posthog#8301]
This discussion relates to an idea we've had before and that's been brought up again as a result of the recent outage.

**Problem:** Our events service does a few different things, leaving ingestion open to the possibility of being down if any of those things malfunctions. 

**Solution to discuss:** Splitting out `capture.py` into a completely separate + simpler service that just receives an event and puts it in Kafka.

**Pros**

The main thing is ensuring we **don't ever lose events**.

**Potential cons**

- Added complexity
- If Postgres is the issue, maybe we can already account for this and send to the dead letter queue without a separate service
- No validation done on tokens sent in the payload (if we want to completely detach from Postgres) 

**Alternatives**

- Extend/improve dead letter queue usage
- Update the existing Django capture endpoint to cover these points (skip middleware? split out decide? don't do token validation?)

@fuziontech @tiina303 @timgl @guidoiaquinti

**Comment by guidoiaquinti** [comment]
Before creating another service, I think we could try first to improve what we have and I think there are several low hanging fruits ready to be picked here.

Considering that the primary concern here is the dependency with PostgreSQL, we currently use the database only for some basic validations that we could easily offload to _read only database replicas_ and/or a _K/V caching tier_. The validation logic is not complex, and it doesn’t seem to need read-after-write consistency (aka: we can tolerate reading from a non-super-consistent state). The current database workload is scaling linearly with the number of events we ingest (bad) and the events service strictly depends on the availability of the main PostgreSQL. By adding N _replicas_ or _K/V caching nodes_ we can spread that load and the availability concern. 

Note: we don't have (yet) great visibility into query shapes/performance but to give you a sense of the query volume used by the validation above, we are currently peaking at ~200k QPS for the single query shape `WHERE “posthog_team”.“api_token” = $1 LIMIT $2`

**Comment by hazzadous** [comment]
> Before creating another service, I think we could try first to improve what we have and I think there are several low hanging fruits ready to be picked here.

We can also make the events endpoint only dependent on being able to push to kafka to improve availability, without needing to split out initially (although that depends on what health and liveness checks will do to a pod if pg is down). Although for cognitive simplicity completely removing that dependency I think would be better. We might be able to tend to our pg setup with care, read replicas etc, but for self hosted I'm not sure how complex that becomes.

**Comment by macobo** [comment]
Some low-hanging fruit we can improve right now

### capture.py

So the capture endpoint currently queries the DB to fetch the `Team` object every request via the token object

This is used to:
- Get the team_id
- Check whether team.anonymize_ips is set
- Backfill some feature flags data on web (which in turn results in db queries)

We could instead:
- Only fetch team.id and team.anonymize_ips
- lru_cache the team lookup function on successes (very unlikely teams leave) and failures (how can you use a token that's not valid yet?)
- Potentially make this fetch use a replica DB
- Get rid of the web feature flag properties backfill 
    - it kind of is insane we have this logic. This was added in https://github.com/PostHog/posthog/commit/a1d364c9f9b45e45ccef3730c327a3aa063929d7 by @Twixes predating plugin-server and subsequently made more expensive expensive by @rcmarron (see also https://github.com/PostHog/posthog/issues/7182)

### decide.py

Decide endpoint queries feature flags which is responsible for the load on the service given it's queried every library import on web or when any service anywhere uses feature flags.

We should improve feature flags to perform well under extreme loads - currently it results in multiple expensive queries into a huge postgres table (posthog_person).

Related:
- https://github.com/PostHog/posthog/issues/7182
- https://github.com/PostHog/posthog/issues/7115

**Comment by fuziontech** [comment]
I agree that there are a lot of improvements we can make with the system as it is - but ideally this would be something that is completely separate and encapsulated quite cleanly. Right now we have Decide and Events going to the Events service which is really just the app running on a separate set of resources and only getting those events routed to it.

Ideally we'd have three pools of resources that are separate to protect each from each other:
- app
- feature flags
- events

⚠️ This is something we should eventually split into subdomains as well for each of these. Heavy caching for feature flags and app - none for events. Tunable, of course. ⚠️ 

Events should be really neatly bundled up to only process what needs to be done on the way in. We shouldn't have django middleware, health check endpoints exposed for migrations, or really anything else convoluting that path.

Specifically here for the events endpoint/service we should simply have a service (could live in the PostHog repo) that boots up and does the few things that we need it to do with very little complexity. A lot of this functionality has been enumerated by @macobo

How a basic events service should work:
- https://fastapi.tiangolo.com/ - FastAPI for the endpoint
- Redis is used (with memoization locally - only use memoized value if call to redis fails) to cache all valid API keys -> Team relationships
  - We can very easily evict keys on teams or projects getting destroyed or on key rotation <-  Important when a key is getting spammed with garbage and the team needs to invalidate fast
- Basic caching for `team.anonymize_ips` using Redis + memoization w/ TLRU, or just memoization w/ TLRU - no need to get complicated here
- We use a read replica for PG to query for API validity on cache miss
- We warm the cache on creation of new Keys (optional, but would be nice)
- Celery job to warm the cache on stack boot (optional, but nice)
- The `_health` endpoint for this service would return true if it's able to connect to Kafka and ready to accept HTTP requests, that's it.
- Remove the [feature flag properties](https://github.com/PostHog/posthog/pull/3090) functionality (should be a plugin sounds like)
- Write to disk in the event of a Kafka outage. This one is a tough one because of the constraints of space on disk and the health endpoint. What we could do is the `_health` endpoint could return ✅ if kafka was up, but is now down and has been down only for some acceptable time period. That and there is still sufficient disk available for events to continue to be collected. Once you run out of disk all bets are off: `_health` returns non-200 and the service is bounced until kafka recovers.

This would achieve the following goals:

- [x] Resilient to PG outages
- [x] Reduced load on PG Primary
- [x] Resilient to Redis outages (due to memoization failover)
- [x] Reduced cognitive load during outages and while reading code. Separation of concerns. Less likely code bleeds across boundaries
- [x] Only hard dependency is Kafka. Hard to get around this one. Kafka is the critical service for us. We could write to disk during a Kafka outage as mentioned.

Separate note:
Completion of a simplified events service should come before PG migration https://github.com/PostHog/product-internal/issues/258

Idea here is that we would not have to read from a dead letter queue. Events would just flow in as normal and just wait for the plugin server to come back online from the outage caused from the migration. The migration itself would be an excellent test for the system.

**Comment by yakkomajuri** [comment]
So are we going forward with this or not? By P1 does that mean I should prioritize this next sprint for example?

**Comment by guidoiaquinti** [comment]
> So are we going forward with this or not? By P1 does that mean I should prioritize this next sprint for example?

Yes, I think we should move forward with all the low-hanging fruits we highlighted. Everything else I think should be itemised in GH issues as mid-long term improvements.

**Comment by yakkomajuri** [comment]
@guidoiaquinti sorry, I meant the actual dumb events service concept. I see all the other actionables that would be done instead of it but @fuziontech seems to be advocating for the actual separate service

**Comment by guidoiaquinti** [comment]
I think we should implement all the fixes above and then re-evaluate the cost and benefits of moving ingestion to a separate service.

**Comment by hazzadous** [comment]
The main benefit I see is avoiding being an analytics system for the uptime of the main app, postgres, any other dependencies. We'd still be monitoring the uptime of that new service however, and of kafka. I'm not sure how much of a benefit this would be though.

At the moment we have data loss in the cases of:

 1. web being down (bad code change in capture.py for instance, or just plain down)
 2. kafka being down

At the moment we'd have interrupted but recoverable operation for:

 1. postgres being down. We can replay these from the dead letter queue.

We would be moving to a system where we have issues with:

 1. whatever is taking http requests and pushing them to kafka being down.
 2. kafka being down.

In the case that postgres is down (e.g. maintenance, migration etc.), the plugin-server can be stopped from reading from kafka, and resumed once issues have been resolved. No need to dead letter queue in this case. We can also have retry reading from kafka to smooth over any intermittent issues, before pushing into DLQ if we still have issues. The management in this setup seems a little more controlled than otherwise would be.

However, we may be able to handle this case without having a new service (although we'd still have issues if e.g. bad code pushed to capture.py or we'd setup the liveness or readiness probes to check postgres) but simply not pushing to dead letter queue on postgres errors within capture.py. We'd need to handle api token checking, ip anonymizing within whatever is reading from kafka (plugin-server?).

Personally separating out the different availability characteristics of parts of the system makes be feel less stressed, and makes failure cases a little more clear to me.
