### ISSUE TITLE
PostgreSQL - plugin-server: `posthog_persondistinctid` duplicate key collision

### ISSUE THREAD

**Issue by guidoiaquinti** [PostHog/posthog#8343]
## Bug description
At any point in time we may have N plugin servers running M threads. If two of threads see a distinct id in an event that we’ve never seen before, both might try to insert that distinct ID at the same time, causing one of the inserts to fail because of the table’s constraints:

```
sql_error_code = 23505 STATEMENT:  /* plugin-server:addDistinctIdPooled */ INSERT INTO posthog_persondistinctid (distinct_id, person_id, team_id, version) VALUES ($1, $2, $3, 0) RETURNING *
sql_error_code = 23505 ERROR:  duplicate key value violates unique constraint "unique distinct_id for team"
sql_error_code = 23505 DETAIL:  Key (team_id, distinct_id)=(2109, b0b17d4a-4deb-47b7-9aa3-8975965e1d29) already exists.
```

In order to avoid those errors we should probably using an [upsert](https://www.postgresqltutorial.com/postgresql-upsert/).

## Expected behavior
The race condition doesn't trigger a duplicate key collision

## Environment

- [X] PostHog Cloud
- [X] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [X] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

## Additional context
* [Internal Slack thread](https://posthog.slack.com/archives/C01MM7VT7MG/p1643372009714669)

**Comment by tiina303** [comment]
This is a bit tricky. Looking at the the [`upsertGroup`](https://github.com/PostHog/posthog/blob/5f7d3c566dd97af7c3797ec9d7b99354b35eaff9/plugin-server/src/worker/ingestion/properties-updater.ts#L123 ) function might be the easiest to see (person creation/update is a bit more complex due to distinctId table needing to be updated too). Specifically updates are complex, so we can't just do the update if insert failed, we need to compute exactly what props should be updated (in code, note that postgres fn was less efficient during testing).

**Comment by tiina303** [comment]
Oh 🤦‍♀️  I was looking at the wrong thing. I thought we're talking about the sentry exception that we have [here](https://github.com/PostHog/posthog/blob/master/plugin-server/src/worker/ingestion/process-event.ts#L774)

**Comment by tiina303** [comment]
The good news is we seem to be expecting and handling the error everywhere.

In the end there are 3 functions here where these can come from:
1. [mergeNew](https://github.com/PostHog/posthog/blob/a7e792c3fc5c1abc70d8167e1ead12d4ea24f17a/plugin-server/src/worker/ingestion/process-event.ts#L350) - this can't be it as Guido mentioned it happens multiple times a second & this code path is currently not in use.
2. [`aliasDeprecated`](https://github.com/PostHog/posthog/blob/a7e792c3fc5c1abc70d8167e1ead12d4ea24f17a/plugin-server/src/worker/ingestion/process-event.ts#L377) - we can't really `upsert` here as merging people once created means updating other tables too specifically person properties. However there's hope for this to change in the future with the new person model ideas. Furthermore I've been trying to replace this with `mergeNew`.
3. [`createPersonIfDistinctIdIsNew`](https://github.com/PostHog/posthog/blob/a7e792c3fc5c1abc70d8167e1ead12d4ea24f17a/plugin-server/src/worker/ingestion/process-event.ts#L762) - we should change this one if there's a better way to do it, we'll need to figure out how to handle this case anyway as the new model will still need to upsert persons.
-----
#### how should we `upsert` person properties?

Previously we've explored 2 solutions: 
1. postgres function (which isn't performant and makes many operations/debugging tricky)
2. the currently in use solution of transaction over 1) get person 2) figure out what update should be 3) write the update. 

Instead of this Guido suggested looking into if we could generate the conditional update statement in code and use in `upsert`. Note that atm we're still operating on different tables so it's a bit more tricky (how upserts to distinct_id table work together with person table). **We'll look into this later today.**


Note we should do the same with groups [here](https://github.com/PostHog/posthog/blob/5f7d3c566dd97af7c3797ec9d7b99354b35eaff9/plugin-server/src/worker/ingestion/properties-updater.ts#L123).

-----
#### More detailed code path analysis:
There's 3 call locations for [`addDistinctIdPooled`](https://github.com/PostHog/posthog/blob/a7e792c3fc5c1abc70d8167e1ead12d4ea24f17a/plugin-server/src/utils/db/db.ts#L716)
1. [mergeNew](https://github.com/PostHog/posthog/blob/a7e792c3fc5c1abc70d8167e1ead12d4ea24f17a/plugin-server/src/worker/ingestion/process-event.ts#L350) - this can't be it as Guido mentioned it happens multiple times a second & this code path is currently not in use.
1. [addDistinctId](https://github.com/PostHog/posthog/blob/a7e792c3fc5c1abc70d8167e1ead12d4ea24f17a/plugin-server/src/utils/db/db.ts#L702) - looking at call locations we see it's used only in [`aliasDeprecated`](https://github.com/PostHog/posthog/blob/a7e792c3fc5c1abc70d8167e1ead12d4ea24f17a/plugin-server/src/worker/ingestion/process-event.ts#L396,L429) i.e. the currently in use code path for people merging. This could totally be it as we fetch persons but don't run this in a transaction & furthermore we have the error handling here to retry the merge, which would then run [`mergePeople`](https://github.com/PostHog/posthog/blob/a7e792c3fc5c1abc70d8167e1ead12d4ea24f17a/plugin-server/src/worker/ingestion/process-event.ts#L459) instead, which merges the properties and does a [`moveDistinctIds`](https://github.com/PostHog/posthog/blob/a7e792c3fc5c1abc70d8167e1ead12d4ea24f17a/plugin-server/src/utils/db/db.ts#L764). We do really need to merge the properties, but we could do the `upsert` first for distinctIds & then deal with merge later (in theory - problem this is the old code path, which means merges have an order, so that makes everything more complex).
1. [In person creation](https://github.com/PostHog/posthog/blob/a7e792c3fc5c1abc70d8167e1ead12d4ea24f17a/plugin-server/src/utils/db/db.ts#L535) - we run this in a transaction together with create person, but the `distinctIds` are passed in ... looking at it's call locations
    1. [`mergeNew`](https://github.com/PostHog/posthog/blob/a7e792c3fc5c1abc70d8167e1ead12d4ea24f17a/plugin-server/src/worker/ingestion/process-event.ts#L355) - as before can ignore code not in use
    2. [`aliasDeprecated`](https://github.com/PostHog/posthog/blob/a7e792c3fc5c1abc70d8167e1ead12d4ea24f17a/plugin-server/src/worker/ingestion/process-event.ts#L432) - again the merging people old code & it's the same problem here that we need to merge people props in the right way.
    3. [`createPersonIfDistinctIdIsNew`](https://github.com/PostHog/posthog/blob/a7e792c3fc5c1abc70d8167e1ead12d4ea24f17a/plugin-server/src/worker/ingestion/process-event.ts#L762) - call locations expect this could fail
        1. [session recordings](https://github.com/PostHog/posthog/blob/a7e792c3fc5c1abc70d8167e1ead12d4ea24f17a/plugin-server/src/worker/ingestion/process-event.ts#L711) - we don't care and could use an `upsert` instead we just need the person to exist
        2. [capture](https://github.com/PostHog/posthog/blob/a7e792c3fc5c1abc70d8167e1ead12d4ea24f17a/plugin-server/src/worker/ingestion/process-event.ts#L606) - here we either create the person with props or if the creation failed with the dup key problem we update the existing person properties later. We could change this to `upsert` if (1) we always try to update person properties later (2) `upsert` returns if we created with the props & we can keep everything the same on the call location.

**Comment by tiina303** [comment]
`createPersonIfDistinctIdIsNew` race condition would be fixed by https://github.com/PostHog/posthog/issues/9181

**Comment by tiina303** [comment]
I believe we have proper retries around everything now

**Comment by guidoiaquinti** [comment]
> I believe we have proper retries around everything now

Good job team! 👏
