### ISSUE TITLE
PostgreSQL - `properties` query is constantly timing out

### ISSUE THREAD

**Issue by guidoiaquinti** [PostHog/posthog#8364]
## Bug description

The query is semi-constantly failing on cloud as it's taking more than the threshold to execute
```
SELECT ("posthog_person"."properties" -> 'utm_campaign'), COUNT("posthog_person"."id") AS "count" FROM "posthog_person" WHERE ("posthog_person"."team_id" = 1243 AND ("posthog_person"."properties" -> 'utm_campaign') IS NOT NULL) GROUP BY ("posthog_person"."properties" -> 'utm_campaign') ORDER BY "count" DESC LIMIT 50
```

Note: it is scanning **over 20GB** of data. See query plan below 👇 

<details> 

```json
[ { "Plan": { "Node Type": "Limit", "Parallel Aware": false, "Startup Cost": 4046931.50, "Total Cost": 4046931.53, "Plan Rows": 50, "Plan Width": 40, "Actual Startup Time": 27318.768, "Actual Total Time": 27318.781, "Actual Rows": 50, "Actual Loops": 1, "Output": ["((properties -> 'utm_campaign'::text))", "(count(id))"], "Shared Hit Blocks": 851810, "Shared Read Blocks": 2663385, "Shared Dirtied Blocks": 10, "Shared Written Blocks": 32047, "Local Hit Blocks": 0, "Local Read Blocks": 0, "Local Dirtied Blocks": 0, "Local Written Blocks": 0, "Temp Read Blocks": 0, "Temp Written Blocks": 0, "I/O Read Time": 15204.869, "I/O Write Time": 296.256, "Plans": [ { "Node Type": "Sort", "Parent Relationship": "Outer", "Parallel Aware": false, "Startup Cost": 4046931.50, "Total Cost": 4046948.22, "Plan Rows": 33428, "Plan Width": 40, "Actual Startup Time": 27318.767, "Actual Total Time": 27318.775, "Actual Rows": 50, "Actual Loops": 1, "Output": ["((properties -> 'utm_campaign'::text))", "(count(id))"], "Sort Key": ["(count(posthog_person.id)) DESC"], "Sort Method": "top-N heapsort", "Sort Space Used": 32, "Sort Space Type": "Memory", "Shared Hit Blocks": 851810, "Shared Read Blocks": 2663385, "Shared Dirtied Blocks": 10, "Shared Written Blocks": 32047, "Local Hit Blocks": 0, "Local Read Blocks": 0, "Local Dirtied Blocks": 0, "Local Written Blocks": 0, "Temp Read Blocks": 0, "Temp Written Blocks": 0, "I/O Read Time": 15204.869, "I/O Write Time": 296.256, "Plans": [ { "Node Type": "Aggregate", "Strategy": "Hashed", "Partial Mode": "Simple", "Parent Relationship": "Outer", "Parallel Aware": false, "Startup Cost": 4046592.41, "Total Cost": 4046709.41, "Plan Rows": 33428, "Plan Width": 40, "Actual Startup Time": 27317.620, "Actual Total Time": 27318.658, "Actual Rows": 197, "Actual Loops": 1, "Output": ["((properties -> 'utm_campaign'::text))", "count(id)"], "Group Key": ["(posthog_person.properties -> 'utm_campaign'::text)"], "Shared Hit Blocks": 851810, "Shared Read Blocks": 2663385, "Shared Dirtied Blocks": 10, "Shared Written Blocks": 32047, "Local Hit Blocks": 0, "Local Read Blocks": 0, "Local Dirtied Blocks": 0, "Local Written Blocks": 0, "Temp Read Blocks": 0, "Temp Written Blocks": 0, "I/O Read Time": 15204.869, "I/O Write Time": 296.256, "Plans": [ { "Node Type": "Index Scan", "Parent Relationship": "Outer", "Parallel Aware": false, "Scan Direction": "Forward", "Index Name": "posthog_person_team_id_325c1b73", "Relation Name": "posthog_person", "Schema": "public", "Alias": "posthog_person", "Startup Cost": 0.11, "Total Cost": 4043295.80, "Plan Rows": 3296613, "Plan Width": 36, "Actual Startup Time": 0.139, "Actual Total Time": 26661.054, "Actual Rows": 841969, "Actual Loops": 1, "Output": ["(properties -> 'utm_campaign'::text)", "id"], "Index Cond": "(posthog_person.team_id = 1243)", "Rows Removed by Index Recheck": 0, "Filter": "((posthog_person.properties -> 'utm_campaign'::text) IS NOT NULL)", "Rows Removed by Filter": 2541475, "Shared Hit Blocks": 851810, "Shared Read Blocks": 2663385, "Shared Dirtied Blocks": 10, "Shared Written Blocks": 32047, "Local Hit Blocks": 0, "Local Read Blocks": 0, "Local Dirtied Blocks": 0, "Local Written Blocks": 0, "Temp Read Blocks": 0, "Temp Written Blocks": 0, "I/O Read Time": 15204.869, "I/O Write Time": 296.256 } ] } ] } ] }, "Planning Time": 0.201, "Triggers": [ ], "Execution Time": 27319.312 } ]
```

</details>

## Expected behavior
The query should not be failing.

## How to reproduce

1. Run the query

## Environment

- [X] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

**Comment by macobo** [comment]
cc @alexkim205 @mariusandra @EDsCODE for prioritization. I think this query is triggered from various analytics filters for autocomplete, has to do with data taxonomy

**Comment by alexkim205** [comment]
Thanks for the context here, it looks like this query traces back to the `PersonViewSet` GET method  here: https://github.com/PostHog/posthog/blob/7d84ac966bb252da4cc41ba6c183f47b42c59738/posthog/api/person.py#L132-L145

This code path is hit when you navigate to the `https://app.posthog.com/persons` and partially fill out this a query like so:

<img width="840" alt="Screen Shot 2022-02-01 at 9 57 47 AM" src="https://user-images.githubusercontent.com/13460330/152024208-4c0cb244-e41a-451d-ad78-d02713a7c7de.png">

Here we'll try to list out all the possible property values by default which takes a long time since this query runs. It's not blocking a user's ability to query for properties if they know what they're searching for, but I can see how it would slow down discovery if they're going in blind. I would flag this as mid-high priority since it affects perceived performance of the app and the taxonomic filter is used heavily in a lot of areas.

**Comment by mariusandra** [comment]
Something like this returns results instantly in metabase:

```sql
SELECT property, count(property) as "count" FROM (
    SELECT 
        ("posthog_person"."properties" -> 'utm_campaign') as "property"
    FROM "posthog_person" 
    WHERE 
        "posthog_person"."team_id" = 1243 AND 
        "posthog_person"."properties" -> 'utm_campaign' IS NOT NULL
    ORDER BY "id" DESC 
    LIMIT 10000
) AS P 
GROUP BY property
ORDER BY "count" DESC
LIMIT 100
```

**Comment by guidoiaquinti** [comment]
> Something like this returns results instantly in metabase:

Yes but that's because those are different queries (returning different results) or am I missing something? (maybe it's 👍 for our use case, I'm just commenting at the two queries)

**Comment by mariusandra** [comment]
The query above was posted during a call with @alexkim205 , apologies for the lack of context around it. Here's a better analysis.

The issue here is about the person property suggestions being way too slow:

![2022-02-03 09 27 40](https://user-images.githubusercontent.com/53387/152306977-399b4cbb-260c-4690-ab2b-51561fa62741.gif)

While suggestions for event properties are quite fast:

![2022-02-03 09 28 36](https://user-images.githubusercontent.com/53387/152307155-540814c0-0c57-4d34-b9b0-05bb55fcc9f0.gif)

That's because the event property query has an `and` clause with `timestamp > 7 days ago`... and is done on ClickHouse, but the person property query looks through every person, and is done on Postgres.

The query posted above is a (draft for a) quick win to give us some breathing room while we're figuring this out. Moving the query to clickhouse will surely be another win, but I'd still implement some kind of limit on the number of rows scanned.

So indeed that query is not doing the same as what we have now, but I think it's good enough, considering how its compatriot events query works.

**Comment by guidoiaquinti** [comment]
Make sense, thank you for the additional context!
