### ISSUE TITLE
Greater than on user properties disappeared?

### ISSUE THREAD

**Issue by marcushyett-ph** [PostHog/posthog#8488]
## Bug description

I used to be able to do something like:
![image](https://user-images.githubusercontent.com/85295485/153005908-b7fb3361-9e5a-4d5c-81b6-6148c121c888.png)

Hubspot score > 100

My current workaround is pretty ugly:
![image](https://user-images.githubusercontent.com/85295485/153006591-8f753b1f-7fe6-4323-a877-9294552c62d4.png)

## Expected behavior

I would expect to see greater/ less than for any numeric field.

## How to reproduce

1. Add a user property filter, select hubspot_score

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

**Comment by marcushyett-ph** [comment]
@alexkim205 @pauldambra not sure if this might be related to any of the changes you've made recently?

**Comment by pauldambra** [comment]
Hmmm running `select * from posthog_propertydefinition where team_id = 2 and name = 'hubspot_score'` shows we detected it as a string

**Comment by marcushyett-ph** [comment]
Hmm...any idea's why, and or if we can update it to be an int?

**Comment by pauldambra** [comment]
Just digging in

**Comment by pauldambra** [comment]
🤔 , the detection code we use has only ever been used to show a value in the events table 

![Screenshot 2022-02-08 at 14 39 06](https://user-images.githubusercontent.com/984817/153009421-d9addee0-d3eb-4756-a074-f9a591d2f815.png)

Because it's only been used as a display value in the events table I guess nobody has noticed it's wrong before

![Screenshot 2022-02-08 at 14 41 31](https://user-images.githubusercontent.com/984817/153009739-2c47cb2a-b405-4b57-bd60-0d324d6203ec.png)

**Comment by pauldambra** [comment]
We ~should be able to~ can fix this on event ingestion....

**Comment by marcushyett-ph** [comment]
Does that mean we'll need to re-ingest every historical event / update every user property to fix this? Or is there something we can do to fix the historic data?

**Comment by pauldambra** [comment]
We check on ingestion whether we should try to update the value. We might be able to catch it there

The property definitions are separate to the events. So we can do a migration on a smaller dataset than the events if we can't fix it otherwise

**Comment by marcushyett-ph** [comment]
@pauldambra made a small PR to cast as an Int during ingestion: https://github.com/PostHog/hubspot-plugin/pull/21

**Comment by mariusandra** [comment]
nice, this actually prevented you from getting wrong data (sort: "1", "10", "11", "12", "2", ...)

**Comment by pauldambra** [comment]
@mariusandra I'm thinking the lowest complexity thing is to run a migration that sets all detected strings to null alongside fix to redetect correctly

If the property type is undetected we show all the possible operators in the UI...

**Comment by mariusandra** [comment]
This property is now fixed. Issue closed @marcushyett-ph ?

**Comment by marcushyett-ph** [comment]
Great thank you!

**Comment by yakkomajuri** [comment]
Still can't see greater than and smaller than

**Comment by yakkomajuri** [comment]
@joethreepwood

**Comment by joethreepwood** [comment]
This was an issue for me when trying to create a filter that looked at the `joined_at` property between two dates. With no option to create a filter that looks between two values and no option to use either greater than or lesser than operators, there's no way for me to easily create a cohort of users who `joined_at` between (for example) Jan 2022 and Feb 2022.

**Comment by marcushyett-ph** [comment]
I think this is because we don't recognize this as an integer - @pauldambra fixed this before for `hubspot_score`, can we do the same fix for this.

**Comment by yakkomajuri** [comment]
We had tried some values that would supposedly be integers and didn't work but I see now that the issue is detecting the type rather than these missing.

**Comment by pauldambra** [comment]
I think this is an interesting signal for how this could be improved (As part of data management @alexkim205 ?)

`joined_at` the event property has been detected as a string

<img width="812" alt="Screenshot 2022-06-22 at 12 45 16" src="https://user-images.githubusercontent.com/984817/175011054-5a00a1ba-4575-49d7-9d90-652273db4c7b.png">

So you're only getting string comparison operators

`joined_at` the person property... well, we don't do detection on person property types. So it has no type and you get all operators. Although it turns out if you've visited the event property first then you get presented with the string operators

<img width="811" alt="Screenshot 2022-06-22 at 12 45 24" src="https://user-images.githubusercontent.com/984817/175011352-d7a425b5-3fe6-45c4-885f-827ed2667ba4.png">

I added docs here: https://posthog.com/docs/user-guides/events#event-filtering recently. But it feels like a user has to understand a lot of context to make this work.

-----

`joined_at` the event property seems to have the format `2022-06-22T10:47:06.272163+00:00`. That does match our detection regex for ISO 8601 dates. So, we _could_ clear the detected property for that one property

But we'll have to do this one at a time as we discover them

-----

Feels like a sensible next steps
* allow users to override the types in the data management area.
* I think we're way overdue adding this detection for person properties too
* fix the bug that is caching operator lists (presumably where the key matches between person and event but I've not checked)

**Comment by yakkomajuri** [comment]
As a short term step to unblock @joethreepwood I just set `is_numerical` on the db
