### ISSUE TITLE
History Log RFC

### ISSUE THREAD

**Issue by pauldambra** [PostHog/posthog#8545]
In order to work towards #8088 (HogBook) and #7819 (history of an item for investigations) we will add an audit log.

## What is it?

A log of changes made by humans to (a minimum of) insights and feature flags. That can be viewed in the PostHog UI

### example UI

![Screenshot 2022-02-10 at 14 18 25](https://user-images.githubusercontent.com/984817/153449355-73b53f76-bb09-4c0d-bd42-c4fa09ed7663.png)

## What is it not?

It is not a log of all user activity. So it can't, for example, be used to investigate what data a person has seen or exported

## Why work on it now?

As part of our strategy to make discoveries easier. We believe this is part of collaboration.https://github.com/PostHog/product-internal/blob/00e7ed032b1b8056286848c4ef21be8d937f2e1f/requests-for-comments/2022-02-01-collab-v2.md

## How to implement it?

We investigated using a django extension called reversion. But it's data model is fixed and didn't easily allow us to record the team associated with a change. 

So we will add a custom mechanism in the post_save django signal

This allows us to easily alter what we store and where we store it in future.

## Where to store it?

Since we believe that we will store less than 1TB of data and the query pattern is unknown right now. We will store the data in Postgres not Clickhouse (and not some new store)

To provide flexibility in future and because it is cheap to add now. We may partition the table by date. That would allow us to copy partitions to long-term storage and then drop them from the DB easily

## What to store?

Each item will be stored with model name, model primary key, team id, and timestamp 

This gives us a unique key

We could store an incrementing version ID for each instance, or each model, but don't want the cost of a DB lookup for every saved version

Alongside that we will store the state of the model as JSON

Storing only new state of the model means 
* to generate N history items, we load N + 1 versions from the database
* we must generate the human readable history description at read time not at save time
* we don't have to read from DB or edit each model to allow us to load the pre-save version of a model when writing a version

If we have multiple servers handling changes for the same model at the same time, they will either use the exact same timestamp (and so one of the writes will fail) or will be stored with very similar timestamps. If those stored versions are identical we can ignore them when generating a history log.

To generate a history log we can load a page of data slightly larger than we need and walk backwards through the list generating the human readable descriptions by comparing version N with version N-1

**Comment by pauldambra** [comment]
PRs > Issues

see #8521 for example of using django reversion
see #8542 for example of using custom version saving
see #8551 for example of using django-simple-history

**Comment by rcmarron** [comment]
Another idea could be to use `django-simple-history` which is basically the same thing as `reversion` but it allows for [custom fields on the history table.](https://django-simple-history.readthedocs.io/en/latest/historical_model.html#adding-additional-fields-to-historical-models)

**Comment by pauldambra** [comment]
# Why add team_id to any history?

To avoid showing history from tenant A to someone in tenant B (when in PostHog Cloud). 

When self-hosted this restriction is unnecessary (true?)

## What models might we audit

| model | has team id? | has organisation id |
|-------|--------------|--------------------|
|cohort|✅|❌|
|dashboard|✅|❌|
|dashboard item (insight)|✅|❌|
|event definition|✅|❌|
|experiment|✅|❌|
|feature flag|✅|❌|
|group|✅|❌|
|organization|❌|✅|
|plugin|❌|✅|
|plugin config|✅|❌|
|property definition|✅|❌|
|team|✅|❌|
|user|?|?|

NB user has a current team and current organisation

---

So we can't group history by team id anyway

**Comment by pauldambra** [comment]
# Options


| method | pros | cons|
|-|-|-|
|[django-reversion](https://github.com/etianen/django-reversion)| <ul><li>easy to add</li><li>battle tested (2.7k stars)</li><li>built in rollback between version</li></ul>|<ul><li>writes all posthog data into json in a model</li><li>adding custom fields requires a separate model<li>can't change storage</li><li>references to other models e.g. user are by primary key only so if the user is deleted we can't display any info about them anymore</li><li>can only be used to audit models</li></ul>|
|[django-simple-history](https://github.com/jazzband/django-simple-history)| <ul><li>easy to add</li><li>battle tested (1.5k stars)<li>writes every model field to its own column in history</li><li>build in [history diffing](https://django-simple-history.readthedocs.io/en/latest/history_diffing.html)</li><li>built in rollback between version</li></ul>|<ul><li>adding custom fields requires a separate model<li>can't change storage</li><li>every model migration will generate a historical model migration too</li><li>references to other models e.g. user are by primary key only so if the user is deleted we can't display any info about them anymore</li><li>can only be used to audit models</li></ul>|
|custom code|<ul><li>no magic, just code</li><li>can change to write to e.g. kafka instead of straight to postgres in future</li><li>all revisions in one table</li><li>can be used to audit events which are not driven by CRUD on models</li></ul>|<ul><li>no admin integration (without making it)</li><li>can't auto rollback versions</li></ul>|

**Comment by pauldambra** [comment]
# Partitioning SQL Tables

We talked about partitioning the audit table(s) in order to make deleting data easier and to improve performance as we grow

https://pganalyze.com/blog/postgresql-partitioning-django

Support for partitioning doesn't exist in Django ORM and extra manual work likely to be too costly now

# Reducing DB load

Saving a version record every time we save a model can be naively expected to double DB load (two writes instead of one)

We discussed pushing audit records into kafka instead so the app doesn't have to wait while they are saved or put load onto DB from saving them

Similarly agreed that this was too much complexity for _now_. If we go with one of the django apps then we would have to move away from that in order to move to kafka

**Comment by pauldambra** [comment]
## What's the deleted user problem?

Here's a suggestion (from @clarkus) for what to show for a deleted user

In order to show this we need to store user's primary key, name, and email. With that we can look up the user by primary key, and discover they are no longer in the DB. Then still show name and gravatar using stored email but decorate so the viewing user knows that the history user was deleted

<img width="557" alt="Screenshot 2022-02-10 at 20 53 59" src="https://user-images.githubusercontent.com/984817/153495191-42f37c52-e05a-4615-9feb-d2b8f40815a2.png">

However, if all we have stored for the user is a primary key then once they're deleted we can't show any information about them because they're not there to query
 
 ### storing only primary key
 
 If we store only primary key to the user. Then once they are deleted we can't look up their name and email anymore.
 
In this case we would fall back to displaying a default unknown user avatar and name.

<img width="569" alt="Screenshot 2022-02-11 at 08 24 30" src="https://user-images.githubusercontent.com/984817/153559752-c0b417da-813e-4012-8254-92c5bd797cfb.png">
 
### some changes should alter history

The canonical example is when a user's name is changed. 

Here user `john`'s name is changed to `jane`. An immutable log (where we store only email and name, or where we use stored email and name in preference to primary key would always show `john` for historical items when it is likely that the customer's need is that historical items show `jane` after the name change

<img width="564" alt="Screenshot 2022-02-11 at 08 27 09" src="https://user-images.githubusercontent.com/984817/153559769-57070adc-da95-43f5-83a3-b7a5f917e698.png">

## To solve for this

* We should store email, name, and primary key. 
* when loading a history item we look up the users by primary key and display their current information
* if a user has been deleted we show the information captured at the time the historical item was written to DB and indicate the user was deleted

This increases storage but not significantly (e.g. a tiny fraction of session recording or element models)

You could allow some updates to have a user interface option to "also update history" but that seems like unnecessary complexity (at least for now)

**Comment by hazzadous** [comment]
I'm trying to get the following clear in my head as I'm not sure it marries up with others view:

 1. audit log
 2. insight versioning
 3. insight history
 4. social feed

The type of use cases for each:

## audit log

Some event has happened and I need to review e.g. what actions (read write update share etc) has made. I would imagine this would be like, there is some sensitive data that has been exposed, and we need to tell which users have requested it. Or a user has gone rogue and we need to be able to review, across the system, all actions they have performed. Let's say a personal api key was compromised. This doesn't have to be able to programmatically reconstruct objects as if it was some event sourcing system, just enough for a human to see what actions have been performed. Data structures here do not have to maintain exact schema compatibility with, say, the insights storage, but need to be enough to understand what happened, and understand exposure to risk. Traceability over readability. It should be tamper proof.

It doesn't need read-after-write consistency

## insight versioning

I want to be able to see which previous versions of an insight there are, to view the insight at a specific version, and possibly revert the latest version to one of these.

It does require read-after-write consistency

## Insight history

I want to be able to see a history of an insight such that I can understand who is working on it, talk to them about it etc. It doesn't need to log every action that may have been performed, e.g. reads. It should be displayable in a "pretty" format to the user for each type of action being recorded, which can be specific to a model (i.e. actions on insights are going to be different to actions on feature flags).

How is this different from insight versioning? I'm going to say it includes things like share actions i.e. changes that are not just definition changes. It perhaps also doesn't need to include the actual definition at each point. It is just contextual information rather than versioning.

## Social feed

I want to be able to show users what other users have been doing within a team, maybe emailing users that have subscribed to certain types of items.

It doesn't need read-after-write consistency

I think it would help to keep these distinct when thinking about this. Choose one and implement it satisfying its own requirements. Audit log can by all means be enhanced by the addition of insight versioning as we can now link to the exact state of an insight but it doesn't need to. Avoid premature abstraction and, as we go we can introduce them where they make sense.

I think what we want here is insight history and/or feature flag history. It may be that it is implemented using some common library, but it is likely best served as specific to the individual models. For instance, we will likely want to have an API that looks like:

```
GET /api/insights/<insight_id>/history
{
    "actions": [
        {
            "user_id": 1,
            "action": "update_tags",
            "timestamp": "2020-01-01T12:23:12Z",
            "details":  {
                "new_tags": ["some", "tags"]
            }
        },
        {
            "user_id": 2,
            "action": "changed_name",
            "timestamp": "2020-01-01T12:23:12Z",
            "details": {
                 "name": "Some name",
            }
        },
        ...
    ]
}
```

I'm not sure what other things we'd need here, what options might there be in the three dots list? But this should get us to something as has been mocked up.

As for implementation, I haven't looked at the libraries that much, but I suspect that it will be more trouble than it's worth using them. I would avoid using django signals and rather be more explicit, creating history within each API endpoint or insight service method. Signals are all very well for exposing hooks for a library where you want it has to be decoupled, but we're in control here. I would also suggest that we don't want to hook into the save method. Making saving a model to the database depend on potentially performing other tasks is too much coupling.

As for storage considerations, if we exclude full versioning, I don't think this is going to be a lot of data, this isn't going to be an audit log of all actions including read. Of course I'm assuming here that we do not actually want an audit log, @pauldambra am I way off here?

**Comment by pauldambra** [comment]
@hazzadous you're so way on that I've changed the issue name. That's a great way to think about it!

**Comment by pauldambra** [comment]
@paolodamico if we change from thinking about "audit log" to "history of insight" or "history of feature flag" etc does that work for you? Based on @clarkus designs I'm guessing that's a better name

**Comment by mariusandra** [comment]
@hazzadous what happened to your spaces?
![image](https://user-images.githubusercontent.com/53387/153576350-78bf777c-faa3-476b-801d-d7b258af5bfe.png)

**Comment by hazzadous** [comment]
@mariusandra yeah I don't know what happened there 🤷

**Comment by paolodamico** [comment]
Thanks for putting this together @pauldambra, I'll give some punctual feedback points:
- Calling it "History" instead of audit log makes sense to me.
- In terms of deleted users I think it's fine (at least for an MVP) to just set to null, and treat that as deleted users (we may have to distinguish from alterations not started by a user) and show a generic "Deleted user" as per Chris's designs. It also removes guesswork around respecting a deleted user's privacy.
   - Also, if the user just left the project (where it's still helpful to know who made the changes), we would still have the user info.

**Comment by neilkakkar** [comment]
> We could store an incrementing version ID for each instance, or each model, but don't want the cost of a DB lookup for every saved version

Curious - how is this different from storing a timestamp, w.r.t cost of a DB lookup for every saved version?

**Comment by pauldambra** [comment]
> Curious - how is this different from storing a timestamp, w.r.t cost of a DB lookup for every saved version?

The DB can write the current timestamp without needing to know the previous timestamp

But to write that a particular version is N+1 it has to know N

So rather than

|model|version number|
|--|--|
|a|1|
|b|1|
|a|2|
|a|3|

|model|created at|
|--|--|
|a|10:13|
|b|10:13|
|a|11:13|
|a|12:30|

**Comment by clarkus** [comment]
What about users who aren't deleted but that leave a project? They could still be participating in other projects in the org, just not this one. Do we need to represent that the user still exists, just not in this project? It's a bit different from the deletion case.

**Comment by paolodamico** [comment]
100% @clarkus, I added a comment above on that. If the user leaves the project only, makes sense to keep showing the user info

**Comment by clarkus** [comment]
Just linking for historical purpose - here is a quick redraw of a read only feature flag screen to illustrate how the overview and history tabs work of a detail view. https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf/PostHog-App?node-id=8281%3A55613

**Comment by pauldambra** [comment]
feature flag and person history rolled out to 100% of cloud users

**Comment by pauldambra** [comment]
feature flag and person history set as active flags for release 1.35.0 in #9476
