### ISSUE TITLE
Filter out internal users not working

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/posthog#8558]
## Bug description

Clicking a recent data point in [this graph](https://app.posthog.com/insights/167b_0_u/edit#filters=%7B%22insight%22%3A%22TRENDS%22%2C%22events%22%3A%5B%7B%22id%22%3A%22user%20signed%20up%22%2C%22math%22%3A%22dau%22%2C%22name%22%3A%22user%20signed%20up%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%2C%22properties%22%3A%5B%5D%2C%22custom_name%22%3Anull%2C%22math_property%22%3Anull%7D%5D%2C%22date_to%22%3Anull%2C%22display%22%3A%22ActionsLineGraph%22%2C%22interval%22%3A%22day%22%2C%22date_from%22%3A%22-180d%22%2C%22properties%22%3A%5B%5D%2C%22filter_test_accounts%22%3Atrue%2C%22actions%22%3A%5B%5D%2C%22new_entity%22%3A%5B%5D%7D) - see the last couple of days of traffic, brings up users like this:

<img width="625" alt="Screenshot 2022-02-11 at 01 20 24" src="https://user-images.githubusercontent.com/47497682/153523756-e89c4c21-c5ea-4f81-9597-272a251f1429.png">

These users should be filtered out - [via the rules](https://app.posthog.com/project/settings#internal-users-filtering):

<img width="1096" alt="Screenshot 2022-02-11 at 01 21 20" src="https://user-images.githubusercontent.com/47497682/153523827-813f82b3-7877-4759-baa8-4dc51201a9be.png">  

## Expected behavior

If posthog.com is in the domain, that user should be filtered out.

**Comment by neilkakkar** [comment]
Here's what's actually happening:

[This is me searching the same insight with a filter](https://app.posthog.com/insights/167b_0_u/edit#filters=%7B%22insight%22%3A%22TRENDS%22%2C%22events%22%3A%5B%7B%22id%22%3A%22user%20signed%20up%22%2C%22math%22%3A%22dau%22%2C%22name%22%3A%22user%20signed%20up%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%2C%22properties%22%3A%5B%7B%22key%22%3A%22email%22%2C%22value%22%3A%5B%22test%2B100%40posthog.com%22%5D%2C%22operator%22%3A%22exact%22%2C%22type%22%3A%22event%22%7D%5D%2C%22custom_name%22%3Anull%2C%22math_property%22%3Anull%7D%5D%2C%22date_to%22%3Anull%2C%22display%22%3A%22ActionsLineGraph%22%2C%22interval%22%3A%22day%22%2C%22date_from%22%3A%22-180d%22%2C%22properties%22%3A%5B%5D%2C%22filter_test_accounts%22%3Atrue%2C%22actions%22%3A%5B%5D%2C%22new_entity%22%3A%5B%5D%7D) for `email=test+100@posthog.com`

[This is me searching the same insight with a filter](https://app.posthog.com/insights/167b_0_u/edit#filters=%7B%22insight%22%3A%22TRENDS%22%2C%22events%22%3A%5B%7B%22id%22%3A%22user%20signed%20up%22%2C%22math%22%3A%22dau%22%2C%22name%22%3A%22user%20signed%20up%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%2C%22properties%22%3A%5B%7B%22key%22%3A%22email%22%2C%22value%22%3A%5B%22test%2B100%40posthog.com%22%5D%2C%22operator%22%3A%22exact%22%2C%22type%22%3A%22person%22%7D%5D%2C%22custom_name%22%3Anull%2C%22math_property%22%3Anull%7D%5D%2C%22date_to%22%3Anull%2C%22display%22%3A%22ActionsLineGraph%22%2C%22interval%22%3A%22day%22%2C%22date_from%22%3A%22-180d%22%2C%22properties%22%3A%5B%5D%2C%22filter_test_accounts%22%3Atrue%2C%22actions%22%3A%5B%5D%2C%22new_entity%22%3A%5B%5D%7D) `person email=test+100@posthog.com`

First one has events, second one doesn't.

The problem is the distinction between event and person properties: The former shows that the **event** property called `email` is set. The latter has the **person** property called `email` unset.

And our UI for persons seems to treat them the same. Figuring out what's happening here next!

**Comment by neilkakkar** [comment]
Ah, nope, all of them are different users who all have the same email set via `$identify`. So frontend is doing as expected, backend query is borked somehow.

**Comment by neilkakkar** [comment]
The SQL we generate:

```
AND NOT (argMax(person.pmat_email, _timestamp) ILIKE '%posthog.com%')
```

But:

```
select pmat_email, NOT pmat_email ILIKE '%posthog.com%' from person where id IN ['017ee019-27dd-0000-174f-3d3e848fde1f', '017edf30-16a7-0000-571d-db9454336ac0']
> '', 1
```

Shows that we're not considering the empty case 😅. But this is how it should be, imo.

What's weird is how these get re-inferred as `test+100@posthog.com`. This shouldn't be possible? 🤷‍♂️ .

**Comment by jamesefhawkins** [comment]
If I then export a list of signups the actual number of rows in the CSV is smaller than the 'number' of signups. ie I can see Feb 6 - Feb 13 800 signups (including these internal users), but when I 'Download CSV' I only get 200.

Not sure if this is the same problem?

**Comment by neilkakkar** [comment]
The culprit is out of sync person properties!

On Clickhouse, where the query runs, the email is empty, so the result is correct (like in my previous message).

The problem, though, is once you have the distinctIDs, we go to postgres to get property information, and [we have these properties set](https://metabase.posthog.net/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7InR5cGUiOiJxdWVyeSIsInF1ZXJ5Ijp7InNvdXJjZS10YWJsZSI6NzIsImZpbHRlciI6WyJhbmQiLFsiPSIsWyJmaWVsZCIsNTU5LG51bGxdLDI5NjkxNjM3OV1dfSwiZGF0YWJhc2UiOjN9LCJkaXNwbGF5IjoidGFibGUiLCJ2aXN1YWxpemF0aW9uX3NldHRpbmdzIjp7fX0=).

This is terrible. I thought we had fixed these issues a while back, but maybe not. And until we figure out what's causing this, it can very easily affect not just test filters, but everything else relying on person properties. Bumping up to P1.

**Comment by neilkakkar** [comment]
Spot checked a few more things, and [this seems to be true for all test+100@posthog.com emails](https://metabase.posthog.net/question#eyJuYW1lIjpudWxsLCJkYXRhc2V0X3F1ZXJ5Ijp7InF1ZXJ5Ijp7InNvdXJjZS10YWJsZSI6NzIsImZpbHRlciI6WyJhbmQiLFsiPSIsWyJmaWVsZCIsNTU5LG51bGxdLCIyOTYxMTUwODIiXV19LCJ0eXBlIjoicXVlcnkiLCJkYXRhYmFzZSI6M30sImRpc3BsYXkiOiJ0YWJsZSIsInZpc3VhbGl6YXRpb25fc2V0dGluZ3MiOnt9LCJvcmlnaW5hbF9jYXJkX2lkIjpudWxsfQ==).


@jamesefhawkins - we ought to do a better job of clarifying that. Looks like export csv has a limit of 200.

**Comment by neilkakkar** [comment]
Thanks to @tiina303 and @hazzadous , we now know it's not a data integrity issue, but some test data making it into prod! Limited to our team.

Hence, bumping to lower priority. Will fix tomorrow morning, if I don't get beaten to it ;)

**Comment by tiina303** [comment]
We do have a data integrity issue too, but it's a known one the collapsing in CH happening based on `_timestamp` can collide & have a plan too of using the `version` field, it's just not out yet.

**Comment by neilkakkar** [comment]
Thanks for correcting here, that comment was indeed outdated.

Since this specific issue was only for team 2 & won't happen anymore (once PR is in), and the CH `_timestamp` one is known, will close this.
