### ISSUE TITLE
Weave brand elements into app

### ISSUE THREAD

**Issue by corywatilo** [PostHog/posthog#8582]
Aside from the Hank the Hog on the Cloud registration page (and some color parity), the PostHog app doesn't share much of the fun branding elements that we use on our website.

A simple way to make website + app feel a little more connected to be to use some light hogs in unobtrusive places. Ideas:

- Hedgehogs in upsells, modals, error states
- Deskhogs, plants, office elements
- Loading states

Anything we add should be subtle and not make the app feel visually tired after a few months. It might be a difficult line to walk, but I'd love to see if we can explore some ideas to bring some light branding into the app.

**Comment by corywatilo** [comment]
@clarkus @lottiecoxon Maybe this is something you can work together on when time allows?

**Comment by clarkus** [comment]
I like this idea, but I agree it's a fine line to walk. I think the balance should be generally "serious business" but with some places where "work is fun". Generally I think the places to expose some personality while still maintaining that fun but serious vibe are:

- Authentication screens - signing in, registering, etc. These screens are often sparse and benefit from something that takes up space or balances an otherwise boring form
- Loading states - definitely think that these are prime for hedgehogification
- Upsells could work, but we have to balance things here. Upsells can show up in a lot of places, so there's a good deal of variety to contend with
- In-product announcements of exciting stuff - app updates, new releases, etc. These often take the form of in-product banners
- Default avatars for users - Right now we have generic letter-marks as placeholders for user avatars. If we had a set to pick from, users could personalize their profile with some hog flare. Note we'd need to introduce some new functionality to make this possible.
- Emails - our product doesn't send any emails unless someone joins the organization. I think it's generally an underutilized interface for the product. Having some email templates with a bit of personality could be very useful. 
- I'll try to think of more ideas

**Comment by lottiecoxon** [comment]
![cloud page](https://user-images.githubusercontent.com/65415371/154090186-9951de15-393a-4bf1-b56a-e7826fe8980b.jpg)

https://user-images.githubusercontent.com/65415371/154090246-c0ba0f44-12b9-4c65-a129-149c7cd69bd2.mov

**Comment by lottiecoxon** [comment]
Potential loading sign?

https://user-images.githubusercontent.com/65415371/154091561-dc4f9c90-4405-4ef0-80b1-b637be6daff1.mov

**Comment by lottiecoxon** [comment]
Announcements :
![Untitled_Artwork 498](https://user-images.githubusercontent.com/65415371/154096382-a4fb1eae-5dc4-41e7-953c-1ac2d64c11e9.jpg)
![Untitled_Artwork 499](https://user-images.githubusercontent.com/65415371/154096404-c8bc439c-2485-4838-a46c-ca4713948dc4.jpg)

**Comment by lottiecoxon** [comment]
Idea for avatar maker
![Untitled_Artwork 500](https://user-images.githubusercontent.com/65415371/154098299-44d447b8-6278-428c-8399-e9222b87d3ff.jpg)

**Comment by clarkus** [comment]
@lottiecoxon I linked you to a few screens in figma that correspond to the list above. 

I think the work above is a great start. I'd be game or trying to authentication screen updates in an upcoming sprint if you are. We'd need to coordinate with an engineer to ensure animation and assets are implemented in a scalable way. 

The announcement illustration seem like they could be really great for in-product or email announcements. We don't do those yet, but having something ready to use would be great. 

We're currently working to test how collaboration features impact user discoveries. Longer term this work could bring a user profile into scope. That would be an ideal place to let users pick a hoggy avatar. It doesn't exist yet, but a set of avatars to pick from could be handy.

**Comment by lottiecoxon** [comment]
For a loading animation I am torn between adding in some fun character (at the risk of being too small to see) or doing something more geometric and graph-y (at the risk of lacking character). I tried a walking max but his small feet won't show up when very small. I thought a waving one instead? 

But not committing to full artwork yet to save time.
![Untitled_Artwork 13](https://user-images.githubusercontent.com/65415371/156397475-3e0f26a5-9dc2-4308-aad8-cfe4592e0802.gif)
Will experiment with some other graph based ones tomorrow

**Comment by clarkus** [comment]
I really like that simple animation. The interface is basically made of rectangles, so having something that can work with a sharp edge like this could scale pretty well. It might be worth trying in context just to assess if it feels complimentary to the interface or too disruptive. I like where you're going with the changes for sure. Thanks, @lottiecoxon

**Comment by clarkus** [comment]
Oh also, I think if we can inject some personality (hedgehogs) we should. A lot of the product is serious business™ right now, so this would really bring some of that "work can be fun" feeling to the interface. Something more geometric with less personality wouldn't be as successful I think. All that said, I'm game to try any ideas you come up with.

**Comment by lottiecoxon** [comment]
Seeing as I've been temporarily moved over to the product side - I am going to close this issue and make a new one with the relevant info and references on it as this one will get too long

**Comment by kingabnt** [comment]
#fixed
