### ISSUE TITLE
Integration with github/gitlab to automatically add annotations for new commits/deploys

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#872]
Relies on #708

It'd be awesome to automatically push commits/releases of an app into PostHog, so you can easily see what commits may have changed the outcome in the graphs.

An open questions remains: how do we make sure this doesn't become noisy.
- For some companies who have structured releases (like us) only putting in "releases" probably make sense.
- For companies that only deploy once a week/month, it might make sense to have 'deployments'
- For companies that do continuous deployments, showing all commits as annotations might be too granular. Should we sort by LoC's as a proxy for how big the change was?

cc @EDsCODE

**Comment by jamesefhawkins** [comment]
I cannot wait to see this!

>For some companies who have structured releases (like us) only putting in "releases" probably make sense.

This makes sense - all the functionality comes out at the same time. 

> For companies that only deploy once a week/month, it might make sense to have 'deployments'

Yes. What _exactly_ do you mean by a deployment in this use case - a PR being merged?

> For companies that do continuous deployments, showing all commits as annotations might be too granular. Should we sort by LoC's as a proxy for how big the change was?

I think going to commit level by default is too granular. Pull Request level makes more sense - the use case here is to work out which change to teh code caused a change in user behavior. Since commits may be grouped into 1 PR, it could be *any* of the commits in that PR which could have caused ie the app to break for some users or for a conversion rate to improve.

IMO it's a nice to have to go to commit level, but not a must have, and it may make things harder to understand for users as there could be 20 commits in one PR, and there could be 12 PRs merged on one day.

As a seperate ticket, since it's scope creep, it'd be nice to provide some level of filtering of all their github data at perhaps a dashboard level? ie only to show commits in certain repos, by certain people, touching certain files, etc

**Comment by EDsCODE** [comment]
Below is a picture of a graph with all the recent commits to master which constitute all the merged pull requests. Even for us this seems way too granular. I think it may be a better experience providing users with a page where they can manage their annotations and on this page if they linked github they can choose which annotations to appear on graphs. Otherwise commit/PR frequency is so different from team to team it may be difficult to standardize what goes in and what stays out. Will keep experimenting..

<img width="1293" alt="Screen Shot 2020-07-02 at 2 22 46 PM" src="https://user-images.githubusercontent.com/13127476/86396582-2d43d280-bc70-11ea-9521-8ef68ed02c2d.png">

**Comment by EDsCODE** [comment]
Blocker: 
Determining commit criteria is sloppy. LoC would be a decent indicator but github api is limited at 5,000 requests per hour and you need to make a separate request per commit after listing commits to find that information. Large projects would need a very involved importing pipeline for a weak indicator. 

Some thoughts:
- give user ability to sift through commits and choose ones that are shown
- start tracking commits/data from the day the git integration is added

**Comment by timgl** [comment]
Instead of trying tot filter, maybe sort by LoC for each day? That'll at least surface the biggest ones first, then people can do their own mental filtering.

For GitHub, it might be worth having a look at their GraphQL api. It might allow you to pull LoCs without doing separate requests. I'm really not concerned about historical data, worth getting a first version out and seeing if anyone uses it

**Comment by mariusandra** [comment]
What about encouraging good development practices and showing pull requests (closed_at) instead of commits?

https://developer.github.com/v3/pulls/

**Comment by paolodamico** [comment]
I believe this can now be accomplished with plugins. Ok to close?

**Comment by Twixes** [comment]
AFAIK we haven't really seen a need for this among users yet, and if we do, then indeed we could create a plugin pretty simply even with current capabilities, so I'll go ahead and close
