### ISSUE TITLE
Consolidating Engineering Handbook in a single place

### ISSUE THREAD

**Issue by paolodamico** [PostHog/posthog#8721]
Actionable from Engineering Offsite.

**Comment by tiina303** [comment]
To expand on the problem we have some content in docs and other in handbook and this makes things hard to find
1. [architecture](https://posthog.com/docs/self-host/architecture) in docs, [ingestion overview](https://posthog.com/handbook/engineering/event-ingestion) in handbook
2. async migrations have docs on both sides

Instead of this weird split I'd love all of that to be together & more easily discoverable/findable to both us and self-hosted users and collaborators.

**Comment by Twixes** [comment]
Should be done now (I think).

**Comment by tiina303** [comment]
I wouldn't say it's done. Specifically the problem between docs / handbook -> engineering having content that's useful for self-hosted folks / more technical users. cc @corywatilo we very briefly talked about this during the Iceland offsite.

**Comment by Twixes** [comment]
Ah, well, let's leave open then.

**Comment by Twixes** [comment]
I'm not actually sure what's the scope here. Do you have any actionables @tiina303 (or anyone else)? Otherwise I'm going to close this.

**Comment by tiina303** [comment]
I brought two examples in my comment.
The general idea was that anything that's technical is relevant to self hosted folks or contributors, but looking into handbook seems unintuitive/unexpected. If I'm searching for something it's confusing / hard to know which side it's on. I was hoping the docs/website team would have ideas for what this should be like.
