### ISSUE TITLE
Issues surrounding async migrations

### ISSUE THREAD

**Issue by macobo** [PostHog/posthog#8804]
## Is your feature request related to a problem?

I've been the "biggest" consumer of async migrations so far given that trying to build towards https://github.com/PostHog/product-internal/pull/240 depends on it quite heavily.

Grab bag list of issues in no particular order
1. `Migration.operations` - async migrations assume it'll be a static list. In practice 2/3 migrations need some degree of dynamic behavior, and I foresee this being the case in the majority of cases. This breaks both "current_operation" logic (making it problematic if the list can change) and error handling in cases where `.operations` is read without proper error handling. 
2. SQL interpolation over using sql arguments even in cases where it could be used due to API of `AsyncMigrationOperation.simple_op`
3. `query_id` logic and `execute_op_*` functions are suspect and should be removed/refactored.
    - It opts to reinvent the wheel instead of using the existing mechanism for hooking into query comments
    - `execute_op_postgres` is not needed and might never be - premature optimization
    - They are not used everywhere in the migrations making them kind of pointless from a tracking standpoint as `sync_execute` gets used.
    - The exception catching/unwrapping is a bad idea as it makes debugging hell - I have a git stash I need to use to make using these tools bearable.
4. Rollback logic is not well thought out. For schema statements like `CREATE TABLE`, the rollback often is `DROP TABLE` which won't succeed if the same step failed e.g. due to a zk path conflict.
5. Suboptimal data structures make debugging hard. Examples:
    - `AsyncMigrationOperation.simple_op` should be a data class for easy introspectivity of what the SQL looks like
    - `#precheck` returning tuple of `(success, optional_error_message)` over `Success() | PrecheckError()`
6. Lack of proper CLI tooling for development/testing. Being able to run/roll back migrations via CLI makes the debug loop much more convenient - celery is not a good tool for development.
7. Non-technical: Users path to getting async migrations done with has historically been something that has caused a ton of back-and-forth.
8. Async migrations render clickhouse migrations useless.
    - Now we have async migrations there's very little possibility to ever write clickhouse migrations to change existing tables as they will likely depend on async migrations having been run.
    - We can't also move existing clickhouse migrations to be async migrations since they will not be autorun.
    - Ultimately the user suffers here since they won't automatically get some cheaper migrations.

## Additional context

@yakkomajuri asked me to document issues that have popped up around async migrations and how we could improve them. Doing so in this issue.

cc @tiina303 as well.

**Comment by yakkomajuri** [comment]
A few of these are no-brainer fixes and a few are nits.

Given we have a sync discussion very soon, I believe we should prioritize the topics where some collective thinking is needed:

1. #8691 
2. (8) Async migrations render clickhouse migrations useless (related to the point above)
3. Perhaps (4) Rollback logic

As for the rest, we should strongly prioritize 1, 2, and 4. And then 6 comes after.

3 and 5 are mostly nits. And given user feedback from 1.33.0, 7 is not really a problem.

**Comment by tiina303** [comment]
Thank you for writing this up :)

> 1. Migration.operations - async migrations assume it'll be a static list

I'm working on this already https://github.com/PostHog/posthog/pull/8510 & will finish it to reduce WIP, but didn't manage to get it out before the release freeze.

> 2 & 3 & 5 - how should we interface executing ops & SQL interpolation & making debugging easy

Karl - once you're done with your WIP stuff could we have a quick discussion around what your ideal solution here would be to make sure we address everything from both sides.

> 4. Rollback logic

We discussed this in our sync meeting. A step with single CH sql doesn't get updated to the next `current_operation_index` if (1) CH is down (2) the CH sql statement fails (3) postgres update didn't work (e.g. postgres is down, celery died in after CH sql but before postgres update). In some case we should run the rollback (3), in others we shouldn't (1), (2). We currently run the rollback for the same step. The plan is to see how complicated it is to make all rollbacks safe to be ran if the step was done or not & follow-up from there to prioritize finding a solution or not. (correct me if I got something wrong here from our sync).

> 8. CH migrations useless

we discussed this in sync. The upgrade path plan is to run check for async migrations first and then Django & CH migrations, so we can relay on async migrations having been done if the max version was set. That said due to CH migrations swallowing errors we might prefer writing async migrations anyway, will leave this for Karl to decide what's best.

> autorunning migrations

My proposal in the sync was lets wait and see and decide later once the system has been in place for a bit longer & we're more confident about the stability.
