### ISSUE TITLE
Concept: Insight editor panels

### ISSUE THREAD

**Issue by clarkus** [PostHog/posthog#8929]
## Is your feature request related to a problem?

Our insight editing views are somewhat inconsistent, which isn't a problem necessarily, but as we add new more powerful features, we need to revisit layouts and readjust to optimize for the overall experience using a feature set. An example of this is the upcoming logical operators for filter groups. This is a very powerful and much-requested feature, but it is complicated. It can easily overwhelm other features just because of its place relative to the required fields. This is compounded when we add options specific to each insight type - paths advanced options and funnels come to mind. 

## Describe the solution you'd like

Let's optimize the layout for a variety of viewport sizes by making the editing components completely conditional to the display of the page. There are existing cases where we use panels, but I feel like this is possibly the strongest argument to use them yet because the panel directly impacts the display of the underlying content in real time as edits are made. 

There are still cases where a panel won't work well, but they are in viewport sizes that are already showing insight editors in non-ideal layouts. These changes would make it possible to conditionally show pertinent sections for the insight which would reduce the overall height of the container. This could lead to more focused editing and a bit more robustness across viewport sizes. 

A quick illustration of the [concept](https://www.figma.com/file/NHPA2hVWwaKp4eTGWdigs9/Product-Concepts?node-id=1506%3A24827) in figma

Panels would be placed fixed to the top, right, and bottom viewport edges. As the contents of the editor are revealed, the panel will scroll to access content outside the viewport area. A user can also collapse and expand sections to fit more content into the viewport area. 

<img width="1112" alt="Screen Shot 2022-03-08 at 12 48 20 PM" src="https://user-images.githubusercontent.com/254612/157324983-06703d18-4fdc-4b9b-b063-d0f40fe4d736.png">

Editors in varying states 

![editor panels](https://user-images.githubusercontent.com/254612/157325928-083640ab-9b0b-4724-b353-20e2b1e69851.png)

## Describe alternatives you've considered

This doesn't have to be in a panel. The same separation of editor contents into collapsible sections could be inserted above the insight results to make editing compete less with viewing results. 

Quick illustrations of how this could play out at various viewport sizes and navigation states. 

![wider screen side by side collapsed nav](https://user-images.githubusercontent.com/254612/157335414-784c6aec-f9d0-4996-9f2a-99c5d51f52cd.png)
![side by side collapsed nav](https://user-images.githubusercontent.com/254612/157335418-2f91b2ff-a178-4854-bdbb-57c13c0f36dd.png)
![wider screen side by side](https://user-images.githubusercontent.com/254612/157335419-2b6c65df-d54e-4d1e-998e-7b472d67fbb6.png)
![editor groups above the result](https://user-images.githubusercontent.com/254612/157335421-e9dcf737-376c-42e7-ace6-6e36e83f0220.png)

## Additional context

- This is just an idea for discussion. It'll need more revisions and information to be fully realized. The goal here was to draw enough of the solution to see if it sparks ideas for quick wins, or possibly a longer term change.

**Comment by mariusandra** [comment]
I think these panels improve clarity quite a lot in many ways. My only (totally addressable?) concern is that what used to take one click, might now take 3 clicks. Instead of e.g. updating a filter, we now need to open a panel, edit the filter, then close the panel to see the changes. Even if the graph updates below the panel, the panel will still be in the way of you seeing all the changes.

The way around this is to support "pinning" panels. Kind of like in gmail when composing a mail, you can either use a full screen modal to compose your message, or you can pin it to the bottom-right of the screen.  I'm imagining something a little bit different here though.

I'd take this mockup:

<img width="1112" alt="Screen Shot 2022-03-08 at 12 48 20 PM" src="https://user-images.githubusercontent.com/254612/157324983-06703d18-4fdc-4b9b-b063-d0f40fe4d736.png">

... and add a little "pin" or "sticky" icon to the top-right, after "edit insight". When enabled, it would toggle between the panel floating above the content, and the panel being a permanent part of the page, leaving the graph to take up whatever space remains.

This behaviour could change depending on the resolution. E.g. if there's really no space on a tiny Amazon Fire tablet, you can only use a floating panel.

**Comment by clarkus** [comment]
> I think these panels improve clarity quite a lot in many ways. My only (totally addressable?) concern is that what used to take one click, might now take 3 clicks. Instead of e.g. updating a filter, we now need to open a panel, edit the filter, then close the panel to see the changes. Even if the graph updates below the panel, the panel will still be in the way of you seeing all the changes.

This could be true in some cases, but one thing I didn't cover here was default states, which would eliminate some concerns. Each insight has sections within the builder components - some are completely optional, while others are required to render a result. The workflow for creating would default to showing the required sections as open. This is really the core change as it makes the height of the overall builder directly controllable by the user. If they prefer to see everything, it's a click to expand and see. If not, they can collapse and focus on results. There's no need to collapse to see updates to the insight results. 

For the column and pinning, those are cool ideas to try. I do think some variable positioned builder could be powerful, but I'm not sure. Appreciate the feedback! Will keep iterating as time permits to see if we can balance defaults with the need to toggle section visibility often. A lot of this depends on the complexity of the elements in each section and minimum dimensions to be usable. I'm chasing a min width of 320px, but things are tight. More to come!
