### ISSUE TITLE
Do we need to make UX changes along with the new insight URL change

### ISSUE THREAD

**Issue by rcmarron** [PostHog/posthog#8989]
## Problem

In a recent change, we updated the behavior of the insight URL. Now, insight URLs look like:

https://app.posthog.com/insights/cfHPyAO6/edit

Instead of:

https://app.posthog.com/insights/cfHPyAO6/edit#filters=%7B%22insight%22%3A%22FUNNELS%22%2C%22actions%22%3A%5B%5D%2C%22events%22%3A%5B%7B%22id%22%3A%22user%20signed%20up%22%2C%22name%22%3A%22user%20signed%20up%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%2C%22properties%22%3A%5B%5D%7D%2C%7B%22id%22%3A%22first%20team%20event%20ingested%22%2C%22type%22%3A%22events%22%2C%22order%22%3A1%2C%22name%22%3A%22first%20team%20event%20ingested%22%7D%2C%7B%22id%22%3A%22insight%20analyzed%22%2C%22type%22%3A%22events%22%2C%22order%22%3A2%2C%22name%22%3A%22insight%20analyzed%22%7D%5D%2C%22display%22%3A%22FunnelViz%22%2C%22interval%22%3A%22day%22%2C%22properties%22%3A%7B%22type%22%3A%22AND%22%2C%22values%22%3A%5B%5D%7D%2C%22filter_test_accounts%22%3Atrue%2C%22funnel_viz_type%22%3A%22steps%22%2C%22exclusions%22%3A%5B%5D%7D

The fundamental change is that we used to store unsaved insight data in the URL, so the URL behaved like a "soft save". 

To a user this means the following:
1. I used to be able to create an insight, make some changes, not save it, share the link, and my colleague would see the changes. Now If you don't save the insight, it doesn't show your changes.
2. If I open an old URL that had "unsaved data" stored in it, the experience is the following:
      1. Open URL with unsaved filters
      2. The unsaved data from the URL is applied to the insight
      3. The URL is updated to not include the unsaved data. So it's the new format.
      4. A toast message appears prompting the user to save their insight
      5. At this point, if the user were to copy the new updated URL and open the page, the insight would look different because the unsaved changes would not be seen. However, if they copied their original URL, the insight would show as expected, and the toast would prompt them to save it again.
      
A few questions:
1. Do we need to make the unsaved state more prominent - now that the "soft url save" is no longer a thing?
2. Do we want to explicitly explain this URL change to users? Maybe if they're still using the old style URLs?
3. Are we happy with the experience of opening an old URL described above? Or should we be more explicit in what's happening there

**Comment by rcmarron** [comment]
cc @clarkus @mariusandra @Twixes

**Comment by clarkus** [comment]
> ii. The unsaved data from the URL is applied to the insight

I'm not sure this is a good thing. It actively works against the idea of "you have to save your work in order to share it". It's not obvious there are pending changes because they apply silently. Do we need to do this? If so, I think we need to be clear about what's happening and communicate that it is a SHORT TERM solution. Otherwise it feels like we still support soft saves to the URL just via a different workflow. 

Here's an alternate idea - if a user visits a URL loaded with parameters and these soft changes, what if we prompt the user to apply changes? That would make it such that we can:
1) say very clearly that you have to save insights in order to make work shareable 
2) clarify how this transition is working - you can choose to apply soft changes this time, but also know that this is a short term migration solution to make the changes less disruptive. Longer term, if you don't save work you can't share it in this temporary format. 

> Do we need to make the unsaved state more prominent - now that the "soft url save" is no longer a thing?

Can we quantify the number of users working this way currently? That would inform how aggressive our messaging needs to be. I feel like we can lean on what we have now, but this was a really confusing model to begin with. I think the expectation from most users is that you need to save work in order to share it and make it permanent. Temporary changes are lost when you navigate away from pages. We could prompt a user at this even point to save their work, but it might get annoying. As. an example - a dialog that says "You have unsaved changes. Navigating away from this page will discard those changes. Are you sure you want to do this?" 

I do think `discard changes` is the wrong label for the page level actions. We should change to a secondary `cancel` action to align with our other transactional workflows. 

> Do we want to explicitly explain this URL change to users? Maybe if they're still using the old style URLs?

Depends on the count of users impacted by the change. I'm in favor of obvious communication if we can do that. This might even be something that we communicate outside the product to get ahead of possible user frustration. 

> Are we happy with the experience of opening an old URL described above? Or should we be more explicit in what's happening there

I think we need to push users towards the updated, more obvious model introduced here. The job to be done is educating users that saving is required to share work. Everything else feels like a shorter-term migration effort to help transition, but still push them towards the new model.

**Comment by mariusandra** [comment]
> ii. The unsaved data from the URL is applied to the insight

This is only a temporary stopgap to not break any existing links. We should start measuring if and how often this is used.

> Here's an alternate idea - if a user visits a URL loaded with parameters and these soft changes, what if we prompt the user to apply changes? That would make it such that we can:

I think using a prompt will disrupt users a lot. This is a question you're not expecting to face -> the platform should figure this out on its own.

> Can we quantify the number of users working this way currently? That would inform how aggressive our messaging needs to be.

I think it's hard to get meaningful data. I think users will learn the new behaviour very quickly, and be thankful for it.

I suggest in the interim we use a large alert to show that you have unsaved changes. Something like this:
https://github.com/PostHog/posthog/pull/8993

**Comment by clarkus** [comment]
If I can get to the same insight via multiple URLs and those urls render the insight differently it's going to be really confusing. A prompt might be disruptive, but at least it's clear and obvious. It's hard to make decisions in the absence of data, so I'm just advocating for what would be the most obvious for users.

**Comment by rcmarron** [comment]
> A prompt might be disruptive, but at least it's clear and obvious. It's hard to make decisions in the absence of data, so I'm just advocating for what would be the most obvious for users.

What about something that's super clear and obvious but doesn't fundamentally change the behavior for the user. I'm thinking the experience is something like:
* I open my bookmarked insight that has unsaved information in the URL
* I see the same data as I did last week (with the unsaved filters applied)
* There's an obvious banner/warning/something else stating:

```
This insight had unsaved information stored in the URL. Please click save it to avoid loosing data.

Why? We recently changed how insight URLs work to make the experience more reliable. Information about the insight, is no longer stored in the URL. Rather, it must be saved directly to the insight.
```

**Comment by Twixes** [comment]
This should be improved with a few new mechanisms:

- it's more prominent whether there are unsaved changes (there is no "Save" button without changes)
- there's a prompt preventing accidentally discarding changes to reinforce that URLs no longer store the definition
- also, we'll see less and less old-style URLs as time goes on

I'm not 100% sure this resolves all concerns from this thread, so feel free to reopen if not, but I don't think it's worth investing that much more time into handling a case that is going to be seen less and less.
