### ISSUE TITLE
Refactor various table components to be reusable

### ISSUE THREAD

**Issue by alexkim205** [PostHog/posthog#9035]
## Describe the solution you'd like

We've added a lot of functionality to our tables and a lot of our code has been consolidated with the introduction of Lemon tables. Features that are pretty tightly coupled to table views (below) are disparate throughout our code, and it'd be nice to either extend the LemonTable api or create Lemony components that can be used with LemonTable in a nice devX-y way. This also ensures we're not reinventing the wheel every time we want to add similar functionality to other tables.

- Filtering (with quick actions for clearing filters)
- Column configuration
- Exporting
- List and card view toggles

**Comment by clarkus** [comment]
Clarification - I think this should be a closely related, but separate component because we have other lists that aren't tables that could benefit from this same functionality. I think of it more as data table / card list utility actions. If we bake it into the table component, it could become too tightly coupled and not scale for some views.

**Comment by clarkus** [comment]
Related - https://github.com/PostHog/posthog/issues/9084
