### ISSUE TITLE
[Epic] Integrations

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#906]
For the phase 2 roadmap we want to make PostHog super extensible. This is partly through APIs, but we also want a long list of things we integrate with.

## Data out
- Generic
  - [x] Zapier (this might be worth prioritising as it automatically gives us 100s of integrations)
  - [x] Webhooks
- Data warehouses
  - [x] S3
  - [x] GCS
  - [x] BigQuery
  - [x] Snowflake
  - [x] Redshift
- Email/messaging
  - [ ] Mailchimp
  - [ ] Twilio
  - [ ] Hubspot?
- Ads? (Tag an action as a 'conversion' event for example)
  - [ ] Google
  - [ ] Facebook
  - [ ] Twitter

## Data in
- [x] Segment #929

**Comment by jamesefhawkins** [comment]
I'd add to Data In:

- [ ] Segment


I think in terms of the priorities, it makes sense to do Zapier and Webhooks first. These would allow us to write many tutorials in the docs around dozens of use cases.

**Comment by rushabhnagda11** [comment]
I would love to help out here. Few reasons that I hope make my case stronger. Let me know.

1. I actually use PostHog in Zapier. Since there's no official PostHog Zapier connector, we've integrated through it through the Code option. Basically when X trigger/event happens, please send the event to postHog so that we can track it.
2. I've recently published a zapier plugin for my own company
3. I've also contributed to the posthig-js library -> https://github.com/PostHog/posthog-js/pull/34 (admittedly in a small way)

**Comment by jamesefhawkins** [comment]
This would be amazing. Which part of this epic do you think would make sense to start with?

**Comment by rushabhnagda11** [comment]
I believe the generic integrations provide the most value. I think adding a Zapier connector would be a great start since it'll expose a ton of upstream and downstream connectors to integrate with.

I can also picture some of the email/messaging use cases being implemented via Zapier itself.

**Comment by jamesefhawkins** [comment]
That makes total sense. If you fancy pairing on this or need help at any point, just reach out!

**Comment by rushabhnagda11** [comment]
Awesome! If there's anything, I'll reach out :)

**Comment by Twixes** [comment]
I'm taking over integrations, starting with Zapier. A few things:
1. We're going to need authentication. The addition of a read-write API key to the current read-only one is probably the most fitting here. We could do a fancy OAuth flow too, but that would probably be overkill.
2. This will only work for the `app.posthog.com` instance. We can make it easier for self-deploying users to set up a private Zapier app by publishing docs though. (considered a central directory of self-deployed PostHog instances and routing Zapier requests through that, but that'd be quite unfeasible)
3. 1 Trigger: "Action Performed" + 1 Action: "Capture Event". Is there anything more we should cover?

**Comment by rankengine** [comment]
@Twixes I'm not sure if you are planning on covering this or not, but it would be awesome to have a way for PostHog events to trigger other actions such as sending emails.

For example, I would love to have the ability to have a key event, trigger some communications with our users.

If a user performs a key milestone, we could reach out to congratulate them.

Or if a user hasn't activated in a set period of time passed, then we can send an email to (or from) our customer success team to see if they are hitting any obstacles and need help.

We currently use ActiveCampaign and Intercom, but being able to connect it to any email communications would be really helpful. Thanks!

**Comment by Twixes** [comment]
Sure! The idea is to have a Zapier `Action Performed` trigger, enabling you to process PostHog Action information on that trigger with another Zapier app, e.g. Email by Zapier. You can create an Action from any singular Event or a series of them, so that's your use case right there.

**Comment by hgezim** [comment]
Is the current Zapier app (in beta) not made by PostHog?

Zapier integration was a huge selling point before I started using PostHog. I actually saw it as an option in Zapier and was sold.

**Comment by Twixes** [comment]
Hey, yep! We went through two major re-architectures of our system lately (high perf ClickHouse database backend instead of Postgres + multiple projects and organizations instead of users being part of at most one project), which affected our integrations. Still ironing out some imperfections, but we're nearing bringing back 100% functionality.

Update: We're 100% operational!

**Comment by samwinslow** [comment]
Is this issue still active? A user is interested in adding the ability to send to multiple webhooks, instead of just one. (Their use case is sending to different Slack hooks which each post to a different Slack channel).

I pointed this person in the direction of sending everything to Zapier and doing the routing there, but it still seems likely that someone would want to hit multiple endpoints.

**Comment by Twixes** [comment]
I think this can be closed now – we can export to lots of warehouses using plugins now, we are integrated with Segment, and Zapier allows for connecting to thousands of other apps, so we're in a pretty good spot. For further enhancements, I think individual issues will be better trackable. :)
That'd be a reasonably simple feature @samwinslow but would require a migration of the webhook system to allow selection of a specific webhook, as opposed to the current project-based system. I suggest creating an issue and maybe we will end up building that, but I do think that Zapier fulfills the need pretty well in the meantime.

**Comment by xpiREC** [comment]
I also suggest adding support to list to-do for Reddit conversion.
