### ISSUE TITLE
[Funnels] Remove preview pane before a 2nd step is added?

### ISSUE THREAD

**Issue by corywatilo** [PostHog/posthog#9115]
On the initial funnels view, there are two "Add step" buttons. As a new user, I'm not sure if I should click the one in the query builder, or the one in the results column. (This initial view also just feels a little overwhelming.)

<img width="1384" alt="image" src="https://user-images.githubusercontent.com/154479/159036662-6c2175a5-02fd-46fc-9648-c35c9c9852a3.png">

We should direct people toward the query builder, since that's the standard interaction for building a query throughout different insights views.

## Suggestions:

1. Remove the results pane until a 2nd step is added. (It's unlikely the first thing you're going to do is change the date range, so this isn't needed yet.)
2. Render the pane but show some non-animated skeleton state, indicating "this is where data will be once we have something to show".
3. Drastically fade out the right column to make it look disabled (and kill the button in the results pane).

**Comment by mariusandra** [comment]
We're likely moving to something like this as well: https://github.com/PostHog/posthog/issues/8929

**Comment by clarkus** [comment]
> On the initial funnels view, there are two "Add step" buttons. As a new user, I'm not sure if I should click the one in the query builder, or the one in the results column. (This initial view also just feels a little overwhelming.)

They're really the same action - as long as a user clicks one, they can recover from the empty state. The other option would be to have two funnel steps as a default, but it's hard to know what those values should be. It could be any pageview followed by any pageview, but then a user might be confusing, too. 

> Remove the results pane until a 2nd step is added. (It's unlikely the first thing you're going to do is change the date range, so this isn't needed yet.)

I don't think we should do this. All other insights have a default chart view because they require a single query builder parameter to render a result. Funnels are an exception because they require two steps. 

> Render the pane but show some non-animated skeleton state, indicating "this is where data will be once we have something to show".

This is what the empty state is doing now. It just also offers the action in context to recover from the issue. 

> Drastically fade out the right column to make it look disabled (and kill the button in the results pane).

This would make it hard to understand what you need to do to recover from the issue. I'd rather show the empty state with clear content on how to recover. 

I feel like we should do some research to inform this problem. I agree that the screen is busy, but I don't think the empty state is the core issue.
