### ISSUE TITLE
$initial_current_url gets overriden in subsequent pageview

### ISSUE THREAD

**Issue by aantn** [PostHog/posthog#9157]
## Bug description

A user browses to my site. The InitialCurrentUrl is set correctly and preserved on other events in the same session.

The user leaves, returns later, and the new $pageview overrides the InitialCurrentUrl.

Later on I cannot use InitialCurrentUrl to figure out where the user initially came from.

## Expected behavior
InitialCurrentUrl should never change once set.

## How to reproduce

1. Be me
2. Log in to my posthog site and view one of the problematic users

Or just tell me what details you need to check this. Id? DistinctId?

## Environment

- [x] PostHog Cloud

**Comment by tiina303** [comment]
This happens because of the way we merge users, which is unfortunately not optimal at the moment. 

At ingestion time `alias`/`identify` upon property name conflict uses the value from person 1. (doc: https://posthog.com/docs/integrate/user-properties but the future strategy there is actually something we're re-iterating on currently, so that might not be what we'll end up with).
alias and identify are the same.
The identify call by default is set up (in JS library / our backend) in the way that the anonymous user properties would override the existing person properties (historical reasons, the anonymous user is newer so we kind of want to use their properties most of the times).

**Comment by tiina303** [comment]
Related issue https://github.com/PostHog/posthog/issues/7710

**Comment by aantn** [comment]
In my case the anonymous user *should* arrive first and only later do they login. In that case I wouldn't be hitting that bug, no?

Regardless, I'll check the data further on my end.

Is there anything I can do to workaround this for now? I'd really, really like to preserve that $initial_current_url. Maybe I could copy it over to some other property?

**Comment by tiina303** [comment]
> In my case the anonymous user should arrive first and only later do they login. In that case I wouldn't be hitting that bug, no?

Correct. If it's the first ever login for this individual then the initial url we have in the anonymous user would be applied to the identified user (that previously didn't exist and hence didn't have that value).

> Is there anything I can do to workaround this for now? I'd really, really like to preserve that $initial_current_url. Maybe I could copy it over to some other property?

Since the problem comes from merging, what you could do is `set_once` (so the value wouldn't be overridden in the future) a special property (making sure the anonymous or any other user that gets merged wouldn't have that property set) within the identify event ([js lib](https://posthog.com/docs/integrate/client/js#identifying-users)).
```
posthog.identify('bob', {}, {keep_initial_value_property: value})
```

**Comment by aantn** [comment]
Looks like the issue for us is different. The referrer is getting overriden whenever the user switches subdomains. For example:

1. User gets referred to a.example.com via google. The referrer is google
2. User clicks a link taking her from a.example.com to b.example.com. The refrrer is not b.

**Comment by aantn** [comment]
You can see an example of this in the subsequent events with IDs 017fe0a8-0755-0000-ec9a-71c79a1c5134 and 017fe0a8-0c41-0000-57a8-4d8f2e9d8957 on the hosted posthog server.

**Comment by tiina303** [comment]
Hi @aantn  sorry just getting back to this.

Looked into the ordering for identify again and I was either wrong before or we changed it since, but regardless we're using the identified person's properties on conflicts. However I will note that if events arrive very close together then they could be processed in any order (e.g. network delay causes an earlier sent event to arrive later). This could mean that a `set_once` property from a later call is processed first and since we still don't use timestamps that property would not be overridden when an earlier timestamped event is processed later (set_once only updates the value if it isn't there in the current implementation of person properties updates).

I looked at the person you're referring to and their first events: https://app.posthog.com/person/17fe0a763f61fd-02779ec6b2eb5-9771a39-1fa400-17fe0a763f7afe#activeTab=events
The oldest event there sets the initial referrer url to be `$direct` which we can see is the person person property currently.

Could you elaborate on this specific example - what would you expect to see for this person?

**Comment by aantn** [comment]
Hey, it's been some time so I don't remember exactly what I was referring to.

For that person, shouldn't "Initial Current URL" remain constant throughout the person's history?

**Comment by tiina303** [comment]
> For that person, shouldn't "Initial Current URL" remain constant throughout the person's history?

It did from what I could see.
> The oldest event there sets the initial referrer url to be $direct which we can see is the person person property currently.

**Comment by tiina303** [comment]
Initial referrer problem is discussed here https://github.com/PostHog/posthog-js/issues/419 initial current url seems to work as expected.

**Comment by pstoica** [comment]
Sorry to dig up an old issue, but I think i've been seeing the same behavior as @aantn.

An example person: [62016535-875c-46c4-8d62-23345db3a9d0](https://app.posthog.com/person/18649b6f7fc1a6f-061045ac2c0edf-1f525634-1d73c0-18649b6f7fd25d5#activeTab=properties)

We also have two subdomains, marketing site vs app. Once someone logins in through Auth0, their initial current URL and referrers get completely replaced. But the first events on the marketing site set the correct initial values.

**Comment by tiina303** [comment]
could you give me your project ID and if you're on US or EU cloud?
And what version of the posthog-js lib are you using?

**Comment by pstoica** [comment]
Sure, I'm US-based and the ID is `8442`.
My app is `1.36.1`, and the marketing sites have `1.43.1`. In this sequence I have one server-side event using RudderStack `2.0.0`; I figured these would come later and not cause the race condition.

**Comment by tiina303** [comment]
I think this is happening because we currently have buffer enabled still enabled by default for everyone (which messes with the order of events processing). I'll 👀 to enable it only for the teams that need it.

**Comment by tiina303** [comment]
but know that there isn't a guarantee of event processing order currently, but it will more probably work. We do property updates at ingestion time, ignoring event timestamps (as there isn't a reasonable way to do that without killing Postgres yet)

**Comment by MappyLiam** [comment]
Hi @tiina303,

I came across your [PR](https://github.com/PostHog/posthog/pull/14612) regarding the default disabling of the buffer. I'm currently experiencing an issue related to this while using Posthog Cloud.

I've noticed that some of my users are able to retain their initial referrer, initial Current URL, and other information, while others cannot. The discrepancy seems to be linked to the Merge restriction of the users. Those with the restriction set to 'applied' preserve the initial information, whereas those with 'none' do not. Therefore, it appears that the absence of a processing order guarantee, as you mentioned, is causing this issue due to out-of-order registration of events.

I don't possess a deep understanding of the event processing process in Posthog. So my opinion may sound unclear or nonsense. But let me try.
If utilizing event timestamp querying to ensure order will have a detrimental impact on Postgres, have you considered using the timestamp from the posthog-js client? Alternatively, using a hash of the projectId as a Kafka key could potentially ensure event processing order.

I hope this issue gets resolved well :)

FYI - my projectId : 23476, I'm on US cloud. The version of posthog-js is 1.51.5

**Comment by tiina303** [comment]
@MappyLiam  please use the in-app support ticket option & I can see if in your case there's something you can do specifically.

We can't guarantee in-order processing by team as it would not scale. That said we do have an internal proposal in the works for how this problem could be solved in a scalable way, we'll be looking into implementing that in Q4 or early next year.

**Comment by robbie-c** [comment]
Internal zendesk link of a report here: https://posthoghelp.zendesk.com/agent/tickets/10521 (moved to PostHog: https://us.posthog.com/project/2/support/tickets/13077)

**Comment by tiina303** [comment]
please see https://github.com/PostHog/posthog/issues/7710#issuecomment-1669996908
