### ISSUE TITLE
Person display name customizable

### ISSUE THREAD

**Issue by tiina303** [PostHog/posthog#9169]
## Is your feature request related to a problem?

Person display name is not customizable. Currently we show email if that property exists, then name and otherwise `User <id>`. Code https://github.com/PostHog/posthog/blob/b1f304754fa37a2f72fe4b3ad51f8ed6bdf707b7/frontend/src/scenes/persons/PersonHeader.tsx#L17

## Describe the solution you'd like

Would be nice if that could be customizable. Ideally it would be customizable for cloud users too and without sending a special person property. So it could be in the project settings for example (i.e. what's the person property name that we should use or None to default to the current email then name name). 

## Describe alternatives you've considered

As is.

## Additional context

Community-support request https://posthogusers.slack.com/archives/C01GLBKHKQT/p1647636625776289

**Comment by tiina303** [comment]
cc @liyiy per https://posthog.com/handbook/engineering/feature-ownership

**Comment by lnhrdt** [comment]
Hey @tiina303 I've been thinking a lot more about this since I posted in Slack. And I have an even more specific suggestion / request to make.

Beyond being able to customize the display name between the person properties (email, name, username) I'd like to be able to include other properties, i.e. the name of a group they're associated with. That way I can see something like "John Smith (Company A)" associated with events.

Thanks for submitting this GitHub issue for me!

**Comment by tiina303** [comment]
@liyiy any recommendations for who could pick this up or prioritize against everything else on our plates?

**Comment by liyiy** [comment]
@tiina303 This is a good issue for beginners since it's low urgency and well defined, maybe someone who's starting at PostHog soon or anyone else that wants to give it a try? Otherwise I'll pick this up in the next sprint or two

**Comment by lnhrdt** [comment]
This feature is wonderful for my team. Thank you so much!

**Comment by amacneil** [comment]
It would be great to have this for groups too! Right now it seems to detect `name` but not `Name` for example.
