### ISSUE TITLE
Add properties to users from dashboard

### ISSUE THREAD

**Issue by eikooc** [PostHog/posthog#921]
**Is your feature request related to a problem? Please describe.**
There is no way to add or remove properties for a user without going through the SDK.

**Describe the solution you'd like**
An input field where you can add properties to a user with a value, from the specific user overview on the dashboard

**Describe alternatives you've considered**
Creating a custom solution that interfaces with your SDK. It would just be a shame if everyone should do that when using Posthog.

**Additional context**
The other teams in the organization wants to be able to add properties to a user from a web interface. This is useful for the organization to be able to dynamically add properties that identify a user.

**Comment by jamesefhawkins** [comment]
Thank you - this is an obvious and cool feature idea.

Would it be better to do this in bulk or one at a time?

(and would you want these properties to feed into any other tool?)

**Comment by eikooc** [comment]
Interesting question. I had only thought about the "one at a time" aspect.

The only scenario I can conjure right now is bulk being useful when you haven't used the "one at a time" feature and retrospectively find out you want to add properties to users that have performed an action.

I don't necessarily want the properties to feed into any other tool. What do you have in mind?

On a tangent, maybe it would be cool if it was possible to set up rules that included or excluded users from having a property set such that it can function as a way to dynamically build audiences/cohorts.

**Comment by jamesefhawkins** [comment]
That's helpful - I think ideally we'd make the columns more flexible when you view the entire users list, and that would need to start with at least being able to enter data one at a time but without having to dig into each profile, as a starting point.


Re feeding properties to other tools - the reason I mention this is that we're going to build more integrations/webhooks - see #906, this will allow you to do things like email users after they've signed up, push user data into other databases, work out which ad campaigns actually convert to paying customers rather than just sign ups. In some cases, having user properties synchronised we imagine would be hlelpful.

To address your last point - we have [cohorts](https://posthog.com/docs/features/cohorts) functionality currently. You can do exactly this, then you can use these cohorts to filter the trends and dashboards etc :)

**Comment by eikooc** [comment]
Okay, an integration to BigQuery would be cool for many organizations. Specifically for us, a Hubspot integration would also be beneficial.

If you build webhooks. It would be cool to be able to trigger the webhook on "milestones" of events, for example 10% WoW growth of sign-ups.

Regarding Cohorts, yes I obviously see that now. And with regards to what you said about sending out emails, it would be amazing if the inclusion into a cohort could be the trigger.

**Comment by Twixes** [comment]
Property addition is now possible from the person's page. :)
