### ISSUE TITLE
Support multiple properties in 'Break down by'

### ISSUE THREAD

**Issue by prawnsalad** [PostHog/posthog#938]
**Is your feature request related to a problem? Please describe.**
I cannot break down browser usage by browser and browser version at the same time. I can filter by a browser and then breakdown by version, but I cannot get a list of all browsers + versions in one table.

**Describe the solution you'd like**
Being able to select multiple properties from the list such as "Browser" + "Browser Version".

**Describe alternatives you've considered**

**Additional context**

***Thank*** you for your feature request - we love each and every one!

**Comment by andrewm4894** [comment]
yep - this would be good to see. Similar to how GA does custom reports https://support.google.com/analytics/answer/1151300?hl=en

I think there, there is a limit to how many dimensions and metrics you can use so i think capping it in some way (so not overly complex query) would be ok by users.

**Comment by paolodamico** [comment]
+1 from another [focus customer](https://posthogusers.slack.com/archives/C02G4JL2G0P/p1633952214000500) who have a use case of "looking at conversions by browser & OS or conversion by payment method & device type, etc"

@neilkakkar another interesting consideration would be cross cutting in Quant Analysis.

**Comment by neilkakkar** [comment]
Is this breaking down by two properties independently? (so, the table has a list for browsers, and then a list for browser version), or more along the lines of breaking down by both properties together:

So there's still only one table, and the breakdown value is something like: Browser::Version. ( or maybe a sub-table)

The latter makes sense to me - it surfaces new data we didn't have earlier.

For Quant, not sure what this means yet.  Something like: People with browser X, AND browser version Y, were more likely to convert. .. Interesting.

**Comment by weyert** [comment]
Yes, I would be interested in this too. I would like to break down by tenant id and product :)
For example, we have multiple stores which sells the same products with the same ID but would like to see in which stores the product are most sold / viewed

**Comment by pauldambra** [comment]
Feels like a large enough change that it risks being a long-lived PR and [each task should be possible to finish in a day](https://posthog.com/handbook/engineering/development-process#2-sizing-a-task)

I'd propose a route through this where:

1. I add a feature flag
2. I make a backwards-compatible change to the API to allow it to accept one *or more* properties for breakdown
3. _in the backend_ with the flag off if there is more than one property it ignores all but the first
4.  _in the backend_ with the flag on it starts by doing the same, so there is no change in behaviour and the system doesn't break
5. _in the frontend_ with the flag off there is no change in behaviour
6. _in the frontend_ with the flag on it allows you to select multiple breakdown properties and send them to the API
7. figure out the ClickHouse query needed to make this work
~8. figure out the Postgres query need to make this work~
~9. _in the backend_ behind the feature flag implement that query in the Postgres query builder~
10. _in the backend_ behind the feature flag implement that query in the ClickHouse query builder
11. turn the flag on for review or user feedback

**Comment by Twixes** [comment]
That seems reasonable, though I think we can drop this feature for Postgres-based PostHog, as that's now legacy.

**Comment by pauldambra** [comment]
From a UI perspective, I don't think much needs to change

# Trends

![Screenshot 2021-10-19 at 15 15 41](https://user-images.githubusercontent.com/984817/137930116-feaa0a6e-7eb7-4a90-9d66-ce1005de95e2.png)

# Funnels

![Screenshot 2021-10-19 at 15 14 20](https://user-images.githubusercontent.com/984817/137930122-ea077693-38fd-45b8-aeea-af36728a4382.png)

Currently, we hide the "add breakdown" button once we've added one. I'd propose we don't hide it

@clarkus feels weird to have two different pills to display selected things. Is it? Which should we keep?

-------

Google analytics table with two "dimensions"

![Screenshot 2021-10-19 at 15 22 47](https://user-images.githubusercontent.com/984817/137930521-fcfb2ba3-ef31-47b9-b4af-030ec40d3662.png)

As referenced above GA allow two dimensions on tables. If the first dimension occurs more than once e.g. Chrome on both mobile and desktop it is duplicated

So 

| First Property  | Second property | Tuesday of that week | Wednesday too |
| ------------- | ------------- | -------------- |----- |
| Chrome  | Desktop  | 12 | 34 |
| Chrome  | Mobile  | 134 | 983 |
| Firefox | Desktop | 534 | 6509 |

That allows each of those table rows to be a series on any displayed chart.

**Comment by neilkakkar** [comment]
Q: Are you planning to do this for Funnels as well? If yes, I'd recommend initially treating the value as a single item (like, say, `Chrome::Desktop` ) - so you can avoid any frontend complications & the API contract can remain the same as it is now.

I'd also recommend _initially_ limiting scope to just basic funnels (as strict + any order funnels mean atleast 2 new queries). And you already have a trends query to worry about.

**Comment by clarkus** [comment]
> @clarkus feels weird to have two different pills to display selected things. Is it? Which should we keep?

@pauldambra, we're using this pattern much more and the latest iteration is at https://www.figma.com/file/gQBj9YnNgD8YW4nBwCVLZf?node-id=4325:30344#117756034. It demonstrates the encapsulated style where both the value and the remove action are contained. It also lowers the priority of the component a bit by changing from our primary blue to a more subdued gray. Let me know if you have any questions or if you see anything that should be changed. Worth noting that the means of composing these lists can vary based on context, but the link shows the general pattern for summarizing values.

**Comment by paolodamico** [comment]
- For context, I think it's helpful just to read [the original user request](https://posthogusers.slack.com/archives/C02G4JL2G0P/p1634051098000900?thread_ts=1633952214.000500&cid=C02G4JL2G0P) I mentioned above.
- Workflow-wise I would discard feature flagging the behavior in the backend as there's really no point. If you're sending the extra prop, it follows you're in the flagged version of the frontend.
    - Also workflow-wise we need to update the table below trends to reflect breakdown by both properties (as shown by your GA screenshot).
- Makes sense on not supporting strict/any ordering for now. We can just disable the select option if you have two breakdowns and viceversa, adding a tooltip explaining why.
- @neilkakkar can you clarify wdym by the single item `Chrome::Desktop` from a user perspective?

**Comment by pauldambra** [comment]
I like the implicit feature flag based on how the API is called @paolodamico 

As I get my head around the code. The API already accepts a pair of breakdown and breakdown type

```
breakdown: $browser
breakdown_type: event
```

or

```
breakdown: [1,2]
breakdown_type: cohort
```

Currently only cohorts are sent as an array. Sending an array with breakdown_type event causes the server to 500.

The front end types don't restrict when we use an array for breakdown. So the change to sending and processing an array is much, much smaller than I worried

**Comment by pauldambra** [comment]
> @neilkakkar can you clarify wdym by the single item Chrome::Desktop from a user perspective?

@paolodamico I read it as a suggestion for a step on the road

currently the API can already send back an array of dates and values with a single key

| key | day 1 | day 2 | day 3 |
|-|-|-|-|
|a|1|2|3|
|b|4|5|6|

So, if the server can run the analysis on multiple properties and then return each property combination as a concatenated key. The front end already knows how to display them

| key | day 1 | day 2 | day 3 |
|-|-|-|-|
|a1|1|2|3|
|a2|1|2|3|
|b1|4|5|6|
|b2|4|5|6|

The user can't sort the properties independently but can view them. Which might be a release-able increment.

That also maps to the [original user request](https://posthogusers.slack.com/archives/C02G4JL2G0P/p1634051098000900?thread_ts=1633952214.000500&cid=C02G4JL2G0P). Where they shared a graph with four series 

1.  propA - prop1
2. propA - prop2
3. propB - prop1
4. propB - prop2

You could later alter things so that

| key 1 | key 2 | day 1 | day 2 | day 3 |
|-|-|-|-|-|
|a|1|1|2|3|
|a|2|1|2|3|
|b|1|4|5|6|
|b|2|4|5|6|

**Comment by neilkakkar** [comment]
Yes, that's precisely it! I'd argue* that keeping a single key returned from the API keeps the API always backwards compatible, and whether to display it as a single column, or two, is a frontend decision 🤷‍♂️ .

*: Given I'm not sure how the solution looks like yet.

Can someone add me to the private channel with the user request?

**Comment by pauldambra** [comment]
@mariusandra @macobo 

I think that #6621 is safe to merge. I don't think it is finished. But I think we could merge what's there to keep moving forward

Karl figured out today how to query as an array. Which removes the need for the `thing::otherthing` concatenation. The implementation for that change is pretty small but it broke a lot of tests and I wasn't going to have time to fix them all today.

However, it's a breaking change for the API since that starts to return an array. And I don't know how strongly we try and avoid them. 

So we could merge this, or someone could pick it up and carry on. (or both)

That would leave two things to do...

1) change funnels to use array rather than concat

I guess we could avoid returning a response that is an array when the inbound breakdown is not an array to keep the API change backwards compatible. 

That lets us display the breakdown properties as separate columns without needing to split the response

2) implement in Trends

The requesting customer's example was a bar graph so I'm guessing they would be more excited by having this feature in Trends

**Comment by pauldambra** [comment]
Current plan is to:

* complete backend for multi property breakdown in funnels (#7074)
* add front end for that feature using learning from spike: #6621 
* implement multi property breakdown for trends
* if we choose to carry on:
    * change the API so it is an array of breakdown choices
    * that allows mixing of different types of breakdowns
    * add multi-property breakdown for groups

**Comment by andrewm4894** [comment]
I just had some marketing users looking to get a table of utm medium, source, campaign and then some metrics for each row. I think that's also a nice obvious use case in addition to the original one looking to break browser version and type by etc.

P.s was a small little bit embarrassing that it can't be done in PostHog, especially since I've been trying for months to get them away from GA and use PH instead since so much more powerful, but a little few edges or learning curves for a typical GA non technical user. Just felt like worth mentioning rather than not in case helps with prioritization or anything. Saying with love to try be helpful :)

**Comment by mariusandra** [comment]
@pauldambra is this something that you could continue working on?

**Comment by timgl** [comment]
What's the status of this? Just had another customer ask for this.

**Comment by pauldambra** [comment]
We're not actively working on it... Let's discuss at next sprint planning

**Comment by mariusandra** [comment]
@EDsCODE @neilkakkar based on [feature ownership](https://posthog.com/handbook/engineering/feature-ownership), it makes sense for Team West to own this. Would it be a quick fix, or will you need to uproot a lot of old filtering code?

**Comment by EDsCODE** [comment]
I haven't followed the developments of multi-breakdown previously. I do think it's worth getting through though as it's quite powerful and definitely on our side of feature ownership! Let me double check what it would require or @neilkakkar can chime in if he looks into it early tomorrow

**Comment by neilkakkar** [comment]
If I recall correctly, we got this sorted 80% for funnels, and trends remain, and @pauldambra had an open PR for trends that never made it in?

Makes sense for team west to own this. I've been wanting to clean up the confusion around `breakdowns` and `breakdown` for a while xD

Regarding effort, I don't think its a quick fix, but nor does it require uprooting lots of things - very limited in scope to `ClickhouseTrendsBreakdown`. However, I think the funnels bit isn't complete yet either, since the API doesn't fully support groups + breakdowns ( https://posthog.slack.com/archives/C02283301EK/p1638352561345400?thread_ts=1638296114.339700&cid=C02283301EK )

As such, would propose we do this after person-on-events, as that might end up juggling a few bits here, and handle all the cases™️

**Comment by pauldambra** [comment]
yep, would be awesome to finish the move to add `breakdowns`

Didn't have anything open on trends. 

event and person multi-property breakdowns work on funnels behind `938-breakdown-by-multiple-properties`, and cohorts already supports multiple choices. But, yep, groups was landing at the same time and doesn't work with the multi-property API. 

IIRC the API maintains the behaviour of only working for single type breakdowns, e.g. if first breakdown selected is an event then all the rest have to be event breakdowns but the UI doesn't enforce that

**Comment by neilkakkar** [comment]
Thanks, that's useful context, specially the last bit! Anything else we should take into account?

**Comment by pauldambra** [comment]
Not that I remember, but I'll add more if it occurs to me :)

**Comment by Twixes** [comment]
Extra note: AFAIK multiple breakdowns aren't supported by smart insight names, need to be added in.

**Comment by WTK** [comment]
+1

**Comment by cdbattags** [comment]
Hi folks, any update here? I'd love to see this on PostHog cloud!

**Comment by aluxian** [comment]
Also looking forward to this for https://molin.ai/ where I'm still convincing the team to ditch GA in favour of Posthog.

**Comment by mariusandra** [comment]
Hey all, this is basically possible now. If you select "HogQL" as the breakdown type, you can enter any SQL expression that combines all the properties. For example `concat(properties.$browser, ' ', properties.$os)`. Read more about it [here](https://posthog.com/docs/product-analytics/hogql).

We are also planning on building a "click and select" multi breakdown that leverages HogQL under the hood, but no ETA on that yet.

**Comment by aluxian** [comment]
Thanks @mariusandra, that's awesome! Congrats on shipping HogQL!

Does it support nested properties?

I tried a query and it failed: Query ID: df558add-a301-4192-a04e-85dc9fa284a1

I wanted to break down by `user.created_at` where our events' properties look like this: `{ user: { created_at: '...' } }`

The expression I used is: `properties.user.created_at`

**Comment by mariusandra** [comment]
Hey, unfortunately nested properties are not _yet_ supported... The PR adding this is just around the horizon though: https://github.com/PostHog/posthog/pull/14976

We'll also make the errors better soon... :)

**Comment by dannovify** [comment]
+1

**Comment by aseemk** [comment]
+1 to this issue, but I also filed #20251 to actually _make use of_ multiple "break down by" properties, to be able to produce 2D "pivot" tables (AKA transpose rows into columns), for anyone else interested!

**Comment by xtbp** [comment]
> Hey all, this is basically possible now. If you select "HogQL" as the breakdown type, you can enter any SQL expression that combines all the properties. For example `concat(properties.$browser, ' ', properties.$os)`. Read more about it [here](https://posthog.com/docs/product-analytics/hogql).
> 
> We are also planning on building a "click and select" multi breakdown that leverages HogQL under the hood, but no ETA on that yet.

Thank you for shipping this! Please add this to documentation! We've just finished a meeting where it took us half an hour to find the right syntax. It's also:
`concat(properties.browser, ' ', properties.os)` without $ for us.

**Comment by Twixes** [comment]
Reopening for a bit as multiple breakdowns are initially feature-flagged, but we'll be rolling this out soon! (CC @skoob13)

**Comment by kitsirota** [comment]
@Twixes Thank you so the update!  This is the single biggest hurdle we have today to moving off of GA.  Is this going to be tracked as part of this ticket or is there somewhere else we can monitor for updates?

**Comment by thmsobrmlr** [comment]
We've rolled out multiple breakdowns to everyone 🎉  Closing this issue.
