### ISSUE TITLE
Create payment flow for hosted users

### ISSUE THREAD

**Issue by jamesefhawkins** [PostHog/posthog#958]
We should build the basic payment flow for PostHog hosted.

The simplest way to do this would be:

# 'PostHog SaaS'

* User wants to use app.posthog.com 
* User creates an account (email/password/company)
* We monitor for event volumes at team level across all domains tracked by users on that team
* If event volume > certain amount, trigger alert in PostHog for all members of the team "enter card details to continue"
* User enters card via an embedded stripe form, we keep capturing events

*Notes* 

* We need to create pricing for usage volumes so we could then edit the card payments depending on volume
* The alert and stripe form needs not to be in the repo for self hosted users, which means a private repo to hold this part of the code
* If user comes through our startup or YC scheme, we could manually send them a form to hold card details via Stripe then increase their usage in PostHog SaaS. That means we'd need to be able to manually have a super user or at least edit a value in django backend to increase their account's limits

**Comment by timgl** [comment]
Looks like Stripe's new [Billing Portal](https://stripe.com/blog/billing-customer-portal) could also cut out a lot of the boilerplate we need to write for this.

**Comment by jamesefhawkins** [comment]
This is totally in the right direction.

The top item in their roadmap looks like what we'd need (the metered bit...):

>The customer portal’s product roadmap includes adding new features that improve the experience for your customers and support for additional business models beyond current limitations. Features that are currently being scoped as part of the product roadmap are:

> Updating subscriptions with multiple quantities, multiple products, tiered pricing, and metered billing

**Comment by timgl** [comment]
I don't think we want to charge users literally per event do we? We can just have plans

**Comment by jamesefhawkins** [comment]
Agreed, but we need some way of at least knowing if they are using the right volume for their plan.

**Comment by paolodamico** [comment]
So after researching options for this, I found two different paths we can take at this point and want to get your thoughts on.

1. We do a full billing engine using [Stripe Billing](https://stripe.com/billing), in which we actually charge users the way the website establishes. The main downside I see of this is that I'm not sure if charging on a per-user basis is the right approach (some more research might be needed there, but basically my thoughts are that the company's costs would come chiefly from more usage, rather than number of users in a team), and we could be doing some work that will need to change very soon.

2. We do a simple feature using probably Stripe Checkout that requests the users from a team to input their card information after they reached certain threshold (e.g. 70% usage), and we only capture the card information for future billing. This option already helps in a) having the user's card on-file for seamless billing in the future, b) help gauge that users are actually willing to pay for the service. We could put an internal feature flag here to only ask the card from certain teams. Optionally we could also lock down access to metrics or stop capturing events if a card is not entered and the full usage is exceeded.

Thoughts?

**Comment by timgl** [comment]
1. It looks like with Billing you can do [metered](https://stripe.com/docs/billing/subscriptions/metered)billing? I think that would definitely be what we're looking for in this case?

**Comment by paolodamico** [comment]
The problem with doing metered billing is that we would be able to charge based on the number of events but not on a per-seat basis. We could do this with their [alternative tier pricing](https://stripe.com/docs/billing/subscriptions/per-seat) (only for the Growth plan) and then we would need to handle the case of a team exceeding the first 5k to transition them to the Growth plan and then the 500k events to manually transition them to a different plan (because this would need to happen through the Sales Team).

The other thing is that we would need to implement a "seat licenses" scheme so that a team user can only invite other users if they have added more "licenses" to their team.

**Comment by timgl** [comment]
Ah yep my comment was about _if_ we want to change our billing structure in the future. 

I also definitely agree we shouldn't do pricing per seat, as we want as many people as possible to use this. Let's just do a flat rate $29 for now for up to 500k events. We can always raise the price once we've experimented. Does that make sense to you?

**Comment by paolodamico** [comment]
Perfect! Let's do flat pricing then. I won't use metered billing because when the user exceeds the 500k events we need to change them to an enterprise manually anyways through the Sales Team. So here's what I'm thinking we could do for the Billing Engine v1,

- On the `/api/user` endpoint we intercept the response on PostHog production and check if a) the user's team has no billing set up, b) the user's team is in excess of 5k events on the current calendar month, c) the user's team has no special override that keeps them out of the Growth plan (e.g. startup plan). If that's the case, we'll start the back-end process to set-up billing.

- If the user needs to set-up billing, we show a CTA on the front-end prompting them to enter their card, and when they tap it we redirect them to the Stripe checkout flow to complete the billing information.

- We'll add an additional endpoint on `posthog-production` so that the user can be redirected to the [Stripe Customer Portal](https://stripe.com/docs/billing/subscriptions/customer-portal) to cancel their subscription.


### Help needed

1. How should we do custom code for the hosted version on the front-end? We'll need this to set-up the billing pages and redirect the user to the Stripe Billing Portal.

### Next releases
The following elements will need to be considered for a future release.

1. Create an internal alert for users reaching the 500k threshold to reach out offline and convert them to an enterprise plan.
1. Lock down event capturing and/or dashboard access to users who don't enter the paid program (or cancel it) and exceed the 5k threshold.

**Comment by timgl** [comment]
> the user's team is in excess of 5k events on the current calendar month

It's sometimes impossible to do this specific query on app even in a few minutes, so I don't think it's wise to do this on every request to `/api/user`. Instead, to simplify this, the easiest solution would be to have a `show_payment_warning_message` property that we can manually set to true/false. This would simplify that endpoint logic too.

> How should we do custom code for the hosted version on the front-end? We'll need this to set-up the billing pages and redirect the user to the Stripe Billing Portal.

I thought Stripe handled most of the billing logic on their end? The only thing we'd have to put in the frontend is the warning message, which I think we could just do in our main PostHog repo.

**Comment by paolodamico** [comment]
> It's sometimes impossible to do this specific query on app even in a few minutes, so I don't think it's wise to do this on every request to /api/user. Instead, to simplify this, the easiest solution would be to have a show_payment_warning_message property that we can manually set to true/false. This would simplify that endpoint logic too.

Cool, I'll do it this way then for this v1.

> I thought Stripe handled most of the billing logic on their end? The only thing we'd have to put in the frontend is the warning message, which I think we could just do in our main PostHog repo.

Yes mostly, basically we would just need to a) show the CTA, b) redirect the user to Stripe using their library, c) handle the user returning from Stripe [either failure or success], and d) redirecting the user to the Stripe Customer Portal to manage their subscription

**Comment by timgl** [comment]
> Yes mostly, basically we would just need to a) show the CTA, b) redirect the user to Stripe using their library, c) handle the user returning from Stripe [either failure or success], and d) redirecting the user to the Stripe Customer Portal to manage their subscription

b, c and d you could do as separate views/urls within posthog-production, the CTA would be the only thing to do in the main posthog library

**Comment by EDsCODE** [comment]
related PRs merged
