### ISSUE TITLE
Not able to search users using the search bar at the top left corner

### ISSUE THREAD

**Issue by pavitrakumar78** [PostHog/posthog#9599]
## Bug description

I used to be able to search for users' IDs using the search bar on the top left, but it's not working anymore. 

This is a very important feature for me - am I missing something or was this removed? 

## How to reproduce

1. Log in and navigate to top left corner - search bar and type in an email address
2. Expected result: matching persons (has been this way since I started using PH)
3. Current results: nothing
4. 
![image](https://user-images.githubusercontent.com/5354407/166110388-4962297e-6556-4b03-a056-ad30b8f7ec16.png)

## Environment

- [YES] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

**Comment by neilkakkar** [comment]
Hey @pavitrakumar78 , you can search for persons by going to the `persons` tab from the left side screen. ( https://app.posthog.com/persons )

> has been this way since I started using PH

Surprising, since this is a new feature we're just testing out. The beta released last week!

I had to remove persons from this global search as its not yet performant enough for bigger teams. It will be back though, once we've sorted this out :)

**Comment by pavitrakumar78** [comment]
Thanks for the clarification. It's nice to have the global search include persons also.
