### ISSUE TITLE
Enterprise Edition

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#964]
We want to be able to offer enterprise features to make sure we can afford to maintain and improve our open source version. See [our business model](https://posthog.com/handbook/strategy/business-model).

I think there are two ways of splitting out our code base:
1. GitLab style, where all code is in one repository. One folder is separately licensed.
  - **pro**
    - It makes development a lot easier across both
    - Most people will default to installing PostHog with the enterprise features, which means it's much easier to upgrade
  - **cons**
    - Our main repository won't be MIT licensed, which could cause angry HN comments
2. Old-GitLab style, with two separate repositories. We could pull in the MIT licensed code and then develop the Enterprise Edition code.
  - **pro**
    - Very clearly separates MIT code from Enterprise code
    - We could still have all Docker images, Charts etc point to this repository so that _most_ people can deploy the repo with enterprise features for easy upgrading
  - **cons**
    - harder to develop

cc @fuziontech This is what we talked about yesterday, any thoughts?
cc @jamesefhawkins

**Comment by jamesefhawkins** [comment]
For (1), my biggest concern would actually be people will see a popular repo and then be like "oh it's not MIT in the license summary shown by GitHub" then leave, harming the growth we've had.

To be clearer, in terms of upgrading in (1), is there any reason it's actually harder for a *user* to upgrade? I'd see the downside as it creating a lot of engineering work in order that the upgrade is not harder. ie we could build a "click to upgrade" inside the platform, and that could pull from any repo, rather than expecting people to run commands from the terminal

**Comment by paolodamico** [comment]
I think we can close this @timgl ?

**Comment by Twixes** [comment]
Enterprise Edition is now a thing.
