### ISSUE TITLE
Return to custom date range panel when adjusting date range after already using custom date range =]

### ISSUE THREAD

**Issue by corywatilo** [PostHog/posthog#9664]
When a custom date range is already set, clicking the date range input should probably return the user to the custom range selector:

<img width="920" alt="image" src="https://user-images.githubusercontent.com/154479/166957732-fa78e1c2-2e91-415a-8722-d185f260937e.png">

Currently it opens to the default date range selector, but given they already set a custom range, it seems plausible they're likely to adjust to another custom range.

<img width="856" alt="image" src="https://user-images.githubusercontent.com/154479/166957583-3b580ded-9464-47be-bba3-fc505e2ab0c3.png">

**Comment by marcushyett-ph** [comment]
related: https://github.com/PostHog/product-internal/pull/305

I think @clarkus has a potentially elegant solution in mind for this - great feedback to help validate.

**Comment by clarkus** [comment]
It's a bit disorganized, but there are some concepts at https://www.figma.com/file/PA3RZmpBykvBW1du69Kk0A/Prototypes?node-id=848%3A2344 to address this. It's a work in progress.

**Comment by mariusandra** [comment]
I went to see if this is fixed... and found even more UX problems:

![2022-08-17 13 00 38](https://user-images.githubusercontent.com/53387/185102940-96c1d88a-e3e0-4eff-82b0-75679bf597e8.gif)

**Comment by mariusandra** [comment]
Whatever issues I had in the gif above are resolved. However:
![2022-08-25 13 08 46](https://user-images.githubusercontent.com/53387/186652576-5a538993-6183-46e3-b7ea-31c0f5feefcf.gif)

While preselecting the "custom fixed time period" option is great, clicking it doesn't set the previously selected range as the default. I don't think this is intentional, as I'd consider it good UX to just make a quick tweak without potentially making a dozen "previous month" clicks.
