### ISSUE TITLE
Query builder isn't showing filter name

### ISSUE THREAD

**Issue by corywatilo** [PostHog/posthog#9666]
When [editing a saved insight](https://app.posthog.com/insights/oVHjTLUD/edit), some of the filter names aren't displayed, instead showing an ellipsis. Hovering over the input showed a tooltip with the value.

<img width="659" alt="image" src="https://user-images.githubusercontent.com/154479/166959675-0fc2cfba-941c-468b-88a7-18390204b5b0.png">

The data is there, but it isn't showing any of the text. It seems to be related to the cases where the input width is less than the `max-width` set for the field. (Ie: reducing the `max-width` to less than the input width correctly truncates the text in the field.)

<img width="545" alt="image" src="https://user-images.githubusercontent.com/154479/166960034-0da2d30c-1f88-4303-8729-871e441b25ea.png">

Edit: Seems to happen other places too

<img width="529" alt="image" src="https://user-images.githubusercontent.com/154479/166964421-3bcd1c0b-6fec-46a9-a4da-6e9c4ecdea8b.png">

**Comment by mariusandra** [comment]
The interface has changed significantly since then and this doesn't seem to be an issue anymore. Please reopen if not the case

<img width="1035" alt="image" src="https://user-images.githubusercontent.com/53387/186646803-11485935-c64d-4419-bdb2-922f5a7746f5.png">
<img width="1021" alt="image" src="https://user-images.githubusercontent.com/53387/186646917-189a53af-cd75-4def-aa10-0ef31484cdac.png">
