### ISSUE TITLE
Updating person properties on the UI only updates Postgres (not ClickHouse)

### ISSUE THREAD

**Issue by yakkomajuri** [PostHog/posthog#9856]
I'm sure there's another issue for this but I can't easily find it.

## Bug description

If I add/update a person property via the UI, we patch the row on Postgres but ClickHouse never gets the data. 

## How to reproduce

1. Add/update a person property on a person page

## Environment

- [x] PostHog Cloud
- [x] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_

## Additional context

I've put up https://github.com/PostHog/posthog/pull/9855 but @macobo rightfully pushed back on the "quick fix" and suggested we do this in a more robust way, by updating the actual PATCH endpoint.

There _may_ be some nuance with this:

1. What depends on it?
2. Can we still use the event approach for it or should we send data directly to CH?
3. What do people realistically need to patch? Is it just properties?

**Comment by macobo** [comment]
One related problem which affects the scope of this: our event ingestion doesn't support removing person properties, but the UI does.

@yakkomajuri thoughts on whether we should hide the delete button or build that (new) functionality?

**Comment by tiina303** [comment]
Lets hide the button, and not extend scope currently, we can file a task for it if needed or just wait for a user request.

**Comment by macobo** [comment]
This was a product question, not so much a technical one. We can see the usage here: https://app.posthog.com/insights/fhK1muAh 

Removing person properties is the most popular feature on the page, so we really shouldn't.

**Comment by tiina303** [comment]
If you look at usage by unique person it's not that much, but sure.
I see 3 options:
1. remove it from postgres - we need to make sure redis cache is updated or cleared (which only gets updated when props change with the event sent) and CH person is updated. Downside: likely failures in the future to update this if anything in the events ingestion changes.
2. set the property to `null`, potentially make the `isSet` etc filters ignore `null`. Downside: we'll store more data. Upside: works for any order ingestion. Useful bit of info here would be: how many user properties are set to `null` currently.
3. add a `$del` functionality to user properties & use that. Upside: we'll go through the normal ingestion flow, so everything will work as expected. Downside: tricky for any order ingestion (but we can just put disclaimers around that).

My order of preference: (3), (2) due to the unknowns around setting it to null impact, (1)

**Comment by macobo** [comment]
We discussed this, let's go with 3). Naming suggestion: `$unset`

**Comment by yakkomajuri** [comment]
As per our sync, we're in accordance that $unset should be the way to go - will be prioritized next sprint

**Comment by yakkomajuri** [comment]
can we close @macobo ?
