### ISSUE TITLE
"Could not find person with distinct id xxx to update properties"

### ISSUE THREAD

**Issue by yakkomajuri** [PostHog/posthog#9956]
We drop some events with the following error:

```
Could not find person with distinct id "180f0c0acdbc7-02face95b63e57-33574571-5c094-180f0c0acdc1c" in team "" to update properties
```

This is due to race conditions in the plugin server. The events are currently being sent to the dead letter queue.

**Comment by tiina303** [comment]
The fix for this is https://github.com/PostHog/posthog/issues/9181 because we run into the error, when two different threads process events for the same distinct ID. 

Imagine this timeline (relevant [code entry point](https://github.com/PostHog/posthog/blob/735ceb33a540c6614b0129320c06b7913b7d3164/plugin-server/src/worker/ingestion/process-event.ts#L548)):
1. thread A reaches `isNewPerson` check in `createPersonIfDistinctIdIsNew` ([code](https://github.com/PostHog/posthog/blob/735ceb33a540c6614b0129320c06b7913b7d3164/plugin-server/src/worker/ingestion/process-event.ts#L766)) when the person doesn't exist and we mark the person seen (in memory cache)
2. thread B reaches `isNewPerson` check in `createPersonIfDistinctIdIsNew`, since we just marked it seen we'll skip person creation here
3. thread B reaches person props update [code](https://github.com/PostHog/posthog/blob/735ceb33a540c6614b0129320c06b7913b7d3164/plugin-server/src/worker/ingestion/process-event.ts#L563), from where we hit the [error](https://github.com/PostHog/posthog/blob/735ceb33a540c6614b0129320c06b7913b7d3164/plugin-server/src/worker/ingestion/process-event.ts#L253) as thread A hasn't finished person creation yet
4. thread A finishes person creation

There are other potential reasons we hit this, will look at those once we've solved this main one.

**Comment by yakkomajuri** [comment]
I still agree with you that out of order/parallel processing is probably a big issue here. 

However, the scenario you laid out doesn't make sense - and as a result worries me that we may have issues elsewhere.

As you noted, we update a cache in memory - this cache is not shared across threads, so your point 2 here isn't true.

Here goes a flyby hint: look into person deletion as well 😉

**Comment by tiina303** [comment]
Yes, it's not threads exactly, the problem is that we do `promise.all(messages)`, which was easier for me to explain as threads, I really just meant execution flow. iirc I have also verified this in the past with timestamps of the events in CH & DLQ that it's person creation not deletion in a few cases at least.

**Comment by tiina303** [comment]
Reduced the Sentry noise with https://github.com/PostHog/posthog/pull/10086 while were working on fixing the causes

**Comment by tiina303** [comment]
this has been resolved
